### ISSUE TITLE
The skins in MCA are showing up black and pink and editing crashes game

### ISSUE THREAD

**Issue by Dabogirl** [WildBamaBoy/minecraft-comes-alive#1003]
So after I downloaded it, I wen't to play and all my vilagers apear black and this pink/purple, Like they have no skin files and if you use the book to edit the villagers it crashes. 
_______________________________________________________________________________________________________________

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 3/20/18 5:49 PM
Description: Exception in server tick loop

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at mca.packets.PacketEditVillager.processOnGameThread(PacketEditVillager.java:118)
	at mca.packets.PacketEditVillager.processOnGameThread(PacketEditVillager.java:23)
	at radixcore.modules.net.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:174)
	at radixcore.core.RadixEvents.serverTickEventHandler(RadixEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_RadixEvents_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 354862976 bytes (338 MB) / 939524096 bytes (896 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2628 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                                 | Signature                                |
	|:--------- |:----------------- |:------------ |:-------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                          | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                          | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.2.2628.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.2.2628 | forge-1.12.2-14.23.2.2628.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar            | None                                     |
	| UCHIJAAAA | radixcore         | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar   | None                                     |
	| UCHIJAAAA | mca               | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar         | None                                     |
	| UCHIJAAAA | xaerominimap      | 1.14.9.1     | Xaeros_Minimap_1.14.9.1_Forge_1.12.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['dabogirl4693'/14, l='Copy of New World', x=-419.09, y=82.00, z=-388.84]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
![2018-03-20_17 54 54](https://user-images.githubusercontent.com/37598620/37687507-d0a03e4e-2c69-11e8-8d46-c0922192cc2d.png)
![2018-03-20_17 49 08](https://user-images.githubusercontent.com/37598620/37687523-e1dcb250-2c69-11e8-9e2c-0a682891ab69.png)
![2018-03-20_17 49 02](https://user-images.githubusercontent.com/37598620/37687527-e4fe510a-2c69-11e8-866c-b947b4bd8d55.png)
![2018-03-20_17 48 44](https://user-images.githubusercontent.com/37598620/37687529-e86b4f0a-2c69-11e8-85ce-0d639450cb84.png)
![2018-03-19_13 16 04](https://user-images.githubusercontent.com/37598620/37687538-ef7dc5c0-2c69-11e8-8227-e165795270d5.png)
Those are screem shots i took, Please contact me at dabogirl4692@gmail.com

**Comment by allensutton** [comment]
the same exact thing is happening to me
