### ISSUE TITLE
Crash everytime I go to a cementery

### ISSUE THREAD

**Issue by TaliaPP** [WildBamaBoy/minecraft-comes-alive#1004]
I can't understand why, but when I go to a village and I go to the cementery, it crash inmediatly, and then I can't enter to the world anymore. I don't have more mods in my game, just MCA and Optifine, and I disabled Opfine if that is, but still crashing, what happens? I use 1.9.4 version.

Thak you for your attention.

**Comment by MentalMouse** [comment]
For a while, there was a lethal bug with the tombstones in the cemetery, where just looking at the tombstone would crash the game.  You may need to seek a later version of MCA.

**Comment by MentalMouse** [comment]
BTW, to recover from the crash, you will probably need to use a world editor to remove the gravestones, and/or move your player away from the vicinity.
