### ISSUE TITLE
Custom Skins

### ISSUE THREAD

**Issue by NikksV** [WildBamaBoy/minecraft-comes-alive#1006]
I've been trying to install the MCA mod with custom skins but everytime I use it it crashes the game.
I've tried everything but it seems that it's just not working. I'm on mac so maybe that has something to do?

All it ends up saying is "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Comes Alive (mca)"

**Comment by Magician539** [comment]
Don't delete any skins only add or replace them
