### ISSUE TITLE
MCA Added Skins Are glitching

### ISSUE THREAD

**Issue by KatleKitKat** [WildBamaBoy/minecraft-comes-alive#1008]
When I tried to see the skins i added to mca It was glitching

**Comment by KatleKitKat** [comment]
![yey](https://user-images.githubusercontent.com/37832869/37961084-ecc18fbc-31e9-11e8-9108-59c45446f49f.png)

**Comment by Diamonddragon41** [comment]
The new textures for characters in the most recent minecraft are 64x64. They add an entire extra 32 pixels at the bottom to allot for if the arms have asymmetrical texturing. If you snip off the bottom 32 pixels in GIMP and make it a 64x32 texture like the old textures from before the update, it will work. Make sure your editor can save transparent backgrounds (not Paint)
