### ISSUE TITLE
[1.12.x-5.3.1 MCA] Villagers have no skins (invisible or black body with purple arms)

### ISSUE THREAD

**Issue by D3CAD3-3** [WildBamaBoy/minecraft-comes-alive#1010]
when ever i load up minecraft with version 1.12.x-5.3.1 of MCA the villagers are either not there but their shadow is or they have a black body with purple arms. the invisible villagers occur when playing with other mods and the black bodies occur when only MCA and RadixCore are installed. I checked the game output every time it happened and i found no error regarding missing textures. 
![2018-03-29_14 16 23](https://user-images.githubusercontent.com/37911459/38106134-1e90e6d2-335c-11e8-99a6-bd21645fcde9.png) screenshot of the bug

Edit: after using the villager editor it appears as if there are no textures what so ever and crashes the game

**Comment by liv18** [comment]
I am having the exact same problem

**Comment by ChaonicTheDeathKitten** [comment]
Can confirm issue. Makes the experience of the mod extremely crappy.
I think, I remember a friend showing me a workaround a while ago, copying out all the skins into a seperate folder. (Will add here, once I get the chance to talk to her again)
Using Forge version 14.23.4.2747

**Comment by liv18** [comment]
@ChaonicTheDeathKitten  That would be great if you could. Thank you.

**Comment by ChaonicTheDeathKitten** [comment]
Didn't mean to get your hopes up like this. She forgot how to.

**Comment by liv18** [comment]
@ChaonicTheDeathKitten Thanks for trying.

**Comment by RigoLeu** [comment]
i'm having EXACTLY the same problem. No matter what i try to fix it, i don't undestand what's going on...
