### ISSUE TITLE
Spawn in already married?

### ISSUE THREAD

**Issue by Kurdaneva** [WildBamaBoy/minecraft-comes-alive#1011]
I'm a huge fan of this mod, to the point that I keep coming back even through it's been giving me a bundle of issues. One of the two biggest issues is that whenever my friend joins my LAN server, the game always crashes. We do use other mods however and have been testing to see which mod we have is the one causing the crash. The game runs fine until we reach a village, so we've been trying to just build our own homes and raise children... but to do that we have to spawn in a cleric, and thus the whole server crashes. On the curseforge page I mentioned this error and someone gave me a command that might assist, but the comment I had has been removed for some reason and I'm unable to find the command again. Any help?

**Comment by Nyanpingu** [comment]
I'm having the problem where i try i get engaged to a villager, but they say i'm already married when i i have just created the world but i did have another world where i choose family, but i divorced AND deleted the world. anything to do with config settings?

**Comment by lea2932** [comment]
nyanpingu im having the exact same problem.

**Comment by Diamonddragon41** [comment]
Type "/mca help" in the chat, without the quotes.

**Comment by Pedil** [comment]
i have the same problem. help us creators of the mod; pleaaaseee

**Comment by CygnusKraft** [comment]
I too had this problem when playing a local LAN server with my daughter.  Both her character and mine were married when we started and it said you are "married to"... it is just blank after that (no name) for both of us. I had to find a cleric, request a divorce, and then I could marry.  The problem is that it still does not give the name of the person I am married to when she right clicks on my character, and when my spouse talks to me, my character's name does not show up and it is blank.

**Comment by Pedil** [comment]
thank you! i like a lot that a community for this wonderful mod exists and
that you take care of it.
... But i have another problem, i contracted a villager, for wood cutting,
and he gets 1 wood and then he says his inventory is full. His personality
is friendly. At other side, a greedy female don't even founds less when
working, she don't works!

**Comment by MentalMouse** [comment]
I had the marriage thing, and even after my first divorce, it apparently _restored_ my mystery marriage after I exited and restarted the game.

**Comment by Gabby2805** [comment]
I'm having the marriage issue too, in 5.3.1. I chose 'I live in a village' on the crystal ball which I thought meant you're single... I have no idea who I'm supposed to be married to. How annoying...

**Comment by ModedTroy** [comment]
Can someone help me too?I cant even find a cleric or a spouse
