### ISSUE TITLE
big bugs, parents can procreate with kids!

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#1015]
is this a big bugs?

**Comment by MentalMouse** [comment]
IIRC, It does keep the player from marrying their own kids, but not grandkids or further.  But I don't think it checks NPCs for incest at all, as long as one of the parents has died (so the survivor is no longer married).

**Comment by GrucciNishikino** [comment]
[Well...](https://www.youtube.com/watch?v=eYlJH81dSiw)
