### ISSUE TITLE
I have a suggestion  

### ISSUE THREAD

**Issue by Spoofygamer** [WildBamaBoy/minecraft-comes-alive#1019]
Could you make a config that allows both mca villagers and vanilla villagers to spawn along side one another.
The reason i ask this is because i love the personality of the mca villagers but i feel like something is missing without the vanilla villagers. I hope you understand and thank you for this amazing mod.

**Comment by GrucciNishikino** [comment]
I 100% agree with this. We need MCA villagers to overwrite villagers in villages, but not villagers from, say, Lucky Block.

**Comment by MentalMouse** [comment]
That might also help with modded villagers.
