### ISSUE TITLE
Custom Skin Blinking

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#1025]
I have minecraft 1.12.2 and 5.3.1 mca and i wanted to make my game prettier so i added a few extra custom skins in the child/villager profession. When i put them in the right folder i decided i would make edits of the skins with their eyes closed so they could blink and sleep right. Once i put it into the sleeping folder i launched my world and for some reason instead of changing to the sleep texture, the villagers face would just flash black or white. All of the custom skins i used were 32x64 so i know thats not the problem

**Comment by SolCourage** [comment]
The skins don't work right if they are 1.8 onward. So if they are 1.8+ you need to do is put the skin into a 1.7 skin maker/editor I used the NovaSkin one and save the template you will notice that it now looks like the MCA templates. The blank space that the 1.8 templates have mess with how the mod retrieves the skins.
