### ISSUE TITLE
Problems with memorials 

### ISSUE THREAD

**Issue by Tallahite** [WildBamaBoy/minecraft-comes-alive#1026]
My wife died. Tragic, yes, but what's worse is when I placed her memorial, it crashed my game, and every time I load up, I cannot play that world. (I've put the last week into it) heres the report, in a pastebin for tidiness- https://pastebin.com/fURAHBeP

**Comment by MentalMouse** [comment]
See #1004  .

**Comment by Tallahite** [comment]
Thanks. Now I think it's just MCEdit's problem. It shows up as "UNUSED BLOCK" but it won't let me delete it. Also I'm on the latest version, I think
