### ISSUE TITLE
When getting close to a village, client crash's

### ISSUE THREAD

**Issue by novastormsystems** [WildBamaBoy/minecraft-comes-alive#1031]
Anytime you try and get near a village the client crashs.

This is a Dedicated server with clients connecting. the server doens't crash just the clients
[crash-2018-05-28_09.51.05-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2045762/crash-2018-05-28_09.51.05-client.txt)

**Comment by Obasav** [comment]
I am also having this issue, 
[crash-2018-05-29_11.31.50-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2049033/crash-2018-05-29_11.31.50-client.txt)

**Comment by Cubemania119** [comment]
I have this issue as well,
[crash-2018-06-21_16.49.27-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2125721/crash-2018-06-21_16.49.27-client.txt),
[crash-2018-06-21_16.52.34-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2125722/crash-2018-06-21_16.52.34-client.txt)
