### ISSUE TITLE
[Suggestion] (and some sort of issue)

### ISSUE THREAD

**Issue by Magician539** [WildBamaBoy/minecraft-comes-alive#1037]
The "Issue" So my sister's laptop is incredibly bad and can run 1.0-1.5.1 minecraft at least up to 30fps with mods (by mods I mean optifine and MCA) and cant run 1.5.2 or up without it crashing so I was wondering if you or anyone has some old download links of MCA for 1.5.1 cause 1.0 - 1.5.1 MCA have all been removed. 3.3.0b2 MCA for 1.5.1 is the only one I can find and is a bit buggy (Grandchildren Vanish when fully grown & Children are always called null)

Suggestions: 

In config menu we could have the option to have new and old GUI I prefer the old one cuz the game pauses where the new one doesn't so my wife died when I tried to make her follow me cuz a zombie got her.

Lost Relative Document: Just for Roleplay you can have a sister Grandpa etc and make them come from whistle tho

Retreat feature from 1.5.1: Stop Deaths from occuring by making the villagers retreat for 10 seconds when health is below set health so if it was 5 they retreat when there health is 5 or down.

Bring some old skins back for nostalgia :P

**Comment by PurpleHel** [comment]
Links for old versions https://minecraft.curseforge.com/projects/minecraft-comes-alive-mca/files
