### ISSUE TITLE
fr

### ISSUE THREAD

**Issue by demon57730** [WildBamaBoy/minecraft-comes-alive#1047]
hello I have a problem with your mod

you have all translated into French what I thank you

but the beginning where we click on the table is not enchanted translated his fact that I and French of my server we understand nothing

**Comment by Zorai** [comment]
C'est une solution temporaire mais en attendant qu'une traduction soit éventuellement proposés je te met celle-ci (contenant des fautes d’orthographe je suppose, désolé, mais je l'ai fait rapidement).
(Not a long term solution, but until a traduction is made if possible, i've made up this one to help. There is spelling mistakes i suppose, sorry, but i was in a hurry)

 ![2018-07-12_20 32 42](https://user-images.githubusercontent.com/41168611/42655833-9150055e-861d-11e8-9b31-ecbb872cc023.png)
![2018-07-12_20 33 00](https://user-images.githubusercontent.com/41168611/42655834-917db8f0-861d-11e8-9c47-18064a1c550e.png)
![2018-07-12_20 33 19](https://user-images.githubusercontent.com/41168611/42655835-91ab44be-861d-11e8-9dc7-1798bd463ddd.png)
![2018-07-12_20 33 25](https://user-images.githubusercontent.com/41168611/42655836-91da14c4-861d-11e8-9795-539cd7dd70aa.png)
![2018-07-12_20 33 35](https://user-images.githubusercontent.com/41168611/42655838-92573332-861d-11e8-8289-ab9e1ba6dc37.png)

**Comment by demon57730** [comment]
merci
