### ISSUE TITLE
Can't farm using villagers

### ISSUE THREAD

**Issue by TheProdigalGoat** [WildBamaBoy/minecraft-comes-alive#1049]
When playing using Minecraft Comes Alive (version 1.12.2, build 5.3.1) [latest release], asking a villager to farm may cause the server / game to crash, returning the function 'getCropName' not found in the ActionFarm.java file on line 316. Attached is the logs from 2 crashes.
[crash-2018-07-16_01.38.38-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2196165/crash-2018-07-16_01.38.38-server.txt)
[crash-2018-07-15_16.35.49-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2196166/crash-2018-07-15_16.35.49-server.txt)

Please note there are no other mods other than MCA (version described above) and RadixCore (version 1.12.x, build 2.2.1). Forge version 1.12.2, build 14.23.4.2730 (I have not updated to the latest stable version of forge, but may at a later time.

**Comment by mercadanteus** [comment]
Same here, server in Beastnode crashed every time ask a villager to farm.
