### ISSUE TITLE
Won't let me marry

### ISSUE THREAD

**Issue by 89redneck89** [WildBamaBoy/minecraft-comes-alive#1051]
Hey so, I got engaged and then I try to gift her the wedding ring but she says "I'm sorry no. I'm already married." Anyone have a fix for this..?

**Comment by Ignaciahf** [comment]
Its because you're married with "?" lol its a weird bug, you must go to a cleric and get a divorce and then marry but when you log off and login once again you're again married to "?" ... So much gold I've spent on marriages lol
