### ISSUE TITLE
Its Probably Hopeless But... Cannot get married

### ISSUE THREAD

**Issue by SeamusFD** [WildBamaBoy/minecraft-comes-alive#1058]
I have tried multiple versions of MCA, and any version in 1.12.2 will not allow me to get married. Even when i tried to use the fan fork MCA: Elves and Orcs edition nothing can be done about it. In the strange chance that anyone sees this, I would be appreciative of any help

**Comment by MentalMouse** [comment]
There are multiple other issues reporting this.  You need to find a cleric and get a divorce from the bug.  ;-)
