### ISSUE TITLE
Villager Professions have the wrong inventories (MCA for 1.12.2)

### ISSUE THREAD

**Issue by FatalGTX** [WildBamaBoy/minecraft-comes-alive#1059]
Pretty much what the title says, I've been trying to build a city, and set up shops. However... I'm finding the villagers' trades are not matching up with their professions. Also that some professions, are seemingly non-existent entirely. This is really annoying to find a Librarian or Blacksmith, who won't trade what you'd expect the profession's title to suggest.

So far, I've found the following wrong professions (having a profession title and the wrong trade inventory associated with it)---

Blacksmiths-
Weaponsmiths have the inventory of Farmers and Shepherds,
Toolsmiths have the inventory of Farmers
Fletchers have the inventory of Armorsmiths
I have yet to find a villager with Weapon/Toolsmith inventories

Librarians-
Librarians have the trade inventories of Butchers
Cartographers are non-existent (?)
I have yet to see any villager with the Librarian's inventory

Butchers-
Butchers have the inventory of Farmers
Leatherworkers have the inventories of Fishermen and Shepherds

Priests-
Priests/Clerics do not have trade inventories
Shepherds have Priest/Cleric inventories

Villagers-
Farmers do not have Farmer inventories
Sheperds have the inventory of priests/clerics
Bakers have the inventory of Fletchers
Fletchers have armorsmith inventories
Fishermen probably don't have their correct inventory either

---The list of wrong professions could go on, but none of the Villagers' trades are matching their professions.

**Comment by MentalMouse** [comment]
Hmm. I am using Jordan Peacock's packs for Ruins; on a "fishing boat" ruin, a custom villager that IIRC is supposed to be a fisherman with custom trades, came out as a Farmer with the _correct_ trades.  On the other hand, another ruin (a multi-level pumpkin farm) had 3-4 Clerics with the "usual" no trades.  (I'm guessing the clerics think they're Nitwits.)

**Comment by FatalGTX** [comment]
Only mod I'm running that effects villagers (other than MCA itself) would be Immersive Engineering, cause it adds the Engineer villager and building to villages. However, I've been having Villagers from MCA with the wrong trade inventories for their professions, without Immersive Engineering running, as they've been doing this even before I installed IE.

**Comment by TheGamingGallifreyan** [comment]
This mod works great for me but this one issue has been driving me nuts for months in my worlds, so I spent some time researching Forge mod development and actually managed to fix this and add Cartographers while I was at it. It's a pretty simple fix but I have no idea how to use GitHub so it might take me a bit to figure out how to make a pull request (if the devs will even see it, I don't think this is being worked on anymore unfortunately).

**Comment by Gabby2805** [comment]
> This mod works great for me but this one issue has been driving me nuts for months in my worlds, so I spent some time researching Forge mod development and actually managed to fix this and add Cartographers while I was at it. It's a pretty simple fix but I have no idea how to use GitHub so it might take me a bit to figure out how to make a pull request (if the devs will even see it, I don't think this is being worked on anymore unfortunately).

I'd love access to this, great work.

I'm using version 5.3.1 on 1.12.2 and I am also having this problem. The MCA careers do not match the minecraft careers shown by HWYLA, and their trading inventories would suggest that hwyla is correct. I'm making my own village and I tried to use the Villager Generator to spawn villagers with specific professions and inventories but they immediately get overwritten by MCA and mostly set to farmers (some fishermen and shepherds but no others) regardless of what MCA says their job is.
