### ISSUE TITLE
Multiple client crashes and not spawned into village

### ISSUE THREAD

**Issue by smmmadden** [WildBamaBoy/minecraft-comes-alive#1060]
I've tried using this with Forge 2726 and 2745 versions and both result in numerous client side crashes when getting close to villages.  I found the crystal ball when joining and get prompted for Male/Female and then picking my name, I see some particle effects but left exactly where I joined.  I'm not prompted for any other questions or spawned into or near any village.  Is there something else required besides the two mods (MCA-1.12-x-5.3.1-universal.jar & RadixCore-1.12.x-2.2.1-universal) to get this working right?  The file contents of both Jars show a Modified Data of 1969-12-31 20:00 which is an invalid date from a programming perspective.  This is the default date used in the 70's when computers were starting to make it into the mainstream public.  It shouldn't have that date on them in today's software.

I took a shot at downgrading client & server to Forge 2491 of 9/23/2017 to match the closest to last update of Mod (based on the website).  Same behavior but this time when I found a village using /locate village I tp'd to it, game crashed.  Logged back in and started seeing villager chats, but no villagers.  Moved player around village and it crashed again.  Seems like this is very unstable with not having the exact build, the dated files is causing the problem or something else I can't put my fingers on.

Last test was shutting down the server and client, restarting them and re-joining the game in the village I had to find.  I was only then able to see villagers with the right skins and chat window showing them talking.  Would like to know what build and what setup is required to make this work properly without crashing.  I'm running a server of Windows 10 Professional x64 with 48GB RAM and TB of disk space, so it isn't resource related that I can tell unless W10 isn't supported?

Thanks -Steve

**Comment by MentalMouse** [comment]
Are you perhaps in multi-player mode?  (The crystal ball doesn't spawn stuff in multiplayer.)

**Comment by smmmadden** [comment]
yes I was actually.  This mod isn't for a multiplayer map? :-(

**Comment by MentalMouse** [comment]
Well, you still get the changed villagers, but you can't spawn a house or village, because that would let new players do quite a lot of damage with their crystal balls.  The village in particular basically paves over a roughly 4x4 chunk area (74x62 blocks), completely replacing the surface to a 6- block depth (I'm not sure how high, but I know the depth because I just did mine in the ocean).

**Comment by smmmadden** [comment]
so is the expectation is that we would spawn into the world, then need to create a village, spawn the villagers and then go from there to interact, etc with them?  Or find a village and begin there?  Are you using a specific forge version that you have better results with?  Thanks!

**Comment by MentalMouse** [comment]
For multi-player, you need to find a worldgen village, at which point you can interact with them (including kidnapping them to someplace you built yourself). 

You _ought_ to be able to cure V-zombies too, but last I heard that's not working too well these days -- you tend to get an invisible "Steve the Farmer".  At least one commenter here was able to marry them and have kids, but there's another bug where players start off "married to nobody" and need to get a divorce from a cleric before they can marry.  (Presumably that commenter had already done that.)

For single-player, you get a choice of "I live alone" (no building), "I have a family" (makes a decently large house), or "I live in a village" (well now you do, so much for the landscape or base you _were_ standing in).  ETA:  The village spawns with villagers, the family spawns you a wife and a kid or two.
