### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SrUca** [WildBamaBoy/minecraft-comes-alive#1070]
Can anyone help me? 

The crash report is:

The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: mca:memorial from mod Minecraft Comes Alive returned a null ItemStack in getPickBlock(...). Please report this to them.

**Comment by DatrixTHLK** [comment]
Was there a full crash report? And can you put the crash report into gist.github.com or pastebin for the mod author. And what version of the mod are you using and what version of minecraft and version of the library mod? What were you doing when the crash occured? All these are important for a mod author.
