### ISSUE TITLE
Cant engage and married someone 

### ISSUE THREAD

**Issue by RhedGamer** [WildBamaBoy/minecraft-comes-alive#1071]
I know you guys said find a cleric and divorce her but mine is different! the cleric isnht even married and if i give the devorce paper she will said normal people reply like "what im gonna do with that?"
same with engange and when i talk to un married woman i always have the option to procreate or something! its so weird pls fix it and when i call i can call the whole village and i can procreate my daughter

**Comment by MentalMouse** [comment]
No no, you are not attempting to "divorce the cleric".  You need to invoke the cleric's Special menu, and get her to grant you a divorce, which will release you from marriage unconditionally; that is, without having to track down your nonexistent "glitch-spouse".

**Comment by smmmadden** [comment]
yes, and that works perfectly! :-)

**Comment by RhedGamer** [comment]
im confused? how exactly?

**Comment by RhedGamer** [comment]
and how to unlock the special menu?

**Comment by MentalMouse** [comment]
When you right-click the villager, a few professions including clerics, will have a "Special" menu visible.  Pick that menu for their special abilities.

**Comment by RhedGamer** [comment]
![2018-08-31_22 39 29](https://user-images.githubusercontent.com/42805919/44918935-c6e98280-ad6e-11e8-92c7-c7661ab194d9.png)
see the options are glitching out

**Comment by MentalMouse** [comment]
WTF!  OK, that's a new bug, which I haven't seen before.  You should probably submit that as something to the effect of "Cleric options glitched, special menu not visible".  

For the immediate problem, you might try pressing the duplicated Inventory or Work buttons, just to see if one of them gets you to the Special menu despite their labels.

**Comment by RhedGamer** [comment]
YAY I FOUND A BUG XD btw all that option is the same to all people 
lol i can procreate a man and i can procreate my children XD

**Comment by RhedGamer** [comment]
btw i always reinstalling the mod but its still the same! and where im gonna report this?

**Comment by MentalMouse** [comment]
Rhedgamer:  Where are we "talking" now? Github is for bug reporting.  You can just start a new issue with a subject line about the duplicated/missing buttons.  Make sure to include your version numbers for Minecraft, Forge, MCA, and RadixCore, and attach that picture you just showed us.

**Comment by MentalMouse** [comment]
Rhedgamer:  Where are we "talking" now? Github is for bug reporting.  You can just start a new issue with a subject line about the duplicated/missing buttons.  Make sure to include your version numbers for Minecraft, Forge, MCA, and RadixCore, and attach that picture you just showed us.
