### ISSUE TITLE
Issue: NPCs say I am married when I'm not

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#1077]
So these female NPC's say that I am already married, I started a new world (MC 1.12.2) in creative mode,
I get the relationship to 5 gold stars and when I give them the engagement ring, they say "You're already married"

What the f**k ?

**Comment by MentalMouse** [comment]
Please look through the list of issues before reporting, there's probably eight or ten reports of this bug up already.  Briefly, you start off being married to "?", that is a nonexistent person.  If you get a cleric to give you a divorce, you can then get engaged and marry someone, but when you log out/save & exit, your marriage will reset to ?.

**Comment by SanjivanM** [comment]
So just to be clear (sorry for re-opening), the MCA wiki said you needed a priest.  Which one is needed, a MCA priest or a vanilla cleric villager?
