### ISSUE TITLE
Crash on approaching Village in Multiplayer

### ISSUE THREAD

**Issue by Misteak** [WildBamaBoy/minecraft-comes-alive#1082]
I am playing with FTB Revelation, however with previous modpacks with the 1.7.10 version of this mod in FTB evolved there were no issues.
[crash-2018-09-25_15.38.43-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2416730/crash-2018-09-25_15.38.43-client.txt)
I do realise there are alot of other people with the same issue, just heres to hoping it will be fixed sometime.

**Comment by Misteak** [comment]
update: I managed to fix this by disabling story progression in the server config.

**Comment by Lorex** [comment]
same problem, but disable story progression in the server doesn't work for me.

**Comment by knie1988** [comment]
Same problem here
https://paste.dimdev.org/yetuxokuhe.mccrash
