### ISSUE TITLE
curing zombie villagers

### ISSUE THREAD

**Issue by ClockyVaudeville** [WildBamaBoy/minecraft-comes-alive#1083]
So I can apply weakness and the apple but when they do get cured they just vanish, and when I bring up the editor menu to see if I can reset the texture and get the villager back my game just crashes. Unfortunately there's no crash report as I can see so I don't know if it's a conflict or a bug in the version of the mod. I have the 1.12.1 version of it, latest off of the curseforge web

**Comment by MentalMouse** [comment]
As per other bug reports, the missing villager is probably an Invisible Steve The Farmer.  At least one person has managed to marry an ISTF and have kids with them (after dealing with the marriage bug), but otherwise they're pretty hopelessly bugged.

**Comment by ClockyVaudeville** [comment]
Any idea why? Is it happening to everyone? It was a Steve the Farmer, and when I killed him I got a red sheen over my screen that I couldn't get rid of. I ended up deleting the world and starting a new one, it was the only way I got rid of it.

**Comment by MentalMouse** [comment]
I don't know the details, but it's been around for a while.  Unfortunately, MCA is currently in a remarkably buggy state (Marriage, ISTF, curing, trades, and I don't know what else) , and the moddev either hasn't figured out how to fix it, or hasn't had time to do so.  (AIUI, our moddev is a volunteer with a real life.)

**Comment by ClockyVaudeville** [comment]
Hm. Oh well, I'll hold out the hope that the devs can figure out what's wrong and fix it ^^ thanks for taking the time to answer.
