### ISSUE TITLE
The game crashed whilst rendering entity in world The game crashed whilst rendering entity in world Error: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by FinnOFFICIAL** [WildBamaBoy/minecraft-comes-alive#1088]
The game crashed whilst rendering entity in world
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
This error happens every time i come nearby an villager entity in multiplayer mode

**Comment by Melih5000** [comment]
I agree. 
I HAVE THAT SAME PROBLEM!!!

**Comment by KJ-Shipp** [comment]
Same Problem.

**Comment by PrettyFoxxo** [comment]
Use an older version of Optifne, it solved the problem for me

**Comment by Melih5000** [comment]
I tried the direct, no optifine.
The game crashed whilst ticking entity
Error: java.lang.ClassCastException: com.google.common.base.Present cannot be cast to java.lang.Boolean

pass after a certain time. I didn't understand.

**Comment by alphawolf918** [comment]
Also had this problem. Seems the fix is turning off the conversion of regular villagers to MCA ones.

**Comment by boredhero** [comment]
Can confirm this is an issue. Here is my actual crash log for diagnostic purposes even though it seems this mod is dead in the water. 
[crash-2019-05-30_20.23.51-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/3239221/crash-2019-05-30_20.23.51-client.txt)

**Comment by nop** [comment]
This issue was closed. Was there ever a solution found?

**Comment by alphawolf918** [comment]
Yes, there was an update made. See the CurseForge page.

**Comment by Ashtar084** [comment]
where is this page because I have this error
