### ISSUE TITLE
Problem with the "broken ring"

### ISSUE THREAD

**Issue by rayh206** [WildBamaBoy/minecraft-comes-alive#1090]
It is a simple issue: when I place down a broken ring, then move the camera a little bit, the game crashes.

A detailed walkthrough of the error, its code path and all known details is as follows:
--
06:21:14 | game | ---------------------------------------------------------------------------------------
06:21:14 | game |  
06:21:14 | game | -- Head --
06:21:14 | game | Thread: Client thread
06:21:14 | game | Stacktrace:
06:21:14 | game | at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:64)
06:21:14 | game | at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:44)
06:21:14 | game | at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
06:21:14 | game | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
06:21:14 | game | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
06:21:14 | game | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
06:21:14 | game | at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
06:21:14 | game |  
06:21:14 | game | -- Affected level --
06:21:14 | game | Details:
06:21:14 | game | Level name: MpServer
06:21:14 | game | All players: 1 total; [EntityPlayerSP['Kovuleon'/588, l='MpServer', x=57.65, y=66.00, z=58.91]]
06:21:14 | game | Chunk stats: MultiplayerChunkCache: 441, 441
06:21:14 | game | Level seed: 0
06:21:14 | game | Level generator: ID 00 - default, ver 1. Features enabled: false
06:21:14 | game | Level generator options:
06:21:14 | game | Level spawn location: World: (57,64,55), Chunk: (at 9,4,7 in 3,3; contains blocks 48,0,48 to 63,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
06:21:14 | game | Level time: 2079 game time, 2079 day time
06:21:14 | game | Level dimension: 0
06:21:14 | game | Level storage version: 0x00000 - Unknown?
06:21:14 | game | Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
06:21:14 | game | Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
06:21:14 | game | Forced entities: 173 total; [EntityBat['Bat'/6183, l='MpServer', x=-8.92, y=19.03, z=41.30], EntityRabbit['Rabbit'/54, l='MpServer', x=-19.38, y=68.00, z=64.50], EntityCreeper['Creeper'/6202, l='MpServer', x=108.50, y=41.00, z=24.50], EntityRabbit['Rabbit'/61, l='MpServer', x=1.50, y=64.00, z=53.50], EntityRabbit['Rabbit'/62, l='MpServer', x=-0.50, y=64.00, z=50.50], EntitySheep['Sheep'/67, l='MpServer', x=36.48, y=64.00, z=135.55], EntitySheep['Sheep'/68, l='MpServer', x=36.50, y=63.00, z=132.50], EntitySheep['Sheep'/69, l='MpServer', x=32.49, y=68.00, z=134.27], EntityCreeper['Creeper'/6213, l='MpServer', x=56.93, y=34.00, z=-9.70], EntityEnderman['Enderman'/6214, l='MpServer', x=55.50, y=36.00, z=-12.26], EntityEnderman['Enderman'/6215, l='MpServer', x=56.96, y=34.00, z=-8.32], EntitySkeleton['Skeleton'/6217, l='MpServer', x=-4.50, y=26.00, z=47.50], EntitySheep['Sheep'/74, l='MpServer', x=26.70, y=70.00, z=135.52], EntityRabbit['Rabbit'/75, l='MpServer', x=46.12, y=64.00, z=31.57], EntityRabbit['Rabbit'/76, l='MpServer', x=49.89, y=66.00, z=53.55], EntityRabbit['Rabbit'/77, l='MpServer', x=54.34, y=66.00, z=61.02], EntitySheep['Sheep'/78, l='MpServer', x=43.77, y=66.00, z=80.48], EntitySheep['Sheep'/79, l='MpServer', x=36.20, y=67.00, z=63.67], EntityPig['Pig'/80, l='MpServer', x=45.55, y=64.00, z=123.85], EntityPig['Pig'/81, l='MpServer', x=47.55, y=69.00, z=122.97], EntityPig['Pig'/82, l='MpServer', x=48.50, y=71.00, z=124.50], EntityPig['Pig'/83, l='MpServer', x=48.50, y=71.00, z=124.50], EntityLlama['Llama'/85, l='MpServer', x=44.11, y=62.26, z=122.83], EntityLlama['Llama'/86, l='MpServer', x=42.83, y=62.19, z=124.20], EntityLlama['Llama'/87, l='MpServer', x=44.18, y=62.45, z=123.29], EntitySheep['Sheep'/88, l='MpServer', x=48.43, y=70.00, z=120.91], EntitySheep['Sheep'/89, l='MpServer', x=48.55, y=70.00, z=119.87], EntitySheep['Sheep'/90, l='MpServer', x=46.55, y=66.00, z=120.32], EntitySheep['Sheep'/91, l='MpServer', x=50.50, y=74.00, z=120.50], EntityCreeper['Creeper'/4327, l='MpServer', x=114.50, y=33.00, z=29.50], EntityFallingBlock['Falling Block'/233, l='MpServer', x=-85.50, y=20.00, z=65.50], EntityFallingBlock['Falling Block'/234, l='MpServer', x=-85.50, y=18.00, z=66.50], EntityFallingBlock['Falling Block'/235, l='MpServer', x=-85.50, y=18.00, z=67.50], EntityFallingBlock['Falling Block'/236, l='MpServer', x=-84.50, y=18.00, z=67.50], EntityFallingBlock['Falling Block'/237, l='MpServer', x=-84.50, y=17.00, z=66.50], EntityFallingBlock['Falling Block'/238, l='MpServer', x=-86.50, y=19.00, z=67.50], EntitySkeleton['Skeleton'/4386, l='MpServer', x=39.62, y=42.00, z=71.98], EntityFallingBlock['Falling Block'/414, l='MpServer', x=33.50, y=14.00, z=196.50], EntityFallingBlock['Falling Block'/415, l='MpServer', x=32.50, y=14.00, z=196.50], EntityFallingBlock['Falling Block'/416, l='MpServer', x=34.50, y=14.00, z=196.50], EntityFallingBlock['Falling Block'/417, l='MpServer', x=31.50, y=14.00, z=195.50], EntityFallingBlock['Falling Block'/418, l='MpServer', x=32.50, y=14.00, z=195.50], EntityFallingBlock['Falling Block'/463, l='MpServer', x=70.50, y=35.00, z=-87.50], EntitySkeleton['Skeleton'/4563, l='MpServer', x=-18.50, y=22.00, z=9.50], EntityFallingBlock['Falling Block'/467, l='MpServer', x=71.50, y=35.00, z=-87.50], EntityFallingBlock['Falling Block'/471, l='MpServer', x=69.50, y=35.00, z=-87.50], EntityFallingBlock['Falling Block'/474, l='MpServer', x=68.50, y=38.00, z=-87.50], EntityFallingBlock['Falling Block'/477, l='MpServer', x=64.50, y=3.00, z=-86.50], EntityFallingBlock['Falling Block'/478, l='MpServer', x=62.50, y=3.00, z=-85.50], EntityFallingBlock['Falling Block'/479, l='MpServer', x=65.50, y=3.00, z=-86.50], EntitySpider['Spider'/4602, l='MpServer', x=44.40, y=40.58, z=52.59], EntityWitch['Witch'/4603, l='MpServer', x=49.26, y=40.00, z=47.66], EntityWitch['Witch'/4604, l='MpServer', x=53.38, y=39.00, z=46.23], EntityCreeper['Creeper'/4623, l='MpServer', x=24.85, y=58.00, z=68.39], EntityZombie['Zombie'/4655, l='MpServer', x=43.82, y=13.00, z=38.50], EntityItem['item.tile.flower1.dandelion'/4673, l='MpServer', x=33.88, y=65.00, z=67.42], EntityItem['item.item.seeds'/4675, l='MpServer', x=36.60, y=63.00, z=74.67], EntityBat['Bat'/4693, l='MpServer', x=66.25, y=15.52, z=-5.25], EntitySkeleton['Skeleton'/4706, l='MpServer', x=-10.50, y=16.00, z=42.50], EntityFallingBlock['Falling Block'/685, l='MpServer', x=111.50, y=6.00, z=194.50], EntityFallingBlock['Falling Block'/686, l='MpServer', x=110.50, y=6.00, z=195.50], EntityFallingBlock['Falling Block'/687, l='MpServer', x=110.50, y=8.00, z=196.50], EntityBat['Bat'/4794, l='MpServer', x=17.75, y=35.66, z=90.75], EntityFallingBlock['Falling Block'/711, l='MpServer', x=124.50, y=11.00, z=-80.50], EntityFallingBlock['Falling Block'/712, l='MpServer', x=122.50, y=10.00, z=-80.50], EntityFallingBlock['Falling Block'/713, l='MpServer', x=123.50, y=11.00, z=-81.50], EntityFallingBlock['Falling Block'/714, l='MpServer', x=123.50, y=10.00, z=-80.50], EntityFallingBlock['Falling Block'/715, l='MpServer', x=121.50, y=10.00, z=-80.50], EntityFallingBlock['Falling Block'/716, l='MpServer', x=122.50, y=10.00, z=-81.50], EntityFallingBlock['Falling Block'/718, l='MpServer', x=121.50, y=10.00, z=-81.50], EntityFallingBlock['Falling Block'/719, l='MpServer', x=120.50, y=10.00, z=-81.50], EntityItem['item.item.seeds'/4827, l='MpServer', x=71.54, y=62.00, z=91.10], EntityBat['Bat'/4881, l='MpServer', x=46.13, y=47.03, z=-5.73], EntityFallingBlock['Falling Block'/856, l='MpServer', x=198.50, y=17.00, z=101.50], EntityFallingBlock['Falling Block'/857, l='MpServer', x=198.50, y=15.00, z=103.50], EntityFallingBlock['Falling Block'/858, l='MpServer', x=199.50, y=15.00, z=103.50], EntityFallingBlock['Falling Block'/859, l='MpServer', x=197.50, y=18.00, z=109.50], EntityFallingBlock['Falling Block'/860, l='MpServer', x=198.50, y=17.00, z=110.50], EntityFallingBlock['Falling Block'/861, l='MpServer', x=197.50, y=17.00, z=108.50], EntityFallingBlock['Falling Block'/862, l='MpServer', x=198.50, y=17.00, z=108.50], EntityFallingBlock['Falling Block'/863, l='MpServer', x=197.50, y=17.00, z=106.50], EntityFallingBlock['Falling Block'/864, l='MpServer', x=197.50, y=16.00, z=107.50], EntityFallingBlock['Falling Block'/865, l='MpServer', x=198.50, y=16.00, z=107.50], EntityFallingBlock['Falling Block'/866, l='MpServer', x=197.50, y=16.00, z=105.50], EntityFallingBlock['Falling Block'/867, l='MpServer', x=196.50, y=4.00, z=159.50], EntityFallingBlock['Falling Block'/868, l='MpServer', x=197.50, y=5.00, z=160.50], EntityFallingBlock['Falling Block'/869, l='MpServer', x=197.50, y=4.00, z=159.50], EntityFallingBlock['Falling Block'/870, l='MpServer', x=198.50, y=4.00, z=160.50], EntityFallingBlock['Falling Block'/871, l='MpServer', x=198.50, y=5.00, z=161.50], EntityFallingBlock['Falling Block'/872, l='MpServer', x=198.50, y=4.00, z=159.50], EntityFallingBlock['Falling Block'/873, l='MpServer', x=196.50, y=6.00, z=160.50], EntityFallingBlock['Falling Block'/874, l='MpServer', x=199.50, y=5.00, z=165.50], EntityFallingBlock['Falling Block'/876, l='MpServer', x=197.50, y=5.00, z=162.50], EntityFallingBlock['Falling Block'/880, l='MpServer', x=199.50, y=28.00, z=-78.50], EntityFallingBlock['Falling Block'/881, l='MpServer', x=199.50, y=28.00, z=-77.50], EntityFallingBlock['Falling Block'/882, l='MpServer', x=198.50, y=27.00, z=-77.50], EntityFallingBlock['Falling Block'/883, l='MpServer', x=198.50, y=28.00, z=-76.50], EntityFallingBlock['Falling Block'/884, l='MpServer', x=197.50, y=28.00, z=-76.50], EntityFallingBlock['Falling Block'/890, l='MpServer', x=199.50, y=2.00, z=167.50], EntityFallingBlock['Falling Block'/892, l='MpServer', x=198.50, y=2.00, z=165.50], EntityFallingBlock['Falling Block'/893, l='MpServer', x=195.50, y=3.00, z=197.50], EntityFallingBlock['Falling Block'/942, l='MpServer', x=-85.50, y=20.00, z=65.50], EntityFallingBlock['Falling Block'/943, l='MpServer', x=-85.50, y=18.00, z=66.50], EntityFallingBlock['Falling Block'/944, l='MpServer', x=-86.50, y=19.00, z=67.50], EntityFallingBlock['Falling Block'/945, l='MpServer', x=-85.50, y=18.00, z=67.50], EntityFallingBlock['Falling Block'/946, l='MpServer', x=-84.50, y=18.00, z=67.50], EntityItem['item.item.seeds'/5053, l='MpServer', x=28.37, y=66.00, z=67.40], EntityFallingBlock['Falling Block'/1054, l='MpServer', x=33.50, y=14.00, z=196.50], EntityFallingBlock['Falling Block'/1055, l='MpServer', x=32.50, y=14.00, z=196.50], EntityFallingBlock['Falling Block'/1074, l='MpServer', x=70.50, y=35.00, z=-87.50], EntityFallingBlock['Falling Block'/1078, l='MpServer', x=68.50, y=38.00, z=-87.50], EntityFallingBlock['Falling Block'/1079, l='MpServer', x=69.50, y=35.00, z=-87.50], EntityFallingBlock['Falling Block'/1082, l='MpServer', x=64.50, y=3.00, z=-86.50], EntityFallingBlock['Falling Block'/1083, l='MpServer', x=65.50, y=3.00, z=-86.50], EntityZombie['Zombie'/5254, l='MpServer', x=125.50, y=25.00, z=135.50], EntitySkeleton['Skeleton'/5256, l='MpServer', x=130.50, y=25.00, z=133.50], EntityFallingBlock['Falling Block'/1250, l='MpServer', x=111.50, y=6.00, z=194.50], EntityBat['Bat'/5347, l='MpServer', x=114.75, y=12.00, z=135.10], EntityZombie['Zombie'/3311, l='MpServer', x=23.52, y=49.00, z=67.72], EntityFallingBlock['Falling Block'/1267, l='MpServer', x=123.50, y=11.00, z=-81.50], EntityFallingBlock['Falling Block'/1268, l='MpServer', x=122.50, y=10.00, z=-81.50], EntitySkeleton['Skeleton'/5409, l='MpServer', x=43.50, y=26.00, z=27.69], EntitySkeleton['Skeleton'/5410, l='MpServer', x=42.50, y=26.00, z=27.50], EntitySkeleton['Skeleton'/5411, l='MpServer', x=41.50, y=26.00, z=27.50], EntityItem['item.item.seeds'/5443, l='MpServer', x=4.13, y=69.00, z=115.91], EntityFallingBlock['Falling Block'/1365, l='MpServer', x=198.50, y=17.00, z=101.50], EntityFallingBlock['Falling Block'/1366, l='MpServer', x=198.50, y=15.00, z=103.50], EntityFallingBlock['Falling Block'/1367, l='MpServer', x=199.50, y=15.00, z=103.50], EntityFallingBlock['Falling Block'/1368, l='MpServer', x=197.50, y=18.00, z=109.50], EntityFallingBlock['Falling Block'/1369, l='MpServer', x=197.50, y=17.00, z=108.50], EntityFallingBlock['Falling Block'/1370, l='MpServer', x=197.50, y=17.00, z=106.50], EntityFallingBlock['Falling Block'/1371, l='MpServer', x=197.50, y=16.00, z=107.50], EntityFallingBlock['Falling Block'/1372, l='MpServer', x=197.50, y=16.00, z=105.50], EntityFallingBlock['Falling Block'/1373, l='MpServer', x=196.50, y=4.00, z=159.50], EntityFallingBlock['Falling Block'/1374, l='MpServer', x=196.50, y=6.00, z=160.50], EntityFallingBlock['Falling Block'/1375, l='MpServer', x=197.50, y=5.00, z=160.50], EntityFallingBlock['Falling Block'/1376, l='MpServer', x=198.50, y=4.00, z=160.50], EntityFallingBlock['Falling Block'/1377, l='MpServer', x=198.50, y=5.00, z=161.50], EntityFallingBlock['Falling Block'/1378, l='MpServer', x=199.50, y=5.00, z=165.50], EntityFallingBlock['Falling Block'/1380, l='MpServer', x=197.50, y=5.00, z=162.50], EntityFallingBlock['Falling Block'/1384, l='MpServer', x=199.50, y=28.00, z=-78.50], EntityFallingBlock['Falling Block'/1385, l='MpServer', x=199.50, y=28.00, z=-77.50], EntityFallingBlock['Falling Block'/1386, l='MpServer', x=198.50, y=27.00, z=-77.50], EntityFallingBlock['Falling Block'/1387, l='MpServer', x=198.50, y=28.00, z=-76.50], EntityFallingBlock['Falling Block'/1388, l='MpServer', x=197.50, y=28.00, z=-76.50], EntityPlayerSP['Kovuleon'/588, l='MpServer', x=57.65, y=66.00, z=58.91], EntitySpider['Spider'/5525, l='MpServer', x=37.50, y=34.00, z=87.50], EntityZombie['Zombie'/5526, l='MpServer', x=44.25, y=32.00, z=94.42], EntityZombie['Zombie'/5597, l='MpServer', x=45.50, y=41.00, z=84.50], EntitySkeleton['Skeleton'/5618, l='MpServer', x=-9.79, y=17.00, z=38.50], EntitySkeleton['Skeleton'/5619, l='MpServer', x=-14.50, y=13.00, z=32.50], EntitySkeleton['Skeleton'/5647, l='MpServer', x=111.50, y=33.00, z=19.50], EntitySkeleton['Skeleton'/5670, l='MpServer', x=37.50, y=50.00, z=71.50], EntitySkeleton['Skeleton'/5706, l='MpServer', x=70.50, y=21.00, z=-3.50], EntitySkeleton['Skeleton'/5707, l='MpServer', x=65.50, y=21.00, z=-8.50], EntityCreeper['Creeper'/3678, l='MpServer', x=51.30, y=39.00, z=47.73], EntityCreeper['Creeper'/3679, l='MpServer', x=38.84, y=42.00, z=71.36], EntitySkeleton['Skeleton'/5727, l='MpServer', x=-4.50, y=42.00, z=44.50], EntitySkeleton['Skeleton'/3680, l='MpServer', x=43.30, y=40.00, z=53.70], EntitySkeleton['Skeleton'/5728, l='MpServer', x=-3.50, y=42.00, z=44.50], EntityZombie['Zombie'/5730, l='MpServer', x=100.23, y=26.00, z=11.50], EntityZombie['Zombie'/5731, l='MpServer', x=102.50, y=26.00, z=12.50], EntityCreeper['Creeper'/5733, l='MpServer', x=104.50, y=26.00, z=13.50], EntityCreeper['Creeper'/5734, l='MpServer', x=100.97, y=26.00, z=11.50], EntityCreeper['Creeper'/3702, l='MpServer', x=38.33, y=32.00, z=92.74], EntityItem['item.item.seeds'/5751, l='MpServer', x=76.35, y=64.00, z=58.68], EntityBat['Bat'/5821, l='MpServer', x=111.25, y=36.09, z=8.30], EntityEnderman['Enderman'/5954, l='MpServer', x=10.50, y=46.00, z=48.50], EntitySkeleton['Skeleton'/5956, l='MpServer', x=49.50, y=13.00, z=39.50], EntitySkeleton['Skeleton'/6019, l='MpServer', x=12.50, y=45.00, z=43.50], EntityVindicator['Vindicator'/6021, l='MpServer', x=59.32, y=66.00, z=58.30], EntityBat['Bat'/1964, l='MpServer', x=-17.78, y=13.03, z=72.29], EntityBat['Bat'/6141, l='MpServer', x=55.50, y=14.62, z=45.70]]
06:21:14 | game | Retry entities: 0 total; []
06:21:14 | game | Server brand: fml,forge
06:21:14 | game | Server type: Integrated singleplayer server
06:21:14 | game | Stacktrace:
06:21:14 | game | at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
06:21:14 | game | at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
06:21:14 | game | at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
06:21:14 | game | at net.minecraft.client.main.Main.main(SourceFile:123)
06:21:14 | game | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:21:14 | game | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:21:14 | game | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:21:14 | game | at java.lang.reflect.Method.invoke(Method.java:498)
06:21:14 | game | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
06:21:14 | game | at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
06:21:14 | game |  
06:21:14 | game | -- System Details --
06:21:14 | game | Details:
06:21:14 | game | Minecraft Version: 1.12.2
06:21:14 | game | Operating System: Mac OS X (x86_64) version 10.13.5
06:21:14 | game | Java Version: 1.8.0_74, Oracle Corporation
06:21:14 | game | Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
06:21:14 | game | Memory: 378976632 bytes (361 MB) / 1174405120 bytes (1120 MB) up to 2147483648 bytes (2048 MB)
06:21:14 | game | JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
06:21:14 | game | IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
06:21:14 | game | FML: MCP 9.42 Powered by Forge 14.23.5.2772 10 mods loaded, 10 mods active
06:21:14 | game | States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
06:21:14 | game |  
06:21:14 | game | \| State     \| ID            \| Version      \| Source                               \| Signature                                \|
06:21:14 | game | \|:--------- \|:------------- \|:------------ \|:------------------------------------ \|:---------------------------------------- \|
06:21:14 | game | \| UCHIJAAAA \| minecraft     \| 1.12.2       \| minecraft.jar                        \| None                                     \|
06:21:14 | game | \| UCHIJAAAA \| mcp           \| 9.42         \| minecraft.jar                        \| None                                     \|
06:21:14 | game | \| UCHIJAAAA \| FML           \| 8.0.99.99    \| forge-1.12.2-14.23.5.2772.jar        \| e3c3d50c7c986df74c645c0ac54639741c90a557 \|
06:21:14 | game | \| UCHIJAAAA \| forge         \| 14.23.5.2772 \| forge-1.12.2-14.23.5.2772.jar        \| e3c3d50c7c986df74c645c0ac54639741c90a557 \|
06:21:14 | game | \| UCHIJAAAA \| torohealthmod \| 1.12.2-11    \| Damage-Indicators-1.12.2.jar         \| None                                     \|
06:21:14 | game | \| UCHIJAAAA \| waila         \| 1.8.26       \| Hwyla-Mod-1.12.2.jar                 \| None                                     \|
06:21:14 | game | \| UCHIJAAAA \| radixcore     \| 1.12.x-2.2.1 \| RadixCore-1.12.x-2.2.1-universal.jar \| None                                     \|
06:21:14 | game | \| UCHIJAAAA \| mca           \| 1.12.2-5.3.1 \| MCA-1.12.x-5.3.1-universal.jar       \| None                                     \|
06:21:14 | game | \| UCHIJAAAA \| mw            \| 1.11.7.5     \| Modern-Warfare-1.12.2.jar            \| None                                     \|
06:21:14 | game | \| UCHIJAAAA \| zerocore      \| 1.12-0.1.2.2 \| zerocore-1.12-0.1.2.2.jar            \| None                                     \|
06:21:14 | game |  
06:21:14 | game | Loaded coremods (and transformers):
06:21:14 | game | weaponlib (Modern-Warfare-1.12.2.jar)
06:21:14 | game | com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
06:21:14 | game | GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.34.27' Renderer: 'Intel(R) HD Graphics 615'
06:21:14 | game | Launched Version: 1.12.2-forge1.12.2-14.23.5.2772
06:21:14 | game | LWJGL: 2.9.2
06:21:14 | game | OpenGL: Intel(R) HD Graphics 615 GL version 2.1 INTEL-10.34.27, Intel Inc.
06:21:14 | game | GL Caps: Using GL 1.3 multitexturing.
06:21:14 | game | Using GL 1.3 texture combiners.
06:21:14 | game | Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
06:21:14 | game | Shaders are available because OpenGL 2.1 is supported.
06:21:14 | game | VBOs are available because OpenGL 1.5 is supported.
06:21:14 | game |  
06:21:14 | game | Using VBOs: Yes
06:21:14 | game | Is Modded: Definitely; Client brand changed to 'fml,forge'
06:21:14 | game | Type: Client (map_client.txt)
06:21:14 | game | Resource Packs:
06:21:14 | game | Current Language: English (US)
06:21:14 | game | Profiler Position: N/A (disabled)
06:21:14 | game | CPU: 4x Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
06:21:14 | game | [23:21:14] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /Users/fenny/Library/Application Support/minecraft/crash-reports/crash-2018-11-02_23.21.14-client.txt
06:21:14 | monitor | Process crashed with exit code 255

**Comment by rayh206** [comment]
BOI PLZ FIX THIS

**Comment by D1XG0** [comment]
The same thing happens to me! pls

**Comment by D1XG0** [comment]
could you fix it?
