### ISSUE TITLE
Kids won't do chores

### ISSUE THREAD

**Issue by TypicalTelevision** [WildBamaBoy/minecraft-comes-alive#1092]
I have MCA on my server, within two saves, kids inventory "full" or they just won't work. Hope this issue can get fixed soon, I liked getting lazy after having kids lol

**Comment by silverdrake3** [comment]
I'm having the same issue. I asked my daughter to chop wood, and she'll chop one block and say "My inventory is full!" at which point I can repeat the request and she'll chop one more block, then complain about the full inventory again. All she's carrying is an axe, that's it, so she's got plenty of room in there.
She will, however, farm as long as you like.
