### ISSUE TITLE
Avast get triggered

### ISSUE THREAD

**Issue by InterPlay02** [WildBamaBoy/minecraft-comes-alive#1094]
Hello! o/
Really good mod you have here!

Btw: My Avast Free Antivirus is triggered every time I try to download this mod in the Cursemod Download Page. It says that this file is dangerous, and it blocks the download.
(Just so you can know)
[Yeah. My Avast is up to date.]

**Comment by dapurewitch** [comment]
im getting this very same issue! and getting client side crashing if we get near a village so I had to remove it from my server :( I hate playing without it
[crash-2018-12-08_14.12.23-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/2699044/crash-2018-12-08_14.12.23-client.txt)

**Comment by Kardad** [comment]
Unfortunately this is a problem with Avast, not the mod. It sees something it doesn't recognize, so it thinks it's dangerous.

**Comment by Kardad** [comment]
(I'm not a dev, don't ask me for other help)
