### ISSUE TITLE
Invisible Kids

### ISSUE THREAD

**Issue by alphawolf918** [WildBamaBoy/minecraft-comes-alive#1103]
Upon choosing that you have a family, the kids are kinda...not visible. Can't interact with em either. Latest mod version and recommended Forge for 1.12. Tried changing them with the editor, always causes the server to crash. Not sure what to do as there's nothing in the config about it. Was wondering if there was a fix to this. Thanks.

**Comment by atomic-cherry** [comment]
Have this too, though raising a kid from a baby still seems to work.

**Comment by Lupinarius** [comment]
I have also run into this for a VERY long time. I thought it would be fixed by this time.

**Comment by alphawolf918** [comment]
Yeah the mod author is apparently extremely rude and unsupportive. I'm astounded by the way he/she talks to their users.
