### ISSUE TITLE
mca:memorial item crashes game when placed and breaks world

### ISSUE THREAD

**Issue by Trhod17** [WildBamaBoy/minecraft-comes-alive#1105]
Minecraft 1.12.2, MCA 5.3.1, RadixCore 2.2.1
Crashed when placed on ground
[CrashLog](https://pastebin.com/dkj0udDW)

Edit: the only fix i could find is to use mcedit to delete the item

**Comment by LolaFoord** [comment]
This happened to me too! I can’t even play in my world now. Have you fixed the issue or tried contacting the mod creator directly? Please let me know. I made so much progress in my world! :(

**Comment by MentalMouse** [comment]
This is an old bug.  Assuming it's still the same bug, the problem is with looking at the gravestone.  And naturally, when you load up the game, you're back looking at it.  The only fix I found was to go into MCEdit an delete the gravestone.

**Comment by Trhod17** [comment]
The only fix i could find is the same one that MentalMouse said.

**Comment by LolaFoord** [comment]
Thanks, I got my world back.
