### ISSUE TITLE
SOLVED THE CRASHING DUE TO VILLAGES AND VILLAGERS ON SERVERS

### ISSUE THREAD

**Issue by Frogger870** [WildBamaBoy/minecraft-comes-alive#1114]
The basis of this crash was due to the game trying to redirect you to a tutorial, if you go into the mod config in game and disable to tutorial it will not crash anymore

**Comment by ThanksALotFrogger870** [comment]
Thanks you're a real trooper

**Comment by polsust** [comment]
> The basis of this crash was due to the game trying to redirect you to a tutorial, if you go into the mod config in game and disable to tutorial it will not crash anymore

Hi @Frogger870 I'm also struggling with this bug, could you specify a little more what is required to do?
I disabled the tutorial mode on the config and I still get the crash.

**Comment by Frogger870** [comment]
@icoolskeleton95 the specific things I did we're as follows

-disabled turning all old villagers to new

-went into single player to test new villagers spawning

-saw there was a tutorial so I went and disabled that

-went into MP server to test new villagers spawning and used the crystal ball to test tutorial

**Comment by iCoolSkeleton95** [comment]
Thanks, so I was disabling the tutorial mode on the server and the client, but I found that just disabling it on the client and not on the server config worked for me.

**Comment by polsust** [comment]
I tried disabling the tutorial mode on the client but not on the server. It worked once but then at the restart of the server it crashed. For some reason this does not work for me.

**Comment by Rambut** [comment]
Having the same issue they need to fix it. Is the dev even active anymore?

**Comment by mightyjaffa12** [comment]
dam i wish this would get fixed

**Comment by ielenia** [comment]
It's been over a year since the last commit and release, I think that it's in the public domain according to the licence now
