### ISSUE TITLE
Married To ? issue happening 

### ISSUE THREAD

**Issue by Hyperleogamer** [WildBamaBoy/minecraft-comes-alive#1117]
Im playing witha  freind we are using digimobs as well we are in the digimobs world and we use this right 
1.12.2 btw and we get through the thing but it teleports my freind and not me he picks i live alone BUT it says when i right click them Married To ? and when i click ask to marry it says "therin3 is already married"

**Comment by Trhod17** [comment]
use the command /mca rm <username> to remove marriages (this is a bug that has been around for ages)
