### ISSUE TITLE
Help with the name on minecraft comes alive mod. 

### ISSUE THREAD

**Issue by OJTheGaming** [WildBamaBoy/minecraft-comes-alive#1121]
With the chrystal ball, I type in my name but It goes out as "none". and I can't pick if I have a family or any of those options. What Is going on, can you help me?

**Comment by MentalMouse** [comment]
Are you in single-player?  The crystal ball doesn't work in multi-player, including LAN games.

**Comment by OJTheGaming** [comment]
I’m in single player

**Comment by MentalMouse** [comment]
Iduno then.
