### ISSUE TITLE
TICKING WORLD

### ISSUE THREAD

**Issue by RodrigoTaipe93** [WildBamaBoy/minecraft-comes-alive#1127]
There seems to be an issue with the mod:

- https://paste.dimdev.org/lazetuqomi.mccrash

**Comment by camatthew** [comment]
Update to the latest version of forge. It works now with forge lates

**Comment by camatthew** [comment]
> There seems to be an issue with the mod:
> 
> * https://paste.dimdev.org/lazetuqomi.mccrash

Clos
