### ISSUE TITLE
Unsure how to disable rose gold ore spawning(if it's possible)

### ISSUE THREAD

**Issue by Not-February** [WildBamaBoy/minecraft-comes-alive#1134]
Given that recipes/functions in all versions of MCA that I can think of generally have rose gold as an **option** and are not required to use the mod's content, as a pack developer who likes to make custom recipes and such I would appreciate an easy, user-friendly way to turn off rose gold ore generation.

I tried setting the config weight to '0' last night while using the 6.0.0 beta on curse, but it's still spawning in-world. Is there another value I should be putting into that to disable it altogether? And maybe if there already is such a function, it could be wise to document it in the config file itself, like "set to VALUE to disable spawning altogether". It'd save a lot of headaches, anyways.

Excited to see this mod being worked on again after such a long time!

**Comment by WildBamaBoy** [comment]
I'll make this configurable. 👍
