### ISSUE TITLE
Upgrading to 6.0 causes failure to initialize

### ISSUE THREAD

**Issue by threeringserkus** [WildBamaBoy/minecraft-comes-alive#1139]
Basically title. 

Log returns error "Caused by: java.lang.NoClassDefFoundError: org/apache/http/client/HttpClient
    at mca.core.MCA.preInit(MCA.java:104) ~[MCA.class:?]"

Full log paste located here https://pastebin.com/1XGZhL4A

Really looking forward to getting this on our server. MCA has been my favorite mod since I discovered it on some old technic pack I cant remember the name of

**Comment by alphawolf918** [comment]
Having this same issue. I'm sure it's nothing major but would like a fix please - thank you for updating the mod.

Edit: Crash Report -> https://pastebin.com/UHCFuexs

**Comment by WildBamaBoy** [comment]
Download the hotfix from here: https://minecraft.curseforge.com/projects/minecraft-comes-alive-mca/files/2719010#additional-files
