### ISSUE TITLE
[1.12.2] [Bug] 6.0 causes server crash during Pre-Init

### ISSUE THREAD

**Issue by alphawolf918** [WildBamaBoy/minecraft-comes-alive#1140]
Crash Report -> https://pastebin.com/UHCFuexs

Basically looks like it's trying to look for something on the client via server, that or possibly something in the classpath? Not certain. Works fine in single player and looks very good, love the "Go Home" feature and the rewrite in general. Seeing as how this is in beta I expected bugs anyway, but am very grateful that the mod is being updated. I'm sure it's nothing big. Thank you.

**Comment by WildBamaBoy** [comment]
Download the hotfix here: https://minecraft.curseforge.com/projects/minecraft-comes-alive-mca/files/2719010#additional-files
