### ISSUE TITLE
I can only partly interact with my villagers

### ISSUE THREAD

**Issue by KeyboardHero22** [WildBamaBoy/minecraft-comes-alive#1141]
I'm using MCA 1.12.2, and for some weird reason, there is no kiss, hug, or flirt option for any of my villagers except for one, and all of them are adults.

Also, when I try to give an unmarried villager with 5 gold hearts an engagement ring, it says they don't know what it is or why I'm giving it to them.

**Comment by WildBamaBoy** [comment]
Are you using any other mods alongside MCA?

**Comment by WildBamaBoy** [comment]
Found a potential issue. 64342a923e3bee0d2cd881f681137599b2dcdd2c should help when the update is released.
