### ISSUE TITLE
Suggestion: Villagers store the in-game time they were born, can use for age instead of ticks alive

### ISSUE THREAD

**Issue by jtnicholl** [WildBamaBoy/minecraft-comes-alive#1142]
If villagers stored the in-game time they were born (what you see with the /time query command) this could be used as an alternative way to get their age instead of the number of ticks they've existed. This would have a few advantages: they would continue to grow even when they are not in a loaded chunk, and they would grow overnight when you slept in a bed.

This of course would also have a disadvantage in that rolling time backwards with /time set would probably break things. You would have to only use /time add if you wanted to switch between day and night. As such it might not be a bad idea to store both ticks alive and time of birth and have a config option for which to use. You would also probably want to make aging really slow for an always-on multiplayer server, but there's already a config option for that.

**Comment by WildBamaBoy** [comment]
MCA uses Minecraft's built-in system for aging - the same as animals and such. I really don't want to roll my own, unfortunately.
