### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by VictoriousLoL** [WildBamaBoy/minecraft-comes-alive#1144]
Pretty simple issue - server crashes on start up. It seems as though there's been issues like this exact one before and it was never fixed.

Full Crash Log: 

https://pastebin.com/Fjgh8f6S

Shouldn't be a compatibility issue as I can start up a Single Player World with no issue whatsoever, but a Dedicated Server crashes.

**Comment by WildBamaBoy** [comment]
https://github.com/WildBamaBoy/minecraft-comes-alive/issues/1140
