### ISSUE TITLE
Villager doesn't move, cannot work or procreate

### ISSUE THREAD

**Issue by jambajules** [WildBamaBoy/minecraft-comes-alive#1146]
I tried to use procreate with my villager who I am married to, nothing happened, so I did /mca procreate it says 'Your spouse is not present on this server.' I'm sure I married the villager, it says we're married and when I try proposing he says we already have married. I gave him a fishing rod and tried to send him to fish but he stayed still. He only moves when I put him in following mode. I am using forge 1.12.2, and the mod is meant for 1.12.2, I am also running the Chisels & Bits mod, MrCrayfish's Furniture Mod, More Player Models, and worldedit. Also this is a singleplayer world, I built a house separate from a village and lead the villager to the house.

Edit: Just tried to spawn a baby and turned the age up time to 1 minute. had the baby for 10 minutes and didn't even spawn, though I was able to name it.

**Comment by WildBamaBoy** [comment]
What is the villager's profession?

**Comment by threeringserkus** [comment]
Hello, I have a similar issue. The villager was originally a priest. I figured that may have been the issue so I switched her to a baker. No luck.

**Comment by WildBamaBoy** [comment]
#1148
