### ISSUE TITLE
6.0.0 Beta - I can't procreate with my Wife

### ISSUE THREAD

**Issue by frqnny** [WildBamaBoy/minecraft-comes-alive#1148]
As weird as it sounds, every time I clicked the button it doesn't procreate; she doesn't spin or react to it. 
Her profession is a warrior.

**Comment by frqnny** [comment]
Duplicate of #1146 

Commands: /mca procreate says "Your spouse is not present on the server."

**Comment by WildBamaBoy** [comment]
Known issue with warrior professions.
