### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by dietandry** [WildBamaBoy/minecraft-comes-alive#1150]
https://pastebin.com/r8ZdT7XE - Log
I can start the Minecraft client, but the server crashes upon starting. The log above contains the errors it throws.

**Comment by nickBnbradham-zz** [comment]
Same exact problem. I thought that I found a work around by including the library in the class path at server launch, but for some reason it didn't work.

**Comment by WildBamaBoy** [comment]
Download the server hotfix version from Curse.
