### ISSUE TITLE
Heroes keep drowning

### ISSUE THREAD

**Issue by PurpleHel** [WildBamaBoy/minecraft-comes-alive#1151]
I have villages that spawn in open ocean (cos I like it that way), and I keep finding Heroes and Warriors drowning under walkways because they can't find their way out from under and back to open water. They also like to jump off walkways and cut across open water instead of following the walkway, which makes it that much more likely they get stuck under the walkway and drown.
Using 1.12.2 and MCA 6.0.0-beta

**Comment by WildBamaBoy** [comment]
Fixed with guard AI/procreation. Will be in 6.0.0
