### ISSUE TITLE
another skins glitch

### ISSUE THREAD

**Issue by onlythisonetimemkay** [WildBamaBoy/minecraft-comes-alive#1152]
the child skins don't work exactly. I got that pink and black missing texture.
the crash report is as follows but one of my other mods is probably conflicting with it maybe? Idk, I don't know java. in the meantime, I just won't have children.
edit: added screenshot; see below.
![2019-06-16_20 54 08](https://user-images.githubusercontent.com/51889291/59568851-ff95e680-9078-11e9-8431-3efa655b8bb3.png)

### ---- Minecraft Crash Report ----

WARNING: coremods are present:
  DLFMLCorePlugin (DynamicLights-1.12.1.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 6/16/19 8:39 PM
Description: Exception in server tick loop

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at mca.packets.PacketEditVillager.processOnGameThread(PacketEditVillager.java:118)
	at mca.packets.PacketEditVillager.processOnGameThread(PacketEditVillager.java:23)
	at radixcore.modules.net.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:174)
	at radixcore.core.RadixEvents.serverTickEventHandler(RadixEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_RadixEvents_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 891875352 bytes (850 MB) / 1879048192 bytes (1792 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version      | Source                                        | Signature                                |
	|:------ |:--------------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                   | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                         | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                         | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                       | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | biomesoplenty               | 7.0.1.2441   | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| LCHIJA | dynamiclights               | 1.4.9        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_onfire        | 1.0.7        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_creepers      | 1.0.6        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_dropitems     | 1.1.0        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_entityclasses | 1.0.1        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_mobequipment  | 1.1.0        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_flamearrows   | 1.0.1        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_floodlights   | 1.0.3        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_otherplayers  | 1.0.9        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | dynamiclights_theplayer     | 1.1.3        | DynamicLights-1.12.1.jar                      | None                                     |
	| LCHIJA | eyemod                      | 1.1.0        | eyemod_112_v6.3.jar                           | None                                     |
	| LCHIJA | familiarfauna               | 1.0.11       | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
	| LCHIJA | waila                       | 1.8.26       | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | lucky                       | 7.6.0        | luckyblock-1.12.2-7.6.0.zip                   | None                                     |
	| LCHIJA | radixcore                   | 1.12.x-2.2.1 | RadixCore-1.12.2.jar                          | None                                     |
	| LCHIJA | mca                         | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar                | None                                     |

	Loaded coremods (and transformers): 
DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Redacted'/19036, l='Mods Test', x=1612.90, y=64.00, z=1536.43]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by WildBamaBoy** [comment]
MCA 5.3.1 is no longer supported.
