### ISSUE TITLE
Villagers killing each other after editing

### ISSUE THREAD

**Issue by Hentaliah** [WildBamaBoy/minecraft-comes-alive#1154]
I made sure to only be playing with MCA.
After editing my villager's profession specifically, other villagers would rush in to kill them. This usually happens when I'm cycling through the professions and an enemy profession comes up. (e.g. Outlaw.) Even if I click change profession again and change it, the villager gets killed by the others. 
The other villagers who kill the edited villager are not always Guards/Archers etc. They just beat him/her to death.

Any ideas on how to avoid this?

Edit to add: Just found that the edited villagers can also start killing the other villagers, regardless of whether or not I give them a friendly profession. Also, the villagers do not kill the edited villager every time I edit them. It seems to be a 50/50 from what I've seen so far.
Edit 2: Edited villagers may also kill the player. It seems the evil tag (For lack of a better word) does not get removed, even if the profession is changed while editing.

**Comment by WildBamaBoy** [comment]
Fixed in f1dd6a0d
