### ISSUE TITLE
Suggestion: Allow MCA villagers to sit in and maybe use modes of transport from other mods

### ISSUE THREAD

**Issue by SanjivanM** [WildBamaBoy/minecraft-comes-alive#1156]
So if I were to use a boat (Vanilla or IC2), or a vehicle from MTS (https://minecraft.curseforge.com/projects/minecraft-transport-simulator), my spouse and/or kids would get in with me, assuming that there is space left to accommodate them, e.g. more seats.  This would greatly add to the (already) immersive experience that MCA provides, and would also make it seem more realistic.

**Comment by frqnny** [comment]
^^^^ Maybe instead of the "ride horse" option, it is just "Ride" and it lets the villager enter the nearest minecart/horse/etc?

**Comment by WildBamaBoy** [comment]
So there unfortunately doesn't seem to be a way for me to identify when a particular entity is mountable at this time. With this being the case I wouldn't be able to enable compatibility on mounting entities added by other mods.
