### ISSUE TITLE
Nobody accepts my matchmakers rings?

### ISSUE THREAD

**Issue by DroppedSignal222** [WildBamaBoy/minecraft-comes-alive#1161]
Nobody will accept my matchmakers rings. im trying to marry off my children, i put a villager beside them and give one a set of two rings. they never accept. why?

**Comment by WildBamaBoy** [comment]
Using any other mods?

**Comment by WildBamaBoy** [comment]
Confirmed working in a recent build. If you use any other mods let me know.

**Comment by Simm01** [comment]
i found a fix (or at least what work for me) if the villagers that you are trying to marry are saying they are too far away, make sure that you don't have anyone else following you. I had 4 people from and old village that i was bring back to mine and they did not keep up so i thought nothing of it. I ended up going back finding the 4 and killing them and it worked. I know this thread is old figured id give a fix if it happens to anyone else.
