### ISSUE TITLE
Gifted Baby to Spouse 6.0.0

### ISSUE THREAD

**Issue by Catodotjpeg** [WildBamaBoy/minecraft-comes-alive#1162]
I probably should have just placed the baby in my spouse's inventory, but if you gift your baby to them they will say they don't want your trash, and the baby will be lost. Unfortunately since the clerics don't currently do adoptions/resets I'm not sure if there's a way to have another baby with my spouse, since they think I still have the baby. 

But then again after the last one they probably shouldn't trust me with a new one lol 

Version is 6.0.0, and while I do have other mods installed I don't think any of them specifically effect this. Please let me know if you need a mod list. 

Thanks!

**Comment by WildBamaBoy** [comment]
Fixed in a previous commit, will be present in 6.0.0
