### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by frqnny** [WildBamaBoy/minecraft-comes-alive#1168]
Build from the latest bugfixes on this github repository at the time of creation. 
https://paste.dimdev.org/juhimejoba.mccrash

**Comment by Hydraheads** [comment]
I am experiencing this same crash constantly now too, same version

it happens upon loading in an area with villagers via starting up game or tping to someone for me, possibly even just going into a village rarely

**Comment by WildBamaBoy** [comment]
Adding some additional logging here as I can't seem to reproduce this problem.
