### ISSUE TITLE
Can't Have Kids

### ISSUE THREAD

**Issue by Icesong324** [WildBamaBoy/minecraft-comes-alive#1169]
I have the beta version of the mod and I try to have a child with the villager I'm married to but it doesn't show any indication that it worked or show that a child has come into my inventory. Is there a way to fix this?

**Comment by WildBamaBoy** [comment]
Is your spouse a guard? That's typically the issue and will be fixed in the next release.

**Comment by Icesong324** [comment]
That was the case thank you!
