### ISSUE TITLE
Having some trouble with recipies

### ISSUE THREAD

**Issue by ChiyoSumizome** [WildBamaBoy/minecraft-comes-alive#1170]
I have been playing MCA with no issues, but I wanted to make a needle. I checked the crafting recipes, and I tried making a needle but it didn't work. I also tried creating a diamond cutter, using the same recipe that is on the main page, but it didn't work! I need help. I just wanna make a new outfit for my husband and children.

**Comment by WildBamaBoy** [comment]
These are not present in 6.0.0

**Comment by ChiyoSumizome** [comment]
> These are not present in 6.0.0

Oh, well darn. Didn't know that. Thanks.
