### ISSUE TITLE
Miscellaneous Issues & Beloved Features 6.0.0-beta

### ISSUE THREAD

**Issue by solynmc** [WildBamaBoy/minecraft-comes-alive#1171]
I've always been a huge fan of MCA so I'm really excited about it getting worked on again! That being said, I've been playing with it for the past couple hours and I've noticed some things.

1. First and foremost, the config. I'm able to edit it while in-game through Mod Options, but the changes don't take effect. When I reset my game, the changes roll back to default config. It only works if I manually edit the config file.

2. When I give cake to villagers and they have a baby, sometimes (after placing the baby) it is already fully grown. This happens with the first, but subsequent children start off small and progress to adulthood as they should.

3. Archers carry swords and warriors carry bows.
![Screenshot 2019-07-05 06 07 26](https://user-images.githubusercontent.com/52566824/60715811-ecde3700-9eeb-11e9-9dc8-022bbd0cef53.png)

4. Female spawn eggs sometimes create villagers with male skins, and vice versa. I'm not sure if the villager is actually male or female.

5. The randomization of the village editor is a problem. When changing a villager's profession, there is a chance of making them a Marauder, Pillager, or Outlaw. Even after I change them to something else (like Farmer) they will continue to attack whoever their target became in the instant they were an aggressive profession. I had an instance where a man killed his wife because he was a Marauder for a moment.

6. Additionally, changing professions does not change what they trade. They will continue to provide the same trades as their initial profession. I'm not sure if this can be fixed but I thought it good to note.

That being said, I know this is a beta version that's being reworked completely (and thank goodness, since it used to crash a lot!) There's certainly a lot missing in this version that I hope will make a return in the future!

Missed Features/Suggestions:
- Divorce (Player/NPC + NPC/NPC)
- Personalities/Moods (Even if they no longer affect interactions!)
- Villagers Sleeping in Beds (Eyes don't _need_ to be closed)
- Automatic Progression (I'm not sure if this feature is missing but I haven't noticed it happen in my testing. If this does come back [auto-marriage and procreation] I hope there's an anti-incest feature, since in the last version I had problems with my children marrying each other)
- (I can't imagine this will happen anytime soon or that it would be a simple task to code, but) Family trees! The ability to see how many children/grandchildren a villager has, if their brother has gotten married yet, etc.
- The Height/Width Customizations in Villager Editor
- A "nickname" system that villagers will call you instead of your username (not super romantic when your spouse calls you SonicLover69 right?)
- When entering just "/mca" or "/mca-admin," the message that appears should include that "/mca help" and "/mca-admin help" are options that provide command codes.
- The ability to see if a villager is married without opening their menu, somehow? Maybe two golden pixels on their left hand, assuming that wouldn't look too intrusive?
- More config options (someday)!

New Features I Love:
- 64x64 skins! It works and it looks great!
- Villager jobs stated above their head! Green for protectors/red for attackers!
- Radixcore no longer a dependency! Woo!
- Reviving any villager without needing a memorial item!
- Babies growing to adults slowly over time!
- All the fixes! That must've been a lot of work!

This is plenty wordy, so let me just say thank you so much for continuing to work on my absolutely favorite mod! You're the best!!!

**Comment by WildBamaBoy** [comment]
Thank you for the feedback! I really appreciate it. Most of the concerns here have already been fixed, so I will mark this as closed. To address them:

1. Sounds like you have an old configuration from MCA 5. Delete the configuration file and relaunch the game, you should be good to go.
2. This has been fixed with the release version.
3. This has been fixed with the release version.
4. This has been fixed with the release version. 
5. I have reworked this for the release version.
6. Good catch - I'll see what I can do.

Thank you again!
