### ISSUE TITLE
Children are never ready to grow up?

### ISSUE THREAD

**Issue by Owen1212055** [WildBamaBoy/minecraft-comes-alive#1172]
![2019-07-05_20 45 59](https://user-images.githubusercontent.com/23108066/60749314-f1dfcc80-9f65-11e9-93e2-7d2b802a60bb.png)

**Comment by Owen1212055** [comment]
This was on my multiplayer world with my family. All of them reported this issue too.

**Comment by WildBamaBoy** [comment]
I was unable to reproduce this issue. I would suggest trying with only MCA installed first.
