### ISSUE TITLE
Server-Side Crash on Startup

### ISSUE THREAD

**Issue by Nocturne705** [WildBamaBoy/minecraft-comes-alive#1173]
Could be another mod interfering, but the client side with identical mods starts correctly, and the server crashes during startup.  Crashlog attached.
MCA 5.3.1 + RadixCore 2.2.1 loads correctly on the server. When upgrading to MCA 6.0 + No RadixCore the crash manifests.
[crash-2019-07-05_23.19.29-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/3364374/crash-2019-07-05_23.19.29-server.txt)

**Comment by WildBamaBoy** [comment]
Duplicate issue. Use the hotfix version which is an additional download on Curse.
