### ISSUE TITLE
Missing Villager Bed??

### ISSUE THREAD

**Issue by SpadezyMex** [WildBamaBoy/minecraft-comes-alive#1176]
Hello, I have a problem I was trying to create a Villager Bed for the villagers to sleep, but when I tried making the bed nothing pops up... I used creative mode to see if there is a Villager bed in this mod section but apparently there isn't one?... It says you can make a villager bed using a bed and a carpet.. Please help.. Thank you.

![2019-07-15_15 21 46](https://user-images.githubusercontent.com/47359633/61200520-4b898900-a714-11e9-9204-445422e4cce3.png)

**Comment by WildBamaBoy** [comment]
Villager beds have been removed from MCA 6.
