### ISSUE TITLE
NPCs are invisible.

### ISSUE THREAD

**Issue by TheReddest339** [WildBamaBoy/minecraft-comes-alive#1177]
For some reason, some NPCs are invisible. Here's a few captures:
![2019-07-18_09 18 21](https://user-images.githubusercontent.com/52831497/61441542-c386c780-a93d-11e9-8827-f14c7f156814.png)
![2019-07-18_09 18 45](https://user-images.githubusercontent.com/52831497/61441544-c386c780-a93d-11e9-8662-c27306b3fac3.png)

Here's the mods that I have:
![image](https://user-images.githubusercontent.com/52831497/61441678-08aaf980-a93e-11e9-9394-e8ce10165739.png)

**Comment by TheReddest339** [comment]
Could anyone tell me what's wrong?

**Comment by InfernalSkys** [comment]
You're using the old version of MCA, make sure you download MCA beta version 6.0.0 from the official page.
Radixcore is also not needed anymore.
