### ISSUE TITLE
Guard/Hero/etc. AI has Delayed Responses to Threats

### ISSUE THREAD

**Issue by Viosmic** [WildBamaBoy/minecraft-comes-alive#1178]
Guard-type villagers refrain from attacking threats such as zombies even while being attacked, whereas other villagers will quickly run away. Sometimes the delay is so long that the guard-type villagers will end up in dangerously low health, or dead, before they react.

**Comment by WildBamaBoy** [comment]
Priority has been bumped on the AI handling defending, so this should be much better on the release version.
