### ISSUE TITLE
Don't have a crystal ball

### ISSUE THREAD

**Issue by yaypain** [WildBamaBoy/minecraft-comes-alive#1182]
I've tried to look this up but couldn't find anything. When I spawn in- the crystal ball isn't in my inventory? am I doing something wrong?

**Comment by RenaRena91** [comment]
Same problem here. Tried making other worlds with different settings but nothing worked. I've downloaded the latest file with latest forge.

**Comment by Alfadelta9** [comment]
Take a look at the changelog: "Changed: The crystal ball and setup menu is no longer required"

**Comment by RenaRena91** [comment]
> Take a look at the changelog: "Changed: The crystal ball and setup menu is no longer required"

I don't get it. Required for what?

**Comment by Alfadelta9** [comment]
You can start interacting with villagers without the needing of the crystal ball and the setup menu. In past versions you needed to set your gender, destiny, etc.

**Comment by RenaRena91** [comment]
> You can start interacting with villagers without the needing of the crystal ball and the setup menu. In past versions you needed to set your gender, destiny, etc.

Oh, I just wanted it because I like how it set up a village or house for me and put NPCs on a cool looking area that I find. I guess I gotta find a village myself now.
