### ISSUE TITLE
Villagers not reacting to move orders; Can´t marry villagers; Every villager is 'my child'

### ISSUE THREAD

**Issue by Alfadelta9** [WildBamaBoy/minecraft-comes-alive#1183]
Villagers just wander around even if I order them to "Follow Me" or "Go Home", they only seem to react to the "Stay Here" order. Also, they tend to go outside villages and get lost or killed by mobs.

Moreover, I can´t marry villagers. Even if they got 1000 hearts I always get the following line in the chat: "adult.interaction.marry.fail.marriedtogiver" although my player isn't married. 

Finally, whenever any villager die I get notified as a child death. The chat goes like this: "Your child *Villager Name* has died by *Mob Name*"

**Comment by WildBamaBoy** [comment]
Are you using any other mods?

**Comment by Xboxdestructor** [comment]
yeah im having the same issue with not being able to marry. its saying im married to someone else. the other mods i have installed are "codechickenlib, CustomNpcs, Ichun, jei_, llibary, Mo_Creatures, Morphing Mod, optifine, and Radixcore" also im in 1.12.2

**Comment by Alfadelta9** [comment]
I'm  not running any other mods

**Comment by WildBamaBoy** [comment]
Please attempt to reproduce this issue and provide a download for your saved game.

**Comment by Prizracoss** [comment]
Аnd how to solve this problem?

**Comment by puperto87** [comment]
hola lo que pasa es que cuando me quiero casar me dise adul.interaction.marry.fail.marriedtogiver
