### ISSUE TITLE
crystal ball not appearing?

### ISSUE THREAD

**Issue by yessssssssssss** [WildBamaBoy/minecraft-comes-alive#1184]
i was trying to play mca on 1.12.2 but everytime i load in, the crystal ball wont appear, i tried redownloading and everything, yet to no avail , it still won't show. happen to anyone else?

**Comment by Alfadelta9** [comment]
Take a look at the changelog: "Changed: The crystal ball and setup menu is no longer required"

**Comment by yessssssssssss** [comment]
oh okay , thank you so much !! :^) can i just download an earlier version
to get it then?

**Comment by Alfadelta9** [comment]
As far as I know yes. Earlier versions besides 6.0.0 and 6.0.0 beta should have the crystal ball

**Comment by yessssssssssss** [comment]
earlier version worked! thank you so much!!

**Comment by Alfadelta9** [comment]
No prob :) now if your issue is solved please close this thread.
