### ISSUE TITLE
Can’t Marry Other Players or Place Babies

### ISSUE THREAD

**Issue by ninagaf** [WildBamaBoy/minecraft-comes-alive#1185]
I’m playing in 1.12.2 on a single player world which I occasionally open into a LAN and wasn’t able to use the ring to marry another player or have children with the other player which I believe is possible. When marrying a villager I was able to have a baby but after 10 minutes was not able to place it in the world. I’m playing with some other mods is that the problem? are any of these known to affect MCA?
-morph
-backpacks
-Pam’s harvestcraft
-mo creatures
-Pam’s flowers
-JEI
-Xaero’s Minimap
-anamania
-tree chopper

**Comment by WildBamaBoy** [comment]
Use the `/mca` commands. Use `/mca help` for more details.
