### ISSUE TITLE
Babies not growing

### ISSUE THREAD

**Issue by Dysastus21** [WildBamaBoy/minecraft-comes-alive#1186]
so ive been playing around with this mod for a couple days, and i gotta say thats its great not having to hear the annoying vanilla villager noise or see their noses, but im having issues with the babies. they just won't grow up. Im not in creative mode and ive set the grow up time to 10 minutes but they still wont grow up. Im using the latest release of MCA non beta version

**Comment by WildBamaBoy** [comment]
After you see "Ready to Grow" while hovering over the baby, right-click the ground to spawn it.
