### ISSUE TITLE
cant give npcs skins

### ISSUE THREAD

**Issue by Oceandud** [WildBamaBoy/minecraft-comes-alive#1188]
whenever i try to give an character a custom skin it glitches out and changes the textures spots the body of the character is where the head is supposed to be and there are no legs body or arms
![what](https://user-images.githubusercontent.com/53288217/61846917-e4d44000-ae76-11e9-9378-ac5888af0492.JPG)

**Comment by WildBamaBoy** [comment]
You must use the new 64x64 skin format.
