### ISSUE TITLE
Cannot create a mine, can only prospect

### ISSUE THREAD

**Issue by sylentwrath** [WildBamaBoy/minecraft-comes-alive#1192]
My child does not have the option to create a mine, only prospect. unsure of what i need to provide for this regarding logs, but im using the newest version from curseforge that does not require the additional download. any ideas?

**Comment by simply-existent** [comment]
In the 6.0.0 Beta changelog, it says:

> Changed: Mining is now called Prospecting.

That's what mining is called now, apparently.

**Comment by MrMicrobe23** [comment]
Not the issue they were stating, the mine cannot be created in order for the villagers to do the chore asked

**Comment by MrMicrobe23** [comment]
they did not ask what the name changed to as that is irrelevant

**Comment by WildBamaBoy** [comment]
Mining is now called Prospecting, as such, they will only prospect for new ores. Mines are no longer created.
