### ISSUE TITLE
Can't interact with villagers

### ISSUE THREAD

**Issue by ErayRonald** [WildBamaBoy/minecraft-comes-alive#1193]
so i am using a modpack called ftb interactions and the mod does fully work when using on a server with only the minecraft comes alive mod.
so i guess a different mod is interfering with it.
my question is , how can i find out what mod is doing this?
or is it the controls??

**Comment by WildBamaBoy** [comment]
What version of this modpack are you using?

**Comment by ErayRonald** [comment]
> 
> 
> What version of this modpack are you using?

i tried 6.0 and .5.3.1
and ftb version was 1.9.1

**Comment by WildBamaBoy** [comment]
Did both versions of MCA have this issue?

**Comment by ErayRonald** [comment]
> 
> 
> Did both versions of MCA have this issue?

yes

**Comment by ErayRonald** [comment]
help kevin
