### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by duhnunes** [WildBamaBoy/minecraft-comes-alive#1194]
Hello @WildBamaBoy , I noticed that old translations no longer work(crowding), and are not included within .jar, so I took the original content and duplicated it and translated it to my language pt_br, but there is something wrong. Some things like items (Staff of Life, Books, Spawn Villager etc ..) have been translated, but the interaction parts with the characters and their phrases have not been translated.

**Comment by WildBamaBoy** [comment]
Closing as a PR is active
