### ISSUE TITLE
Special either isn't available or doesn't work properly.

### ISSUE THREAD

**Issue by BURNINGSHADOW278** [WildBamaBoy/minecraft-comes-alive#1197]
I have this problem with the new version of MCA (6.0.0) on minecraft 1.12.2 but also on the older version 5.3.1 but also on the 5.2.3 version on minecraft 1.10
so the problem is:
if I want to hire a villager to do something for instance: mine.
I find a miner or make one click on special and I can hire this villager that part work fine I can choose to hire it for 1, 2 or 3 hours. the problem then is that there are no other option I can't tell the villager to go mine it will just do nothing for an hour.
there are also villagers like a guard that don't have any options when you click on special you can't hire them at all even though the wiki says they are supposed to be able to hunt for you.
I don't have much problem with this though my biggest problem is hiring a villager but getting nothing in return.

Am I missing something? or can I get it working somehow.
Sincerely, Noah

**Comment by WildBamaBoy** [comment]
Special is not available on 6.0.0.
