### ISSUE TITLE
Marriage Issues

### ISSUE THREAD

**Issue by Gabby2805** [WildBamaBoy/minecraft-comes-alive#1201]
I start the game, both single player and server, 'married to ?'.
I got divorced by a cleric and was able to get engaged to a villager, now I want to marry him...but he says he's already married.
I'm using 5.3.1, is there a way round this? Perhaps a command or a config file? Last time I tried updating it deleted all my villagers and I've put a lot of work into building a village and building relationships.

**Comment by duhnunes** [comment]
versions prior to 6.0.0 are no longer supported
( https://github.com/WildBamaBoy/minecraft-comes-alive/issues/1130#issue-451146860 )

> All previous issues in this repository created before this one have been closed. MCA has been rewritten from scratch thus invalidating all previous issues and pull requests.
> 
> For any new issues going forward, report only problems with version 6.0.0.

 I didn't notice problem with marriage with the new MCA.
But if so, type "/ mca-admin help" to see more options... (MCA 6.0.0)
