### ISSUE TITLE
Villagers don't procreate with each other

### ISSUE THREAD

**Issue by TsundereMatrix** [WildBamaBoy/minecraft-comes-alive#1202]
I am playing on 1.12.2. I can marry villagers and able to procreate with the one I marry myself and marry them with a matchmaker's ring just fine but they never procreate by themselves. My village of maybe 10 villagers is now down to 3 villagers. I married 2 of them with the matchmaker's rings and they don't do anything. I even added more doors and buildings to the village but still no offspring. 

In other villages, I noticed that many villagers wonder far away from their village for no reason. Probably because they have no set home point.

**Comment by WildBamaBoy** [comment]
You must force them to procreate with each other by gifting them cake.
