### ISSUE TITLE
Player to player

### ISSUE THREAD

**Issue by SandyyChan** [WildBamaBoy/minecraft-comes-alive#1203]
A few friends of mine made a server and another friend wanted to do the 100 baby challenge but when we got the first kid and waited for 30 minutes we tried again and this error kept on popping up. "You already got a child" so we waited until he was an adult and tried again the same error again. "You already got a child." Hopefully this will help you to fix this issue. This was on a minecraft server as well.

**Comment by WildBamaBoy** [comment]
What version of MCA?

**Comment by SandyyChan** [comment]
The newest version of MCA

Sent from Yahoo Mail on Android 
 
  On Sat, Aug 17, 2019 at 7:32 PM, Dusty A<notifications@github.com> wrote:   
What version of MCA?

**Comment by Wolfan01** [comment]
Hi. please I have the same issue, can I have an answer me too, I can't have anymore baby

**Comment by WildBamaBoy** [comment]
Please attempt to reproduce this and include a download for your saved game.
