### ISSUE TITLE
Modded Mob interactions (Mod added Hostiles Ignoring villagers, and vice versa)

### ISSUE THREAD

**Issue by GeflGabe** [WildBamaBoy/minecraft-comes-alive#1204]
The gist is that MCA villagers don't interact with many modded mobs (Such as enemies from Techguns.), I may be wrong, but it might have something to do with things regarding custom AIs versus Vanilla AIs. I would also like to suggest bringing back at least the villager health in the configs, since it's particularly useful for making sure villagers can be balanced with any mod that adds new enemies.

A smaller issue I have also noticed that when spawning in villagers via MCA male and female spawn eggs, it will sometimes also produce a "dead" or frozen vanilla villager entity where they were spawned.

As a sidenote, I just want to say, I love what you've guys done to rebuild this mod, and it's insane how you guys integrated any possible modded careers such as the Engineer from Immersive Engineering, or the Jam guy from Actually Add-ons. The NPCs sizes are also a lot more consistent. Thank you for making this wonderful mod, I almost never play 12.2 without it installed, and I hope to see it grow even further from now.

**Comment by WildBamaBoy** [comment]
Thank you for the kind words! We will see what can be done regarding defending against modded creatures.

**Comment by WildBamaBoy** [comment]
- [x] Add villager health configuration option 
- [x] Guards should attack other creatures that attack them (for modded compatibility)
