### ISSUE TITLE
MCA villagerMCA can't summon

### ISSUE THREAD

**Issue by soyelchecho** [WildBamaBoy/minecraft-comes-alive#1206]
I can't spawn villagers by command in minecraft
I need to spawn a mcavillager with a name but with the /summon command it is impossible.

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:
1. Launch Minecraft
2. Create a Creative World
3. open chat
4. write /summon mca:villagermca ~ ~ ~
5. down enter and it doesn't generate/spawn the village

**Minecraft Information (please complete all questions entirely):**
 - Minecraft Version: 1.12.2
 - Forge Version: 1.12.2 - 14.23.5.2768
 - MCA Version: MCA-1.12.x-5.3.1
 - Launcher: FenixLauncher

I need to spawn a custom mca villager if someone know how it is possible, pls tell me, I tried to found a solution but there aren't issues or docummentation about that :/
 
thank.

**Comment by duhnunes** [comment]
Well, you can get into the creative(or JEI) and get the villager "egg" (pink for female, blue for male) to generate 1 MCA villager.
To edit the villager, you take the book "villager editor" and customize it

**Comment by soyelchecho** [comment]
> 
> 
> Well, you can get into the creative(or JEI) and get the villager "egg" (pink for female, blue for male) to generate 1 MCA villager.
> To edit the villager, you take the book "villager editor" and customize it


yeah, but I need to do this in a command line or command block, there are some method?

**Comment by duhnunes** [comment]
I don't think so, if the command not working. But better wait for wildbamaboy's answer.

**Comment by WildBamaBoy** [comment]
5.3.1 and earlier are not supported.
