### ISSUE TITLE
No hearts on villagers

### ISSUE THREAD

**Issue by AndrewKlasen** [WildBamaBoy/minecraft-comes-alive#1207]
**Describe the bug**

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:
1. Launch Minecraft
2. Create a World
3. Click on a villager

**Minecraft Information (please complete all questions entirely):**
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2838
 - MCA Version: 6.0.0
 - Launcher: Standard

**Mods List**
Complete this section if you are NOT using a mod pack but have other mods installed alongside MCA.
 - Between Lands
-BetterPVP
-Furniture Mod
-Laptop Mod
-roguelike dungeons
-vein miner
-twilight forest
-storage drawers
-MineColonies
-Mallasis Doors
-Galactic Planets
-Custom NPC's
-Additional structures
-EXP Clumps
-BilboCraft
-Biomes O' Plenty

**Comment by WildBamaBoy** [comment]
This is intended on 6.0+
