### ISSUE TITLE
mca villagers sudden disappearance

### ISSUE THREAD

**Issue by karmacodez** [WildBamaBoy/minecraft-comes-alive#1208]
**Describe the bug**
Villagers wandering and finally leaving the village empty

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:

1. Launch Minecraft
2. Create a World
3. Go to any village and remain there for a couple of days in game time and start seeing how villagers start to reduce population moving outside of it.

**Minecraft Information (please complete all questions entirely):**

 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2811
 - MCA Version: 6.0.0
 - Launcher: T-launcher 2.53

**Modpack Information**
None

**Mods List**
RPG-HUD
JourneyMap
More Player Models

**Additional context**

As I try to see what the issue was up to so I used a seed that I know several village locations as a new survival game with cheats on, so I went to nearest village 1 and remained there for some days and villagers suddenly starting to disappear, so I used journeymap to locate them and found them going to somewhere else... As I set the difficulty to pacific they didn't die so I just follow them to see where they were going... And I saw they stop wandering as they got to map origin (coordinates 0,0) and stayed wandering around that point in a 4 to 6 chunks radius, after that I made them follow me back to their respective town and manually set home for each one and watch them for a couple of game days and they stopped the wandering outside town till now, so I went to village 2, and did the same besides that this time I manually set home points to only 2 villagers and the others remain same as spawned, same thing happened they start moving towards origin, this time the ones I set home point remained on village the rest leaved the town same as village 1, but this one's wandered a lot more far from origin but never leaved the area, so I made a kinda structure in the origin and they started going on it at night as that was their original location.

So it's seems that when they spawn are not set to location and as days go by they took origin as original home point and migrate towards it leaving towns empty, as I was on peacefully they didn't die trying and got there but for others having this issue they surely died trying to reach origin, so hope it helps you tracking down this issue as I love this mod and I like to see it again working as it should.

**Comment by WildBamaBoy** [comment]
Issue fixed in 6.0.1.
