### ISSUE TITLE
Watch a few bugs

### ISSUE THREAD

**Issue by KozakuraGames** [WildBamaBoy/minecraft-comes-alive#1209]
**Describe the bug**
I have noticed that once you are in your world and you find a village, it contains very few, although even and manipulated the spawning of these to increase it, in the same way I find the surprise that after some time some villagers "flee" to some random place in the world in particular (all to the same sector). Another possible bug I found is that the guards act TOO much like a normal villager, that is, they run away from hostile mobs instead of attacking them. Finally, the villagers do not have a fixed starting point, but they must be given manually (which is most likely to cause the villagers to flee from the village).

**Steps to Reproduce**

Open the world, find a village of natural spawning, spend some time in the surroundings without leaving the chunck keeping them active, after a while the villagers flee from the village (the guards do not attack hostile monsters from the beginning)

**Minecraft Information:**
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2836
 - MCA Version:  6.0.0
 - Launcher: Fenix

**Mods List**
33 mods
-CyclopsCore 1.5.0
-Durability Show 5.0.0
-EvilCraft 0.10.77
-ExtraUtilities2 1.9.9
-GrimPack 6.0.0.6
-Horizontal Glass Panels 1.0
-HowlingMoon 0.9
-Hwyla 1.8.26-B41
-Ice and Fire 1.8.0
-Instant Lava 1.0.2
-Inventory Tweaks 1.63
-Iron Furnaces 1.3.5
-IvToolkit 1.3.3
-Jei 4.15.0.268
-Jei Integration 1.5.1.36
-Just Enough Buttons 1.2.3
-Llibrary 1.7.19
-MCA 6.0.0
-No More Recipe Conflict 0.12
-Optifine HD_U_E3
-Re-Zombies V1.5
-Reap 1.5.2
-Recurrent Complex 1.4.8.2
-Spartan Shields 1.4.1
-Teletoro 1.12.2-26
-Torcherino 7.1
-Ultimate Storage 1.0
-VeinMiner 0.38.2.647+b31535a
-Wawla 2.5.273
-Yamda 1.0.2
-MoVillages 1.5.4

**Comment by TheServbots111** [comment]
Hello, look I have a problem and I wanted to make a post for others to help me but I did not know how to do it, the case is that I installed the Minecraft Comes Alive for 1.12.2 and enters the game and the world but when I approach a village crashed and so it goes until I get out of there


[Error.zip](https://github.com/WildBamaBoy/minecraft-comes-alive/files/3567378/Error.zip)

**Comment by WildBamaBoy** [comment]
These issues have been fixed in 6.0.1.
