### ISSUE TITLE
are Missing special tasks on Villagers intendet?

### ISSUE THREAD

**Issue by DerDon1991** [WildBamaBoy/minecraft-comes-alive#1210]
**Describe the bug**
Can't divorce or adopt with priests. can't marry other Players.

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:
1. Launch Minecraft
2. Create a World
3. try to interact with Players(LAN) or priests

**Minecraft Information (please complete all questions entirely):**
 - Minecraft Version: [1.12.2]
 - Forge Version: [14.23.5.2838]
 - MCA Version: [. 6.0.0]
Standard

**Mods List**
Minecraft Comes alive
forge

**Comment by WildBamaBoy** [comment]
Yes, this is intended for now.
