### ISSUE TITLE
player to player marriage

### ISSUE THREAD

**Issue by aeddog** [WildBamaBoy/minecraft-comes-alive#1211]
When playing on a personal server and trying to marry the other person playing, just nothing happens. We can each separately (on single player worlds with the same mods) marry villagers, just not each other on the server.

Minecraft Version: 1.12.2
Forge Version 14.23.5.2838
MCA Version: 6.0.0
Launcher: Twitch

Mods List
- advanced combat
- animania
- applecore
- appleskin
- baubles
- better advancements
- bibliocraft
- biomes o plenty
- blood magic
- botania
- chameleon
- chisel
- connectedtexturesmod
- controlling
- corvus
- craftstudio api
- crafttweaker
- croparia v2
- cxlibrary
- deconstruction table
- doggy talents
- dynamic surroundings
- fairy lights
- fossils and archeology revival
- guide api
- hwyla
- inventory pets
- inventory spam
- inventory tweaks
- iron backpacks
- journeymap
- jei
- jer
- kindred legacy
- lemonlib
- llibrary
- lootbags
- magic clover
- malisiscore
- malisisdoors
- mantle
- metal chests
- mo creatures
- more furnaces
- mouse tweaks
- mr crayfish's furniture mod
- natures compass
- notenoughids
- oreexcavation
- orelib
- pams harvestcraft
- patchouli
- placebo
- plants
- rats
- slime breeder advanced
- SOL carrot edition
- storage drawers
- straw golem
- tbone
- thaumcraft
- thaumic jei
- twilight forest
- tinkers construct
- torohealth damage indicators
- wawla

**Comment by WildBamaBoy** [comment]
Are you attempting to gift a ring or are you using the appropriate mca command to do this? Use `/mca help` to see all commands used for marriage to a player.
