### ISSUE TITLE
You already have a baby (issue)

### ISSUE THREAD

**Issue by Wolfan01** [WildBamaBoy/minecraft-comes-alive#1212]
I play with a friend and want to have a big familly, we have add a first child who became an adult and we have married him. After that my friend have wrote the command: /mca proceate to have an other one but when I accept the request, the message: you already have a baby, pop up in the chat. So we can't have any other child.
  An other player has sent the same request 10 days ago but there is no any solution in the thread.

We're playing on a LAN world, in survival.
Forge: 1.12.2  14.23.5.2838

Other mods:

MCA 1.12.2 6.0.0 (the latest)
Avatar mod 2
Inventory tweaks
Schematica
Lunatrius Core
journey map
Just enought item

**Comment by Teirdalin** [comment]
Can confirm that this is happening in most recent version of MCA.
Priests also do not exist, and clerics don't have any special commands.
So if your child/adult gets left behind on an old map or whatever, you're unable to have another.

**Comment by Wolfan01** [comment]
We’ve found a solution, my girlfriend has just to pick a baby in the creative inventory, and go back in survival.

**Comment by WildBamaBoy** [comment]
Please try to reproduce this issue and provide a link to your saved game.
