### ISSUE TITLE
Have guards dissapeared in last version?

### ISSUE THREAD

**Issue by ChechuDEV** [WildBamaBoy/minecraft-comes-alive#1213]
Hi, I recently updated the mod and I have lost most of villagers (I recreated them as I could) but I can't generate any guard nor villager (without profession)
MC version: 1.12.2
MCA version: 6.0.0

I supose is a change you have done but I want to know if its true.

(Also crystal ball and some items as broken ring and toy dissapeared)

**Comment by DaniilAnoli** [comment]
Hi, Guard was renamed to Hero. About Villager I'm not sure, but I think it's Nitwit. I hope this helps you.
