### ISSUE TITLE
Villages are not populated

### ISSUE THREAD

**Issue by adegans** [WildBamaBoy/minecraft-comes-alive#1214]
**Describe the bug**
Newly generated villages are empty/have no population

**Steps to Reproduce**
Discover a regular village and see it empty.

**Minecraft Information (please complete all questions entirely):**
 - Minecraft Version: 1.12.2
 - Forge Version:14.23.5.2838
 - MCA Version: 6.0.0
 - Launcher: MultiMC

**Modpack Information**
Complete this section if you are using a modpack.
 - Modpack Name: No official pack, but i have some 63 mods like Tconstruct, Ref Storage, Immersive engineering, Journeymap and EnderIO + a bunch of supporting smaller mods. Optifine + WorldEdit
 - Modpack Version: N/a

**Mods List**
Mods:
  [📁] 1.12 (folder)
  [✔️] ActuallyAdditions-1.12.2-r149
  [✔️] ActuallyBaubles-1.12-1.1
  [✔️] AkashicTome-1.2-12
  [✔️] AutoRegLib-1.3-20
  [✔️] Baublelicious-1.4.0-4
  [✔️] Baubles-1.12-1.5.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BetterBuildersWands-1.12-0.11.1.245+69d0d70
  [✔️] Chameleon-1.12-4.1.3
  [✔️] ChickenChunks-1.12.2-2.4.1.71-universal
  [✔️] CodeChickenLib-1.12.2-3.1.5.331-universal
  [✔️] CookingForBlockheads_1.12.2-6.4.71
  [✔️] CTM-MC1.12.2-0.3.3.22
  [✔️] diethopper-1.1
  [✔️] EnderCore-1.12.2-0.5.59
  [✔️] EnderIO-base-1.12.2-5.0.46
  [✔️] EnderIO-conduits-1.12.2-5.0.46
  [✔️] EnderIO-integration-tic-1.12.2-5.0.46
  [✔️] EnderIO-machines-1.12.2-5.0.46
  [✔️] environmentaltech-1.12.2-2.0.20.1
  [✔️] extrautils2-1.12-1.9.9
  [✔️] forestry_1.12.2-5.8.1.322
  [✔️] gravestone-1.10.1
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] ImmersiveEngineering-0.12-89
  [✔️] immersivepetroleum-1.12.2-1.1.9
  [✔️] InventoryTweaks-1.63
  [✔️] IronBackpacks-1.12.2-3.0.8-12
  [✔️] ironchest-1.12.2-7.0.71.846
  [✔️] jei_1.12.2-4.15.0.268
  [✔️] jeiintegration_1.12.2-1.5.1.36
  [✔️] journeymap-1.12.2-5.5.4
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] Mantle-1.12-1.3.3.49
  [✔️] MCA-1.12.2-6.0.0-universal
  [✔️] mcjtylib-1.12-3.0.6
  [📁] memory_repo (folder)
  [✔️] minecolonies-1.12.2-0.10.259-RELEASE-universal
  [✔️] NotEnoughIDs-1.5.4.4
  [✔️] OpenGlider-1.12.1-1.1.0
  [✔️] OptiFine_1.12.2_HD_U_E3
  [✔️] Quark-r1.5-127
  [✔️] RebornCore-1.12.2-3.14.1.457-universal
  [✔️] RebornStorage-1.12.2-3.3.4.85
  [✔️] refinedstorage-1.6.14
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] rftools-1.12-7.56
  [✔️] RoguelikeDungeons-1.12.2-1.8.0
  [✔️] TConstruct-1.12.2-2.12.0.135
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] TinkerToolLeveling-1.12.2-1.0.5
  [✔️] torchmaster_1.12.2-1.7.1.74
  [✔️] TreeChopper-1.12.2-1.2.4
  [✔️] valkyrielib-1.12.2-2.0.20.1
  [✔️] WailaHarvestability-mc1.12-1.1.12
  [✔️] Waystones_1.12.2-4.0.72
  [✔️] worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist

**Additional context**
Just exploring the world - Found 3 villages with the intent to lasso a bunch to my own village, but haven't found a single villager.

**Comment by adegans** [comment]
I've updated to 6.0.1, but the villagers are still missing :(

**Comment by adegans** [comment]
Did some more testing, without MCA the villagers were missing as well.
After deleting the village.dat from Saves > [worldname] > data and regenerating the chunks with the villages in them it worked...

Not sure if that's a MCA related issue, or some quirk with worldgen from another mod.

**Comment by WildBamaBoy** [comment]
Definitely wouldn't be MCA in this instance - it only replaces villagers that have already naturally spawned.
