### ISSUE TITLE
MCA Version 6.0.0/6.0.1 Bugs

### ISSUE THREAD

**Issue by Gipanu** [WildBamaBoy/minecraft-comes-alive#1216]
**Describe the bug**
I just updated to the newest version of MCA(6.0.1),all my villagers disappeared so I tried to spawn new ones using villagers egg spawners. Whenever I spawn a villager I have the following issues:1.They always spawn with a fletcher/Nitwit/Normal Villager  that I can't interact with at all :Hit him,dig a hole under him so he falls,talk with him,etc. I can't do any of these stuff.
2.All my villagers are apparently my kids even though they are fully grown up and I'm not even married.   

**Steps to Reproduce**
1. launch Minecraft
2. Create a World/Load existing world
3.Spawn Villagers using egg spawns

**Minecraft Information (please complete all questions entirely):**
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2838
 - MCA Version: 6.0.1
 - Launcher: Standard 

**Modpack Information**
No Mod Pack

**Mods List**
Aether Legacy
Atum
Backpacks mod
BattleTowers 
BiblioCraft
Bookshelf
Camping mod
CodeChickenLib
Disenchanter
DoggyTalentes
Enchanting Plus
Erebus
Just Enough Items
LuckyBlock
Minecraft Comes Alive 6.0.1
Mo Swords
Mo Villages
MrCrayFish Furniture mod
Multimob
Primitive Mobs
RadixCore
RikMuldsCore
RougeLike Dungeons
Ruins
ToroHealth
TreeCapitator
Twilight Forest
UndergroundBimoesConstructs
Xaero Minimap
Xaero World Map
 

**Additional Context**
Nothing else to add.

**Comment by WildBamaBoy** [comment]
Does this issue still occur when you use MCA by itself?
