### ISSUE TITLE
ore stone varints compatability

### ISSUE THREAD

**Issue by EternalOne11** [WildBamaBoy/minecraft-comes-alive#1217]
Can you add support on your end for ore stone variants mod if possible on your side?
https://www.curseforge.com/minecraft/mc-mods/ore-stone-variants 
asked them on their side but just a little worried since they haven't updated it in awhile.
already made the textures.
[mca_rose_gold_ore_overlay](https://user-images.githubusercontent.com/42950385/64132009-6f735d80-cd9a-11e9-95b1-c1673cc5cfe9.png)
![dense_mca_rose_gold_ore_overlay](https://user-images.githubusercontent.com/42950385/64132010-6f735d80-cd9a-11e9-88dd-f3134631c6c5.png)

**Comment by WildBamaBoy** [comment]
This is not something I am willing to implement on my end, unfortunately.
