### ISSUE TITLE
Tried to summon guard, got red tint 

### ISSUE THREAD

**Issue by QwiteRayven** [WildBamaBoy/minecraft-comes-alive#1220]
**Describe the bug**
Edit: I noticed the problem that I was having was more of my fault!
So I changed this bug report to be about a different problem

As I play I notice that most of the villagers wander really far away from the village
even when it becomes nighttime and they have a home set!

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:
1. Launch Minecraft
2. Create a World
3. Find a village
4. Live normally for a few days
5. Notice most villagers are gone
6. Find them about 100-200 blocks away from village just sitting around

P.S please make a way to spawn guards when you can! it'd be cool^^

**Minecraft Information (please complete all questions entirely):**
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2838
 - MCA Version: 6.0.1
 - Launcher: Standard

**Mods List**
Complete this section if you are NOT using a modpack but have other mods installed alongside MCA.
 - Please list the other mods you have installed

DoggyTalents-1.12.2-1.15.1.4-universal.
( CFM ) furniture-6.3.1-1.12.2.
Pam's HarvestCraft 1.12.2zf.
WearableBackpacks-1.12.2-3.1.3.
StorageDrawers-1.12.2-5.3.8.
- Chameleon-1.12-4.1.3.
animania-1.12.2-1.6.2.
- CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.
fossilsarcheology-8.0.2.
- llibrary-1.7.17-1.12.2.

**Additional context**
Playing on an aternos server I made for my friends, the villagers kept wandering really far from the village and didn't go back at night, either causing them to die or just get lost enough that we couldn't have them returned again

We set each home and marked them with signs so that we knew who lived where to prevent over crowding, we thought this would work, but when night came none of them walked or teleported to the homes we set for them, either staying outside or simply going to whatever home was closest 

This would be fine normally, but sometimes villagers will start to walk away from the village and get lost, but since they don't teleport home at night they just go off somewhere and don't come back at all, forcing us to make them follow us back 

( This had made most of the village die off a few times! )

**Comment by WildBamaBoy** [comment]
Fixed with PR 1228
