### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by ClockyVaudeville** [WildBamaBoy/minecraft-comes-alive#1221]
Okay so I have no idea how this new version works, I married and everything and then I went to have a kid, after 10 minutes elapsed (how long it takes for a baby to be ready to grow up) I can't actually place my kid to get him to grow up, he's been in my inventory 20 minutes now and nothing. I checked in the config and I have the time set to 10 minutes so what's going on? What am I doing wrong? I looked online and all of the wikis and such are extremely outdated, if I could get help with this that would be great.

**Comment by WildBamaBoy** [comment]
Please use the proper issue format. Ensure this issue occurs with only MCA installed.
