### ISSUE TITLE
Villagers Legs are gone..?

### ISSUE THREAD

**Issue by Wilsoon7721** [WildBamaBoy/minecraft-comes-alive#1222]
I was playing my own custom-made modpack and it was normal, I messed around with the config a little bit to have more fun, and one time, suddenly, when I came back from doing something in-game, and all the villagers nearby have their legs missing. I quit the game and went back in the world and it didn't work.

[Config: Pastebin](https://pastebin.com/pnMnx5E1)

Screenshot of missing legs:
![2019-09-10_00 18 41](https://user-images.githubusercontent.com/40225169/64548134-9dd7d680-d360-11e9-9fea-5514ef7a8603.png)

**Comment by WildBamaBoy** [comment]
Please use the proper issue format. This is going to be an issue with some of the other mods you have in the pack and not a fault in MCA.
