### ISSUE TITLE
Villagers don't greet you anymore + Heroes defend pillagers

### ISSUE THREAD

**Issue by Duxiquie** [WildBamaBoy/minecraft-comes-alive#1223]
**Describe the bug**
I found two (?) issues with the new versions of MCA, the greeting issue is in both 6.0.0 and 6.0.1, and I've only seen the heroes issue in 6.0.1 (haven't tested it with 6.0.0).

In previous versions, villagers used to greet the player when they're close, however this is not the case anymore in 6.0.0 and up. Villagers just walk around like regular mobs until you right click them for any interaction. (Unless this is a feature yet to be added, it's an issue I think?)

As for the heroes defending pillagers issue, it seems they kill other heroes if they have hit a pillager. What usually happens is that a pillager hits a normal villager/hero A first, when A hits the pillager back another hero B comes in and usually kills hero A/the pillager/both. If the player hits a pillager or hero in survival, you'll get hit as well.

I'm also not sure if this is intentional, but every village you come across for the first time always has a mix of normal villagers and pillagers spawned, regardless of being in survival/creative.

Both these issues happened in survival/creative mode if that's anything useful.

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:
1. Launch Minecraft
2. Create a World
3. Find a village and walk/fly around

**Minecraft Information (please complete all questions entirely):**
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2838
 - MCA Version: 6.0.0 and 6.0.1
 - Launcher: Standard

**Mods List**
I normally use plenty of other mods (I have 70+ in total), but I loaded Minecraft with just MCA installed to see if the issues would be fixed. The issues were still there, so I don't think they're caused by mod conflicts.

**Comment by TsundereMatrix** [comment]
I have also noticed these problems especially with the hero defending pillagers. I noticed that if the player goes out into deeper water, the hero will give up and head back to the village. If the player goes back to the village the hero is passive again.

**Comment by Luke100000** [comment]
"In previous versions, villagers used to greet the player when they're close, however this is not the case anymore in 6.0.0 and up." I am working on an improved AI fork and so far I know there is no such thing as greeting any more. I do not know if a re-implementation is planned.

**Comment by WildBamaBoy** [comment]
Greeting is no longer implemented.

Duplicate issue submitted for guards defending pillagers. This is fixed in 6.1.0.
