### ISSUE TITLE
Spouse does not go inside at night and gets killed by zombies

### ISSUE THREAD

**Issue by TsundereMatrix** [WildBamaBoy/minecraft-comes-alive#1224]
Describe the bug
This has happened to every spouse I have had in survival mode. If I am elsewhere at night and I do not sleep, my spouse goes outside and gets killed by zombies. They only go inside during the day. Unmarried NPCs do what vanilla villagers do, they go inside at night whether I go to sleep or not and are safe 99% of the time.
Edit: If I sleep before mobs spawn, this does not happen.

Steps to Reproduce
1. Launch Minecraft
2. Create a World
3. Find village
4. Marry villager
5. Set home and leave area
6. Do not sleep at night

Minecraft Information
 - Minecraft Version 1.12.2
 - Forge Version: 14.23.5.2844
 - MCA Version: 6.0.1 
 - Launcher: Twitch

Modpack Information
Custom Modpack made by myself

Mods List
Minecraft Comes Alive
AppleCore
Pam's HarvestCraft
HungerOverhaul

Additional context
This has happened before I added AppleCore, HarvestCraft and HungerOverhaul mods so I believe its a MCA villager issue. It only happens to villagers that I marry. I never lost any unmarried villagers to zombies before.

**Comment by HeberLemus** [comment]
can confirm that this happens. i remember in MC 1.7, even if you didnt give them a bed they would still return to their home point you set at night.

my only solution so far has been to keep them in "stay here" or ensure that if they are doing a task, mobs cant approach them (lighting and fencing the area) but that defeats the point of them being able to walk around or having to continually babysit them every 10 mins that you are doing something else

**Comment by TsundereMatrix** [comment]
> can confirm that this happens. i remember in MC 1.7, even if you didnt give them a bed they would still return to their home point you set at night.
> 
> my only solution so far has been to keep them in "stay here" or ensure that if they are doing a task, mobs cant approach them (lighting and fencing the area) but that defeats the point of them being able to walk around or having to continually babysit them every 10 mins that you are doing something else

Yeah, that's the only solution I could think of too. I feel like I'm holding them hostage by doing that though... but its for their own good anyway. Make them stay when you're away and then let them roam around when you are home.

**Comment by HeberLemus** [comment]
seems like someone made PR#1228 to fix part of this issue, but it hasnt gotten merged in yet

**Comment by WildBamaBoy** [comment]
Fixed with PR 1228
