### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#1227]
**Describe the bug**
This bug duplicates items from your children inventory

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:
1. Have a child
2. Give said child items such as Armour and weapons 
3. Have said child die due to any cause
4. The items in the inventory will drop
5. Revive said child
6. Check their inventory, they will have everything they dropped still there
7. takes items

**Minecraft Information:**
 - Minecraft Version: 1.12.2
 - Forge Version: e.g. 14.23.5.2846
 - MCA Version: 6.0.1
 - Launcher: Standard

**Mods List**
Mod List

AbyssalCraft
Actually Additions
Actually Baubles
Aether Legacy
Aether Continuation
Aether Lost Content
Apple Skin
Battle Towers
Baubles
Better Survival
BiblioCraft
Biomes O' Plenty
Blood Magic
Botania
Chunk Animator
Classic Combat
Clumps
Cooking for Blockheads
Curio
Cyclic
Damage Indicators Mod
Decocraft
Divine Objects
Doomlike Dungeons
Mo'Creatures
Dungeon Mobs
Dynamic Surroundings
Elevator Mod
Embers
Familiar Fauna
Foam Fix
Forestry
Fossils and Archeology Revival
Grappling Hook Mod
Gravestone Mod
HungerOverhaul
Ice and Fire
Ido Movement
Inventory Tweaks
Iron Backpacks
Iron Chests
JourneyMap
JurassiCraft
Just Enough Items
Lapis Stays in the Enchanting Table
Minecraft Comes Alive
Mo' Bends
Mob Amputation
MrCrayfish's Furniture Mod
Mystical Wildlife
NeatherEx
Pam's Harvest Craft
Phosphor Lighting Engine
Potion Fingers
Realistic Item Drops
Recurrent Complex
Rin's So Many Enchantments
Rougelike Dungeons
Ruins Mod
Serene Seasons
Shiny Gear
Spartan Weaponary
Spartan Fire
SwingThroughGrass
Thaumcraft
The Eight Fabled Blades
The Lost Cities
The Twilight Forest
Tinkers' Construct
Tinkers' tool Leveling
Trash Slot
Tree Chopper
Trinkets and Baubles
Wall-Jump!
Waystones
Wolf Armor and Storage

**Comment by LemADEC** [comment]
Any chance we get a fix for that one?

**Comment by Luke100000** [comment]
> 
> 
> Any chance we get a fix for that one?

I fixed it, or at least it does no longer happen for me. My pull request is open for 28 days already, not sure if WildBamaBoy is interested in a merge. You can pull my fork. It's just a single (workaround) line.

**Comment by WildBamaBoy** [comment]
Fixed in the PR by @Luke100000
