### ISSUE TITLE
[REQUEST] Permissions Documentation Addition (QOL)

### ISSUE THREAD

**Issue by KuwuroUsagi** [WildBamaBoy/minecraft-comes-alive#1230]
**Please describe the problem you are experiencing and requesting a change for**
Jumping through hoops to figure out what permissions to give players in a server so they can make use of all/most of the /mca commands

**Describe the solution you'd like to see**
Documentation with permissions needed to give ability to run /mca commands

**Describe alternatives you've considered**
Hunting through the repository and using trial and error on differing variations of mca.sendproposal, mcaserver.sendproposal, MCAserver.sendProposal.*, etc, etc.

**Additional context**
Just a quality of life documentation thing for server admins who want to get permissions hammered out in a quick and easy fashion.

**Comment by WildBamaBoy** [comment]
With the current setup I believe that MCA would only have 2 permissions. The /mca command and /mca-admin. With future versions I will be reworking this to be separated out into their own individual subcommands.

Definitely will document this as well when the time comes.

**Comment by KuwuroUsagi** [comment]
How can a server owner give players access to the base mca commands without giving out operator? (ThutPerms, LuckPerms, PEX, GroupManager etc)
