### ISSUE TITLE
Crash on villager death

### ISSUE THREAD

**Issue by GuzSantana** [WildBamaBoy/minecraft-comes-alive#1231]
---- Minecraft Crash Report ----
// My bad.

Time: 2019-10-26 02:55:45 UYT
Description: Ticking entity

java.lang.NullPointerException
    at mca.entity.EntityVillagerMCA.lambda$onDeath$3(EntityVillagerMCA.java:331)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
    at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.util.stream.ReferencePipeline.forEach(Unknown Source)
    at mca.entity.EntityVillagerMCA.onDeath(EntityVillagerMCA.java:329)
    at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1023)
    at net.minecraft.entity.EntityLivingBase.outOfWorld(EntityLivingBase.java:1573)
    at net.minecraft.entity.Entity.onEntityUpdate(Entity.java:503)
    at net.minecraft.entity.EntityLivingBase.onEntityUpdate(EntityLivingBase.java:226)
    at net.minecraft.entity.EntityLiving.onEntityUpdate(EntityLiving.java:269)
    at net.minecraft.entity.Entity.onUpdate(Entity.java:389)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2096)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at mca.entity.EntityVillagerMCA.onUpdate(EntityVillagerMCA.java:259)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbm000(World.java:5118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: mca:entityvillagermca (mca.entity.EntityVillagerMCA)
  Entity ID: 10867
  Entity Name: entity.EntityVillagerMCA.name
  Entity's Exact location: -2163.50, -175.33, 696.50
  Entity's Block location: World: (-2164,-176,696), Chunk: (at 12,-11,8 in -136,43; contains blocks -2176,0,688 to -2161,255,703), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
  Entity's Momentum: 0.00, -3.17, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,Attributes:[{Base:0.0d,Name:"aether.slashDamageLevel"},{Base:0.0d,Name:"aether.pierceDamageLevel"},{Base:0.0d,Name:"aether.impactDamageLevel"},{Base:0.0d,Name:"aether.slashDefenseLevel"},{Base:0.0d,Name:"aether.pierceDefenseLevel"},{Base:0.0d,Name:"aether.impactDefenseLevel"},{Base:20.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.5d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Modifiers:[{UUIDMost:6347420946757602131L,UUIDLeast:-8821247810626955871L,Amount:-0.035208733128857535d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"}],Invulnerable:0b,playerHistoryMap:{},AbsorptionAmount:0.0f,babyAge:0,FallDistance:162.83344f,girth:0.0f,ForgeCaps:{"tinkertoolleveling:entityxp":[],"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Player Property Tracker":{DismountedDragon:0b,GauntletDamage:0},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Chain Property Tracker":{ConnectedEntities:[]},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"aether:entityinfo":{hasSpawnArea:0b},"twilightforest:cap_shield":{permshields:0,tempshields:0},"vampirism:iextendedcreature":{maxBlood:15,poisonousBlood:0b,bloodLevel:15},"bma_addon:freeze_data":{}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,playerToFollowUUIDMost:0L,Leashed:0b,spouseUUIDLeast:0L,Air:300s,Offers:{Recipes:[{maxUses:7,buy:{id:"minecraft:emerald",Count:3b,Damage:0s},sell:{id:"fossil:biofossil",Count:1b,Damage:0s},uses:0,rewardExp:1b},{maxUses:7,buy:{id:"minecraft:emerald",Count:6b,Damage:0s},sell:{id:"fossil:relic_scrap",Count:1b,Damage:0s},uses:0,rewardExp:1b},{maxUses:7,buy:{id:"fossil:relic_scrap",Count:2b,Damage:0s},sell:{id:"minecraft:emerald",Count:1b,Damage:0s},uses:0,rewardExp:1b}]},uuidMost:5895447324729559863L,marriageState:0,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],tallness:0.0f,activeChore:0,Profession:7,Pos:[-2163.5d,-175.3334085790759d,696.5d],name:"Sylvie",isProcreating:0b,CanPickUpLoot:1b,HurtTime:10s,CareerLevel:1,choreAssigningPlayerLeast:0L,Inventory:[],Willing:0b,parents:{},ForgeData:{},gender:2,moveState:0,ageState:4,Riches:0,FallFlying:0b,ForcedAge:0,PortalCooldown:0,inventory:[],uuidLeast:-5130228887855777250L,DeathTime:0s,bedY:0,bedZ:0,bedX:0,spouseUUIDMost:0L,choreAssigningPlayerMost:0L,Age:0,Motion:[0.0d,-3.1721350593413487d,0.0d],infected:0b,UUIDLeast:-5130228887855777250L,Health:0.0f,texture:"mca:skins/female/butcher/butcherf1_converted.png",LeftHanded:0b,startingAge:0,OnGround:0b,Dimension:0,Rotation:[2.8321767f,0.0f],UpdateBlocked:0b,ProfessionName:"fossil:archeologist",UUIDMost:5895447324729559863L,playerToFollowUUIDLeast:0L,Fire:-1s,ArmorItems:[{},{},{},{}],spouseName:"",homePositionY:0.0d,homePositionX:0.0d,Career:1,homePositionZ:0.0d}

-- Affected level --
  Level name: Mundo nuevo--
  All players: 1 total; [GCEntityPlayerMP['ayuwoki'/10784, l='Mundo nuevo--', x=-2151.79, y=11.25, z=779.63]]
  Chunk stats: ServerChunkCache: 1748 Drop: 0
  Level seed: 8969506521282461907
  Level generator: ID 01 - flat, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-2163,4,759), Chunk: (at 13,0,7 in -136,47; contains blocks -2176,0,752 to -2161,255,767), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
  Level time: 92 game time, 92 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 89085 (now: false), thunder time: 108839 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_221, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 15749171904 bytes (15019 MB) / 17381195776 bytes (16576 MB) up to 19327352832 bytes (18432 MB)
  JVM Flags: 9 total; -Xmn128M -Xmx24532M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx18G
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 94 mods loaded, 94 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                         | Version                  | Source                                               | Signature                                |
       |:------ |:-------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                  | 1.12.2                   | minecraft.jar                                        | None                                     |
       | LCHIJA | mcp                        | 9.42                     | minecraft.jar                                        | None                                     |
       | LCHIJA | FML                        | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                      | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | micdoodlecore              |                          | minecraft.jar                                        | None                                     |
       | LCHIJA | foamfixcore                | 7.7.4                    | minecraft.jar                                        | None                                     |
       | LCHIJA | versionchecker             | @VERSION@                | [1.12.2]+VersionChecker-1.4.0.jar                    | None                                     |
       | LCHIJA | orbis-lib                  | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build127.jar                  | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHIJA | aether                     | 0.2.6                    | aether_ii-1.12.2-0.2.6+build127-universal.jar        | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCHIJA | backpacks16840             | 3.5.6                    | backpacks+1.12.2+-+3.5.6.jar                         | None                                     |
       | LCHIJA | battletowers               | 1.6.5                    | BattleTowers-1.12.2.jar                              | None                                     |
       | LCHIJA | baubles                    | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
       | LCHIJA | subcommonlib               | 1.2.0.1                  | subcommonlib-sublib-1.12.2-1.2.0.4.jar               | None                                     |
       | LCHIJA | rpginventory               | 1.12.2                   | rpginventory-1.12-5.3.0.0.jar                        | None                                     |
       | LCHIJA | beastmaster                | $version                 | beastmaster-1.12.2-1.2.0.1.jar                       | None                                     |
       | LCHIJA | betternether               | 0.1.8.3                  | betternether-0.1.8.3.jar                             | None                                     |
       | LCHIJA | forgelin                   | 1.8.4                    | Forgelin-1.8.4.jar                                   | None                                     |
       | LCHIJA | betterportals              | 0.3.7.1                  | betterportals-0.3.7.1.jar                            | None                                     |
       | LCHIJA | bma_addon                  | 1.11.2 4.0.3.0           | bma_addon-1.12-4.1.0.3.jar                           | None                                     |
       | LCHIJA | bookshelf                  | 2.3.585                  | Bookshelf-1.12.2-2.3.585.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | micsiege                   | 1.0.4                    | BrutalZombieSiege_1.12.2-1.0.4.jar                   | None                                     |
       | LCHIJA | buildcraftlib              | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | buildcraftcore             | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | buildcraftbuilders         | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | buildcrafttransport        | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | buildcraftsilicon          | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | buildcraftcompat           | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | buildcraftenergy           | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | buildcraftfactory          | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | buildcraftrobotics         | 7.99.24.3                | buildcraft-all-7.99.24.3 (1).jar                     | None                                     |
       | LCHIJA | chococraft                 | 0.9.8.0                  | chococraft_1.12.2-0.9.8.0.jar                        | None                                     |
       | LCHIJA | codechickenlib             | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux               | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal (1).jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                   | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal (1).jar           | None                                     |
       | LCHIJA | cofhworld                  | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal (1).jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | mantle                     | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55 (1).jar                         | None                                     |
       | LCHIJA | jei                        | 4.15.0.287               | jei_1.12.2-4.15.0.287.jar                            | None                                     |
       | LCHIJA | twilightforest             | 3.9.984                  | twilightforest-1.12.2-3.9.984-universal.jar          | None                                     |
       | LCHIJA | tconstruct                 | 1.12.2-2.13.0.171        | TConstruct-1.12.2-2.13.0.171.jar                     | None                                     |
       | LCHIJA | conarm                     | 1.2.5                    | conarm-1.12.2-1.2.5.jar                              | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | customspawner              | 3.11.4                   | Custom-Mob-Spawner-Mod-1.12.2.jar                    | None                                     |
       | LCHIJA | cyclopscore                | 1.5.1                    | CyclopsCore-1.12.2-1.5.1.jar                         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | dynamictrees               | 1.12.2-0.9.5             | DynamicTrees-1.12.2-0.9.5 (1).jar                    | None                                     |
       | LCHIJA | traverse                   | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                         | None                                     |
       | LCHIJA | dttraverse                 | 1.5                      | dttraverse-1.5.jar                                   | None                                     |
       | LCHIJA | ebwizardry                 | 4.2.5                    | ElectroblobsWizardry-4.2.5-MC1.12.2.jar              | None                                     |
       | LCHIJA | eplus                      | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | erebus                     | 1.0.30                   | Erebus-1.0.30.jar                                    | None                                     |
       | LCHIJA | evilcraft                  | 0.10.78                  | EvilCraft-1.12.2-0.10.78.jar                         | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCHIJA | evilcraftcompat            | 1.0.0                    | EvilCraft-1.12.2-0.10.78.jar                         | None                                     |
       | LCHIJA | galacticraftcore           | 4.0.2.238                | GalacticraftCore-1.12.2-4.0.2.238 (1).jar            | None                                     |
       | LCHIJA | galacticraftplanets        | 4.0.2.238                | Galacticraft-Planets-1.12.2-4.0.2.238 (1).jar        | None                                     |
       | LCHIJA | mjrlegendslib              | 1.12.2-1.1.9             | MJRLegendsLib-1.12.2-1.1.9.jar                       | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | extraplanets               | 1.12.2-0.5.8             | ExtraPlanets-1.12.2-0.5.8.jar                        | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | extrautils2                | 1.0                      | extrautils2-1.12-1.9.9.jar                           | None                                     |
       | LCHIJA | foamfix                    | 0.10.8-1.12.2            | foamfix-0.10.8-1.12.2.jar                            | None                                     |
       | LCHIJA | llibrary                   | 1.7.19                   | llibrary-1.7.19-1.12.2 (1).jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | fossil                     | 8.0.3                    | fossilsarcheology-8.0.3.jar                          | None                                     |
       | LCHIJA | gargoyles                  | 1                        | Gargoyles+mod+1.12.2+patch+1.jar                     | None                                     |
       | LCHIJA | grimoireofgaia             | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar                   | None                                     |
       | LCHIJA | overlord                   | 2.4.14                   | Overlord-1.12.2-2.4.14.jar                           | None                                     |
       | LCHIJA | guideapi                   | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                          | None                                     |
       | LCHIJA | waila                      | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
       | LCHIJA | iceandfire                 | 1.8.3                    | iceandfire-1.8.3.jar                                 | None                                     |
       | LCHIJA | infernalmobs               | 1.7.6                    | InfernalMobs-1.12.2.jar                              | None                                     |
       | LCHIJA | libraryex                  | 1.0.12                   | LibraryEx-1.12.2-1.0.12.jar                          | None                                     |
       | LCHIJA | malisiscore                | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                         | None                                     |
       | LCHIJA | malisisdoors               | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                        | None                                     |
       | LCHIJA | mca                        | 6.0.0                    | MCA-1.12.2-6.0.0-universal.jar                       | None                                     |
       | LCHIJA | mechsoldiers               | 1.1.6                    | MechSoldiers-1.12.2-1.1.6.jar                        | None                                     |
       | LCHIJA | minions                    | 2.0.3                    | Minions-1.12.2.jar                                   | None                                     |
       | LCHIJA | mocreatures                | 12.0.5                   | Mo-Creatures-Mod-1.12.2.jar                          | None                                     |
       | LCHIJA | mowziesmobs                | 1.5.4                    | mowziesmobs-1.5.4 (1).jar                            | None                                     |
       | LCHIJA | multimob                   | 1.0.5                    | multimob-1.0.5.jar                                   | None                                     |
       | LCHIJA | netherex                   | 2.0.15                   | NetherEx-1.12.2-2.0.15.jar                           | None                                     |
       | LCHIJA | ptrmodellib                | 1.0.4                    | PTRLib-1.0.4.jar                                     | None                                     |
       | LCHIJA | radixcore                  | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal (2).jar             | None                                     |
       | LCHIJA | rustic                     | 1.1.1                    | rustic-1.1.1.jar                                     | None                                     |
       | LCHIJA | spartanshields             | 1.4.1                    | SpartanShields-1.12.2-1.4.1.jar                      | None                                     |
       | LCHIJA | thermalfoundation          | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal (1).jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalexpansion           | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal (1).jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalcultivation         | 0.3.3                    | ThermalCultivation-1.12.2-0.3.3.12-universal (1).jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermaldynamics            | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal (1).jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalinnovation          | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal (1).jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | tinkertoolleveling         | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0 (1).jar              | None                                     |
       | LCHIJA | tlauncher_custom_cape_skin | 1.4                      | tlskincape_1.12.2-1.4.jar                            | None                                     |
       | LCHIJA | umbralux                   | 1.12.2                   | umbralux-1.12.2-2.1.0.2.jar                          | None                                     |
       | LCHIJA | of                         | 0.13.1                   | Useful+Interior+-+0.13.1+[1.12.2].jar                | None                                     |
       | LCHIJA | vampirism                  | 1.5.5                    | Vampirism-1.12.2-1.5.5.jar                           | None                                     |
       | LCHIJA | teamlapen-lib              | 1.5.5                    | Vampirism-1.12.2-1.5.5.jar                           | None                                     |
       | LCHIJA | vampirism_integrations     | vampirism_integrations   | VampirismIntegrations-1.12.2-1.1.0.jar               | None                                     |
       | LCHIJA | vanillafix                 | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                             | None                                     |
       | LCHIJA | xaerominimap               | 1.17.4                   | Xaeros_Minimap_1.17.4_Forge_1.12.jar                 | None                                     |
       | LCHIJA | phosphor-lighting          | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar          | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238 (1).jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.8-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      iceandfire (iceandfire-1.8.3.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
                                        gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
                                      BCModPlugin (backpacks+1.12.2+-+3.5.6.jar)
                                        brad16840.core.ClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Suspected Mods: Minecraft Comes Alive (mca)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [GCEntityPlayerMP['ayuwoki'/10784, l='Mundo nuevo--', x=-2151.79, y=11.25, z=779.63]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 1

**Comment by WildBamaBoy** [comment]
Dupe of #1226
