### ISSUE TITLE
Dont have a crystal ball

### ISSUE THREAD

**Issue by Idkbythispoint** [WildBamaBoy/minecraft-comes-alive#1319]
**Describe the bug**
When i make a new world i don't get a crystal ball, and when I look it up in the creative menu it doesn't appear, the item seems to not exist

**Steps to Reproduce**
Please include steps we can take to reproduce the bug:
1. Launch Minecraft (Found with the a bit of everything modpack with mca also installed
2. Create a World
3. You dont have a crystal ball

**Minecraft Information (please complete all questions entirely):**
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2854
 - MCA Version: 6.1.0
 - Launcher: ATLauncher

**Modpack Information**
Complete this section if you are using a modpack.
 - Modpack Name: A Bit Of Everything
 - Modpack Version: 3.7.3

**Mods List**
Complete this section if you are NOT using a modpack but have other mods installed alongside MCA.
 - Please list the other mods you have installed

**Additional context**
Add any other context about the problem here that you feel is useful. Screenshots, world files, logs, etc.

**Comment by Idkbythispoint** [comment]
added the version

**Comment by Idkbythispoint** [comment]
All other items also seem to exist

**Comment by Dvoric** [comment]
@clarkxl  If you had looked at the changelog, or just searched through all issues before creating a new one, you would know that the feature was officially removed a year ago. Here is a direct quote: "Changed: The crystal ball and setup menu is no longer required." It was removed to "make things less complicated."

The fact you've taken so much time to turn this into an issue, and update it twice, is hilarious. Maybe next time use an extra minute and actually search the issue first ... you might save yourself some time ... and from looking ultra dumb.

**Comment by Idkbythispoint** [comment]
Sorry, that wasnt my intent and i shouldve done more searching.
