### ISSUE TITLE
Permissions node.

### ISSUE THREAD

**Issue by RedTrainerF** [WildBamaBoy/minecraft-comes-alive#1344]

**Comment by JahxSenpoopie** [comment]
> #1230
> 
> i may be rewinding this issue, Players simply cannot accept marriage proposal due to no permissions.
> we cant give them all OP for this to work lol.
> Which permission nodes will make it work?
> 
> Server: `**[CHAT] I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.**` With red color.
> 
> Server/Mod Version: 1.12.2

You need to use cheats to access mca commands

**Comment by AmroWazzan** [comment]
emm, well let me re-point something i didnt mention, i am a Mod in the specific server and i cant give everyone Cheats to access those commands.
