### ISSUE TITLE
Progress with Villagers Lost

### ISSUE THREAD

**Issue by magues** [WildBamaBoy/minecraft-comes-alive#1353]
Hi,

Everytime I save and quit minecraft to enter again, all the progress such as hearts and marriage is lost. It shoes that a certain villager is my son or daughter but the hearts are reset and no work or inventory button is available. The same happens with my wife, it shows that we are married, but the villager does not recognize it, the hearts are reset to 0 and no work , inventory or procreate option is available any more.

I use Minecraft 1.12
Version of the mod 1.12.2-6.1.0-universal
Forge -12.23.5.2854

Thank you :)

**Comment by Luke100000** [comment]
Please attach your world file and the name of relevant villagers, so I can take a look at this.
