### ISSUE TITLE
HELP !!!

### ISSUE THREAD

**Issue by Kasia1403** [WildBamaBoy/minecraft-comes-alive#1360]
How to fix IRQL NOT LESS OR EQUAL error ? I get this error when loading Minecraft 1.12.2 with MCA mod ( newest version ). Could someone help ? Sorry, but changing MCA version to 5.3.1 doesn't help.
[latest.log](https://github.com/WildBamaBoy/minecraft-comes-alive/files/6501330/latest.log)

**Comment by Luke100000** [comment]
Development happens here now: https://discord.gg/MDcv8kmYHP
Please send me the entire error, then I can take a look at it.
