### ISSUE TITLE
[1.5.2] Baby is not growing into a child

### ISSUE THREAD

**Issue by ThePwnd** [WildBamaBoy/minecraft-comes-alive#151]
So firstly, I realize that I'm running this on a wayyy backdated version of Minecraft so I know that puts me at the bottom of the priority list, but I'm not asking anyone to fix this because I realize there are more pressing issues like, keeping the mod up to date.  I'm just wondering if anyone has experienced this problem before and would maybe have some solutions/ideas.

As in the description I'm playing Minecraft 1.5.2, Forge 7.8.1.738, and MCA v3.5.4.  I married an NPC villager, had a baby, and I've been waiting a good half an hour but I'm not getting notified that its ready to grow into a child.  I've also tried right-clicking him on the ground about a dozen times throughout this half hour but nothing is happening.  The default is 10 minutes for this process to occur, and I've double checked my config file to ensure I didn't change the value and just forget, and no, I haven't.  I thought maybe I wandered too far away and unloaded the chunks where the baby was (I left it in my NPC wife's inventory), so I stood next to her for two full day cycles and still nothing has happened.  I've also transferred the baby to my inventory and waited an equal amount of time and still nothing.  Am I missing something?

If anyone has any idea what's wrong or could think of a workaround I would really appreciate it.

P.S.  I am playing with A TON of mods, so if there are any known incompatibilities I'm unaware of, let me know.

**Comment by wolfie2902** [comment]
I believe I may have the same issue however, in config, I do not have a MCA file only a file 'MCA.cfg'. Any ideas?

**Comment by WildBamaBoy** [comment]
This issue is for Minecraft 1.5.2 only. Minecraft 1.7.10 and 1.8.9 are the only supported versions right now.
