### ISSUE TITLE
New Feature Suggestions 

### ISSUE THREAD

**Issue by jedsilei** [WildBamaBoy/minecraft-comes-alive#195]
Hello Wildbamaboy i have something for you to please add new features from the mod MCA, There should be a reviving item to revive dead villagers or dead relatives, Because people such as me are upset because of the death of villagers (I know it's just a game) also upset because of their cool builds and what their done in their world but then their one of the family member died so they just never played that world again. True Story. So please add this feature

**Comment by HillustratedMike36** [comment]
Even though this is closed, this could be noted as mod-compatibility. [NightKosh]'s Gravestone Mod can bring resurrect villagers...although they will not be the same person (but same profession).
