### ISSUE TITLE
you already have a baby glitch 

### ISSUE THREAD

**Issue by FluffyFighter667** [WildBamaBoy/minecraft-comes-alive#203]
i got a wife on here and when ever i try to procreate it says you already have a baby but i dont i killed the one i had and it still dose that plz help!

**Comment by tzeraph** [comment]
Almost the same thing here. Wife died, and after remarriage, I cannot create new children with new wife. Getting the same message as the op "You already have a baby child"

**Comment by Kippchi** [comment]
im having this problem, mine died and i cannot have children with any other spouse, player included, is there a fix for this?

**Comment by chiller-squirrel** [comment]
I am currently having the same issue on MCA 1.7.10-5.1.2 is there a fix for this I can perform.
