### ISSUE TITLE
Pams HarvestCraft

### ISSUE THREAD

**Issue by morlanius** [WildBamaBoy/minecraft-comes-alive#206]
I would like to see support for pams harvestcraft recipes for the cooking and farming functions.
Apart from that everyone seems to be really enjoying the mod in one way or another.

**Comment by morrissimo** [comment]
Crazy timing: briefly looked for any info on integrating HarvestCraft with MCA a few days ago but didn't see anything. Came here tonight to open an issue ...and found this one :)

So: :+1: in favor of HarvestCraft-MCA integration
