### ISSUE TITLE
Language gender issues

### ISSUE THREAD

**Issue by LorenzoDCC** [WildBamaBoy/minecraft-comes-alive#207]
There's a problem in localised languages - some of them have gender-sensitive terms (like Fazendeiro and Fazendeira, he-farmer and she-farmer, respectively). Could you, if possible, mess with the code to be able to change the term depending on the gender? Because having "Ashley He-Farmer" going around is pretty weird :worried:

**Comment by MrKunji** [comment]
I will fix it :p

**Comment by LorenzoDCC** [comment]
I googled 'lazy' and a bunch of pics of me showed up. Weird.
