### ISSUE TITLE
Add Monarch System

### ISSUE THREAD

**Issue by WildBamaBoy** [WildBamaBoy/minecraft-comes-alive#217]

**Comment by DemonicIntent** [comment]
Monarch System:
 - No More Just Crafting!
  - You can still craft the Monarch Outfit & Crown
- Added in Different Types of Crowns
 - Decoration: Monarch Outfit & Crown
 - Coronation Crown
To Become King:
 - Event/Action: Earn X Amount of Respect from doing "quests/chores" for the townspeople.
  - After earning X Amount, talk to a priest
   - If you have the "ability" you may take coronation to become King/Queen
     - Choose a Kingdom Name
 - After becoming King, villagers within X Radius become peasants/Knights
  - Other Villagers will have to be asked to join your Kingdom
On a Server:
 - Villagers of different Kingdoms can do war with each other.
  - Wars can be setup with "Documents"
   - By creating a "Document of War" and giving to another player.
    - If player accepts the war (Right-Clicks with Document) villagers will fight with each other on sight
    - If Player refuses the war, drops the document. The creator of the War Document will be seen as an enemy
    - Only attacked if they enter the town. UNLESS v
     - Player who denies the "Document of War" gives the sender a "Document of Peace"
      - If Sender accepts it, ties with the two are neutral
   - By Creating a "Document of Trade" two kingdoms can become Allies, in which will help each other.
    - By fighting their Allies Enemies, or by doing trade of goods.
Not on A Server, but want to do war:
 - Random Kingdoms start cropping up NPC ran, some good/bad/neutral.
  - Kingdoms start cropping up 1-2 Hours of the player starts a kingdom.
   - Kingdoms will attack/or apply for peace at random.
=============================================
This is just an idea, could be more prolonged or shortened. But I do think this will add in some game play for those whom like such things.

**Comment by WildBamaBoy** [comment]
Oh dang...

**Comment by TheShootingStar45** [comment]
Very great idea!

**Comment by Orange1861** [comment]
MCA is turning into Millenaire, :).

**Comment by TheShootingStar45** [comment]
I can't wait for the big update of MCA!

**Comment by DRULES679** [comment]
Well... Maybe not the all villagers in a certain radius become peasants. And, if you're in creative, maybe you can just automatically have the monarch ability.

**Comment by DemonicIntent** [comment]
@DRULES679 That would be more of a story-progression add-on maybe, that could be disabled by default but enabled by the player if they want to.

**Comment by DRULES679** [comment]
@DemoniIntent, I was about to say that, how it there could be a setting to put it on classic monarch mode, which makes the monarch system act like the pre-5.0 updates. Make even a configuration that will, if you're configuring it from in-game, will open up a configuration menu to change specifric things.
All in all, all those ideas are great. I'm looking forward to this update!

**Comment by DRULES679** [comment]
**@DemonicIntent** Also, just asking for the single play people.

IDEA: What if when you won a war, your could choose options for what your reward would be. 

- Conquer the loser (their village is now owned by/a part of yours)
- Opponent isn't aloud to attack you or your village in anyway but you can attack them/their village, 
- Ally them (the winner and loser don't attack eachother, can support one another when one is at war, can extend into a large group using ally documents) 
- The enemy pays you a fine 
- No reward(s?)... (etc)

**Comment by Valorum5** [comment]
When is this set to be released?

**Comment by WildBamaBoy** [comment]
Moved somewhere secret...

**Comment by BlazingRoman** [comment]
Sorry if this is necroposting, but what ever happened to this update? its been 3 years and this monarchy update still hasn't happened.
