### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Minecraft88887** [WildBamaBoy/minecraft-comes-alive#223]
i found a Bug where if you put a Enchanted item in a Villagers Inventory it will Remove the Enchant i noticed this because i put a Sharpness XX sword in a Childs Inventory i noticed it did not one hit a Creeper the Enchant was gone i am using the Latest version of Forge

Please Patch the Bug, Minecraft88887

**Comment by WildBamaBoy** [comment]
Resolved in rewrite #228 
Get MCA 5 once it's released.
