### ISSUE TITLE
[Villager inventory bug] and [Enchantments lost] - MCA-1.7.10-4.1.5-universal

### ISSUE THREAD

**Issue by jyumai** [WildBamaBoy/minecraft-comes-alive#236]
There seems to be an issue with the villager's inventory (fiancee in this case), where sometimes the slots are shifted out of place but the textures are placed correctly. The shift seems to be random and changes position every time I restart mc. I have NEI, optifine, sildurs basic shaders and liteloader installed as well as several other mods. I am using forge-1.7.10-10.13.2.1291. I can however, place items into the main bag and armor slots. The four slots to the far right do not work at all even if one or two are highlighted when I hover over them (correct me if I am wrong but these are weapon/tool slots?). Even if I disable NEI the slots are still out of place.

Also, enchanted weapons still become de-enchanted when placed in a villager's inventory.

**Comment by WildBamaBoy** [comment]
Resolved in rewrite. #228
Get MCA version 5 once it's released.
