### ISSUE TITLE
Issue with new option to change the name from Mojang.com

### ISSUE THREAD

**Issue by ThunderRunner** [WildBamaBoy/minecraft-comes-alive#237]
So with the recent ability to change your in game name, I found that if you do change your name, this causes your relationships with npcs to change. For example, if you were married before you changed your name, you are considered to be a completely different character to all npcs including your family after you do change it.

**Comment by WildBamaBoy** [comment]
MCA does not support any name changes. This issue is known and will not be fixed, unfortunately.

**Comment by ThunderRunner** [comment]
Will it not be fixed simply because it can't be for because you don't want to?

**Comment by WildBamaBoy** [comment]
It will not be fixed since there isn't really a feasible way to repair it due to how MCA is written currently.

**Comment by ThunderRunner** [comment]
Alright, thanks for the info, do you think that it'll be back to normal if I change my name back?

**Comment by WildBamaBoy** [comment]
I can't say for sure. It would be easier to spawn NPCs you are related to again and modify them using the villager editor.

**Comment by ThunderRunner** [comment]
I was unaware I could do that. I'll have a look into it.
