### ISSUE TITLE
Hunting Bug

### ISSUE THREAD

**Issue by Stevymcstevyman** [WildBamaBoy/minecraft-comes-alive#243]
I have found a bug in my game where if you send your child hunting and choose the kill option, your child will disappear and not reappear with the whistle. "[child name]: [child name], you son/daughter, had died." You'll get that message after a few minutes after you send your child hunting. This has been tested 5 times on the same MCA version, and has been confirmed by those 5 tests. Can you fix it in the  new MCA 5 please?

**Comment by WildBamaBoy** [comment]
This is the intended function of the hunting chore. They will disappear, then reappear if it is calculated that they have not died. This is determined by whether or not the child is wearing armor or has a weapon.

**Comment by Stevymcstevyman** [comment]
Thanks for the information. I'll try to make my child wear armor the next
time. :)
