### ISSUE TITLE
PLEASE HELP CRYED MY EYES OUT

### ISSUE THREAD

**Issue by LittleMissRue** [WildBamaBoy/minecraft-comes-alive#249]
Okay, i had a Fiancée and he supposivle died. After her death other villagers keep congratulating me for my engagement. My friends are just like on their server I love my husband bla bla bla bla bla and I am just balling my eyes out like I cant have the same fun mod experiance whaaa! Ect. I am on my friend's server and I use wistle nothing happens no one comes but my adopted child. And I try and hit "Divorce Spouce" with priests and nothing happens! Like what the heck bro? 

-LittleMissRue

Using MCA-1.7.10-4.1.5-universal
And RadixCore-1.7.10-1.3.4-universal

**Comment by LittleMissRue** [comment]
How do I fix it

**Comment by moinecraftperv** [comment]
Maybe it doesn't recognize you as married so try find another villager and try to marry them
