### ISSUE TITLE
Some instructions?

### ISSUE THREAD

**Issue by SACavendish** [WildBamaBoy/minecraft-comes-alive#253]
I am a big fan of this mod and what it does, but since MCA 5 I got a little lost... do we no longer have monarch? hiring is permanent? CTRL function is out? I mean I'm used to the older one and I just feel like a wiki page or something that can guide me would be useful, to make the transition. Thank you very much for the big update though! Also I am aware that this is just a Beta, I just thought I'd drop a line.

P.S.: I sent you a wall of a mail back when you were open to suggestions for MCA 5 (under the name of Meyerhof) , something I really worked on, and I understand it was a lot of text but just knowing that you got it even if you did not read it would be good to hear. Thanks.

**Comment by WildBamaBoy** [comment]
Check the changelog for a full list of changes. An updated guide will be posted on our website soon.

As for your e-mail, I do have it. We're still reviewing those during beta. :)
