### ISSUE TITLE
Please read my ideas of minecraft comes alive 

### ISSUE THREAD

**Issue by minecraft213** [WildBamaBoy/minecraft-comes-alive#262]
Here is my suggestions for mca that you guys should make it that you can have up 4 to 8 baby's at a time and that it should take at least a day for a baby to come out and can you guys add princess or a prince and you can Marry them and you like become the prince or princess and then when the queen or king dies you become prince or princess and their is a castle it would be awesome please reply and don't close this

**Comment by WildBamaBoy** [comment]
Only submit bug reports to GitHub, not suggestions.
