### ISSUE TITLE
Name is set as "none", child does not call me 'dad'

### ISSUE THREAD

**Issue by moinecraftperv** [WildBamaBoy/minecraft-comes-alive#263]
So my child does not call me dad, he greets me just like every adult (Hey there!) and for some reason when villagers use a phrase thats supposed to contain my name in it, it's like "thank you, none" (i can't remember the exact sentence)
And when i right click the ground with the "crystal ball" item, my computer will always overheat and crash.. 
Can you add the GUI that appears every time you create a new world, like set gender, preference and name - i right clicked "special" from a librarian villager but it's empty :(

**Comment by WildBamaBoy** [comment]
Your name defaults to "none" if you do not use the crystal ball. If you crash while using it, are you able to get me a crash report so that I can look into this?
