### ISSUE TITLE
Feature Request: Configurable Permissions for the last Step during "Live-Start" using the Orb

### ISSUE THREAD

**Issue by impulse255** [WildBamaBoy/minecraft-comes-alive#272]
Please add an Option to disable the House/Village-Spawning at the end of using the Crystal.
When setting up MCA 5 in an existing SMP world this may help not destroying existing structures.

Thanks for considerung and kind regards!

**Comment by WildBamaBoy** [comment]
House and village spawning is automatically disabled on servers.
