### ISSUE TITLE
Missing options for my wife and son

### ISSUE THREAD

**Issue by sergio239** [WildBamaBoy/minecraft-comes-alive#273]
There's stuff missing in the GUI, but only for my son and my wife :(

![2015-03-27_12 29 29](https://cloud.githubusercontent.com/assets/11638309/6866973/a796d0ae-d47d-11e4-8a02-61a9f6ad273e.png)

**Comment by WildBamaBoy** [comment]
Are you on single player, LAN, or a server?

**Comment by sergio239** [comment]
I'm on singleplayer, although I've opened the world in LAN a few times.

**Comment by zombiex227** [comment]
That happened to me on my private server, i disconnected and reconnected and it was fixed.

**Comment by sergio239** [comment]
It goes fine when I do that, but it reapears after I get into the world several times.

**Comment by sergio239** [comment]
It goes fine when I do that, but it reappears after I get into the world several times.

**Comment by WildBamaBoy** [comment]
Going to take a look at this later today.

**Comment by WildBamaBoy** [comment]
Unable to reproduce this on my end using several different methods. Assuming that some previous fix may have already resolved this. If it happens again when MCA is brought out of beta, let me know.
