### ISSUE TITLE
Giving a Divorce Paper to your spouse will make them say they are not married, whilst not affected the engagement/marriage.

### ISSUE THREAD

**Issue by rain77** [WildBamaBoy/minecraft-comes-alive#277]
(I know you are supposed to talk to the Cleric to divorce your spouse.)

When you give a Divorce Paper to your spouse, they will say they aren't married. The engagement/marriage won't be affected when you do this.

**Comment by WildBamaBoy** [comment]
Unable to reproduce. Probably related to #276

**Comment by Savannah21** [comment]
When i give the divorce papers to my wife it says interaction.divorce.notmarriedtoplayer
