### ISSUE TITLE
Baby doesn't grow when in spouse's inventory

### ISSUE THREAD

**Issue by MaxoutExtre** [WildBamaBoy/minecraft-comes-alive#283]
By giving your baby to your spouse, it will only pause its growth unless you take the baby back.

**Comment by WildBamaBoy** [comment]
Note to self:

			for (int i = 0; i < inventory.getSizeInventory() - 1; i++)
			{
				ItemStack stack = inventory.getStackInSlot(i);
				
				if (stack != null && stack.getItem() instanceof ItemBaby)
				{
					ItemBaby item = (ItemBaby)stack.getItem();
					item.onUpdate(stack, worldObj, this, 1, false);
				}
			}
