### ISSUE TITLE
Add "Cook Food" option for spouse

### ISSUE THREAD

**Issue by MaxoutExtre** [WildBamaBoy/minecraft-comes-alive#284]
Some villagers can cook faster, while some cook slower

**Comment by HillustratedMike36** [comment]
I was hoping after they are done cooking your food, they drop the food they cooked.

**Comment by TheShootingStar45** [comment]
But, if it is possible, i'd like if our inventory isn't full, they send the cooked foods directly into our inventory. That would be so useful! =)
