### ISSUE TITLE
Heart points nowhere to be seen above child

### ISSUE THREAD

**Issue by MaxoutExtre** [WildBamaBoy/minecraft-comes-alive#285]
So, I was chopping down wood when my axe accidently hit my daughter (I used the "Pick Up" option, so she was on top of me). I dropped her to the ground and checked how many hearts were lost, only to notice that there were no heart points. Even after positive interactions, the hearts wont increase.

**Comment by MaxoutExtre** [comment]
Update: Close this issue

**Comment by moinecraftperv** [comment]
You might want to gift her a diamond/gold/iron block and see if the hearts go.back up
