### ISSUE TITLE
(Add) Height and Girth Factor config

### ISSUE THREAD

**Issue by JoshuaDR** [WildBamaBoy/minecraft-comes-alive#288]
Please add something at the config folder where people can activate or deactivate height and girth factors. People can disable random height and girth factors so when spawning villagers they have normal sizes big and small but not fat and thin. The reason of this is because I don't want my villagers fat and sometimes thin but mostly fat. When I'm spawning villagers they mostly appear fat. I want them to appear like players taking out of the loneliness of minecraft. I'm actually making a mod pack.
![2015-04-01_16 41 24](https://cloud.githubusercontent.com/assets/11750955/6937598/03d91286-d88f-11e4-8cbe-e677361b3c3a.png)
I like minecraft comes alive mod making villagers act like players but please add this configuration at future updates.
Just for you to know I'm using v5.0.0 for Minecraft Comes Alive. This one of the best mods that I know keep up the good work :) .

**Comment by Candlemancer** [comment]
As an alternative to this, or perhaps in addition, I think changing the way height and girth is generated from truly random to a randomly sampled normal distribution would help a lot. (Plus it is much closer to how height and girth are distributed among real people.)

To implement such a change would just require switching RadixMath.getNumberInRange() (assuming it's not used elsewhere) from 
````java
return (rand.nextFloat() * (maximum - minimum)) + minimum;
````
to
````java
return (rand.nextGaussian() * standardDeviation) + mean;
````

Setting standardDeviation to 0.3 and mean to 0.10 would give you a total range pretty close to what you have now, though a lot more villagers would have average height and girth. You'd still have some villagers who were tall, some who were short, some who were wide, and some who were skinny, but overall villagers would look more average.

**Comment by WildBamaBoy** [comment]
@Candlemancer I like this solution. I'll throw it in. :)

**Comment by Hernan0708** [comment]
I agree with you guys. most of my villagers are fat and MCA needs Girth and Height in the Config.
