### ISSUE TITLE
-Question- Villagers and Ocelots

### ISSUE THREAD

**Issue by moinecraftperv** [WildBamaBoy/minecraft-comes-alive#290]
Do they have the same ID or something? cuz when i spawned creepers in a village they all run away for some reason, same thing happens when i spawn a villager near a creeper, it just flees like it saw an ocelot
Btw please make villagers try to avoid water cos lots of guards get stuck in the well and sometimes in the farm where theres a column of water in between the crops
Sometimes im trying to lure a creeper away from my village so nothing gets destroyed but a villager walks near and the creeper runs towards the village and just boom

**Comment by WildBamaBoy** [comment]
This is intended behavior. Creepers will run away from villagers so that damage to a village is minimal. Don't try to lure them, they'll stay away on their own.
