### ISSUE TITLE
Add dialogue upon a villager's death

### ISSUE THREAD

**Issue by rain77** [WildBamaBoy/minecraft-comes-alive#293]
There should be an aesthetic feature where villagers emit dialogue upon being killed by a player. (Different dialogue from being hit by a player)

**Comment by SNDGIRL** [comment]
Yeah good idea! Maybe like, "How could you do something like that?" or "Murderer!" or "Guards help! Someone is being assaulted!" Just saying something that villagers would say :)

**Comment by WildBamaBoy** [comment]
Going to deny this for now, but will keep it in mind.
