### ISSUE TITLE
Sometimes after death, unable to hit or interact with spouse 

### ISSUE THREAD

**Issue by rain77** [WildBamaBoy/minecraft-comes-alive#294]

**Comment by WildBamaBoy** [comment]
As in, after your death correct? Were you using any other mods/did you die in a different dimension?

Also does restarting the game seem to resolve the issue?

**Comment by rain77** [comment]
Yeah, after my death.
I wasn't using any other mods, and I was in the regular world.
I haven't tested restarting the game yet. However, dying again will resolve the issue.

**Comment by WildBamaBoy** [comment]
Unable to reproduce this after several tries. Considering it a fluke.
