### ISSUE TITLE
Guard Blinking without helmet

### ISSUE THREAD

**Issue by JoshuaDR** [WildBamaBoy/minecraft-comes-alive#295]
![2015-04-05_00 51 44](https://cloud.githubusercontent.com/assets/11750955/6993658/2a9c2d58-db2e-11e4-8f5a-5ba939c06707.png)
This skin of a guard changes when he sleeps. When the guard sleeps he close his eyes and taken of his helmet. When a villager blink it will use its sleeping skin. This guard when he blinks his helmet will disappear which is kinda weird. In this photo, I did not caught him blinking without his helmet because it was too fast to be captured by a screenshot.
![2015-04-01_16 41 24](https://cloud.githubusercontent.com/assets/11750955/6993670/bbd68d36-db2e-11e4-8438-ccbca775def7.png)
What you just need to do is change his sleeping skin so that he will not removed his helmet when blinking. I found this problem so that it will not stay in future updates.

**Comment by JoshuaDR** [comment]
Just asking what is Aesthetic?

**Comment by damcboss** [comment]
Aesthetic means preferred looks
