### ISSUE TITLE
In 1.6.4 my baby can't be placed

### ISSUE THREAD

**Issue by AllyMarie** [WildBamaBoy/minecraft-comes-alive#298]
I am playing in 1.6.4 and I've been playing for hours and can't place my baby. It never tells me it's ready to grow or anything. Not even given to my spouse works! Solutions?

**Comment by WildBamaBoy** [comment]
1.6.4 is no longer supported, however an update to 5.0.0 on 1.6.4 is in progress.

What you can do to reset the process is find a priest, use Special->Give Up Baby, then have another child, which should then work for you.
