### ISSUE TITLE
my wife doplicated!

### ISSUE THREAD

**Issue by Bbuddy** [WildBamaBoy/minecraft-comes-alive#299]
i was just having a normal day and when i got home to go to bed my wife was standing in the bed and at the same time sleeping in the bed this is 1.7.10 by the way and it was wierd kill one of hers :/

**Comment by moinecraftperv** [comment]
loool

**Comment by WildBamaBoy** [comment]
What version of MCA were you using?

**Comment by SNDGIRL** [comment]
Probably a glitch or something, or maybe a witch came in your house and created a twin of your wife 0.0

**Comment by JoshuaDR** [comment]
Yup, it could be just a glitch.

**Comment by SNDGIRL** [comment]
Probably

**Comment by WildBamaBoy** [comment]
Closing as no further info was provided.
