### ISSUE TITLE
Generated Villages and Houses

### ISSUE THREAD

**Issue by JoshuaDR** [WildBamaBoy/minecraft-comes-alive#303]
Does minecraft comes alive works in server hosting?
This may cause a problem when players can use the enchanting table and generate a village or house where ever they want.
![2015-04-09_13 49 12](https://cloud.githubusercontent.com/assets/11750955/7061162/9ad1d5b0-dec0-11e4-8754-099e96596b81.png)

**Comment by WildBamaBoy** [comment]
Generated structures cannot be spawned on a server.

**Comment by JoshuaDR** [comment]
Thanks for the information :)
