### ISSUE TITLE
Things you Could Improve On For 5.0

### ISSUE THREAD

**Issue by SNDGIRL** [WildBamaBoy/minecraft-comes-alive#304]
I found quite a bit of bugs for MCA 5.0 including things that I think you guys could improve on, don't get me wrong it's a beautiful mod and all updates have bugs.

- Maybe add new types of Villages like Jungle and Desert, things to fit each biome
- When the village was found for me, it looked like it had just been placed on the map because it was several blocks higher than the actual ground of the forest
- Maybe add back the Monarch content for future updates because I found that quite enjoyable 
- The guards aren't much use in my village they don't attack any mobs and keep getting stuck in the fence
- In the future maybe you could add a new type of Villager like a Hunter or Woodcutter
- When I try to change a villager's name with the village editor, and delete the previous name then type the new one in when I click done it doesn't change the name
- The houses are beautiful but maybe you could make it so it looks more like a village such as the ones in Vanilla Minecraft, maybe you could add some accents to the houses such as furnaces and crafting table etc.

**Comment by WildBamaBoy** [comment]
All things mentioned are already planned. Update from beta to the full version of 5.0.0 in order for the bugs you have mentioned to be fixed.
