### ISSUE TITLE
Possible Things You Could Add

### ISSUE THREAD

**Issue by SNDGIRL** [WildBamaBoy/minecraft-comes-alive#305]
I was thinking a lot about things you could add on, their is always room for improvement right? So here is a list of things you could possibly add:
- I find myself sometimes getting bored from the continued dialoge so perhaps you could add more speech for villagers such as when the player becomes Monarch and gets the achievment the villagers and guards could say "Good day Lady/Lord (Player Name)." 
- The children's chores aren't the best it could be, I think the Mining Chore is the one that needs to be most improved on like you could make the child dig straight at the ore instead of in a straight line
- Better Villages, The Villages need to be spiced up a bit and look more like villages you could add a feature where the village is determined on which biome it is in

**Comment by WildBamaBoy** [comment]
Closing duplicate issue
