### ISSUE TITLE
Archers do not face their targets.

### ISSUE THREAD

**Issue by JoshuaDR** [WildBamaBoy/minecraft-comes-alive#306]
Is it me or the archers in my village fire the arrows wrong. The archers does not aim and face to their target. For some information I use minecraft 1.7.10 and use MCA 5.0.0. Please change this in future updates.
![2015-04-10_14 55 10](https://cloud.githubusercontent.com/assets/11750955/7090171/a1db2320-dfd3-11e4-9501-d71e652cfbe8.png)

**Comment by SNDGIRL** [comment]
The guards don't even attack anything for me

**Comment by SNDGIRL** [comment]
Maybe they have a skill and it improves the more they use a bow

**Comment by JoshuaDR** [comment]
Sorry for my bad english ^_^

**Comment by SNDGIRL** [comment]
Yeahhh!! It's fixed!
