### ISSUE TITLE
Conflict with Grimore of Gia

### ISSUE THREAD

**Issue by Alexander175** [WildBamaBoy/minecraft-comes-alive#307]
Hello my name is Alex and i was told to report this problem here when i thought is was another mods problem but anyways the problem is with the 2 mods MCA and Grimore Of Gia 3 the trader cards from the mod Grimore Of Gia 3 are suppose to spawn a specific mob but instead it spawn a random villager from MCA. There is no crash report or anything.

Playing the latest version of MCA and RadixCore.

**Comment by SNDGIRL** [comment]
Maybe some files got mixed up, sorry I can't help

**Comment by WildBamaBoy** [comment]
If the mod is attempting to spawn regular villagers, they will appear as MCA villagers. What exact version of Grimore of Gia are you using?

**Comment by Alexander175** [comment]
I am using Grimore Of Gia version 1.0.9 for 1.7.10

**Comment by WildBamaBoy** [comment]
This is a problem on Grimore of Gia's end. They do not assign new profession IDs to their villagers (Creeper Girl, Slime Girl, Trader). MCA will overwrite any "villager" whose ID is 0 - 4, the default profession IDs.
