### ISSUE TITLE
Villagers Dieing if Sleeping at home point

### ISSUE THREAD

**Issue by RottenBananaMC** [WildBamaBoy/minecraft-comes-alive#308]
I summoned a villager. I set its home point (3x3 extra space) when it turned night, the villager went to its home point and died. it happened about three times to me.

-Rotten_Banana

**Comment by RottenBananaMC** [comment]
MCA 5.0.0 17.10

**Comment by moinecraftperv** [comment]
the villager suffocated in the wall right??

**Comment by SNDGIRL** [comment]
This has happened to other people, so it looks like it is common, make sure they aren't close to any walls and if that doesn't work then don't set home points or go back to the previous version until this one gets the bugs and glitches fixed

**Comment by WildBamaBoy** [comment]
Villagers can always die from outside causes. I am aware in some cases that villagers are dying because they teleport into a wall instead of their home point.
