### ISSUE TITLE
Story Progression Glitch

### ISSUE THREAD

**Issue by Natemaster200** [WildBamaBoy/minecraft-comes-alive#309]
I turned the story progression feature off in the config file, but villagers still get married and have children without my permission. Is this supposed to happen? How could I fix this?

Another question: Would setting the story progression rate as "0" stop story progressions from occurring or would it make them constant?

**Comment by SNDGIRL** [comment]
That is another thing on the list that doesn't work, for now if you really don't want villagers having children on their own go to the previous version until this one is fixed

**Comment by WildBamaBoy** [comment]
Story progression at zero would cause some major issues. I'll fix that as well.
