### ISSUE TITLE
Child stuck in wall glitch

### ISSUE THREAD

**Issue by moinecraftperv** [WildBamaBoy/minecraft-comes-alive#310]
![2015-04-11_17 59 38](https://cloud.githubusercontent.com/assets/11499922/7101060/75c9ac00-e075-11e4-98e9-175e2b032988.png)
villagers also randomly get stuck in walls and sometimes suffocate to death
sometimes villagers dont teleport properly to their home point and die when they get stuck in the wall
sometimes villagers get stuck in their bed instead of sleeping on it and sometimes die even if theres no solid block 1 block above the bed

**Comment by WildBamaBoy** [comment]
Set home points away from any nearby walls to avoid this issue. Home points will be improved in the future.
