### ISSUE TITLE
Enter player username in villager editor to apply that player's skin.

### ISSUE THREAD

**Issue by Time6628** [WildBamaBoy/minecraft-comes-alive#311]
Would it be possible to make player skins automatically become a possible NPC skin? I think that would be really cool for servers. Maybe a config option? Thanks for reading!
-Time

**Comment by Orange1861** [comment]
That would be a GREAT feature. :)

**Comment by HillustratedMike36** [comment]
I agree...but I would think this feature should be configuratable and not built-in and is more like "not recommended, unless you want the actual Minecraft user coming after you for plagiarism."

**Comment by Time6628** [comment]
@HillustratedMike36 Minecraft skins aren't private so you don't have to worry about plagiarism.

**Comment by PumpkinPuff** [comment]
Totally just a suggestion - not sure if i can make those here but.
How about having an item that JUST changes the skin, height and such. For people who have servers but doesn't want people editing their villagers jobs/roles but the players want a skin change?
