### ISSUE TITLE
MCA-1.7.10-4.1.5-universal Children attack me on sight crashing world and deleting map on Blastoff Ftb modpack

### ISSUE THREAD

**Issue by tortmancomith** [WildBamaBoy/minecraft-comes-alive#312]
I found a zombie villager and cured it making a villager female. After some bribery we were married and had a girl. When the girl was grown it attacked me on sight and killed me bypassing sync mod respawn and deleting my world. I rolled back the world tryed again same results. I installed the 5.0 version and same thing started fresh game same thing. I really enjoy your mod but ruining my world isnt a option i have the beast locked in her room now. is there anything i can do to fix this. if not im going to have to uthinize the kid and not try the new mod out.

**Comment by WildBamaBoy** [comment]
MCA 4.1.5 is no longer supported, sorry.

**Comment by tortmancomith** [comment]
it does it on 5.0 as well

**Comment by WildBamaBoy** [comment]
Then I'll need a crash report.

**Comment by tortmancomith** [comment]
i dont know if i have that report but my guess is the child going insane killing me trying to give me her life while sync mod clones you is why it crashed its a shame ill most likly take the mod out let the mod pack auther know on ftb what the issue is only other thing i could do is nuke the family again load 5.0 and reproduce it. but the crash i dont carew as much as all children are hostile to me with ove 1k affection

and positive attitude to me
