### ISSUE TITLE
Will the future update 5.1.0 add skins?

### ISSUE THREAD

**Issue by JoshuaDR** [WildBamaBoy/minecraft-comes-alive#314]
Cause I'm actually adding many skin inside the MCA mod .jar file in the skins folder. I'm just asking if you are going to add more skins in the future update 5.1.0 cause I will be rearranging the skin names again. It's okay, are you going to add more skins? Just asking.
![2015-03-01_17 21 26](https://cloud.githubusercontent.com/assets/11750955/7106101/52aa520c-e169-11e4-9d10-8e464168ba56.png)
![2015-03-01_17 21 27](https://cloud.githubusercontent.com/assets/11750955/7106102/52d4f6ce-e169-11e4-8344-91ffa0ae0d44.png)
![2015-03-01_17 21 33](https://cloud.githubusercontent.com/assets/11750955/7106103/556b3402-e169-11e4-9f4b-96a3a1a3cfb8.png)

**Comment by WildBamaBoy** [comment]
#311
