### ISSUE TITLE
MCA Villergers hate Malisisdoors

### ISSUE THREAD

**Issue by QORTEC** [WildBamaBoy/minecraft-comes-alive#316]
On my server it seams that MCA villagers don't understand Malisisdoors.

The Malisisdoors mod adds a bunch of new doors, as well as adding new smother animations to "vanilla" doors. (Also by opening one side of a double door both doors open.) How ever MCA villagers dont seam to understand "vanilla" doors after Malisisdoors has finished modifying them.
 - villagers wont willingly use the door
 - villagers don’t consider a house attached to that door safe

In the Malisisdoors config the following is responsible for the vanilla doors modification:

    # nullEnables the animations for doors, fence gates and trap doors. This replaces
    # the doors entirely so conflicts may arise if another mod tries to modify them too.
    B:config.modifyVanillaDoors=false

Will it be possible to support Malisisdoors modified vanilla doors?

(Off topic question is there a IRC room for MCA?)

**Comment by WildBamaBoy** [comment]
There is no IRC room for MCA, and I'm not sure I could do anything to fix this problem. MCA villagers use Minecraft's default AI for moving around a village and opening/closing doors.
