### ISSUE TITLE
villager bed glitches for child

### ISSUE THREAD

**Issue by kokomo616** [WildBamaBoy/minecraft-comes-alive#322]
![2015-04-22_19 53 04](https://cloud.githubusercontent.com/assets/12076195/7288005/895dd23e-e929-11e4-9302-5b9ddecc868c.png)

villager children sink into the bed and if the head of the bed is against the wall they will spawn in it and die or phase through the wall

**Comment by AngleWyrm** [comment]
Similar experience with a married female villager, who attempted to sleep in my villager bed and took damage until she died. Villager bed pictured on right:
![2015-04-26_14](https://cloud.githubusercontent.com/assets/2841453/7339689/d4c538c2-ec24-11e4-9b4c-10bfd585b886.png)

**Comment by WildBamaBoy** [comment]
#341
