### ISSUE TITLE
Installed and all the villagers disappeared

### ISSUE THREAD

**Issue by RascalkingMCA** [WildBamaBoy/minecraft-comes-alive#324]
I replaced my MCA 4.1.5 and RadixCore 1.3.4 with the latest updates in the mods folder.  Got the message that the blocks had disappeared (monarch stuff etc.), it backed up the word (thankfully) and when the game loaded ... all the villagers in my world were gone...  Anyone else get this?

**Comment by WildBamaBoy** [comment]
Check the changelog, MCA 5 is not compatible with the previous version.
