### ISSUE TITLE
Hardcore mode SSP world deleted before check if secret is to be used...

### ISSUE THREAD

**Issue by plaguewolf** [WildBamaBoy/minecraft-comes-alive#325]
so im getting a client crash when playing hardcore mode. and i dont know what im doing wrong. and i also dont know if its a 'secret' and im not supposed to talk about ti XD

i get a kid, make sure he/she is grown hen die.

but when i die in hardcore mode, i get presented with the vanilla 'delete world' menu. nothing else. then i click on delete world and i get a menu that says goto main menu or respawn. if i hit respawn the internal server crashes and i get a menu that says game over man you cant respawn in a hardcore world?

what what? wot.

log says its cause of a java.IO error, as in the world gets deleted and then asks if you want to respawn. but when i checked the files (/minecraft/saves/world) it was already deleted when MCA respawn menu showed up.

so is the 'secret' for SMP only? no ssp? or am i missing something?
and also i discovered a bug while testing the above. client does not like it when you exit/save game while in the hut that spawns so you can shoose gender and such. it crashed...

client doesnt crash after removing chickenbones wireless redston, but it still deletes world and has an IO coniption fit

**Comment by WildBamaBoy** [comment]
Hardcore mode feature is no longer present in the latest versions of MCA. Any crashes from the game over GUI is not caused by MCA.
