### ISSUE TITLE
MCA and flans mod

### ISSUE THREAD

**Issue by EatDaFire** [WildBamaBoy/minecraft-comes-alive#332]
flan's mod and MCA cannot be used at the same time because the wedding ring uses the same recipe that another does which is 3 gold in a horizontal line, I don't remember what it was called because I removed flans mod a long time ago due to this crafting issue

**Comment by DemonicIntent** [comment]
This can be overlooked, I don't see a need to change any crafting recipes when you can easily use another mod and re-create the recipe for that particular mod. Try asking around the forums for someone to make a simple patch mod as well. After installing both MCA 5 & Flans you can then add the patch which would slightly change the crafting recipe. 

When Making Modpacks, this problem arises often, the best way to fix it, is by doing some research and creating your own fix for it.

**Comment by WildBamaBoy** [comment]
Above workaround will be present in version 5.0.3. You'll have to disable the recipe in the configuration file and use rose gold for wedding rings instead.
