### ISSUE TITLE
Name/Profession bug still exists!!

### ISSUE THREAD

**Issue by moinecraftperv** [WildBamaBoy/minecraft-comes-alive#333]
![2015-04-27_16 48 27](https://cloud.githubusercontent.com/assets/11499922/7440229/c4aa061a-f0da-11e4-8ccf-21ef83bd2a75.png)

i'm using MCA version 5.0.2 and naturally spawned villagers still get this kind of name and title
(created a new world after installing 5.0.2)

**Comment by WildBamaBoy** [comment]
I don't see the problem here? Name is Cece, profession is Mason.

**Comment by moinecraftperv** [comment]
ohh i thought mason was only a guys name sorry o.O
