### ISSUE TITLE
Babies don't spawn in full inventory.

### ISSUE THREAD

**Issue by Orange1861** [WildBamaBoy/minecraft-comes-alive#334]
I was playing MCA 5.0.3 and I procreated with my wife. I had a full inventory and my baby didn't spawn and I couldn't have another one because a baby needs to become a child before you can have another one (I checked in creative mode) . I fixed the problem by getting a new baby through creative mode and spawn her as a child.

I think the lack of a baby spawn is a bug.

**Comment by Orange1861** [comment]
Does functional mean fixed or it is supposed to be like that?

**Comment by DemonicIntent** [comment]
The functional label means that it will/could be fixed in the future as it does affect the mod.
