### ISSUE TITLE
Make child an adult?

### ISSUE THREAD

**Issue by Orange1861** [WildBamaBoy/minecraft-comes-alive#335]
I got an achievement saying my son is grown up but it stills says Tim the child. I read that you give them a non enchanted golden apple but when I give them one nothing happens but him saying stuff like "I love it!".

I am playing in MCA 5.0.3.

**Comment by DemonicIntent** [comment]
Some of the information you have found on MCA, is usually for the older versions such as anything like 4, or older. MCA 5 was a rewrite of the system, and the feature may not be added yet. If you feel like they may miss this feature why not add an Issue asking if this feature would be added. Or updating your current post/issue.

**Comment by WildBamaBoy** [comment]
Their profession will remain "Child", indicating they are the child of a player. Dialogue issues after growing up were noted and fixed in f79856d2b6e813661f53780230b5c0b70f49d7ae. Fix will be present in MCA 5.0.4.
