### ISSUE TITLE
Crown absent/uncraftable (5.0.3)

### ISSUE THREAD

**Issue by goleog** [WildBamaBoy/minecraft-comes-alive#336]
It's not in the creative menu nor is it even craftable, and I don't have any other mod that would conflict with MCA. When upgrading from (4.1.5) I got the usual 'missing-blocks' warning, but immediately afterwards the crown was still present. Then I created a new world and the crown disappeared.

**Comment by goleog** [comment]
![2015-05-05_21 50 50](https://cloud.githubusercontent.com/assets/12265932/7487680/f69aef66-f370-11e4-9714-3104042c1e35.png)
![2015-05-05_21 50 59](https://cloud.githubusercontent.com/assets/12265932/7487678/f6989c70-f370-11e4-8868-3d5eadb9d966.png)
![2015-05-05_21 51 21](https://cloud.githubusercontent.com/assets/12265932/7487677/f6986b10-f370-11e4-83c7-db0d180d9b78.png)
![2015-05-05_21 50 18](https://cloud.githubusercontent.com/assets/12265932/7487679/f69a5416-f370-11e4-876e-7ac435a763d0.png)

**Comment by WildBamaBoy** [comment]
Monarch system and all associated items have been removed in order to be reworked in a future update. Please read all changelogs before reporting issues.
