### ISSUE TITLE
People rotate in bed.

### ISSUE THREAD

**Issue by Orange1861** [WildBamaBoy/minecraft-comes-alive#337]
My wife rotates on the villager bed about 50% of nights. Most adults do this too.  
 
I will add a picture soon.

I am playing on MCA 5.0.3 and minecraft 1.7.10.

**Comment by Dextrositylight** [comment]
I've seen this too, with witchery installed it's quite amusing to watch as witchery adds little camp beds and they're tossed off their little beds and swung at a weird angle into the villager beds then slowly turn to correct themselves! xD
For something possibly a bug it's quite entertaining, people do move in their sleep, just not like Michael Jackson! ;)

**Comment by WildBamaBoy** [comment]
#341
