### ISSUE TITLE
Grown up child villager still recognized as child

### ISSUE THREAD

**Issue by moinecraftperv** [WildBamaBoy/minecraft-comes-alive#339]
![2015-05-06_16 59 27](https://cloud.githubusercontent.com/assets/11499922/7509846/654fd05e-f4c8-11e4-9f83-2db6bdbf5d8d.png)

Using MC 1.7.10 and MCA 5.0.3

**Comment by WildBamaBoy** [comment]
Fixed in f79856d2b6e813661f53780230b5c0b70f49d7ae.
