### ISSUE TITLE
Procreate - Legacy Version

### ISSUE THREAD

**Issue by HillustratedMike36** [WildBamaBoy/minecraft-comes-alive#342]
I (think) in the MCA 4.1.5, if you use Procreate, your spouse would be holding your baby. In newer versions, you hold them. What I purpose is a configuratable function for [you/spouse] to hold babies when using Procreate.

in other words, this is more like a feature request than an issue.

**Comment by WildBamaBoy** [comment]
You'll hold it by default, and if your inventory is full your spouse will hold it. Not really any reason to change it.
