### ISSUE TITLE
Crash When Trying to Marry Villager

### ISSUE THREAD

**Issue by AmmolS** [WildBamaBoy/minecraft-comes-alive#345]
When trying to marry a villager after I am already engaged to them, the world will close by displaying "Shutting down internal server...". Afterwards it will say "Connection Lost: A fatal error has occurred, this connection is terminated" as if I lost connection to a server. The game does not crash and no crash report can be found. However, this is outputted in the Game Output of the Minecraft Launcher: http://pastebin.com/0HkKEJ5L

After starting the world again and trying to interact with the villager that I am trying to marry, it will display "That villager is being interacted with." When unloading the chunks the villager is within and reloading them, the villager can be interacted with again. However the villager will retain the "Engaged" status with my player and will not be married, and the villager will think I am already married to another villager when I try to gift the villager a wedding ring.

My player can marry the villager fine if the villager is not already engaged with me.

Tested with: 
MCA 5.0.4
Radix Core 2.0.1

**Comment by WildBamaBoy** [comment]
That's a weird one, are you running any other mods?

**Comment by AmmolS** [comment]
Yes, I actually had about 85 mods installed but after doing some testing, it seems the issues only occurs when Thaumcraft is installed. Also, I noticed it only crashes if I try to marry a villager from a naturally generated village, it doesn't crash in a MCA village.

**Comment by WildBamaBoy** [comment]
I'll have to look into this further with Thaumcraft installed.
