### ISSUE TITLE
Spouse

### ISSUE THREAD

**Issue by Tamkay** [WildBamaBoy/minecraft-comes-alive#346]
When I went into a different dimension my spouse followed me through the portal but then disapeered. i've tried using the whistle in both dimensions (one i came from and one i went to) and she doesnt come. additionally i cannot divorce her using a priest and i cannot remarry as i am aparently still married? please help

**Comment by WildBamaBoy** [comment]
The whistle will only call family members within your current dimension. It is likely that they died - you can reset your marriage status using the priest.
