### ISSUE TITLE
Procreate not available.

### ISSUE THREAD

**Issue by JX3carpenter** [WildBamaBoy/minecraft-comes-alive#347]
Hello, after a while I noticed that in the mod I wasn't able to make a child with my wife in the mod anymore because the procreate option and some others wasnt available. Im running a server im not sure if that matters. I also recently updated it. Help will be appreciated much.

**Comment by JX3carpenter** [comment]
I also have a couple of mods installed but it used to work fine with them.

**Comment by WildBamaBoy** [comment]
Make sure you are using 5.0.5_1, and remember that changing your Minecraft name can cause this to happen. As far as I'm aware, this was fixed several updates ago and I haven't had reports since.

**Comment by JX3carpenter** [comment]
Yes I am using the latest version and no one changed there name recently. I currently reverted to the 4. Version they seem to work for my server.


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by WildBamaBoy** [comment]
Hmm..reopening this for further review.

**Comment by WildBamaBoy** [comment]
Would you happen to remember if when hovering over the rings in the interaction menu, did it still say "Married to you"?

**Comment by WildBamaBoy** [comment]
Should be fixed in b9f0bb072425aa0e30329822c038f64ea3df6a7d (MCA 5.0.6)
