### ISSUE TITLE
Villagers don't detect damage when hit by sword

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#348]
When i accidentally hit a guard by my sword, the guard didn't hit me back. even if i attack other villagers like Farmers, Librarians, etc. if i hit Villagers with my hand, they hit me back.

please fix this.

Version:

1.7.10

**Comment by Hernan0708** [comment]
Version:

MC: 1.7.10
MCA: 5.0.5_1
Radix-Core: 2.0.1

**Comment by WildBamaBoy** [comment]
This is not a bug.
