### ISSUE TITLE
Could have sworn there used to be a config option for removing the Crystal Ball. Where did it go?

### ISSUE THREAD

**Issue by dizzysoul** [WildBamaBoy/minecraft-comes-alive#349]
Maybe I'm wrong, but I think the previous version of MCA had a config option for enabling/disabling the Crystal ball on spawn. Ever since the _1 update, I can't find this config option anymore. Can we get it back?

And if I happen to be imaging things, then I apologize, and please consider this a feature request. I'd like to spawn the Crystal Ball dynamically through a quest line, and not at start, so I'd like to disable this feature.

**Comment by WildBamaBoy** [comment]
There was not a configuration option for this, but I'll add it. :)
