### ISSUE TITLE
Can you add a config option for damage.

### ISSUE THREAD

**Issue by Orange1861** [WildBamaBoy/minecraft-comes-alive#351]
Can you add a config option for damage for guards and regular villagers (separately) because I would like to increase their damage. Regular villagers should have 1-5 damage in the config and guards should have 3-11. Default should be the current damage.

**Comment by Orange1861** [comment]
If you want to merge these suggestions then maybe you call it "Add crystal ball and villager damage to config".

**Comment by WildBamaBoy** [comment]
That's not what pending merge means. :P

**Comment by Orange1861** [comment]
Oh, what does it mean then?

**Comment by DemonicIntent** [comment]
To my own knowledge as an advent reader on updates to the MCA Mod, I do believe "pending-merge" means that said feature is to be added in a future update, and that it has been created.
