### ISSUE TITLE
Rework babies and Children?

### ISSUE THREAD

**Issue by Orange1861** [WildBamaBoy/minecraft-comes-alive#352]
I think that babies and children should be reworked.  All babies do is sit in your inventory. Maybe you need to feed the baby or it will cry so you can't sleep. Your children can't  fully grow up and children not from your family already have jobs. Now this is fine but there children the size of toddlers that are guards. 

I hope you read this and this was not made criticize your work, this is a GREAT mod so this only a suggestion.

Orange1861

**Comment by WildBamaBoy** [comment]
Children do fully grow up, but their title remains "Child" to identify them as the child of a player. I will add a sort of aging system to notify players of the child's actual age, but as of right now no further expansion on babies is planned.
