### ISSUE TITLE
MCA Rough Idea Platform - Will Update As More Ideas Are Made

### ISSUE THREAD

**Issue by DemonicIntent** [WildBamaBoy/minecraft-comes-alive#356]
**Why not a Story Line? Oh and some Side Questing?..**
===========================================
A story line that fits Minecraft, but adds to the Mod's Main Idea, having a family.
The story would either follow a medieval like play through gaining honor.
Or the story would follow a political play through something more modern.

*The following will explain both a Medieval & Modern Story Line - At The End (Will feature Side Quests, for both themes)*

**Medieval**
========
Most medieval story lines are based on gaining as much honor and respect as possible, as well as a currency to fit it.
**Main Story Line:**
* - Quest One - * 
How To Start: Speak to NPC to start your life in VILLAGE.
How To Finish: Talk to said NPC.
Story Marker: You just finished talking to NPC and were asked to help out around the VILLAGE, look around and help out some of the VILLAGE members.

* - Side Quest (Part 1) - *

**Farmer:** "I've ran low on seeds, mind heading to the market to fetch me some?" +1 Respect/16 Seeds

**Blacksmith:** "I'll need more coal for my furnace, think you can bring me back a few?" +2 Respect/16 Coal

**Baker:** "Can you fetch me some wheat from the field?" +1 Respect/32 Wheat

**Leather-worker:** "I'm a bit low on leather, think you can get me some?" +2 Respect/8 Leather

**Guard:** "My sword seems a bit dull, could you get me one from the blacksmith?" +3 Respect/1 Iron Sword

**Librarian:** "If I am to finish this book, I'll need more paper, fetch me some will you?" +1 Respect/16 Paper

**Reach Total Respect:** 80
Once you have reached 80 RESPECT talk to the priest and turn the respect into HONOR - the HONOR will be used for things such as having personal guards, NPCs will work for you (farm an area, mine for you, cut wood for you), and finally enough HONOR can be used to become MONARCH.

**The system used is below:** *(The Tag Names Below Can Be Anything)*
20x RESPECT = 1x HONOR
20x HONOR = 1x PRESTIGE

**Types Of Villagers:**
*(There Isn't Enough of Them!)*
 - Farmer
 - Blacksmith
 - Baker
 - Guard 
 - Lumberjack
 - Leather-worker *(Sells Leather Crafted Gear)*
 - Librarian
 - Priest
 - Merchant *(Different Types of Merchants: 3-4 In Each Village)*
 - Craftsman *(Wood Objects: Doors, Signs, Stairs, Etc.)*
 - Artillator *(Sells Bows, and Arrows)*
 - Peddler *(Traveling Merchant)*
 - Knight
 - Grand Master *(Head of the Knights)*

**Each of the Above Villagers can be used to create extensive story lines and quests, giving rise to a monarchy system.** *Modern System Coming Soon* *Along with more detail for the medieval.*

**Comment by HillustratedMike36** [comment]
Can this story-line be optional...?

**Comment by n00b7** [comment]
maybe like a option in the config file?

**Comment by TheShootingStar45** [comment]
This is a very nice idea, implementing some storylines to enchancing gameplay and adds honor, respect, and prestige system to the game, that can be useful for in-game mechanics.

**Comment by gyser8** [comment]
Not a bad idea. Just one suggestion about it. What it's missing is the CURRENT monarch. If that monarch is assassinated by an assassin or you, the Grand Master becomes the new monarch, and the best knight becomes Grand Master. However, with 10 prestige, you can become monarch instead of the Grand Master. A ceremony will be planned in a few days for your crowning, and when that day hits, you got to be there, or else it'll go to the grand master. If you arrive there, the grand master (or priest) will give a speech, and at the end of it, everyone will say, "Long live the king!", and the grand master (or priest) will give you the helmet and clothes, making YOU the monarch. However, you could get assassinated, so stay sharp.

**Comment by DRULES679** [comment]
That's a pretty great freaking idea. I like it. A story mode!

**Comment by WildBamaBoy** [comment]
Moved somewhere secret...
