### ISSUE TITLE
Villager don't shelter from the rain anymore

### ISSUE THREAD

**Issue by sergio239** [WildBamaBoy/minecraft-comes-alive#357]
In previous versions of MCA, I remember that what it started raining, villagers ran to nearby buildings to shelter from the rain. Now, the just stay outside as if nothing happened. I think that was a cool feature that should be reimplemented :)

**Comment by HillustratedMike36** [comment]
I second the vote. I found it annoying just to toggle downfall just for the villager's interaction with the environment.
