### ISSUE TITLE
MCA server trouble

### ISSUE THREAD

**Issue by HarlequinDust** [WildBamaBoy/minecraft-comes-alive#358]
For some reason, MCA won't work on my server. One interesting thing is that I also have TMI installed and, in the menu, you can see MCA items. For example, all of the rings, babies, etc. However, when I try to cheat something in from MCA using TMI, I get this message: 'There is no such item with the ID MCA: {whatever item I click on}. Also, the villagers are still testificates and I was not spawned in with a crystal ball, asked my gender, ect.

I also have it installed on my client and it works perfectly. I don't understand why it's not working on my server. I also have the latest version of forge

**Comment by Orange1861** [comment]
Why did you close this?

**Comment by HarlequinDust** [comment]
I messed around with it for a bit and was finally able to fix it
