### ISSUE TITLE
Odd blinking animation for one of the guards.

### ISSUE THREAD

**Issue by HzAero** [WildBamaBoy/minecraft-comes-alive#359]
Found that one of the female guards was blinking funny. She only blinks halfway while other characters blink all the way (according to their eye shape). In the Villager Editor, she exhibits the same symptoms, but the other female guard models do not. It seems as though this one guard's set of eyes register as small eyes rather than large ones. Unfortunately, I'm not sure if there are more examples of this phenomenon.

![2015-05-27_11 40 35](https://cloud.githubusercontent.com/assets/8908585/7840447/5c6a2d8e-0465-11e5-9061-7bcb2fc198d1.png)

![2015-05-28_11 00 07](https://cloud.githubusercontent.com/assets/8908585/7863198/f238d22a-0528-11e5-903d-13cae0286ac6.png)

Edit: On an unrelated note, notice that the title "Village Editor" in the first picture is merging with some elements, but not in the second picture. It seems that if the resolution size of the window exceeds that of the GUI Scale, the title element will move out of place. For instance, setting the GUI Scale to "Small" with a rather large window could move the title element behind the character portrait.

**Comment by Orange1861** [comment]
Can you post a picture of her odd blinking.

**Comment by HzAero** [comment]
It was challenging, but I got the exact moment she blinks. I'll include the picture in the first post as well.

![2015-05-28_11 00 07](https://cloud.githubusercontent.com/assets/8908585/7863198/f238d22a-0528-11e5-903d-13cae0286ac6.png)

**Comment by Orange1861** [comment]
I saw that you spammed f2. LOL

**Comment by Hernan0708** [comment]
This doesnt happen for me.

how many mods are you using?

**Comment by HzAero** [comment]
I was using about 24 mods when I took the picture.

**Comment by Orange1861** [comment]
What are they?

**Comment by HzAero** [comment]
Automagy | Baubles | BiblioCraft | BloodMagic | Botania
CraftGuide | DenseOres | Ex Astris | Ex Nihilo | ExtraTiC
IguanaTinkerTweaks | Jabba | LookingGlass | Metallurgy | Minecraft Comes Alive
Mystcraft | Optifine Standard | Pam's HarvestCraft | Rougelike Dungeons | Storage Drawers
Tinker's Construct | Thaumcraft | Thaumic Horizons | TiC Tooltips | VeinMiner | Waila

Scratch that, 26 mods, excluding Forge and any core mods.

**Comment by WildBamaBoy** [comment]
Confirmed GuardF9's sleeping/blinking skin does not have its eyes closed.
