### ISSUE TITLE
Crystal Ball Problems

### ISSUE THREAD

**Issue by TheGreenPuma** [WildBamaBoy/minecraft-comes-alive#360]
When I used the crystal ball on my private server, I didn't go to the room with the enchantment table. It right away asked the questions. But it skipped the most important question: Choose your destiny. So I just answered a few questions for nothing. Why is this happening?

P.S: My singleplayer is <u>fine</u>.

**Comment by WildBamaBoy** [comment]
That's intended on servers to prevent griefing

**Comment by TheGreenPuma** [comment]
How do I turn this off?

**Comment by SvEgiiVEteR** [comment]
same problem ...
can add the option to include the server or not?
I like playing with my friends, and they do not griefing))
