### ISSUE TITLE
Mod still overwrites mod NPCs from other mod(s) when they spawn naturally

### ISSUE THREAD

**Issue by TheKodex** [WildBamaBoy/minecraft-comes-alive#362]
Ok, so you fixed that they don't overwrites these, and no they don't when I do the /summon command, hurray! But they do overwrite when they spawn naturally in the overworld. If you want to know in details, there's missing NPCs from the mod Nevermine 2: Advent of Ascension version 2.2 (NPC called LottoMan). I see villagers and guards of all kinds scattered all around the world, just like without this mod, the LottoMan is scattered. Coincidence? I think not.

**Comment by WildBamaBoy** [comment]
If overwriting is enabled and the "villager" from the other mod does not have a unique profession ID (anything other than 0 - 4), MCA will continue to overwrite that villager.

**Comment by TheKodex** [comment]
Then there's not much I can do. Thanks for your quick answear.
