### ISSUE TITLE
[Server thread/WARN]: Fetching addPacket for removed entity

### ISSUE THREAD

**Issue by TheKodex** [WildBamaBoy/minecraft-comes-alive#363]
Frequent warning message on server caused by this mod.

Tested with and without, to make sure if this mod was the cause of course. :)

**Comment by TheKodex** [comment]
To add: This happens when I'm logged in with client, and begin to move around.

**Comment by WildBamaBoy** [comment]
Forge version? Console log? This can usually be ignored, but I haven't seen this running MCA on a server.

**Comment by TheKodex** [comment]
The title states the console log message.
Server and Client is version 10.13.3.1355 (I know, not the recommended version)
But I can remember back in 1.7.2 aswell, that MCA did cause the same warning message on server, even though that's not relevant with 1.7.10 as is.

**Comment by WildBamaBoy** [comment]
I'd need to see a full console log to get context for the message, if there is any.

**Comment by TheKodex** [comment]
I'm afraid there's nothing else that would give a clue...

http://pastebin.com/tPaS1np5

This log is when I did a quick test today. There's lots of other logs from past days, but they pretty much writes the same, without any further informartion :/

**Comment by WildBamaBoy** [comment]
I can only theorize something odd going on with some of the other mods you are using and MCA, like a mod preventing a villager's spawning or something like that. I can't reproduce the problem on a server running only MCA.

**Comment by TheKodex** [comment]
Yes, you are right, there is another mod that makes this warning. It stopped happening when I turned the overwrite option to false. I think this has something to do with the other issue I posted earlier, when that mod tries to spawn NPC, and MCA wants to overwrite this NPC, with success, but it generates this fetch warning. I'm sorry that I didn't research this further before posting this issue.

**Comment by Orange1861** [comment]
What is this mod?

**Comment by WildBamaBoy** [comment]
@TheKodex No problem, the next update should prevent this from happening as a very kind user fixed an issue where mods' villagers were being overwritten by MCA. :)

**Comment by TheKodex** [comment]
@Orange1861 Nevermine 2: Advent of Ascension

@WildBamaBoy That's nice! :+1:
