### ISSUE TITLE
Odd villager Personality

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#368]
One villager in my village has an odd personality. it says "personality.none"

btw she is very nice :)

![2015-05-28_16 55 30](https://cloud.githubusercontent.com/assets/12505188/7873705/a9d8fa96-055a-11e5-80fb-b4791cf42b85.png)

**Comment by Hernan0708** [comment]
Minecraft 1.7.10
MCA v5.0.6
RadixCore v2.0.2

**Comment by WildBamaBoy** [comment]
Was this villager spawned naturally or spawned in with an egg?

**Comment by Hernan0708** [comment]
it was naturally

**Comment by Hernan0708** [comment]
(Full info)

Minecraft v1.7.10
MCA v5.0.6
Radix-Core 2.0.2

World Info:

Village Created By: Crystal Ball
Villager: Created Naturally By Crystal Ball
Gamemode: Survival

**Comment by Orange1861** [comment]
I have seen this bug by using spawn egg.

**Comment by WildBamaBoy** [comment]
I'm unable to see any means by which this can be reproduced. Closing for now.
