### ISSUE TITLE
Boy age GUI broken

### ISSUE THREAD

**Issue by Diamondcup67** [WildBamaBoy/minecraft-comes-alive#369]
My spouse has given birth to 1 girl and 3 boys, I'm not sure if it is broke for one of them as he has just grown up to a child. But two boys will not show how old they are. They still grow in height, but the age doesn't change at all. It remains at Age: 4. The girl, named Ashlie, her GUI is working. But for the boys, it wont work.
I also figured out they can't grow into adults, so they remain kids forever.

**Comment by UniqueAlien** [comment]
Ya that has been happening for me too.

**Comment by Diamondcup67** [comment]
I also figured out this also is happening to one of my newborn baby girl, so it might not be just boys

**Comment by xNightWolfx** [comment]
I have 2 boys and 2 girls,My first boy is the oldest one but It says that he's still 4 he's tall but 4,My Girls are fine both their ages and size are ok,But My other boy who is the youngest is still 4 but he should be older

**Comment by WildBamaBoy** [comment]
Fixed in a82d7d6f74d0d494c7faa0a011926266f256fd8b
