### ISSUE TITLE
I don't have manu before married

### ISSUE THREAD

**Issue by earth55535** [WildBamaBoy/minecraft-comes-alive#370]
like as, cookfood,combat 
i don't have it even me married.

**Comment by moinecraftperv** [comment]
The mod creator hasn't added those features back in yet

**Comment by earth55535** [comment]
oh thank you old vertion have it?

**Comment by moinecraftperv** [comment]
v4.1.5

**Comment by earth55535** [comment]
thank u i'm thing i should waiting for update.
