### ISSUE TITLE
Fighting villagers and crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [WildBamaBoy/minecraft-comes-alive#371]
Hello! So I have an issue. Is not a crash, well...is a mix of both. I was planting weed in my garden (psychedelicraft), when all of a sudden this zombie comes out of nowhere (I was doing it at night). The villagers that were living with me, came rushing and started attacking the zombie. However, one of them hit other villager, and that's when the pandemonium started. All the villagers started fighting each other; it seems that the Golems got confused too, because they also started fighting villagers. At the end (since I also installed Gravestone mod), all the garden was full of heads and tombstones. Only one villager was left. I know the feature of villagers fighting mobs is also shared with REVAMP mod. I don't know what is happening. By the way, after I close my world, this crash happened > http://pastebin.com/hJZbQyCR

**Comment by Hernan0708** [comment]
Hehe lol,

1. U planted weed?! xD

2. Villagers fighting hahah!

btw this doesnt happen for me. what mods are u using?

**Comment by WildBamaBoy** [comment]
Can't seem to reproduce a crash like this. Likely due to some of the other mods you're running.
