### ISSUE TITLE
some times when you set home they dont spawn there at night they go some were else.

### ISSUE THREAD

**Issue by UniqueAlien** [WildBamaBoy/minecraft-comes-alive#373]
they spawn in another house when you set there spawn in a certain house.

**Comment by moinecraftperv** [comment]
somewhere else as in somewhere nearby? outside the house? somewhere far away? Check that the villager is moving freely, not staying or following you when it was night time. Sometimes villagers phase through walls and either end up outside the house or suffocate to death ..

**Comment by WildBamaBoy** [comment]
For #341

**Comment by popcorn8784** [comment]
I have that problem too! when I set my kids spawn in my house, it worked fine, but when I set their spawn in a different house, they went to my houses spawn!
