### ISSUE TITLE
Furniture

### ISSUE THREAD

**Issue by Orange1861** [WildBamaBoy/minecraft-comes-alive#374]
Can you add furniture for the villagers to use? Or can you make villagers use furniture from other mods(like MrCrayfish's furniture mod).

**Comment by UniqueAlien** [comment]
That would be a good Idea pls make this happen.

**Comment by Hernan0708** [comment]
uh... he cant add that. its MrCrayfish's. if you want furniture, install the mod separately

**Comment by Hernan0708** [comment]
wait. oh you mean, villagers use Furniture. probably WildBamaBoy could do something. good idea

**Comment by Orange1861** [comment]
Yes, that's what I meant. (The second comment)

**Comment by HillustratedMike36** [comment]
Villagers using furniture from MyCrayfish...? Genius. Gives a good reason to start putting that in a pre-made village and seeing the villagers actually use it.

**Comment by WildBamaBoy** [comment]
Suggestion noted. :)
