### ISSUE TITLE
A Guard Without a Sword

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#375]
I found a guard without a  sword. i attacked it and it hit me with its hand.

![2015-06-03_07 55 16](https://cloud.githubusercontent.com/assets/12505188/7963176/2e97722a-09c6-11e5-872e-ab208e36d32f.png)

![2015-06-03_07 55 14](https://cloud.githubusercontent.com/assets/12505188/7963186/37f57812-09c6-11e5-9a85-94ff240ca6c4.png)

**Comment by UniqueAlien** [comment]
They lose there sword when married apparently they can't be a guard and married.

**Comment by Hernan0708** [comment]
oh.

**Comment by Hernan0708** [comment]
k nvm (closed)
