### ISSUE TITLE
(Add) Villager Outfits/Villager Change Clothes

### ISSUE THREAD

**Issue by RottenBananaMC** [WildBamaBoy/minecraft-comes-alive#376]
1.It would be cool if villagers could change outfits during the morning, day, and night.

2. if children grow into an adult, they could have different clothing but with the same face and body texture.

2. Villagers could have swimwear when going into water.

MCA really needs this. :)

**Comment by RottenBananaMC** [comment]
hehe, sorry for (2) 1.

(I hate my autocorrect xD)

**Comment by Hernan0708** [comment]
I like this idea!!!

**Comment by HillustratedMike36** [comment]
Like what OreSpawn does for the Girlfriend and Boyfriend mobs...? I am interested.

**Comment by WildBamaBoy** [comment]
Closing this as I'm not certain it's feasible, but good idea nonetheless. We will keep it in mind.
