### ISSUE TITLE
Changed Username and Wife is Married to Old Username

### ISSUE THREAD

**Issue by notreallybritish** [WildBamaBoy/minecraft-comes-alive#378]
I recently changed my Minecraft username. When I went on my MCA world, it said that my wife was married to my old username, and that my children were fathered by my old username. Is there any way to get my family back?

**Comment by Hernan0708** [comment]
What version?

on MCA v5.0.0 Villagers recognize players by their UUID not their Username. if you are playing in v4.x immediately upgrade to v5.0.0 or Higher (v5.0.0-v5.x )

**Comment by notreallybritish** [comment]
I'm pretty sure it's v5.0.0. I'll update it to the latest version and see if it makes a difference.

**Comment by notreallybritish** [comment]
I updated to 5.0.6 and the problem persists.

**Comment by WildBamaBoy** [comment]
MCA does not support name changes.

**Comment by Hernan0708** [comment]
oh. it thought you put it in the changelog in 5.0.0
