### ISSUE TITLE
Villagers trading

### ISSUE THREAD

**Issue by AlphonseVaher** [WildBamaBoy/minecraft-comes-alive#379]
When I trade with a villager they do not open up any new options when you complete a trade with them. 

Useing version 5.0.6.

**Comment by moinecraftperv** [comment]
You need to complete the latest trade more (usually 1-5 times) before you can unlock next trade

**Comment by WildBamaBoy** [comment]
Unable to reproduce this.

**Comment by Orange1861** [comment]
Yup. I don't have this bug.

**Comment by rmonk** [comment]
I am using version 5.1.1.0 and I also am unable to get more trades after they "lock out" their first trade.  Do you have to gift/talk/etc with the villagers up to a particular heart level for them to unlock a new trade?
