### ISSUE TITLE
Weirdly spawned "Twin" Villagers

### ISSUE THREAD

**Issue by moinecraftperv** [WildBamaBoy/minecraft-comes-alive#382]
![2015-06-07_16 50 12](https://cloud.githubusercontent.com/assets/11499922/8029714/b68cd528-0df2-11e5-8955-74e02b8a77f8.png)
Villagers spawned in naturally generated village. They have the same name, skin,profession, traits but different trades , 
MCA v5.0.6
Radixcore 2.0.2

**Comment by WildBamaBoy** [comment]
It's likely one of the other mods you are using improperly spawning villagers.
