### ISSUE TITLE
Marriage to another player in LAN bug.

### ISSUE THREAD

**Issue by Syngence** [WildBamaBoy/minecraft-comes-alive#383]
I don't know if this is really already a known bug/issue but whenever i reconnect to the LAN server my wife made and I go to her avatar to right click and i notice that our kids "father and mother" is  just her LOL!...So I dont know if it got messed cause I DC and reconnect cause this happens even when we already have a baby and then i Disconnect and reconnect with the  same issue. Anyway to fix this?

**Comment by WildBamaBoy** [comment]
Known along with other LAN issues. Unfortunately there is no fix at this time.
