### ISSUE TITLE
Creating Villages in 1.8 beta

### ISSUE THREAD

**Issue by acerus23** [WildBamaBoy/minecraft-comes-alive#384]
When creating a village in the 1.8 version, it crashes the game and upon reloading, a village has been created with no roofs or villagers. I've done this twice now to the same result.

**Comment by WildBamaBoy** [comment]
Crash report?

**Comment by acerus23** [comment]
Time: 6/9/15 11:48 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:270)
at
net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715)
at
net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
at
net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 216211872 bytes (206 MB) / 613511168 bytes (585 MB) up to
1060372480 bytes (1011 MB)
JVM Flags: 6 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode
-XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
FML: MCP v9.10 FML v8.0.25.1296 Minecraft Forge 11.14.0.1296 5 mods loaded,
5 mods active
mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
FML{8.0.25.1296} [Forge Mod Loader] (forge-1.8-11.14.0.1296.jar)
Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Forge{11.14.0.1296} [Minecraft Forge] (forge-1.8-11.14.0.1296.jar)
Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.8-universal.jar)
Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6b-1.8-universal.jar)
Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['Acerus23'/210, l='New World',
x=-134.89, y=79.00, z=432.25]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Orange1861** [comment]
I think this is now fixed.

**Comment by acerus23** [comment]
it still does it for me. I downloaded it again from the radix core website
to see if they updated that download, but it does the same thing.

**Comment by WildBamaBoy** [comment]
Use MCA 5.0.6-1.8 and RadixCore 2.0.2.1. Issue is resolved.
