### ISSUE TITLE
textures erroring

### ISSUE THREAD

**Issue by BoomerMax** [WildBamaBoy/minecraft-comes-alive#386]
on my PC ceertain jobs have no textures

**Comment by WildBamaBoy** [comment]
Minecraft version, which jobs have the problem, MCA version...

**Comment by BoomerMax** [comment]
1.7.10 child mca 5.0.6, oh! and by the way, please keep mca 5.1 for 1.7.10! i dont like 4.1.5 but i just love the monarch system and lost relative document for my modpack along with crystal ball from 5.0! can you do 5.1 for 1.7.10?

**Comment by BoomerMax** [comment]
1.7.10 child mca 5.0.6, oh! and by the way, please keep mca 5.1 for 1.7.10!
i dont like 4.1.5 but i just love the monarch system and lost relative
document for my modpack along with crystal ball from 5.0! can you do 5.1
for 1.7.10?

**Comment by BoomerMax** [comment]
oh and is there any way to keep ttestificates in 4.1.5?

**Comment by WildBamaBoy** [comment]
MCA 5.1 will be for 1.7.10 and 1.8. I cannot reproduce the issues you are experiencing. Assuming they are no longer relevant.
