### ISSUE TITLE
Bug- Holding a baby

### ISSUE THREAD

**Issue by rangersjosh** [WildBamaBoy/minecraft-comes-alive#388]
Holding a baby is bugged, it moves up and down really fast and you can actually hardly see it. It's not game crashing its just annoying.

**Comment by PortedOasis** [comment]
I've had this as-well.

**Comment by justineschluter** [comment]
This and a few other things have been happening with my game

**Comment by TheShootingStar45** [comment]
Yes, it's a bit weird

**Comment by CatLady808** [comment]
I have the same problem, and also, when I click "pick up" on the villager options, then I suffocate the baby. Is this a BUG???
