### ISSUE TITLE
1.8 beta report

### ISSUE THREAD

**Issue by XxL3G1TS4VAG3xX** [WildBamaBoy/minecraft-comes-alive#391]
1) Many Villagers Tend to become invisible and all you see is the shadow of them.
2) I have got of minecraft then got back on when I went to interact with my character's wife it said she wasn't married to my character.

If I've put this in the wrong area I am sorry. I am new to Github and your new website.

**Comment by moinecraftperv** [comment]
1. Are you using shaders?
2. Did you accidentally play in offline mode or recently change your username?

**Comment by XxL3G1TS4VAG3xX** [comment]
No I am not using shaders.

I'm not playing in offline mode and I haven't changed my name. 

Also I have another issue I have the latest version of MCA and it says there is a new version available

**Comment by WildBamaBoy** [comment]
Use the now latest version, everything should be fixed.
