### ISSUE TITLE
"You Already Have A Baby" Bug/Glitch

### ISSUE THREAD

**Issue by PhantomAzn** [WildBamaBoy/minecraft-comes-alive#392]
So I was playing on my singleplayer world with my Kovacic's Modpack installed and had been playing normally. I had messed around with the "Minecraft Comes Alive" mod until I got to the point where when I had clicked the "Procreate" option on my spouse it wouldn't accept and instead gave me a "You Already Have A Baby" notification even when I had none in my inventory or anywhere else, it wasn't in my spouse's inventory, and I had already placed down all babys and turned them into children. My guess for this problem is that I had spawned in a baby boy in creative and had deleted it right after as it was a mistake. I was hoping someone could tell me how to fix this issue and/or if it is resetable or not. 
Thank You!

**Comment by WildBamaBoy** [comment]
MCA version?

**Comment by PhantomAzn** [comment]
I believe the version is 1.8.7 (The Latest One) although I can't be so sure since it doesn't specify. It only says 2.1.2 if that helps at all.

**Comment by PhantomAzn** [comment]
What I meant to say is that the mod is version 1.8 -_- sorry I had misunderstood.

**Comment by PhantomAzn** [comment]
I have found a solution to my problem, I'm sorry for wasting your time. Thank you for actually reading this post though, I appreciate it. Have a Nice Day!
