### ISSUE TITLE
Doors Not generating right sometimes

### ISSUE THREAD

**Issue by n00b7** [WildBamaBoy/minecraft-comes-alive#395]
forge 1.8-forge11.14.1.1412
radix core 2.0.2.1-18
MCA 5.0.6-1.8
windows

this is what a door looked like when i selected the "i have a family option"
edit:it only happens when mca generates the door on the house
![2015-06-14_11 25 07](https://cloud.githubusercontent.com/assets/11874683/8149192/e0f8bdbe-1288-11e5-9fc6-bbe8d45a9539.png)

**Comment by WildBamaBoy** [comment]
MCA for 1.8 has been updated, give that a try and if the issue occurs come back.
