### ISSUE TITLE
Game crashes after using Crystal Ball

### ISSUE THREAD

**Issue by rlym8** [WildBamaBoy/minecraft-comes-alive#398]
Minecraft 1.8. When I load up the world with other mods in it, game crashes after using crystal ball. I tried it without other mods - it worked. Can someone help me figure out what mod is causing it. Don't know if this is considered a bug...

Here's the crash report :

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  VeinMinerCorePlugin (VeinMiner-1.8_0.27.0.unknown.jar)
  DLFMLCorePlugin (DynamicLights-1.8.jar)
  TMIForgeLoader (TooManyItems2015_02_14_1.8_Forge.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 15.6.15 18.23
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.world.World.func_175701_a(World.java:216)
	at net.minecraft.world.World.func_180495_p(World.java:831)
	at noppes.npcs.ServerEventsHandler.invoke(ServerEventsHandler.java:160)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_ServerEventsHandler_invoke_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:120)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2041)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.World.func_175701_a(World.java:216)
	at net.minecraft.world.World.func_180495_p(World.java:831)
	at noppes.npcs.ServerEventsHandler.invoke(ServerEventsHandler.java:160)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_ServerEventsHandler_invoke_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:120)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Augustas'/403, l='MpServer', x=-186,12, y=75,76, z=265,48]]
	Chunk stats: MultiplayerChunkCache: 223, 223
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -208,00,64,00,256,00 - World: (-208,64,256), Chunk: (at 0,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2142 game time, 2142 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 92 total; [EntitySkeleton['Skeleton'/257, l='MpServer', x=-177,59, y=20,00, z=229,03], EntityRabbit['Rabbit'/258, l='MpServer', x=-176,63, y=65,00, z=244,03], EntitySkeleton['Skeleton'/259, l='MpServer', x=-176,50, y=21,00, z=269,50], EntityBat['Bat'/260, l='MpServer', x=-187,25, y=37,10, z=257,75], EntityRabbit['Rabbit'/261, l='MpServer', x=-180,16, y=67,00, z=246,28], EntityRabbit['Rabbit'/262, l='MpServer', x=-178,19, y=69,00, z=309,50], EntityRabbit['Rabbit'/263, l='MpServer', x=-179,97, y=69,00, z=305,03], EntityBat['Bat'/282, l='MpServer', x=-167,25, y=28,00, z=187,34], EntitySkeleton['Skeleton'/283, l='MpServer', x=-164,50, y=47,00, z=204,84], EntitySpider['Spider'/284, l='MpServer', x=-173,31, y=45,00, z=211,47], EntityCreeper['Creeper'/285, l='MpServer', x=-165,50, y=46,00, z=213,50], EntitySkeleton['Skeleton'/286, l='MpServer', x=-169,88, y=45,00, z=212,31], EntityEnderman['Enderman'/287, l='MpServer', x=-171,50, y=21,00, z=226,22], EntityRabbit['Rabbit'/288, l='MpServer', x=-168,84, y=65,00, z=247,13], EntityRabbit['Rabbit'/289, l='MpServer', x=-165,31, y=69,00, z=278,22], EntityRabbit['Rabbit'/290, l='MpServer', x=-164,78, y=70,00, z=279,78], EntityRabbit['Rabbit'/291, l='MpServer', x=-169,75, y=68,00, z=278,50], EntityRabbit['Rabbit'/292, l='MpServer', x=-161,53, y=71,00, z=279,03], EntityRabbit['Rabbit'/293, l='MpServer', x=-172,66, y=68,00, z=301,34], EntityCreeper['Creeper'/294, l='MpServer', x=-173,06, y=17,00, z=340,38], EntityRabbit['Rabbit'/295, l='MpServer', x=-170,75, y=67,00, z=341,00], EntitySkeleton['Skeleton'/309, l='MpServer', x=-144,50, y=26,00, z=199,50], EntityZombie['Zombie'/310, l='MpServer', x=-148,50, y=25,00, z=192,91], EntityBat['Bat'/311, l='MpServer', x=-144,53, y=26,09, z=197,75], EntityZombie['Zombie'/312, l='MpServer', x=-159,56, y=47,00, z=194,13], EntityRabbit['Rabbit'/313, l='MpServer', x=-150,31, y=72,00, z=271,69], EntityRabbit['Rabbit'/314, l='MpServer', x=-146,50, y=74,00, z=277,50], EntityRabbit['Rabbit'/315, l='MpServer', x=-154,06, y=75,20, z=291,22], EntityRabbit['Rabbit'/316, l='MpServer', x=-146,66, y=73,00, z=288,34], EntityRabbit['Rabbit'/317, l='MpServer', x=-157,03, y=68,00, z=296,03], EntityRabbit['Rabbit'/318, l='MpServer', x=-158,78, y=66,00, z=319,38], EntityRabbit['Rabbit'/319, l='MpServer', x=-149,50, y=66,00, z=323,50], EntityRabbit['Rabbit'/320, l='MpServer', x=-148,66, y=67,00, z=325,34], EntityRabbit['Rabbit'/321, l='MpServer', x=-159,38, y=67,00, z=344,38], EntityRabbit['Rabbit'/322, l='MpServer', x=-154,66, y=66,00, z=339,34], EntityBat['Bat'/329, l='MpServer', x=-133,81, y=27,00, z=196,22], EntityBat['Bat'/330, l='MpServer', x=-129,88, y=31,11, z=199,75], EntityCreeper['Creeper'/331, l='MpServer', x=-139,50, y=16,00, z=214,50], EntityCreeper['Creeper'/332, l='MpServer', x=-137,50, y=22,00, z=296,50], EntityZombie['Zombie'/333, l='MpServer', x=-142,50, y=49,00, z=291,50], EntityZombie['Zombie'/334, l='MpServer', x=-141,06, y=49,00, z=294,66], EntityZombie['Zombie'/335, l='MpServer', x=-142,50, y=49,00, z=292,50], EntityCreeper['Creeper'/338, l='MpServer', x=-116,59, y=53,00, z=279,97], EntityCreeper['Creeper'/339, l='MpServer', x=-118,72, y=54,00, z=271,91], EntityCow['Cow'/341, l='MpServer', x=-110,19, y=74,00, z=304,16], EntityPlayerSP['Augustas'/403, l='MpServer', x=-186,12, y=75,76, z=265,48], EntityZombie['Zombie'/150, l='MpServer', x=-258,44, y=40,00, z=205,97], EntityRabbit['Rabbit'/152, l='MpServer', x=-260,41, y=69,20, z=204,56], EntityRabbit['Rabbit'/153, l='MpServer', x=-264,50, y=67,00, z=201,97], EntitySkeleton['Skeleton'/155, l='MpServer', x=-264,19, y=41,00, z=208,59], EntityCreeper['Creeper'/159, l='MpServer', x=-257,97, y=40,00, z=229,75], EntityRabbit['Rabbit'/160, l='MpServer', x=-266,41, y=68,00, z=224,47], EntityBat['Bat'/161, l='MpServer', x=-241,28, y=18,25, z=300,78], EntityCreeper['Creeper'/168, l='MpServer', x=-251,50, y=15,00, z=187,50], EntityCreeper['Creeper'/169, l='MpServer', x=-240,50, y=20,00, z=202,50], EntitySkeleton['Skeleton'/170, l='MpServer', x=-255,19, y=53,03, z=193,69], EntityCreeper['Creeper'/171, l='MpServer', x=-246,06, y=22,00, z=209,50], EntityCreeper['Creeper'/172, l='MpServer', x=-245,47, y=19,00, z=211,56], EntitySkeleton['Skeleton'/173, l='MpServer', x=-255,50, y=39,00, z=210,81], EntityCow['Cow'/174, l='MpServer', x=-248,56, y=65,00, z=333,38], EntityBat['Bat'/175, l='MpServer', x=-250,69, y=25,84, z=345,66], EntityCow['Cow'/177, l='MpServer', x=-242,56, y=66,00, z=338,16], EntitySkeleton['Skeleton'/196, l='MpServer', x=-231,41, y=17,00, z=222,94], EntitySkeleton['Skeleton'/197, l='MpServer', x=-227,22, y=14,00, z=213,78], EntityCreeper['Creeper'/198, l='MpServer', x=-235,50, y=18,00, z=218,50], EntityBat['Bat'/199, l='MpServer', x=-229,91, y=19,10, z=214,25], EntityCreeper['Creeper'/200, l='MpServer', x=-233,84, y=18,00, z=212,78], EntityCow['Cow'/201, l='MpServer', x=-229,06, y=66,00, z=334,00], EntityBat['Bat'/202, l='MpServer', x=-223,31, y=48,02, z=345,41], EntityCow['Cow'/203, l='MpServer', x=-237,56, y=67,00, z=343,78], EntitySkeleton['Skeleton'/722, l='MpServer', x=-211,50, y=24,00, z=189,50], EntitySkeleton['Skeleton'/723, l='MpServer', x=-207,50, y=24,00, z=189,50], EntityBat['Bat'/219, l='MpServer', x=-204,88, y=24,47, z=192,41], EntitySkeleton['Skeleton'/220, l='MpServer', x=-216,84, y=10,31, z=220,69], EntitySpider['Spider'/221, l='MpServer', x=-212,81, y=15,78, z=219,03], EntityBat['Bat'/222, l='MpServer', x=-208,31, y=13,10, z=235,69], EntityZombie['Zombie'/223, l='MpServer', x=-226,84, y=12,41, z=223,38], EntitySkeleton['Skeleton'/224, l='MpServer', x=-209,50, y=16,00, z=228,50], EntitySkeleton['Skeleton'/225, l='MpServer', x=-208,50, y=16,00, z=228,50], EntityZombie['Zombie'/226, l='MpServer', x=-216,34, y=49,00, z=226,41], EntityCreeper['Creeper'/227, l='MpServer', x=-221,72, y=31,00, z=254,63], EntitySheep['Sheep'/228, l='MpServer', x=-216,44, y=70,00, z=289,31], EntityBat['Bat'/243, l='MpServer', x=-205,41, y=25,03, z=190,81], EntityZombie['Zombie'/244, l='MpServer', x=-207,56, y=39,00, z=208,94], EntityZombie['Zombie'/245, l='MpServer', x=-207,50, y=37,00, z=213,50], EntitySkeleton['Skeleton'/246, l='MpServer', x=-201,50, y=14,00, z=226,50], EntitySkeleton['Skeleton'/247, l='MpServer', x=-203,94, y=13,00, z=237,44], EntitySkeleton['Skeleton'/248, l='MpServer', x=-207,00, y=41,00, z=225,56], EntitySpider['Spider'/249, l='MpServer', x=-206,50, y=12,00, z=241,50], EntitySheep['Sheep'/250, l='MpServer', x=-194,34, y=68,00, z=296,44], EntitySheep['Sheep'/251, l='MpServer', x=-195,22, y=68,00, z=304,41], EntitySheep['Sheep'/252, l='MpServer', x=-198,56, y=66,00, z=294,16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 185435496 bytes (176 MB) / 504397824 bytes (481 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	Forge{11.14.3.1450} [Minecraft Forge] (forge-1.8-11.14.3.1450.jar) 
	UCHIJAAAA	TooManyItems{1.8} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	VeinMiner_coremod{0.26.1_build.unknown} [Core mod] (minecraft.jar) 
	UCHIJAAAA	securitycraft{v1.7.4.1} [SecurityCraft] ([1.8] SecurityCraft v1.7.4.1.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.3.3} [Damage Indicators] ([1.8]DamageIndicatorsMod-3.3.3.jar) 
	UCHIJAAAA	XaeroBetterPvP{1.5} [Better PVP Mod] (BetterPvP_1.5.0_1.8_Forge.jar) 
	UCHIJAAAA	braziermod{1.0} [Brazier Mod] (Brazier-Mod-1.8.jar) 
	UCHIJAAAA	chiselsandbits{1.0} [Chisels & Bits] (chiselsandbits-1.1.jar) 
	UCHIJAAAA	customnpcs{1.8.0_beta} [CustomNpcs] (CustomNPCs_1.8.0_beta.jar) 
	UCHIJAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.jar) 
	UCHIJAAAA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	UCHIJAAAA	RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.8-universal.jar) 
	UCHIJAAAA	MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6b-1.8-universal.jar) 
	UCHIJAAAA	moreplayermodels{1.8.0_beta} [MorePlayerModels] (MorePlayerModels_1.8.0_beta.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7-build5(1.8).jar) 
	UCHIJAAAA	redstonepaste{1.7.1} [Redstone Paste] (redstonepaste-mc1.8-1.7.1.jar) 
	UCHIJAAAA	SlimevoidLib{3.0.0.4-beta-1.8} [Slimevoid Library] (SlimevoidLibrary-3.0.0.4-beta-1.8.jar) 
	UCHIJAAAA	smoothbedrock{2.2.0.8} [SmoothBedrock] (SmoothBedrock-1.8-2.2.0.8.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.8} [Sound Filters] (SoundFilters-0.8_for_1.8.jar) 
	UCHIJAAAA	VeinMiner{0.26.1_build.unknown} [Vein Miner] (VeinMiner-1.8_0.27.0.unknown.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.26.1_build.unknown} [Mod Support] (VeinMiner-1.8_0.27.0.unknown.jar) 
	UCHIJAAAA	chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)] (VillageInfoSSP-1.8-2.1.jar) 
	UCHIJAAAA	WirelessRedstone{2.0.0.1-alpha-1.8} [Wireless Redstone] (WirelessRedstoneCore-2.0.0.1-alpha-1.8.jar) 
	UCHIJAAAA	craft++{2.3.1} [Craft++] (craft.-2.3.1.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
NowWithRendering (redstonepaste-mc1.8-1.7.1.jar)
  net.fybertech.nwr.NowWithRendering
VeinMinerCorePlugin (VeinMiner-1.8_0.27.0.unknown.jar)
  portablejim.veinminer.asm.ItemInWorldManagerTransformer
DLFMLCorePlugin (DynamicLights-1.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
TMIForgeLoader (TooManyItems2015_02_14_1.8_Forge.jar)
  TMIForgeTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3621' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.8-Forge11.14.3.1450
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3621, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Just For Steve 1.8.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by WildBamaBoy** [comment]
CustomNPCs is the problem. This area is only for issues with MCA. I'd advise posting on the forum page for CustomNPCs.

**Comment by rlym8** [comment]
I see. Thank you.

**Comment by Orange1861** [comment]
CustomNPCs does not really work with anything.
