### ISSUE TITLE
Rose Gold Missing Texture in 1.8

### ISSUE THREAD

**Issue by MtnDrew** [WildBamaBoy/minecraft-comes-alive#402]
When it spawns naturally or is placed in the world it shows as the missing texture pink and black grid. 

I'm thinking that this has to be a compatibility issue most likely because this would have been noticed immediately, but I've been reading through the issue tracker and haven't seen anything mentioned. 

My apologies if I've missed something before posting this.

Forge 11.14.3.1450
RC 2.0.3-1.8
MCA 5.0.6.1-1.8

**Comment by Hernan0708** [comment]
Are you using a texture pack

**Comment by MtnDrew** [comment]
No I am not.

**Comment by WildBamaBoy** [comment]
Are you using Optifine?

**Comment by TwoFrsh4U** [comment]
I'm having the same problem as MtnDrew.  The only other mod I have is nei.  And I'm not using any texture pack.

**Comment by justineschluter** [comment]
i have the same problem i have one other mod and a texture pack but neither are affecting it. This is also happening to the tombstone animation and the whislte. Another thing thats happening is that when my babies grow up the child skins dont go thru and i have to change it. the texture thing is also happening with the villager book to change their skin. I also dont have the diamond dust and my villagers arent automatically getting married and having babies. As you can see my game has a lot of problems. If you can help i would love that.

**Comment by WildBamaBoy** [comment]
#436
