### ISSUE TITLE
Spouse is gone, but other npc's think I'm still married...

### ISSUE THREAD

**Issue by TheQuadShot** [WildBamaBoy/minecraft-comes-alive#405]
I used a golden lasso to take my wife into my Tardis, I think she tried to walk out of the door. She isn't in the tardis anymore and she's not in the overworld. I didn't see a death message and I have tried the whistle in both places and she doesn't respond. If I try to get engaged to another npc she tells me I'm already married. Is there a way to clear this? I couldn't see anything in the configs. Also divorce papers do nothing (I think I have to give them to her).

**Comment by WildBamaBoy** [comment]
Use a priest to reset your marriage.

**Comment by TheQuadShot** [comment]
just an fyi, I couldn't get the priest to do anything, (He was one of the first 3 guy's I made) However I just went back into my tardis and got the death msg for my spouse, she died from "notInWorld"

**Comment by TheQuadShot** [comment]
oops, I'm a derp... the priest I went to was a AW priest, sorry.
