### ISSUE TITLE
Spouse Does Not Drop Ring or Items From Inventory When Killed

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#406]
(NOTE: This Was One Of My Tests ''Test 003'') I Killed My Spouse To See What Happend, Then She Didn't Drop Her Belongings in Her Inventory.

![2015-06-17_13 10 09](https://cloud.githubusercontent.com/assets/12505188/8217565/14351602-14f3-11e5-925d-89c374718034.png)
![2015-06-17_13 11 40](https://cloud.githubusercontent.com/assets/12505188/8217582/2ca14986-14f3-11e5-9638-ab59076c4306.png)
 

Minecraft v1.7.10
Forge 10.13.2.1291
MCA v5.0.6
RadixCore v2.0.2
Windows

Btw This Villager Was Spawned By Egg and I Married Her. Also i am in Creative Mode!

I Really Enjoy This Mod ;)
-Hernan0708

**Comment by ProtoMJC** [comment]
I have this problem. Unfortunately, my wife was holding our infant, and now I can't even have children with my new wife. So they technically keep their inventory somewhere, just not anyway you can easily access it.
