### ISSUE TITLE
(Add) Crystal Ball Warp Effect Config

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#407]
Please Add a config option for nether warp effect (on/off)

The Main Reason It Needs a Config Because it causes too much lag when generating a structure or using the Crystal Ball.

![2015-06-17_13 26 44](https://cloud.githubusercontent.com/assets/12505188/8217930/f3db15a8-14f4-11e5-985d-23370de0cd66.png)

![2015-06-17_13 27 12](https://cloud.githubusercontent.com/assets/12505188/8217946/00a37050-14f5-11e5-8f1e-98393b8bc01e.png)

![2015-06-17_13 27 10](https://cloud.githubusercontent.com/assets/12505188/8217959/10bad8a2-14f5-11e5-83a9-e0412b68189f.png)

**Comment by WildBamaBoy** [comment]
Your lag is from the actual generation of the structure, not the portal graphic.

**Comment by Hernan0708** [comment]
oh
