### ISSUE TITLE
Missing texture and crashing D:

### ISSUE THREAD

**Issue by XxDARKWOLF67Xx** [WildBamaBoy/minecraft-comes-alive#409]
After i installed MCA for mine craft 1.8 rose gold ore and block, Villager editor, Tombstone and the whistle have missing textures. The rose gold is textured in the menus but not when placed. The villager editer will occasionally crash the game when opened.

**Comment by Hernan0708** [comment]
i think you should post your crash log for proof.

**Comment by XxDARKWOLF67Xx** [comment]
Ok. I checked if my texture pack was cousing the missing textures but its not.

**Comment by XxDARKWOLF67Xx** [comment]
Causing*

**Comment by XxDARKWOLF67Xx** [comment]
Villager Editor Crash Log: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/16/15 3:05 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at mca.client.gui.GuiVillagerEditor.func_73863_a(GuiVillagerEditor.java:408)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1078)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.client.gui.GuiVillagerEditor.func_73863_a(GuiVillagerEditor.java:408)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)

-- Screen render details --
Details:
	Screen name: mca.client.gui.GuiVillagerEditor
	Mouse location: Scaled: (341, 78). Absolute: (960, 540)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['XxDARKWOLF67Xx'/236, l='MpServer', x=-260.80, y=70.00, z=-269.49]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -248.00,64.00,-184.00 - World: (-248,64,-184), Chunk: (at 8,4,8 in -16,-12; contains blocks -256,0,-192 to -241,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 120244 game time, 53293 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 104 total; [EntityBat['Bat'/201221, l='MpServer', x=-260.56, y=14.91, z=-302.09], EntityBat['Bat'/203013, l='MpServer', x=-186.63, y=17.28, z=-239.88], EntityCreeper['Creeper'/203524, l='MpServer', x=-236.50, y=34.02, z=-333.50], EntityCreeper['Creeper'/202250, l='MpServer', x=-283.31, y=28.00, z=-331.72], EntitySpider['Spider'/202248, l='MpServer', x=-282.72, y=30.09, z=-330.31], EntityZombie['Zombie'/203276, l='MpServer', x=-185.50, y=24.00, z=-208.50], EntityZombie['Zombie'/200227, l='MpServer', x=-224.66, y=38.00, z=-307.66], EntityZombie['Zombie'/200483, l='MpServer', x=-290.50, y=18.00, z=-265.50], EntityZombie['Zombie'/200482, l='MpServer', x=-288.50, y=18.00, z=-265.50], EntityBat['Bat'/198436, l='MpServer', x=-338.46, y=42.03, z=-237.33], EntityZombie['Zombie'/200490, l='MpServer', x=-305.50, y=56.00, z=-210.50], EntitySkeleton['Skeleton'/202029, l='MpServer', x=-296.50, y=14.00, z=-284.50], EntityZombie['Zombie'/203317, l='MpServer', x=-284.50, y=26.02, z=-202.50], EntityZombie['Zombie'/203316, l='MpServer', x=-285.50, y=26.02, z=-203.50], EntitySkeleton['Skeleton'/202813, l='MpServer', x=-292.50, y=15.00, z=-279.50], EntitySkeleton['Skeleton'/202812, l='MpServer', x=-294.50, y=15.00, z=-281.50], EntityItem['item.item.arrow'/177474, l='MpServer', x=-211.56, y=67.00, z=-211.53], EntityCow['Cow'/69, l='MpServer', x=-332.03, y=65.00, z=-298.03], EntityCow['Cow'/70, l='MpServer', x=-342.63, y=69.00, z=-302.66], EntityItem['item.item.bone'/177743, l='MpServer', x=-241.88, y=69.00, z=-274.31], EntitySkeleton['Skeleton'/200526, l='MpServer', x=-296.94, y=30.02, z=-345.50], EntitySkeleton['Skeleton'/200525, l='MpServer', x=-301.50, y=28.00, z=-341.50], EntityItem['item.item.arrow'/177741, l='MpServer', x=-241.13, y=69.00, z=-274.28], EntityCreeper['Creeper'/200531, l='MpServer', x=-276.50, y=18.00, z=-261.50], EntityEnderman['Enderman'/200529, l='MpServer', x=-304.50, y=28.00, z=-341.50], EntityPlayerSP['XxDARKWOLF67Xx'/236, l='MpServer', x=-260.80, y=70.00, z=-269.49], EntitySpider['Spider'/202075, l='MpServer', x=-240.31, y=34.00, z=-334.63], EntitySkeleton['Skeleton'/202079, l='MpServer', x=-237.50, y=34.00, z=-335.50], EntitySquid['Squid'/202591, l='MpServer', x=-267.50, y=60.09, z=-309.50], EntitySpider['Spider'/202078, l='MpServer', x=-244.69, y=35.09, z=-333.91], EntitySkeleton['Skeleton'/202080, l='MpServer', x=-238.22, y=34.00, z=-333.59], EntitySquid['Squid'/202592, l='MpServer', x=-272.53, y=61.63, z=-314.41], EntitySkeleton['Skeleton'/201568, l='MpServer', x=-233.50, y=34.00, z=-351.50], EntityCow['Cow'/103, l='MpServer', x=-296.59, y=67.00, z=-300.25], EntityCow['Cow'/104, l='MpServer', x=-294.97, y=67.00, z=-300.03], EntityCow['Cow'/106, l='MpServer', x=-299.84, y=69.00, z=-268.81], EntityHuman['Zoe'/107, l='MpServer', x=-277.53, y=70.47, z=-257.94], EntityHuman['Soren'/108, l='MpServer', x=-273.13, y=71.00, z=-264.31], EntitySkeleton['Skeleton'/202607, l='MpServer', x=-200.41, y=33.00, z=-350.09], EntityItem['item.item.string'/171119, l='MpServer', x=-259.53, y=70.00, z=-265.75], EntityHuman['Joel'/109, l='MpServer', x=-260.75, y=70.00, z=-266.59], EntityCow['Cow'/110, l='MpServer', x=-312.47, y=63.00, z=-198.72], EntityBat['Bat'/203123, l='MpServer', x=-237.66, y=34.59, z=-329.63], EntityBat['Bat'/203122, l='MpServer', x=-231.03, y=32.50, z=-342.34], EntityCreeper['Creeper'/202608, l='MpServer', x=-202.50, y=33.00, z=-348.50], EntitySkeleton['Skeleton'/200820, l='MpServer', x=-340.50, y=16.02, z=-329.50], EntityHuman['Trenton'/120, l='MpServer', x=-235.31, y=67.00, z=-284.06], EntityHuman['Camryn'/121, l='MpServer', x=-263.84, y=71.00, z=-247.44], EntityHuman['Phil'/122, l='MpServer', x=-258.56, y=68.00, z=-253.69], EntityHuman['Edith'/123, l='MpServer', x=-271.41, y=69.00, z=-235.34], EntityZombie['Zombie'/201090, l='MpServer', x=-196.50, y=52.00, z=-249.50], EntityHuman['Rayna'/131, l='MpServer', x=-285.81, y=69.00, z=-257.44], EntitySkeleton['Skeleton'/201088, l='MpServer', x=-194.50, y=52.00, z=-247.50], EntityHuman['Juliet'/132, l='MpServer', x=-263.72, y=70.00, z=-232.72], EntityHuman['Nik'/134, l='MpServer', x=-273.50, y=70.00, z=-254.22], EntityHuman['Aven'/135, l='MpServer', x=-257.22, y=67.00, z=-249.34], EntityZombie['Zombie'/201867, l='MpServer', x=-277.50, y=16.00, z=-329.50], EntitySkeleton['Skeleton'/202123, l='MpServer', x=-203.50, y=32.00, z=-332.50], EntityHuman['Esme'/138, l='MpServer', x=-275.22, y=70.00, z=-251.25], EntitySkeleton['Skeleton'/201103, l='MpServer', x=-279.50, y=18.00, z=-262.50], EntityZombie['Zombie'/201869, l='MpServer', x=-286.13, y=16.00, z=-329.56], EntityZombie['Zombie'/201868, l='MpServer', x=-278.50, y=16.00, z=-330.50], EntitySkeleton['Skeleton'/201104, l='MpServer', x=-282.50, y=18.00, z=-263.50], EntityZombie['Zombie'/200853, l='MpServer', x=-305.50, y=55.02, z=-218.50], EntitySpider['Spider'/202143, l='MpServer', x=-306.50, y=57.00, z=-206.50], EntityMinecartChest['container.minecart'/158, l='MpServer', x=-252.50, y=35.06, z=-319.50], EntityHuman['Zina'/159, l='MpServer', x=-257.49, y=70.00, z=-262.74], EntityHuman['Sean'/160, l='MpServer', x=-265.44, y=69.00, z=-252.16], EntityCreeper['Creeper'/202145, l='MpServer', x=-256.50, y=11.00, z=-264.50], EntityCreeper['Creeper'/198816, l='MpServer', x=-270.60, y=53.00, z=-285.50], EntityBat['Bat'/203168, l='MpServer', x=-340.25, y=13.84, z=-290.25], EntityMinecartChest['container.minecart'/171, l='MpServer', x=-235.50, y=30.06, z=-293.50], EntityItem['item.item.bone'/178094, l='MpServer', x=-228.88, y=67.00, z=-220.13], EntityCow['Cow'/172, l='MpServer', x=-234.91, y=69.00, z=-280.84], EntityItem['item.item.arrow'/178093, l='MpServer', x=-229.06, y=67.00, z=-220.22], EntitySkeleton['Skeleton'/200887, l='MpServer', x=-269.50, y=19.00, z=-269.50], EntityCow['Cow'/73913, l='MpServer', x=-312.75, y=71.00, z=-328.88], EntityBat['Bat'/200123, l='MpServer', x=-249.28, y=29.11, z=-340.91], EntityCow['Cow'/73915, l='MpServer', x=-305.63, y=69.00, z=-330.38], EntityCow['Cow'/73914, l='MpServer', x=-315.56, y=70.00, z=-332.25], EntityBat['Bat'/200120, l='MpServer', x=-240.25, y=31.10, z=-344.53], EntitySkeleton['Skeleton'/203448, l='MpServer', x=-189.50, y=30.02, z=-250.50], EntityCow['Cow'/73916, l='MpServer', x=-311.88, y=71.00, z=-330.13], EntityBat['Bat'/201411, l='MpServer', x=-298.56, y=18.00, z=-324.06], EntityCreeper['Creeper'/202690, l='MpServer', x=-199.34, y=47.00, z=-224.06], EntityCreeper['Creeper'/202689, l='MpServer', x=-195.44, y=48.00, z=-232.03], EntityBat['Bat'/201409, l='MpServer', x=-341.69, y=42.03, z=-251.25], EntityCreeper['Creeper'/202688, l='MpServer', x=-197.31, y=46.00, z=-225.84], EntityBat['Bat'/201414, l='MpServer', x=-297.56, y=19.69, z=-325.63], EntityBat['Bat'/201412, l='MpServer', x=-301.41, y=19.06, z=-324.47], EntityCow['Cow'/201, l='MpServer', x=-186.06, y=63.00, z=-252.00], EntityBat['Bat'/201416, l='MpServer', x=-294.94, y=17.72, z=-322.00], EntitySkeleton['Skeleton'/200147, l='MpServer', x=-338.50, y=41.00, z=-230.50], EntityCow['Cow'/112853, l='MpServer', x=-296.25, y=67.00, z=-302.41], EntitySkeleton['Skeleton'/201690, l='MpServer', x=-286.09, y=50.00, z=-337.47], EntitySkeleton['Skeleton'/201689, l='MpServer', x=-283.66, y=50.00, z=-336.47], EntityZombie['Zombie'/191710, l='MpServer', x=-266.91, y=60.00, z=-269.56], EntitySkeleton['Skeleton'/201692, l='MpServer', x=-283.50, y=50.00, z=-329.50], EntitySquid['Squid'/196590, l='MpServer', x=-243.46, y=59.89, z=-296.18], EntitySkeleton['Skeleton'/203503, l='MpServer', x=-248.50, y=34.02, z=-299.50], EntityPlayerSP['XxDARKWOLF67Xx'/236, l='MpServer', x=-163.32, y=62.08, z=-185.94], EntitySpider['Spider'/203505, l='MpServer', x=-244.50, y=34.02, z=-303.50], EntitySkeleton['Skeleton'/203504, l='MpServer', x=-249.50, y=34.02, z=-301.50], EntitySkeleton['Skeleton'/200184, l='MpServer', x=-216.50, y=20.00, z=-229.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 66469224 bytes (63 MB) / 630145024 bytes (600 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1446 8 mods loaded, 8 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1446.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{11.14.3.1446} [Minecraft Forge] (forge-1.8-11.14.3.1446.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.5.82} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.82-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RadixCore{2.0.2.1-1.8} [RadixCore] (RadixCore-2.0.2.1-1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MCA{5.0.6-1.8} [Minecraft Comes Alive] (MCA-5.0.6-1.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SilentGems{1.3.00} [Silent's Gems] (Silents-Gems-Mod-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCCDeobfPlugin (unknown)
  
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.82-universal.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3412' Renderer: 'Intel(R) HD Graphics 4600'
	Launched Version: 1.8-Forge11.14.3.1446
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3412, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: Canadian English (Canada)
	Profiler Position: N/A (disabled)

**Comment by Hernan0708** [comment]
if i were u. you should downgrade to 1.7.10 and install MCA because it will be fixed in a long time. (MCA 5.1 is coming soon! xD)

**Comment by XxDARKWOLF67Xx** [comment]
Hell i might see if i can fix the missing textures myself but I can deal with the crash as of now.

**Comment by Hernan0708** [comment]
ok. mca 5.1 may be a while.

**Comment by WildBamaBoy** [comment]
Remove everything except MCA and see if the problem continues.

**Comment by XxDARKWOLF67Xx** [comment]
MCA is the only mod i have installed.

**Comment by XxDARKWOLF67Xx** [comment]
I tried un-installing not enough items and code chicken core and the problem has persisted.

**Comment by XxDARKWOLF67Xx** [comment]
And the crashing is not persistent. I reproduced the scenario and it crashed again. I reproduced it again by copying saves so i had the same exact scenario as before and it did not crash.

**Comment by XxDARKWOLF67Xx** [comment]
---- Minecraft Crash Report ----


// Daisy, daisy...

Time: 6/16/15 3:46 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
at mca.client.gui.GuiVillagerEditor.func_73863_a(GuiVillagerEditor.java:408)
at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1078)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
at net.minecraft.client.main.Main.main(SourceFile:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by XxDARKWOLF67Xx** [comment]
![2015-06-18_09 53 58](https://cloud.githubusercontent.com/assets/12942854/8232758/13394cac-15a0-11e5-95f2-cc2548f99639.png)

**Comment by XxDARKWOLF67Xx** [comment]
![2015-06-18_09 53 53](https://cloud.githubusercontent.com/assets/12942854/8232766/23dce096-15a0-11e5-9a65-25a7436b7368.png)

**Comment by XxDARKWOLF67Xx** [comment]
![2015-06-18_09 54 02](https://cloud.githubusercontent.com/assets/12942854/8232768/2c1d6e74-15a0-11e5-8957-067a1f3e4cc4.png)

**Comment by WildBamaBoy** [comment]
Update to 5.0.6.1 and let me know if the issue continues.

**Comment by XxDARKWOLF67Xx** [comment]
The missing textures remain. The same as before. The crashing however; is fixed.

**Comment by Hernan0708** [comment]
just downgrade to 1.7.10................................................

**Comment by WildBamaBoy** [comment]
Hrm. Odd. Are you using the standard Minecraft launcher, or something else like MultiMC?

**Comment by XxDARKWOLF67Xx** [comment]
Standard minecraft launcher.

**Comment by Hernan0708** [comment]
Do you have Optifine?

**Comment by WildBamaBoy** [comment]
Okay, on your launcher, select your Forge profile and click Edit Profile. Check the Launcher Visibility box and set it to "Keep the launcher open". Run the game and the launcher will change to the Game output tab.

After Minecraft starts up, copy/paste the entire log to http://www.pastebin.com/ and post the link to it here.

**Comment by WildBamaBoy** [comment]
Actually, just got this to occur myself.

**Comment by justineschluter** [comment]
http://pastebin.com/fRkSMgnr i have the same problem as this guy so i did as u said and poted it here this is the link

**Comment by Klown1337** [comment]
Yeah I was wondering where the texture went as well.
