### ISSUE TITLE
Missing texture on farm block break

### ISSUE THREAD

**Issue by TheQuadShot** [WildBamaBoy/minecraft-comes-alive#412]
This is the crop farm and the tree farm does the same thing (I'm guessing that they all have this issue)
![2015-06-18_10 57 41](https://cloud.githubusercontent.com/assets/11265900/8238215/2725eab4-15a9-11e5-87a2-0083cb9c6577.png)

**Comment by Hernan0708** [comment]
probably its from the other mods you are using. there is no problem for me. 

btw if it has a missing texture it would have black and purple checkers not letters and fonts.

texture pack? mods?

**Comment by TheQuadShot** [comment]
I have the "latest" for 1.7.10. I'm also running forge version .1422 I do have other mods, but no texture packs, and yes I thought it was weird, it looks like the ftb thumbnail. I'm not running an ftb mod pack, this is one of my "own mixes". I haven't seen this on any other block in this instance. could you tell me how I can figure this out? Thanks either way! :)

**Comment by WildBamaBoy** [comment]
Can't reproduce with only MCA installed - likely some issue with another mod. MCA just places the blocks for the farming chore, they aren't modified in any way from the originals. Try removing mods until the problem stops, but back up your world before doing so.
