### ISSUE TITLE
''Set Home'' Option Does not detect house

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#414]
When i set a villagers home, it does not detect a roofed structure. i can set a villagers home point outside and in water

![2015-06-18_12 24 02](https://cloud.githubusercontent.com/assets/12505188/8240393/228b405e-15b7-11e5-96a7-f3d8f4b9fa1b.png)

![2015-06-18_12 42 13](https://cloud.githubusercontent.com/assets/12505188/8240440/848830d2-15b7-11e5-98ee-facb068992bf.png)

I remember in MCA 4.0 if you set a villagers home point. it must be inside a structure.

Minecraft 1.7.10
MCA v5.0.6
RadixCore v2.0.2
Forge 10.13.2.1291

(i will stop posting today)

**Comment by WildBamaBoy** [comment]
Homes have always been able to be set both inside structures and outside structures.

**Comment by Hernan0708** [comment]
oh.
