### ISSUE TITLE
Spouse guard villagers don't go to sleep or spawn back after marriage 

### ISSUE THREAD

**Issue by AlyKat892** [WildBamaBoy/minecraft-comes-alive#415]
I decided to marry a guard in my survival world and one night he didn't spawn back. 
![2015-06-19_18 06 05](https://cloud.githubusercontent.com/assets/12972495/8263923/021529b4-16ae-11e5-8119-fe0c7c24d317.png) -I set time to night so you could see

**Comment by Hernan0708** [comment]
where did he go then?

did you set his home point? are there any nearby structures? difficulty enabled? monsters nearby?

**Comment by AlyKat892** [comment]
I had it on peaceful and there where no monsters. I spent like 10 minutes and found him wondering around the village like he was still a guard

**Comment by Hernan0708** [comment]
i dont think they sleep....?

**Comment by AlyKat892** [comment]
Ok well then
