### ISSUE TITLE
Won't let me download Forge- Do i absolutely need it?

### ISSUE THREAD

**Issue by FIRESapphire** [WildBamaBoy/minecraft-comes-alive#416]
Whenever I try to download Forge from the MCA download page, a window pops up stating: These libraries failed to download. Try again. org.scala-lang:scala-compiler:2.11.1 
Out of Memory: Try restarting in installer with JVM Argument: -Xmx1G

Now I've restarted it about a hundred times now, and I've deleted a boatload of stuff because of the out of memory part. I've even changed the Minecraft JVM Argument a couple times, but always with the same result. I need to face it, i need help. Also, do i absolutely need Forge for MCA? Can I just skip it all together? So please respond with some advice. I don't really know a lot about computers.

**Comment by Orange1861** [comment]
Yes, you need forge for MCA because forge is the mod loader. Now do you have Win-RAR? If you don't you can't install forge. If you have Win-RAR then go to http://files.minecraftforge.net/ then click on 1.7, then you click all downloads, find 10.13.3.1366 then click on universal.

**Comment by moinecraftperv** [comment]
Most of the errors for installing libraries come from not running the respective vanilla minecraft version at least once. For example, if you want forge for 1.7.10, you need to launch 1.7.10 so the launcher will download the necessary files, then quit the game and try installing forge again.

**Comment by WildBamaBoy** [comment]
99% of all mods require Forge. Your PC does not have enough memory to run the Forge installer. You may want to post on Forge's support forums, as it's their product, not mine: http://www.minecraftforge.net/forum/index.php?board=15.0
