### ISSUE TITLE
Colored Diamond doesn't work

### ISSUE THREAD

**Issue by Kittysoftpaws9** [WildBamaBoy/minecraft-comes-alive#417]
I saw the update video from SheFoxDeadly for MCA 1.8 and on this website there is diamond dust and colored diamonds. I cannot craft diamond dust or get it from the creative inventory. The only other mod I have is Radix Core and Optifine. Someone please help meeeee!

**Comment by Orange1861** [comment]
Read the changelog before you post, they were removed in the 1.8 update :(.

**Comment by Kittysoftpaws9** [comment]
Oh, dangit  😕
