### ISSUE TITLE
Can't set down child after picking up

### ISSUE THREAD

**Issue by Kittysoftpaws9** [WildBamaBoy/minecraft-comes-alive#418]
In MCA 1.8 you can pick up your child but can't set them back down. Is there a way to fix this?

**Comment by Hernan0708** [comment]
its a bug. you cant fix it. 

try dying or kill yourself. probably your child may get off.

**Comment by TwoFrsh4U** [comment]
Save and Quit the game then start the world again.

**Comment by Firehawk4nzzz** [comment]
press the ride horse button it works for some reason
