### ISSUE TITLE
Villagers don't accept Redstone Block as a Gift

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#422]
When i Gave an Iron Ingot to a Villager, She Didn't Accept it

![2015-06-22_18 32 45](https://cloud.githubusercontent.com/assets/12505188/8297024/3daa8a6c-190d-11e5-8ecb-b94fa9a8b604.png)

But, When i give her Plain Redstone, She Accepts it

![2015-06-22_18 34 26](https://cloud.githubusercontent.com/assets/12505188/8297039/78da60bc-190d-11e5-8663-b55e83299dd3.png)

**Comment by Hernan0708** [comment]
I mean Redstone Block...

**Comment by HillustratedMike36** [comment]
1. (unrelated) You can edit your OP right...? Just saying....

2. How many different times did you givE her redstone blocks?

**Comment by Hernan0708** [comment]
1. what?

2. once

**Comment by moinecraftperv** [comment]
Sometimes when you interact with a villager too much (gifting them too often in a short amount of time) they won't accept it.. Try gifting the redstone block to a villager that you have never interacted with - please note that villagers like gold, iron and diamond blocks more
