### ISSUE TITLE
Children won't work, pathing weird. 

### ISSUE THREAD

**Issue by TheAecy** [WildBamaBoy/minecraft-comes-alive#423]
In my large village, there is a large space with mature wheat. Whenever I had a child follow me, they'd run away to the other side, teleport back to my side, then run away again indefinitely, day and night. Once I covered the space with glass, they stay put, but won't harvest my grain. I can't get them to mine either. 
Edit: Tis the 1.8 version.

**Comment by Hernan0708** [comment]
1. They are not running away. its just a bug

2. Every Child has different levels and abilities with chores. some take longer than others and some are just lazy

**Comment by TheAecy** [comment]
1. That's why I'm reporting the bug. I apologiseif it has already been documented. 

2. I've tried with 4 different children. None of them have harvested anything. They just run off to a different portion of the village, aside from one who stands around with with a hoe looking around but never doing anything.

**Comment by WildBamaBoy** [comment]
Deleted incorrect comment. Looking at this soon.

**Comment by CatLady808** [comment]
NONE of the jobs work for me! But if they work, they don't start for 5 minutes.(except for tree cutting, which makes baby cut down HOUSES),
