### ISSUE TITLE
Update Milestone Progress Percentage

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#424]
Can you please Update Percentage of Milestones for updates. its been 7% since April (i think)

![e](https://cloud.githubusercontent.com/assets/12505188/8321772/04528214-19e0-11e5-849a-2fb2701d0573.PNG)

i am not saying ''HURRY UP'' i am trying to say update your progress so we know how much is complete with the update.

-Hernan0708

Good Work :+1:

**Comment by WildBamaBoySucksBalls** [comment]
Yo WildBitchBoy u better update ur progress faggot. u little gay ass stupid ugly slutty shitty fucking thug!

**Comment by WildBamaBoy** [comment]
The progress displayed is accurate.
