### ISSUE TITLE
Her title say's child, but her age is adult

### ISSUE THREAD

**Issue by TheQuadShot** [WildBamaBoy/minecraft-comes-alive#425]
I'm running on 1.7.10 and "latest" mca
![2015-06-24_00 58 32](https://cloud.githubusercontent.com/assets/11265900/8325320/6d473d50-1a0d-11e5-8c84-1f416145fba7.png)

**Comment by WildBamaBoy** [comment]
Not a bug, "Child" identifies them as the child of a player. "Child" is their profession.

**Comment by TheQuadShot** [comment]
I'm in single player and I never had a daughter, or am I missing something?
