### ISSUE TITLE
Crash when stopping

### ISSUE THREAD

**Issue by QORTEC** [WildBamaBoy/minecraft-comes-alive#426]
I am getting the following crash when I "Save and Quit" my single player game as well as /stop on my server.

http://pastebin.com/hiEuuBWp

**Comment by WildBamaBoy** [comment]
Update MCA.

**Comment by WildBamaBoy** [comment]
Derp, RadixCore I mean.

**Comment by QORTEC** [comment]
The client/server is running Minecraft 1.7.10, and I have RadixCore 2.0.2 installed (downloaded form curseforge.com).

Minecraft: 1.7.10
Forge: 10.13.3.1408
MCA: 5.0.6
RadixCore: 2.0.2

I can provide additional information if needed.

**Comment by QORTEC** [comment]
@WildBamaBoy is 1.7.10 still supported (bug-fixes)?

**Comment by WildBamaBoy** [comment]
Yes. You need RadixCore 2.0.2.1.

**Comment by WildBamaBoy** [comment]
Actually, that's for 1.8. I can't get my versions straight. >_>
I'll look into this.

**Comment by QORTEC** [comment]
I just noticed that another bug-report I submitted (https://github.com/WildBamaBoy/radix-core/issues/15) likely belongs together with this issue, lines 31-62 of the error (http://pastebin.com/wTjStyh7) are nearly identical to the crash report above.

I hope this helps, sorry for not noticing sooner.
