### ISSUE TITLE
Minecraft Comes Alive Babies Aren't Growing Up

### ISSUE THREAD

**Issue by JustALady** [WildBamaBoy/minecraft-comes-alive#428]
Everytime I procreate and then get a baby it never says that your baby is ready to grow up, I've tried giving up my babies to the priest and trying again yet the baby never grows up. I've had children grow up before but I've been trying and its been about 6 babies since I've had one grow up.

**Comment by WildBamaBoy** [comment]
Minecraft version, MCA version?

**Comment by JustALady** [comment]
1.7.2 Minecraft version, and 1.7.10 - unspecified

**Comment by WildBamaBoySucksBalls** [comment]
rape them

**Comment by WildBamaBoy** [comment]
If you're using MCA 5, the notification does not show up. The baby's age will appear when you mouse over it. If you're not using MCA 5, update now.
