### ISSUE TITLE
Child creating large hole when asked to mine

### ISSUE THREAD

**Issue by gyser8** [WildBamaBoy/minecraft-comes-alive#429]
Hey, Bama. You might remember me and my suggestion, but there's a big issue. All I have is Toomanyitems, Optifine and MCA for 1.8(including the core), and I asked my child to mine. But he just kept making mines within the mine, so I stopped him. I made him start again, but guess what? He just kept making more mines. Here's the problem in this picture.
Thanks again, gyser8
![2015-06-26_16 23 16](https://cloud.githubusercontent.com/assets/13070436/8387640/e32f887e-1c1f-11e5-8406-f1153a578f0e.png)

**Comment by WildBamaBoySucksBalls** [comment]
like a pussy
