### ISSUE TITLE
Looking at a villager causes me to see all caves under the ground and weird colors

### ISSUE THREAD

**Issue by Dancinggirl122** [WildBamaBoy/minecraft-comes-alive#430]
When I scroll over a villager, even a child, everything glitches. The trees turn a white color, and I can see the caves in the ground and the mobs in them. The buildings also glitch making them like see through. When I click the villager for interactions it goes away, as well as when I look away from a villager. Please help :p

**Comment by WildBamaBoySucksBalls** [comment]
you are probably on drugs faggot

**Comment by HillustratedMike36** [comment]
Are you using a custom resource pack...? What version of MCA (and RadixCore) did you use?

**Comment by WildBamaBoy** [comment]
Are you using damage indicators?

**Comment by patruck15** [comment]
I had the same issue and removing [1.8]DamageIndicatorsMod-3.3.3 fixed the issue.

Installed:
RadixCore-2.0.3-1.8-universal
MCA-5.0.6.1-1.8-universal

**Comment by WildBamaBoy** [comment]
Confirmed damage indicators is the issue.
