### ISSUE TITLE
Villagers Do not Move if Riding a Horse

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#434]
(Note: This is My Tests ''Test014'') When i Put a Villager on a Horse, she Doesn't move at all.

btw Her Arms Twitch when she is on the horse.

![2015-06-29_15 34 53](https://cloud.githubusercontent.com/assets/12505188/8420200/ea7cb6c2-1e74-11e5-9c6b-1dffa6b1cf00.png)

![2015-06-29_15 37 06](https://cloud.githubusercontent.com/assets/12505188/8420206/f1b0c17c-1e74-11e5-977f-3fd1d1599ec9.png)

Minecraft 1.7.10
MCA v5.0.6
RadixCore v2.0.2

**Comment by TheShootingStar45** [comment]
Yes, It shows that it doesn't move by regularly, and it moves only if you asked them to follow you, but there isn't any walking animation, just teleporting. A Bug.
