### ISSUE TITLE
Villager Editor, Tombstone, and Whistle are missing its texture

### ISSUE THREAD

**Issue by TheShootingStar45** [WildBamaBoy/minecraft-comes-alive#436]
Hi!
The texture of the 3 items are missing, but they are still usable as usual.
![mca1 8missingsometexture](https://cloud.githubusercontent.com/assets/13146673/8471969/5aec60e8-20c7-11e5-9f76-7594e4d67ed8.png)
Minecraft Version: 1.8
Minecraft Comes Alive Version: 5.0.6.1
RadixCore Version: 2.0.3
Using other texture: no
The texture is just "null"

Well, this is just a common bug. It's okay.
Thanks for reading.

**Comment by WildBamaBoy** [comment]
#409
