### ISSUE TITLE
Spouse's talk bug when choosing "I have a family" destiny

### ISSUE THREAD

**Issue by TheShootingStar45** [WildBamaBoy/minecraft-comes-alive#437]
Hi!
When i choose "I have a family" destiny, i've got my spouse talking to me like she wasn't married to me, and she thinks i'm just her friend.
![spousetalksstrange](https://cloud.githubusercontent.com/assets/13146673/8472403/394ad5c4-20cb-11e5-9f69-03a0064f8478.png)
But i can still procreate with her.
![2015-07-02_15 02 31](https://cloud.githubusercontent.com/assets/13146673/8472435/89d87afa-20cb-11e5-9121-968b0ede4c4c.png)
Minecraft Version: 1.8
RadixCore Version: 2.0.3
MCA Version: 5.0.6.1

Thanks for reading!
Notify me if i was wrong, or something that still missing.

**Comment by Hernan0708** [comment]
1. Bug
2. Bug
3. Bug
4. That is Normal

btw i play in 1.7.10 and that doesnt happen to me. 


:( 1.8 is always buggy

**Comment by TheShootingStar45** [comment]
Yes, still waiting for the update, so i prefer play 1.7.10 first before the other things are fixed.
