### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by Melih5000** [WildBamaBoy/minecraft-comes-alive#439]
MCA 5.1 or 5.1.X versions of the Turkish language  next.Thanks wildbamaboy

**Comment by WildBamaBoy** [comment]
Additional languages will be implemented in 5.1.

**Comment by Melih5000** [comment]
texture problem be corrected?
[![image](http://i.hizliresim.com/JY0q8n.png)](http://hizliresim.com/JY0q8n)
New skins will be added?
