### ISSUE TITLE
'Stay Here' Villagers still Moving

### ISSUE THREAD

**Issue by Klown1337** [WildBamaBoy/minecraft-comes-alive#440]
It seems that when I hire a guard and select the 'Stay Here' option, the guard still moves though only in small steps every couple of seconds.  I dont know if this is a bug or not, but when I told to the guard to stay at the entrance of my house, after 10 minutes i see him 30 blocks away in the woods.

**Comment by TheShootingStar45** [comment]
I had the same thing, villager have a chance to move after being told to stay at their position, if they are moving, or they are interested at something, like a village, etc.
But in 1.7.10 it seems OK, villagers are less likely to move, less chance. But in 1.8 villagers have more chance, so it could be a bug.

-TheShootingStar45

**Comment by Klown1337** [comment]
Hmm that's interesting, thanks for the confirmation that it wasn't just me lol. Hopefully it's a bug and it will be fixed soon.

**Comment by TheShootingStar45** [comment]
Maybe it caused by an Al in the MCA's assets. They are forced to stop while the Al is still working.
(Maybe)
PS: Sorry if that was wrong.
Notify me if i was missing something.

**Comment by WildBamaBoy** [comment]
Known issue that will be reworked in 5.1.
