### ISSUE TITLE
Villagers Duplicating

### ISSUE THREAD

**Issue by RottenBananaMC** [WildBamaBoy/minecraft-comes-alive#442]
In My Survival World. i found a few villagers duplictating.

HELP ME! THERE WERE 5 OF THE SAME ONES!! (i think)

![2015-07-07_12 14 04 - copy](https://cloud.githubusercontent.com/assets/11895017/8530842/272c9528-23e9-11e5-8688-5c587d7f7c4d.png)

![2015-07-07_12 14 04](https://cloud.githubusercontent.com/assets/11895017/8530846/2f9db84a-23e9-11e5-82ea-06981de5f15d.png)

![2015-07-07_12 13 35](https://cloud.githubusercontent.com/assets/11895017/8530854/39574856-23e9-11e5-8bbf-baf47a580e8e.png)

**Comment by WildBamaBoy** [comment]
If a mod happens to add villagers, this could happen. Otherwise villagers are not going to duplicate by any means.
