### ISSUE TITLE
Modded Weapon Dialogue Bug

### ISSUE THREAD

**Issue by DNDarkness14** [WildBamaBoy/minecraft-comes-alive#443]
This buggy thing happens on 1.7.10 Flan's Mod installed additionally its content packs. When i shot/knife a villager. They say the dialogue when they got hit with bare hands. Doing the same actions after they got hit, meaning. They still try to fight back such a dangerous opponent with a 10+ damage knife and a Sniper Rifle? (The stock weapons dialogues are still intact. This may happen on other weapon mods, ex: Balkon's Weapon mod)
This is one of the screenshot of the dialogue bug:
![2015-06-28_18 57 51](https://cloud.githubusercontent.com/assets/13232677/8564797/139c4f86-2582-11e5-8d52-12d3ccbe7a5e.png)
This happens after shooting them with "few" rounds
This bug really lives on a long time. This also happens on one of the oldest versions
Well the versions are:
MCA: 5.0.6 1.7.10
Radix Core: 2.0.2 1.7.10

Pardon me cause i'm a little bit confused on the difference of a glitch and bug

**Comment by WildBamaBoy** [comment]
Villagers will use the same set of dialogue whenever you hit them with something, even from another mod. This is not a bug or glitch.
