### ISSUE TITLE
Villagers Despawning?

### ISSUE THREAD

**Issue by HmanWP** [WildBamaBoy/minecraft-comes-alive#444]
I play on a server with MCA on it, and we have a problem with people despawning. I know that villagers don't despawn, however, multiple wives and children have disappeared with no death messages, in perfectly lit up places that they can't leave. Anyone know what's going on?

**Comment by WildBamaBoy** [comment]
They are either being lost or are dying without the death messages. If the players are not online, the death messages will not appear.

**Comment by HmanWP** [comment]
They're in a room with no way out, and I'm pretty sure they can't die unless they find a way to suffocate
