### ISSUE TITLE
Duplicates of all Villagers

### ISSUE THREAD

**Issue by TheWolfWhoGrins** [WildBamaBoy/minecraft-comes-alive#447]
I went on an adventure and came back to find all my villagers have duplicated so there are two of each. They are completely identical and have the same relationship status as their twin.
![2015-07-09_17 17 58](https://cloud.githubusercontent.com/assets/13263320/8608296/10c2e8b4-265f-11e5-96ff-8b668423cfab.png)

**Comment by RottenBananaMC** [comment]
i keep having the same problem. but WildBamaBoy thinks other Mods are conflicting with it. 

3 people already told him that. but he wont listen. probably he might do something about it.

**Comment by TheWolfWhoGrins** [comment]
MCA is the only mod that I have so that isn't the issue. Hopefully he does resolve it because until then I'm turning into a serial killer to "deal" with the clones.

**Comment by WildBamaBoy** [comment]
What's your MCA version and Minecraft version?

**Comment by TheWolfWhoGrins** [comment]
Sorry for the late reply.
MCA-5.0.6.1-1.8
Minecraft version 1.8 w/ Forge11.14.3.1450

**Comment by WildBamaBoy** [comment]
When you see a villager like this, log out of the game and back in. Is the villager still there?

**Comment by TheWolfWhoGrins** [comment]
Yes. Also in my original comment I said they all have the same relationship status as their twin but this is false. The duplicates started with however many hearts the original had when they were created, but now any action I perform on one does not affect the other. Not sure how useful that info is.

**Comment by WildBamaBoy** [comment]
Should be fixed in 8d7ab24bfb056e0261e2bfa231e20a2776598030.
