### ISSUE TITLE
¡Enemies villagers!

### ISSUE THREAD

**Issue by Mackshoon** [WildBamaBoy/minecraft-comes-alive#448]
Good, I realize that they are collecting suggestions for vercion 5.1 and wanted to contribute.

Agregen want a system of enmity, for example if my brother can play with me I will order a relative of MCA to attack my brother.

or just to my son but if I am king, you can order all
guards to attack if they see my brother.

forgive my English, do not speak English, I use google translator.

------------------------------------------------------------------------------------------------------------------------

Buenas, me doy cuenta de que estan recopilando sugerencias para la vercion 5.1 y quise aportar.

Quisiera que agregen un sistema de enemistad, por ejemplo si mi hermano juega conmigo yo le pueda ordenar a un familiar de MCA que ataquen a mi hermano.

o no simplemente a un hijo mio sino que si soy monarca, pueda ordenar a todos los
guardias a atacar a mi hermano si la ven.

Grasias por la atencion n.n

**Comment by WildBamaBoy** [comment]
We will be implementing something similar to this in 5.1 with the monarch system.
