### ISSUE TITLE
Can't drown my child!!!

### ISSUE THREAD

**Issue by Firehawk4nzzz** [WildBamaBoy/minecraft-comes-alive#449]
when you spawn a child under water on MCA version 5.0.6, Minecraft version 1.8 the game crashes...not a huge deal seeing as most people probably never think too spawn their child under water...or maybe you guys did it on purpose to prevent lunatics (like myself) from drowning their children, either way, just figured id give you a heads up, also if you have fixed that particularly insignificant bug in the newest version of the mod...you know, the one that's not multiplayer compatible, disregard this post, i just won't play on the new version because i can't do multiplayer, that was one of the greatest features in my opinion, but regardless, great mod, keep up the good work

**Comment by Firehawk4nzzz** [comment]
also not a big concern but could you possibly bring back the ability too cook and eat my child...i'm not crazy i'm curious, what does MCA child taste like?

**Comment by WildBamaBoy** [comment]
Crash report.
