### ISSUE TITLE
MP LAN Second player not generating home and gender/preference not saving

### ISSUE THREAD

**Issue by Atziloot** [WildBamaBoy/minecraft-comes-alive#450]
Currently running Minecraft 1.7.10, MCA 5.0.6, Radix Core 2.0.2.
I open the game to LAN, Second player joins gets crystal goes through the process and comes back to overworld. No house generated. They disconnect and reconnect and spawn with the crystal ball again. The no house thing is fine, I'm just wondering if the gender/pref are being saved if so I will have them do it once and then disable the crystal spawning. I saw #252 but was unclear how to address my issue.

**Comment by WildBamaBoy** [comment]
MCA currently has known issues with LAN. There's no way around it at this time. Use a server.
