### ISSUE TITLE
Giant Children and Not Growing up

### ISSUE THREAD

**Issue by PhantomHeart** [WildBamaBoy/minecraft-comes-alive#451]
I have currently 5 children. One is a baby, two are adult girls, one is a child, and on is an adult male.

All three adult children are GIANT. They are at least 4 blocks tall. Each child also does not grow up into an ADULT. They just keep saying they are still a kid or what is this when I try to marry them to someone when they are over 50 years old. The boy hasn't aged over 4 either.

This is currently happening in the MCA official server

**Comment by WildBamaBoy** [comment]
Resultant of differing config values. WIll be resolved soon.
