### ISSUE TITLE
Villager didn't accept plain shaped diamond as a gift.

### ISSUE THREAD

**Issue by TheShootingStar45** [WildBamaBoy/minecraft-comes-alive#453]
Hi!
When i gift my uncolored shaped diamond (ex. like plain shaped diamond heart, diamond star, etc)
to my spouse, she denies it.
![2015-07-12_23 33 37](https://cloud.githubusercontent.com/assets/13146673/8638758/1db501fa-28ef-11e5-8d38-62fee4acef81.png)

Minecraft Version: 1.7.10
Minecraft Comes Alive Version: 5.0.6.1
RadixCore Version: 2.0.2

This is just a common bug, i apologize if this was already been documented.
Thanks for reading!
Notify me if i made a mistake.

**Comment by Hernan0708** [comment]
well. i do see another bug in this picture

Your Spouse's Chat Succession rate did not change. even when she is sad.
