### ISSUE TITLE
Overiding MCA villagers have the wrong health

### ISSUE THREAD

**Issue by Orange1861** [WildBamaBoy/minecraft-comes-alive#456]
When MCA villagers overide the reg. villagers, the MCA villagers have the same health as the reg. villagers until you reload the world. Example: You set in the config that all MCA villagers have 30 hearts. When MCA overides reg. villagers with MCA villagers, the MCA villagers have 20 hearts instead of 30. When you leave and reload the world, the MCA villagers have the correct health.

I use 1.7.10 Minecraft and forge 1452.

**Comment by Hernan0708** [comment]
probably META-INF is trying to reset the health (in MCA files)
