### ISSUE TITLE
Can't unlock high tier trades

### ISSUE THREAD

**Issue by Parix94** [WildBamaBoy/minecraft-comes-alive#457]
Hi everyone, when i trade with a villager i can't unlock the next-tier items.
I mean, in example, a blacksmith,
When i trade coal for emeralds (T1 trade), i don't unlock the next tier trade as an armor or a diamond pickaxe.
Same with the librarians. I can't get the Name-Tags this way.
Can anyone help me?

**Comment by moinecraftperv** [comment]
You need to complete the latest trade 1-5 times before being able to unlock the next

**Comment by Orange1861** [comment]
You are supposed to wait for the villager to get regen which takes one trade. I have a simlar problem.

**Comment by WildBamaBoy** [comment]
Unable to reproduce this.
