### ISSUE TITLE
Build Chore - Feature Request

### ISSUE THREAD

**Issue by assasing123** [WildBamaBoy/minecraft-comes-alive#459]
Allow villagers to build at a designated location schematics placed on the blueprints/schem folder of buildcraft/worldedit provided you tell them a source for the materials required.

for ease of implementation use a similar system to millenaire.

alternatively... make the mod millenaire compatible.

**Comment by Orange1861** [comment]
From these suggestions MCA will turn from MCA to MCA-Millenaire.
