### ISSUE TITLE
MCA Official Server Bug

### ISSUE THREAD

**Issue by PhantomHeart** [WildBamaBoy/minecraft-comes-alive#461]
I'm a player in the Minecraft Comes Alive Server and I've noticed along with other players that the villagers will not breed. They also will not breed when given cake. It does not take both cake from my inventory and only takes one. I even have gifted the other cake to the other spouse and it still didn't work. I gave two cakes to one spouse and that didn't work either. Thank you.

-A Dedicated Fan

**Comment by Hernan0708** [comment]
1. you cannot make OTHER villagers breed. they will breed on their on. (do to Story Mode)

2. Villagers will only breed with its spouse not another player. just click the Procreate Button to make a baby.

**Comment by WildBamaBoy** [comment]
Gifting cake to villagers will not work 100% of the time.
