### ISSUE TITLE
Old Villager Skins?

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#465]
When i was looking more into MCA 5.0.6's assets, i found 7 skins that were EE??

![s](https://cloud.githubusercontent.com/assets/12505188/8711014/0652d184-2b03-11e5-97d5-7ed33b04daba.PNG)

![se](https://cloud.githubusercontent.com/assets/12505188/8711018/1486ccf6-2b03-11e5-8b63-61b8d3617a09.PNG)

i need to ask you:

1. are these skins not implemented yet? are they a MCA 5.1 milestone?

2. were they used on the old versions of MCA?

3. are they for the unused Generic Villagers?

btw good job on the progress! i am happy you fixed a lot of bugs xD

**Comment by WildBamaBoy** [comment]
These were in previous versions. No longer used as of right now.
Only use GitHub for actual issues, not questions.
