### ISSUE TITLE
Possible Mca Overhaul?

### ISSUE THREAD

**Issue by vitreousbeast7** [WildBamaBoy/minecraft-comes-alive#470]
Could you add new mechanics?
Priest:Enchant,Brew Potions,holds mass,etc.
Leatherworker: Makes leather things
Miner:Mines and collects lava?
Farmer:Grows Crops and tends animals
Guard:Seeks territory for expansion
Archer:Holds steady ground when in invasion
Smith:Forges tools, fixes tools
Doctor: Cures wounded and cures sick
Builder:fixes buildings and builds
Merchant: Sells all excess village materials
Warrior: Fights in invasion force in battle
Leader: Supreme Commander,Leads in battle to boost morale and commands village when dead the village is seized 
Commander:Leads a squad-rant into battle 
Negotiator: Negotiates peace between conflicting villages 1/2 chance of working
Duke: Leaders friend; if leader does not have male children duke succeeds him
New Mechanics:
------------------------------------------------------------------------------------------------------------------------------
Morale: When below 0 they work 50% less efficiently,When above 100% they work 50% harder
Goes Down when: A house is damaged,A villager gets sick,a villager gets hurt,getting attacked,someone betrays Goes up when: Mass is held,a child is born, new territory is found, a battle is won,sick has been healed,a marriage happened
Conquest:Villages will fight to become all powerful when leader or all commanders are dead with other side wins battle winning village takes the rest of the villagers prisoner
Hunger: Simple: hunger
Betrayal : villager joins neighboring village 
Sickness: Low: slows working and is not infectious Medium: Hurts worker and spreads slowly High : Might kill worker very infectious 
Infection: Medium sickness: Can infect up to 50% of population High sickness: can affect up to 90% of the population
Working: House must be build and tools must be made for a certain worker when a worker dies a new child becomes that worker to compensate
Expansion: village expands 2 chunks at a time when runs in to another village they may negotiate peace(Creates buffer chunks) if not they go into battle also if a village cannot expand anymore they automatically mights the weakest nearby village
Peace: Possible inter village trading or strict no go
Assimilation: Prisoners get released into general population
Jailing: Those who kill or were prisoners of war get put in jail (Priests or leaders cannot be killers)
Aging:Children cannot work 0-10 Children and adults 11-24 work at max 90% efficiency Adults 25-35 can work at max 175% efficiency adults 36-45 work at 80% efficiency  adults 45-55 work at 50% efficiency and adults 56+ do not work 
Succession: Leaders eldest child success him if he doesn't have a heir a duke becomes leader
Fertility: When villagers 13-20 procreate they have a 25% chance of having a child when villagers 21-35 procreate they have a 75 percent chance of have in a kid 35-45 50% chance villagers 46+ cannot have children
Inbreeding: Causes permanent low sickness if villager related within 2 generations procreate this gets neutralized after 5 generations 5% chance of happening when population has enough diversity not to inbreed
New villagers: Occasionally a traveling merchant joins a village 3000% more common when population is low
New Structures:
-------------------------------------------------------------------------------------------------------------------------------

Castle:Where leader lives and materials are stored
Walls:Prevents invasion force from getting in
Paths:Villagers move 5% quicker
Houses: For a certain worker
Roads:villagers move 25% quicker
Jail: Prisoners are held in
Outposts: Put up when expanding
Animal barns: animals are raised in
Fields: Crops are grown in
Wells: water is obtained from
Mine: A mine
Quarry: Above ground mine, generally sand gravel or coal/stone
Types of Village or ruling types:
-------------------------------------------------------------------------------------------------------------------------------
Hamlet 2-10 villagers Leader Title: Leader
Settlement 11-45 villagers Leader title: Ruler
Village 46-100 villagers Leader title: Elder
Town 101-450 villagers Leader title: Lord
Kingdom 451-1000 villagers Leader Title: King
State 1501-2000 villagers leader title : sovereign
dominion 2000-4000 villagers leader title : All mighty
   Ruling types
False democracy: +50% morale +10% army force
Democracy: +75% morale +5% army force
Dictatorship -25% morale +50% army force -25% consumpsion rate
Utopian: +100% morale +75% army force +50% consumption rate
Advancements:
-------------------------------------------------------------------------------------------------------------------------------
Low: +20% effectiveness
Medium +35% effectiveness
High +75% effectiveness
Advanced: +100% effectiveness
Highly Advanced +200% effectiveness 
Sorry unknown material for advancements

If your the leader of a village (crystal ball) you also choose what kind of village you can make
Misc: With each advancement more availability of tools weapons materials blocks and structures
Plus more ore and ability to be polygamous
Edit to to have a family: you will be put in a random sized and type village and will work there if you can kill the leader you will lead that village but the archers and guards will attack you also you will be able to act as a npc
Adds shops and currency
Also could you make villages more common and also they can be made in any biome.(Like one in each biome)

**Comment by WildBamaBoy** [comment]
This isn't really the place for suggestions, but I'm going to mark this as a feature to pick through later.

**Comment by WildBamaBoy** [comment]
Moved somewhere secret...
