### ISSUE TITLE
MCA 5.0.4 for 1.7.10 -- Villagers vanished while "staying"

### ISSUE THREAD

**Issue by ZenOokami** [WildBamaBoy/minecraft-comes-alive#472]
I've had three villagers vanish thus far. I'd ask them to stay somewhere while I went off to do something, turn around and they'd just be gone.

**Comment by Orange1861** [comment]
Update to the latest version before reporting bugs.

**Comment by ZenOokami** [comment]
Curious - is 5.1.0 the current latest version or the 5.0.6 found on the curse/radix site?

If it's the former, where's the compiled version for 5.1.0?
