### ISSUE TITLE
Rendering glitch when looking at villager

### ISSUE THREAD

**Issue by Dhs92** [WildBamaBoy/minecraft-comes-alive#475]
![EXAMPLE #1](http://i.imgur.com/acQ02VM.jpg)

![EXAMPLE #2](http://i.imgur.com/LpetBuc.jpg)

![Mod List](http://i.imgur.com/in1lEeq.png)

Using forge version 11.14.3.1487

**Comment by WildBamaBoy** [comment]
Caused by Damage Indicators.
