### ISSUE TITLE
1.7.10 Tombstone, and Whistle are missing their textures

### ISSUE THREAD

**Issue by PitchBright** [WildBamaBoy/minecraft-comes-alive#477]
MC: 1.7.10
MCA: MCA-5.0.6.1-1.7.10

![screen shot 2015-07-21 at 7 48 36 am](https://cloud.githubusercontent.com/assets/8009866/8800018/09e15a2c-2f7d-11e5-961e-cc639a122477.png)

If you're not still fixing 1.7.10 stuff, would you mind replying with directions on how I can add these missing textures to a resource pack to feed the mod the textures it needs?

I've tried:

/mca/textures/items/Tombstone.png
/mca/textures/items/tombstone.png
/mca/textures/items/Whistle.png
/mca/textures/items/whistle.png

and none of those worked. Where exactly is the mod looking for the textures and what are the correct filenames? (I noticed the textures changed from starting with a lowercase letter to uppercase somehwere between v5.0.3 and v5.0.6.1

**Comment by Orange1861** [comment]
The villager editor has the same bug.

**Comment by RottenBananaMC** [comment]
Probably Incorrect Item ID's?!?!?!

**Comment by TheShootingStar45** [comment]
Yes, it's already documented and its textures will be reworked soon.

**Comment by PitchBright** [comment]
I thought it was only documented for 1.8.
