### ISSUE TITLE
What Happend To Home Point/Bed Detection?

### ISSUE THREAD

**Issue by RottenBananaMC** [WildBamaBoy/minecraft-comes-alive#478]
I Remember in MCA 4.1.5 if you set a villagers home point, it will detect if the area is clear. 

The Main reason i am saying this, because it may or can prevent Villagers from suffocating/interfering with nearby blocks. 

MCA 4.1.5 (image down below)
![2015-07-22_13 45 06](https://cloud.githubusercontent.com/assets/11895017/8812000/2a2038b6-2fbf-11e5-9137-f1bfcebde5df.png)

btw Did you remove this feature? or is it bugged out?

NOTE: when you rework Beds in MCA 5.1 please re-add Home Point Detection

**Comment by HillustratedMike36** [comment]
Not the suggestions page...this is a bug reporting page.
