### ISSUE TITLE
Cakes won't work and disappearing villagers

### ISSUE THREAD

**Issue by Orthod0x** [WildBamaBoy/minecraft-comes-alive#480]
My friend and I have been on a 1.7.10 mod server I set up and we found that our villagers disappear, only a few have survived this long. We don't know the cause, they aren't dying because their spouses still say they are married for awhile. It seems to happen after they get married, even my daughter vanished after I gave her a house and a husband. 
Secondly, giving cakes to couples won't let them produce a kid, this is a recent problem and were not sure whats causing it. I swear we live in glitchburg.

**Comment by RottenBananaMC** [comment]
Probably Players are Killing them when you are offline.

**Comment by Orange1861** [comment]
Are you using 5.0.6.1?

**Comment by TheAwesomeGem** [comment]
Try using gravestone mod to keep track on how they died.

**Comment by HillustratedMike36** [comment]
Difficulty of server...? Other mods used...?

**Comment by TheShootingStar45** [comment]
It's a bit of bug, just use two cakes and gift them. It's also recommended to disable CTRL while giving. The How To Play Section in minecraft comes alive said that giving cake will not always work. (But this section is not a bug, by the way) hope that will be reviewed sooner.

**Comment by WildBamaBoy** [comment]
Villagers are dying via player, mob, etc. Cakes do not always work - you may have to gift more than one. This is intended.
