### ISSUE TITLE
Villagers need to eat food

### ISSUE THREAD

**Issue by Artembelov** [WildBamaBoy/minecraft-comes-alive#482]
Make it so they plant and harvest crops and they have a need to eat or they are either weak or die? possible? how about taking the harvest/plant part from the newest vanilla villagers that do that and put some of that to lighten the load

**Comment by Hernan0708** [comment]
1. this is utterly useless

2. this page is only for BUGS

**Comment by HillustratedMike36** [comment]
Yeah, this is for bugs only...although this might be one key feature exclusively for Hardcore Mode.
