### ISSUE TITLE
Unexpected error while syncing player memory

### ISSUE THREAD

**Issue by Tencao** [WildBamaBoy/minecraft-comes-alive#483]
As I was flying around sorting my modpack out, the client kept getting spammed this error. The reason it's such a huge issue, is it's causing massive memory leaks when connecting to the server, spiking from 1GB to 2GB and so on. 

http://pastebin.com/nieP1XbG

**Comment by WildBamaBoy** [comment]
This can be ignored. It's not causing your memory issues.
