### ISSUE TITLE
Children Dissapearing Without Reason

### ISSUE THREAD

**Issue by Ace1362** [WildBamaBoy/minecraft-comes-alive#487]
My children seem to disappear anytime I leave them for a few minutes they give no death message and won't come for the whistle this is quite annoying

Edit:
I have lost 6 children to this and it has quite ruined my experience is there anyone else who is having this issue?

**Comment by Hernan0708** [comment]
Did you send them to do chores?

**Comment by WildBamaBoy** [comment]
They are dying from players, mobs, etc.
