### ISSUE TITLE
Can't have anymore kids

### ISSUE THREAD

**Issue by sevth7** [WildBamaBoy/minecraft-comes-alive#489]
So my wife got turned into a zombie with our kid in her inventory.... after that I re-married and every time I try to have a kid with the new wife it says "you already have a baby"
Help?

**Comment by TheShootingStar45** [comment]
When your spouse accidentally die with your baby in their inventory, they may drop the baby. But if they turned into a zombie, they won't bring back their inventory. But the baby is still be as your child, even you have lost him/her. If you lost your baby, go to priest's special menu, and press "Reset Baby" for MCA 5.x.
Now you can have more kids.

**Comment by sevth7** [comment]
... Now I have to find a priest... Thanks for the help * that did fix it!
