### ISSUE TITLE
config option for max villager height

### ISSUE THREAD

**Issue by AngleWyrm** [WildBamaBoy/minecraft-comes-alive#491]
mezzodrinker: "[Villager death when going to bed, Ref. issue #463 Villager Suffocation] is caused by the height of some villagers being greater than the size of the bed. If you put that bed in a corner, it's a given that villagers that are taller than 2 blocks (2m) suffocate in the wall."
AngleWyrm3: "Is there a config option to prevent npc's from being too tall to get in bed?"
mezzodrinker: "No there isn't."

Suggestion:
As a fix for tall people dying while trying to go to bed at night, add a config option for max villager height. End the nightmares!

Post beginning thread conversation at: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-0-6-2-mc-1-8-loved-by?comment=15639

**Comment by WildBamaBoy** [comment]
Config option not added - overall issue was resolved without the need to implement this type of option.
