### ISSUE TITLE
Add ability to bring dead villagers back to life.

### ISSUE THREAD

**Issue by WildBamaBoy** [WildBamaBoy/minecraft-comes-alive#495]

**Comment by HillustratedMike36** [comment]
Will this be like the reviving them through a tombstone and they will be dropped as a egg to be simply respawned...? 

Or like a new item (like a machine) that keeps track of all the MCA villagers, diving them into 2 categories; Alive or Dead.

The Alive category would show the basic villager information, including an option to teleport to them.
The Dead category would also show the information, but include why they died and the time they died.

Also, in both categories, there can be window to see your relationship with them.

**Comment by techmago** [comment]
If you have the mod "gravestone" installed, you can revive villages.

**Comment by LiHangZ** [comment]
If u use gravestone u can only revive him/her into another random person,
the relationship between other people and u will be reset

**Comment by TheShootingStar45** [comment]
The idea's function will still be a secret =)

**Comment by DemonicIntent** [comment]
Something like a command for example as a start? Then later a ritual held around their on-ground tombstone to bring them back? Adding some lore to story-mode progression.

**Comment by MentalMouse** [comment]
A couple of mods can produce spirits, notably EvilCraft.  

By "gravestone" I assume you mean a new, durable item that remembers the person, rather than the current stone signs?

**Comment by jkhero73** [comment]
Maybe just revive them as a zombie, and have to cure them before the guards kill him/her.
