### ISSUE TITLE
Player inventory bug on MP LAN server [1.7.10]

### ISSUE THREAD

**Issue by craft90** [WildBamaBoy/minecraft-comes-alive#498]
I'm aware that MCA currently have issues with LAN worlds currently. So here's another game-breaking bug. Occasionally when I join my friend's LAN world I run into an error where I start with an empty inventory although I had inventory full of stuff previously. I tried to cheat in stuff and continue playing but then next time I joined I spawned with a previous incarnation of my inventory, losing what I had last time. This basically makes our world unplayable. Until this bug is fixed I'm afraid we can't use your mod. We don't have the money to set up our own server (unless there's a free alternative).

Edit: MCA 5.0.6 for MC 1.7.10 and Radix Core 2.0.2

**Comment by WildBamaBoy** [comment]
MCA would not be causing this issue. If using other mods, investigate problems with them. Otherwise something's up with the world itself causing playerdata issues.
