### ISSUE TITLE
Wrong player association

### ISSUE THREAD

**Issue by FluxcapGaming** [WildBamaBoy/minecraft-comes-alive#499]
My friend and I are playing on a lan game that I host.  We each found brides and he married his first.  When I married mine she keeps referring to me by his name when ever I get back home.  My friend then had a child with his wife and this prevented me from having a child with mine as the config is limited to one child.  My wife somehow thinks I am my friend.  We also have the morph mod where we can morph into each other so I thought this may be the issue but I was not morphed as him during any of this or him me.

**Comment by WildBamaBoy** [comment]
Known issue with MCA on LAN.
