### ISSUE TITLE
Kids dont have a mother D:

### ISSUE THREAD

**Issue by XxDARKWOLF67Xx** [WildBamaBoy/minecraft-comes-alive#500]
When i interact with my twin girls it says they dont have a mother. Same with my son who is an adult. 

![2015-08-02_18 06 17](https://cloud.githubusercontent.com/assets/12942854/9028269/87385d36-3941-11e5-9559-a7d141ed217a.png)
![2015-08-02_18 06 22](https://cloud.githubusercontent.com/assets/12942854/9028271/8ad81dd2-3941-11e5-9549-41863fa488d2.png)

**Comment by XxDARKWOLF67Xx** [comment]
Now i had another son and it shows the mother.
![2015-08-02_18 17 08](https://cloud.githubusercontent.com/assets/12942854/9028310/0daf3f78-3943-11e5-860f-4bbc4f7b83f5.png)

**Comment by XxDARKWOLF67Xx** [comment]
And now he disappeared. dosnt even come for the whistle XD

**Comment by XxDARKWOLF67Xx** [comment]
Another bug! I found out why my kid disappeared! Because another one did >_>. when children get in villager beds they can die/vanish

**Comment by WildBamaBoy** [comment]
I am unable to reproduce this problem in 1.7.10, please confirm the version of Minecraft and MCA you're running.
