### ISSUE TITLE
No more buttons to the menu (MCA-1.7.10-5.0.7.1-universal)

### ISSUE THREAD

**Issue by RomixERR** [WildBamaBoy/minecraft-comes-alive#507]
This was all in the previous version ( MCA-4.1.1 MC-1.7.10):
1. No armor inventory on the left:
![2015-08-09_15 10 10](https://cloud.githubusercontent.com/assets/13717583/9154823/93736028-3eaa-11e5-96b5-491ebc21d073.png)
2. Button cooking:
![2015-08-09_15 11 38](https://cloud.githubusercontent.com/assets/13717583/9154824/93750c5c-3eaa-11e5-8149-12ccc8102392.png)
3. Button battle:
![2015-08-09_15 11 41](https://cloud.githubusercontent.com/assets/13717583/9154822/9372a1f6-3eaa-11e5-9f0e-89711318410c.png)
4. Hours for mercenary:
![2015-08-09_15 12 16](https://cloud.githubusercontent.com/assets/13717583/9154821/93722c80-3eaa-11e5-87b6-1e87bca64911.png)

Where everything lost in current version? And sorry for my english!
![2015-08-09_14 54 47](https://cloud.githubusercontent.com/assets/13717583/9154884/30c53828-3eac-11e5-9c62-9dd4122d92b9.png)

**Comment by Orange1861** [comment]
Um, Read everything before posting. These were not readded in the 5.0.0 rewrite.

**Comment by moinecraftperv** [comment]
The features aren't added back in the latest versions yet
