### ISSUE TITLE
Increase romantic interaction success chance?

### ISSUE THREAD

**Issue by moinecraftperv** [WildBamaBoy/minecraft-comes-alive#518]
Ever since i've been playing on v5 and later, the success chances of kissing/flirting/hugging your spouse is very low (even if the personality is flirty). In the previous v4 the success rate is very high as long as you keep your spouse happy. Can you modify it a bit such that the more hearts you have with a villager, the higher the success rates of such interactions?

**Comment by Orange1861** [comment]
Um, you posted twice.

**Comment by moinecraftperv** [comment]
oops
