### ISSUE TITLE
Weird hole when spawning in a village

### ISSUE THREAD

**Issue by davidthenut** [WildBamaBoy/minecraft-comes-alive#519]
I'm playing in 1.8 mca and after i spawned in a village to live in on my minimap there where large black boxes when I walked over to them they turned out to giant holes that wernt there before i cant place blocks over them because they disappear! Does anyone know what is wrong??

**Comment by moinecraftperv** [comment]
could be a world hole bug. This can happen in vanilla if the game was using too much memory. Relaunch minecraft and this should be fixed
