### ISSUE TITLE
Weird hole when spawning in a village

### ISSUE THREAD

**Issue by davidthenut** [WildBamaBoy/minecraft-comes-alive#520]
when I spawn in a village a giant hole appears near the village it goes all the way to the end of the world
and any block you try to place over it disappears! Anything i can fix or need to start a new world??

**Comment by HillustratedMike36** [comment]
Is there other mods you are using besides MCA (and RadixCore)?

**Comment by moinecraftperv** [comment]
could be a world hole bug. This can happen in vanilla if the game was using too much memory. Relaunch minecraft and this should be fixed

**Comment by WildBamaBoy** [comment]
Update to the latest version.
