### ISSUE TITLE
Glitchy Textures

### ISSUE THREAD

**Issue by JacobDustSong** [WildBamaBoy/minecraft-comes-alive#527]
So, yeah. Everything is always fine and dandy, then I look at any villager and this happens. I'm running MCA 1.8-5.0.7.1-universal and Radix Core 1.8-2.0.4-universal. I also have Too Many Items installed, along with Hit Splat Damage Indicators. I made an account and posted this just today a few hours after it happened.
![2015-08-26_21 09 59](https://cloud.githubusercontent.com/assets/13990977/9511012/0ce25702-4c2f-11e5-98b6-da3249f20c1c.png)

**Comment by WildBamaBoy** [comment]
This is caused by DamageIndicators.

**Comment by JacobDustSong** [comment]
Thanks a bunch!
