### ISSUE TITLE
Feature Request: Configure maximum offspring per player

### ISSUE THREAD

**Issue by PitchBright** [WildBamaBoy/minecraft-comes-alive#529]
As a server owner, it would be great to be able to limit people to the number of children they are able to have, via configuration.

Especially by: Maximum, Lifetime, Cool-down period… etc.

**Comment by WildBamaBoy** [comment]
So turns out this was actually a configuration option added back in from MCA 4. But, I never made it actually do anything. -.-

**Comment by WildBamaBoy** [comment]
Done, will be in 5.1.

**Comment by PitchBright** [comment]
Thanks Bama!
