### ISSUE TITLE
Villagers may pickup armor again?

### ISSUE THREAD

**Issue by oblisgr** [WildBamaBoy/minecraft-comes-alive#531]

**Comment by oblisgr** [comment]
Will villagers pickup item like armor or weapons from the ground as they did in previous versions.

**Comment by HillustratedMike36** [comment]
WildBamaBoy is already considering this.. #511

**Comment by WildBamaBoy** [comment]
#511 , however villagers will not pick up armor on the ground. Kinda risky considering you can't access everyone's inventory.
