### ISSUE TITLE
Disabled Chores don't apply to Children

### ISSUE THREAD

**Issue by PitchBright** [WildBamaBoy/minecraft-comes-alive#532]
I've disabled all the chores in the config, and they are no longer an option when interacting with Villagers (as expected)… but…  when I had a child, I was able to access his chore menu.

Can we please have a separate section in the config to disable Child Chores, or conversely, make the main setting effective across the board?

Thanks!
-Pitch

**Comment by WildBamaBoy** [comment]
You may still be able to access the chore menu, but when you attempt to run the chore you should get a notification that it is disabled. This is so because the setting exists on the server's side, not the client-side.
