### ISSUE TITLE
[Enhancement] Add question to generate a house or not

### ISSUE THREAD

**Issue by hron84** [WildBamaBoy/minecraft-comes-alive#534]
Please add a question during initial wizard (where the game asks gender and preference) to generate a house or not, since every time I face this wizard I always forgot it will generate house and house generating explodes my current base (basically it overwrites all existing blocks within the range of the house). 

Usually, I do not play with this mod too much, but some modpacks are prefer to include it and the house generation should be mentioned in the wizard somehow to inform ppl those do not know this mod what will happen - and possibly provide a way to prevent exploding his current base.

**Comment by HillustratedMike36** [comment]
Second the vote.
