### ISSUE TITLE
Installed MCA mod and now minecraft crashes when i launch a world

### ISSUE THREAD

**Issue by ChuckHoss** [WildBamaBoy/minecraft-comes-alive#537]
I Installed MCA 1.8-5.0.7.1 mod and now Minecraft crashes when I launch a world. What am I doing wrong? Why won't the mod take effect? Why is my forge user profile crashing when I try to launch a world.
Here are the files I used for the mod: 
Minecraft Forge Version 11.14.1.1334
RadixCore Version 1.8-2.0.5
Minecraft Comes Alive  Version 1.8-5.0.7.1
Here's what I did and what's happening:
- I placed the MCA and Radix .jar files in my "mods" folder under AppData/.minecraft/mods on my Windows 8.1 desktop.(I had added the copy of forge previously as a new profile in my Minecraft).
- If I launch the Forge user profile, I see the Mod was added. If I then try to Launch a world, it crashes and a report comes up from Minecraft saying I have to address any issues with the error to the author of the mod... they won't touch it.
- If I exit out of Minecraft, and re-launch it and choose my user profile, the worlds launch, but the mod for MCA is not applied.
- Also, on versions, I noted that when lauching with my user profile the title bar reads "Minecraft 1.8.8". When Launching with the Forge profile the title bar of the window reads "Minecraft 1.8".  The version of the Minecraft Launcher reads "minecraft Launcher 1.6.44.

Please Help.
Thanks,
Chuck

**Comment by WildBamaBoy** [comment]
Use a new world, if loading an existing world with MCA for the first time, you'll likely crash.
