### ISSUE TITLE
Villagers

### ISSUE THREAD

**Issue by ChrissRR** [WildBamaBoy/minecraft-comes-alive#541]
How can i change it so there will also spawn normal villagers?

(I have a issue with the Witchery mod & MCA, the guards will lay down on a bed but still walk. So maybe that will fix it. but when u have another fix pls tell me)

**Comment by Orange1861** [comment]
Cough cough config.

**Comment by ChrissRR** [comment]
That wont help it, they will still lay down on a bed and walk

**Comment by Orange1861** [comment]
Set config to overwrite original villagers to false.
