### ISSUE TITLE
"You already have a baby." bug?

### ISSUE THREAD

**Issue by fishmealx** [WildBamaBoy/minecraft-comes-alive#543]
I tried to place a baby in creative mode, but I never saw it actually spawn, though the item was removed from my inventory. After that I tried to make a new one and saw the above message. After my wife died in a tragic RPG "accident" I tried with a different NPC with the same message. I saw that this issue was posted and closed as "old," so I thought I'd repost it.

**Comment by WildBamaBoy** [comment]
Use a priest and select "Reset Baby" when this happens.
