### ISSUE TITLE
NPC's names and phrases not working

### ISSUE THREAD

**Issue by red3dred** [WildBamaBoy/minecraft-comes-alive#550]
So, i have been making a personal modpack for me and a couple friends and, upon building and joining the server with the latest version of the mod, something weird happened...

All NPC's are named "name.female" or "name.male";
All their phrases are in such manner: title.nonrelative.female: adult.greeting;

Its quite odd really, both our clients have the same version as the server, is there some bug with a language config? Is there even such a option?

**Comment by WildBamaBoy** [comment]
Did you make any modifications to MCA? What language are you using in-game?

**Comment by WildBamaBoy** [comment]
Actually just found it. Deploying fix.

**Comment by red3dred** [comment]
Game was set to English as normal, but servers have no language setting... The only modifications i did were the story progression timer.

**Comment by WildBamaBoy** [comment]
Fixed in MCA v5.1.0.1
