### ISSUE TITLE
Missing textures for Whistle, Tombstone and Villager Editor

### ISSUE THREAD

**Issue by mezzodrinker** [WildBamaBoy/minecraft-comes-alive#553]
In the latest version (5.1.0.1 for 1.7.10), the items `Whistle`, `Tombstone` and `Villager Editor` have missing textures, so their displayed texture are the common magenta-black checkered squares.

This issue was reported on the Minecraft Forum by EnderYuuko. For further questions, please reply to [this post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-0-7-1-mc-1-8-1-7-10-loved?comment=16311).

**Comment by HillustratedMike36** [comment]
(#436) known, (#477) known, (#409) and known.

A commit (commit/https://github.com/WildBamaBoy/minecraft-comes-alive/commit/13b3ccab421684a4bbc76edcb6904eb790b89734) has been applied for this, yet it worked for a older version (last time I think 5.0.7).

All I can say is that this is a regression. My suspicion looks towards RadixCore, which in MCA 5.1, requires a newer version.

**Comment by WildBamaBoy** [comment]
Fiddlesticks.
