### ISSUE TITLE
Villagers turning invisible when in unloaded chunks

### ISSUE THREAD

**Issue by mezzodrinker** [WildBamaBoy/minecraft-comes-alive#554]
When a chunk gets unloaded, some villagers inside it may turn invisible when the chunk gets loaded again. For example, their lines can still be read in the chat even though they're nowhere to be found.

This issue was reported on the Minecraft Forum by Mr_Killer01. For further questions, please reply to [this post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-0-7-1-mc-1-8-1-7-10-loved?page=804#c16250).

**Comment by WildBamaBoy** [comment]
Can't seem to reproduce this. Anyone experiencing this problem should log out of the game and log back in.
