### ISSUE TITLE
Villager trades do not advance

### ISSUE THREAD

**Issue by mezzodrinker** [WildBamaBoy/minecraft-comes-alive#555]
Villagers' trade offers do not advance when MCA is installed. Confirmed with only MCA and RadixCore installed.

This issue was reported on the Minecraft Forum by Allmynicksaretaken. For further questions, please reply to [this post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-0-7-1-mc-1-8-1-7-10-loved?page=805#c16276).

**Comment by WildBamaBoy** [comment]
Could not reproduce on latest MCA.
