### ISSUE TITLE
Wife appears to beholding a baby

### ISSUE THREAD

**Issue by TNTiger** [WildBamaBoy/minecraft-comes-alive#557]
My wife appears to be permanently holding a baby girl, even though I removed it from her inventory and she is grown up.

**Comment by HillustratedMike36** [comment]
Screenshots...?

**Comment by TNTiger** [comment]
![2015-11-13_17 12 35](https://cloud.githubusercontent.com/assets/15675285/11152693/f6cd9310-8a2b-11e5-93b9-ef1a1a02eb1e.png)
![2015-11-13_17 12 42](https://cloud.githubusercontent.com/assets/15675285/11152694/f6cf239c-8a2b-11e5-89a6-01c1ceb1901a.png)

**Comment by TNTiger** [comment]
Here /\

**Comment by WildBamaBoy** [comment]
Fixed in 32a8093ad6390cf41520d1e28d82fa9876b5b21d
