### ISSUE TITLE
Can't play Lan. Please help!

### ISSUE THREAD

**Issue by TheEpicNerd014** [WildBamaBoy/minecraft-comes-alive#560]
I'm trying to play a Lan with my friends but after we use the orb and we try to connect. It says "A fatal error has occurred, this connection is terminated" We all have MCA 1.8-5.0.7.1. + RadixCore-1.8-2.0.5 + MrCrayfishFurnitureModv3.5(1.8). We are all running forge-1.8-11.14.1.1354.

**Comment by TheEpicNerd014** [comment]
I also can't get the forge that MCA has listed. When I try to install it I get a windows error with the code being 0x80070057

**Comment by mezzodrinker** [comment]
I'd suggest providing a client/server log.

**Comment by TheEpicNerd014** [comment]
What is that? And how?

**Comment by mezzodrinker** [comment]
You should post the contents of your Minecraft launcher's Development Console to [Gist](https://gist.github.com/), [Pastebin](http://pastebin.com/) or a similar service.

**Comment by TheEpicNerd014** [comment]
Will that fix it???

**Comment by mezzodrinker** [comment]
No one said posting a log would fix your problem. It just helps the developers to hunt down your issue.

**Comment by TheEpicNerd014** [comment]
OK

**Comment by TheEpicNerd014** [comment]
How do I find the content I need???

**Comment by wi-ta** [comment]
TheEpicNerd014:
"I get a windows error with the code being 0x80070057"

Sounds to me like the copy error I did get last year.
https://www.youtube.com/watch?v=ORkxtSwzJ2I
Please read the description.
