### ISSUE TITLE
Mod won't show In-Game

### ISSUE THREAD

**Issue by RejectedVintage** [WildBamaBoy/minecraft-comes-alive#565]
So, I downloaded forge and everything downloaded smoothly but..
It says the mod is in minecraft, Im using the "Minecraft comes Alive" for a
trial and the villagers are the same.
So, the mod is in minecraft (I.e. says 4 mods active) but it wont appear in
the game itself

**Comment by wi-ta** [comment]
Hey there 
Did you right click the orb in the beginning ?

**Comment by WildBamaBoy** [comment]
See above, sounds like a bad install.
