### ISSUE TITLE
Several villager texturing issues

### ISSUE THREAD

**Issue by jchoi071** [WildBamaBoy/minecraft-comes-alive#566]
Specifically, villagers of professions Butcher and Child (I can't think of the others right now) don't display textures, and when I try to select one, the game crashes. Also, some villager professions don't seem to support custom textures (for example, Farmer and Librarian) while others do (Baker and Guard). I am using the latest version of MCA (5.1.0.1) and RadixCore (2.1.0).

**Comment by WildBamaBoy** [comment]
Did you update and use the updated MCA on an existing MCA world? Or was this a new world?

**Comment by jchoi071** [comment]
Both.

**Comment by WildBamaBoy** [comment]
Did you try the latest update (released today)?

**Comment by WildBamaBoy** [comment]
No response, closing
