### ISSUE TITLE
Server Crashing. "Ticking entity"

### ISSUE THREAD

**Issue by DarkMalady** [WildBamaBoy/minecraft-comes-alive#567]
Occaisionally my small server crashes. there are only 2-3 players, and we aren't ever doing anything specific, just hanging about the Villiage. 
Crash log. 
http://pastebin.com/6Gzs7u8i

**Comment by WildBamaBoy** [comment]
This crash isn't related to MCA at all. Looks like a zombie in the world is crashing your game.
