### ISSUE TITLE
skins

### ISSUE THREAD

**Issue by bpocnitura** [WildBamaBoy/minecraft-comes-alive#569]
Skins are to village or to medievale, I have a modpack, with some features with aren't in todays days.

Add some modern skins, and put thinks in the villagers house, somethink like beds, furnaces, etc

**Comment by HillustratedMike36** [comment]
This is for issues. But I actually do like your point on some more objects in the village generation, like premade villager beds, and furnances...like 1-2 beds and a furnace per household.

**Comment by WildBamaBoy** [comment]
Not an issue, closing this. Keep in mind you can change the skins at will.
