### ISSUE TITLE
Bug- Villager names and gui in code

### ISSUE THREAD

**Issue by anonomouse13** [WildBamaBoy/minecraft-comes-alive#571]
Firstly, the villager names are buggy both in the chat and the ones above their heads, they say tile.nonrelative.female or tile.nonrelative.male. Most of the text in the mod is like this. MCA version: 1.7.10-5.1.1.0 Minecraft Version: 1.7.10Forge10.13.4.1566-1.7.10
Screenshot:
![2015-11-21_09 20 25](https://cloud.githubusercontent.com/assets/15954229/11317755/58df8198-9031-11e5-8972-755ffa167932.png)

**Comment by HillustratedMike36** [comment]
Are you only running MCA/RadixCore...? If so, I have no idea. If not, try removing the other mods and run MCA/RadixCore independently.

**Comment by anonomouse13** [comment]
I tried to run it with only MCA and Radix Core, but when I tried to generate a new world it said "Shutting down internal server" and then crashed minecraft and nearly crashed my computer. The only other mod is *java legacy fixer* which allows me to run forge on java 8. Here is the log:

[fml-client-latest.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/41009/fml-client-latest.txt)

**Comment by WildBamaBoy** [comment]
Are you playing Minecraft in any language other than English?

**Comment by anonomouse13** [comment]
No, only in English and with no resource packs.

**Comment by HillustratedMike36** [comment]
Are you running any other mods...?

**Comment by anonomouse13** [comment]
No, non other than java legacy fixer.

**Comment by WildBamaBoy** [comment]
Switch your language to English (US) and restart. Does that solve the problem?

**Comment by WildBamaBoy** [comment]
Discuss in #575
