### ISSUE TITLE
kid riding horse bug

### ISSUE THREAD

**Issue by wi-ta** [WildBamaBoy/minecraft-comes-alive#573]
![kid riding horse bug](https://cloud.githubusercontent.com/assets/11215905/11456604/8c3bfaf4-968e-11e5-914b-7593d67ae5dc.jpg)

MC 1.7.10
Forge 1558
MCA 5.1.1.0

**Comment by DNDarkness14** [comment]
Well, does this event causes something horrible to happen? Such as A.I bugging and others. Or this is just a position glitch.
