### ISSUE TITLE
Broken Names

### ISSUE THREAD

**Issue by DNDarkness14** [WildBamaBoy/minecraft-comes-alive#575]
As I've freshly downloaded those mods (The latest MCA and RadixCore in 1.7.10 version). I have noticed that any item name or villagers' name become just like this (This has been issued in an another user's post):
![screenshot_3](https://cloud.githubusercontent.com/assets/13232677/11611309/b246dbc4-9c01-11e5-8a6f-36470f0d6c42.png)
And their broken dialogue:
![screenshot_4](https://cloud.githubusercontent.com/assets/13232677/11611317/11e2f662-9c02-11e5-956d-376c44c3e923.png)
It says either title.nonrelative.male/female depending on their gender. And here are the pics. of the broken item names and including the categories, too.:
![brokenname1](https://cloud.githubusercontent.com/assets/13232677/11611313/e536f280-9c01-11e5-96c7-11cbbc135dea.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/13232677/11611314/e81e2e14-9c01-11e5-85c4-5019b39234bb.png)
And the outfit changer stayed its description unharmed but its name is broken, too:
![screenshot_2](https://cloud.githubusercontent.com/assets/13232677/11611319/3eea7f36-9c02-11e5-9060-a3a79b517737.png)
And a horrible side effect where if I spawned a villager. Tons of lag hits the game. But survivable.

**Comment by WildBamaBoy** [comment]
Are you able to provide a full client-side log up until the main menu? I can't seem to reproduce this problem.

**Comment by DNDarkness14** [comment]
I can't provide it. But, this happened as I've updated the old MCA and RadixCore with the latest one, with the settings changed.

**Comment by Orange1861** [comment]
Are you using English?

**Comment by DNDarkness14** [comment]
Yes, I'm using English and not using any other languages.

**Comment by WildBamaBoy** [comment]
Is it US English or something else? Try English (US) and restart the game.

**Comment by anonomouse13** [comment]
I have tried it in English and it didn't work

**Comment by anonomouse13** [comment]
I tried that and when I did it , it said 'Building terrain' then it said 'Shutting down internal server' and then crashed.
Here is the log:
[fml-client-latest-log.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/67524/fml-client-latest-log.txt)

**Comment by WildBamaBoy** [comment]
Nothing interesting in the log...can you try the latest version on 1.8 and see if that still causes a problem?

**Comment by WildBamaBoy** [comment]
Closing, no response.
