### ISSUE TITLE
Technical bug; Cannot change my MCA NPC Skin files due to not having required files for the eddit

### ISSUE THREAD

**Issue by BlueGolisano** [WildBamaBoy/minecraft-comes-alive#578]
Basicaly, my files don't have the right one containing the MCA setup, using 5.1.1.0 Universal for MC 1.7.10. They're either not generating the files or they were magi-deleted? Checking other areas as well.

**Comment by BlueGolisano** [comment]
*Note: just doubble-checked the files, they haven't appeared. System error on the mod?

**Comment by WildBamaBoy** [comment]
I don't really understand what you mean. To change MCA's skins, see the bottom of this page: http://www.radix-shock.com/mca--faq.html

**Comment by BlueGolisano** [comment]
The pathway used (assets/mca/textures/skins/) does not appear to be there, and I downloaded the .jar file.
Full pathway; C:\Users\[Censored; User name]\AppData\Roaming\.minecraft\assets
at this point, I have only 4 files available, spelling is accurate.
indexes; objects; skins; virtual;

**Comment by mezzodrinker** [comment]
MCA's assets are not placed in `.minecraft/assets/`. They are contained in the mod's `.jar` file. Open it with an archiver of your choice.

**Comment by BlueGolisano** [comment]
okay welp... frak. Got a free one? xD
