### ISSUE TITLE
Children Frozen.

### ISSUE THREAD

**Issue by xXLunarEmeraldXx** [WildBamaBoy/minecraft-comes-alive#579]
I'm on the latest version, the 1.7.10 one,
And I've been having this issue for a while now.
Once my children, or let's just say, ANY children in the mod turns '5' they stay completely still and will not move for the rest of the session. not even if the child becomes full grown.
I find this annoying, and quite boring as i wanna be able to play around with my children.
Yes, I've tried making them follow me and then move freely, but it doesn't work
Is this just only a problem i have?

**Comment by WildBamaBoy** [comment]
Can't seem to reproduce this issue as of now. Try on a new world, and make sure you're still up to date.

**Comment by joshihobbit** [comment]
Hi, I have this problem too and it happens on every world. After my kid grows up, he/she stays frozen even if he/she is on "move freely" mode. Actually on one of my worlds, my son just moves a few steps after waking up and then he stops and stays frozen.
