### ISSUE TITLE
Re-Working cosmetic skins causes "Headpice" to be a giant block of white

### ISSUE THREAD

**Issue by BlueGolisano** [WildBamaBoy/minecraft-comes-alive#581]
![2015-12-12_14 14 24](https://cloud.githubusercontent.com/assets/16262925/11764182/e029a994-a0da-11e5-8b27-a1e56a195e1e.png)
Basicaly, I'm trying to rework the MCA skins so I have a coustom look/feel to it, but the system is being a little shat and making this happen.

**Comment by WildBamaBoy** [comment]
You're not saving the skins with transparency, causing any area without a skin to be white.
