### ISSUE TITLE
Family goes Missing

### ISSUE THREAD

**Issue by ShadowSlayer635** [WildBamaBoy/minecraft-comes-alive#582]
While i was playing a modpack on the ATLauncher, i noticed a strange bug right after i had joined my server... My whole family was missinng (Wife, Son, Daughter) I had assumed they had all died but that wasn't the case. When i tried to get re-married, it already said i was married to my wife who had gone missing. So i tried using a whistle and it didn't work. So i think this is a bug in the mod.

**Comment by WildBamaBoy** [comment]
Probably using an older version. I can only fix the most up-to-date versions.
