### ISSUE TITLE
Dimension Whitelisting Turned off?

### ISSUE THREAD

**Issue by DraksterAU** [WildBamaBoy/minecraft-comes-alive#584]
Hi There,

It'd be great if we can turn off dimension whitelisting (or switch it to blacklist mode!?) .... because at present if I have a multiworld server (which has 40+ worlds and growing through player interaction) It is really hard to auto-whitelist all of them....

The amount of worlds is nothing scary... we just limit world sizes to 250-500 blocks a piece. and use stargates to go between :)

**Comment by WildBamaBoy** [comment]
I'll make sure this is possible.

**Comment by DraksterAU** [comment]
Appreciated man!! :)

**Comment by DraksterAU** [comment]
Awesome!!!! 1.7.10 too! :D (We use cauldron, stuck there haha)
