### ISSUE TITLE
MCA villages not rendering skin

### ISSUE THREAD

**Issue by KotetsuZen** [WildBamaBoy/minecraft-comes-alive#585]
I have Minecraft 1.7.10 and moded with all latest release of MCA with the RadixCore and latest version of forge. With OptiFine_1.7.10_HD_U_C1 MCA villages where completely invisible.

**Comment by WildBamaBoy** [comment]
Can't reproduce this. Try a fresh reinstall of everything. If it continues, show your client log.

**Comment by KotetsuZen** [comment]
Thank you for your help. I found out that AnimationAPI-1.7.10-1.2.4 was
causing the issue.

Thank you so much for putting in the time to make this mod! I been a long
time fan!
