### ISSUE TITLE
Blank Screen?

### ISSUE THREAD

**Issue by RubiksDude19** [WildBamaBoy/minecraft-comes-alive#588]
I used your automatic downloader, then I opened minecraft under the new profile. I selected MCA and 1.8 when doing that. When I opened minecraft it did what forge normally does, then the screen just goes all white. I've tried restarting it a few times but to no avail. Plz help

**Comment by RubiksDude19** [comment]
Btw I have an hp Pavilion with an amd A10 processor and windows 10

**Comment by WildBamaBoy** [comment]
Can't reproduce any issues with this, I'm afraid. Reinstall Minecraft, Java, all that stuff, and try again.
