### ISSUE TITLE
Glitch Found

### ISSUE THREAD

**Issue by AmieStruggles** [WildBamaBoy/minecraft-comes-alive#589]
So my friend was on the Official MCA server (shewolfdeadly) and she died and respawned and got all her stuff then she stop playing for 2-4 minutes then she got kicked for being AFK for longer then 10 minutes then when she logged back on all her armor , wepons , tools , blocks and etc. was gone out of her inventory . Is this something to do with the server messing up or is it a glitch ? Quick reply would be appreciated.

**Comment by WildBamaBoy** [comment]
This page is not for support on the MCA server.
