### ISSUE TITLE
glitch with villagers

### ISSUE THREAD

**Issue by mrossama8** [WildBamaBoy/minecraft-comes-alive#591]
when i look at any (i really mean that) villager everything around him turns into invisible blocks

photo:
![robby the villager glitch](https://cloud.githubusercontent.com/assets/16476886/12035049/9b2763c8-ae49-11e5-8993-6041d93e988f.png)

but if i open his menu the glitch will go away untill i close it,also looking at him from glass dosent do a glitch, please tell me how to fix the solution because i really love the mod.

**Comment by mrossama8** [comment]
the skin gets messed up too

**Comment by WildBamaBoy** [comment]
Caused by Damage Indicators.
