### ISSUE TITLE
Skin Resizing

### ISSUE THREAD

**Issue by sithalo** [WildBamaBoy/minecraft-comes-alive#592]
Skins need to be converted from 64x64 to 64x32

is there some program or site or such that can select and resize multiple mc skins to 64x32 without having to doit one at a time? im wanting to add a large amount of new skins into the mod and its bad enough having to rename them all one by one lol especially with having to make sleeping versions of them all as well.

but if theres some way to resize a number of images in one ish go that would be very helpful

**Comment by WildBamaBoy** [comment]
This page is for bugs only, not questions. Sorry!

**Comment by sithalo** [comment]
oh sorry it said issue so for some reason i guess i thought it meant any issue sorry to bother solved anyway ;-;
