### ISSUE TITLE
Crash with Infected Villagers

### ISSUE THREAD

**Issue by AmmolS** [WildBamaBoy/minecraft-comes-alive#596]
Minecraft will crash after a number of villagers become infected by zombies.

Here's the crash report:
http://pastebin.com/jLcgg16Y

To reproduce the issue:
1. Spawn in about 10+ villagers
2. Spawn in about 10+ zombies
A few seconds after the zombies attack the villagers and begin infecting them, the game will crash.

Sometimes the issue won't occur at first, but will occur the second time if you try it in another area on the same world. Also, try playing on hard.

Tested with:
Minecraft - 1.7.10
MCA - 5.1.1.1
RadixCore - 2.1.1
Forge - 10.13.4.1558

**Comment by WildBamaBoy** [comment]
Appears to be caused by zombie AI, not MCA.

**Comment by AmmolS** [comment]
Thanks for looking in to it.
Is there any fix to this without disabling the infected villager feature? It appears that disabling it in the config fixes it. It's also worth mentioning that I had no other mods installed.
