### ISSUE TITLE
Problem running on Minecraft 1.8.9

### ISSUE THREAD

**Issue by aapena22** [WildBamaBoy/minecraft-comes-alive#597]
I'm getting the following message after the installation of MCA-1.8-5.1.1.1-universal and RadixCore-1.8-2.1.0-universal in the mod folder:

Forge Mod Loader has found a problem with your minecraft installation 
The mod listed bellow does not want to run in Minecraft version 1.8.9
Minecraft Comes Alive (MCA) wants Minecraft [1.8,1.8]
The file 'ForgeModLoader-client-0.log'contains more information

**Comment by mezzodrinker** [comment]
Apparently you can't run this mod on 1.8.9. Try it with 1.8.8 and below.

**Comment by aapena22** [comment]
ummm. Any future update in mind?

**Comment by mezzodrinker** [comment]
I'm not a developer, just a person who pretends to know quite much about this mod.

**Comment by aapena22** [comment]
I have a licensed version for windows, in minecraft website I don't see where download a previous version for windows. Any idea?

**Comment by mezzodrinker** [comment]
Install Forge for 1.8.8 or below, maybe?

**Comment by aapena22** [comment]
Nope. I tried several versions without success. Thanks for you help.

**Comment by WildBamaBoy** [comment]
You must use the base version of Minecraft 1.8. Currently no update is planned, as there's only 20 something mods that have updated thus far. Not really any benefit to updating, either.

**Comment by WildBamaBoy** [comment]
If in doubt, use the installer at the bottom of this page: http://www.radix-shock.com/mca--download.html
