### ISSUE TITLE
Zombie Villager Cause Crash

### ISSUE THREAD

**Issue by RebelProudGaming** [WildBamaBoy/minecraft-comes-alive#598]
The Villagers crash when ever they become infected. Works fine until they are turning into a zombie, is this a conflict of other mods i have or a problem? http://pastebin.com/9dYKZVV4

**Comment by rob5251** [comment]
Just had the same issue on my server.
http://pastebin.com/yvXQ0ExD

**Comment by RebelProudGaming** [comment]
Wounder what causes it.

**Comment by RebelProudGaming** [comment]
Before called a server only problem this is client side also.

**Comment by AmmolS** [comment]
I'm also having the issue and I already reported it before. WildBamaBoy says it's caused by the zombie AI.
https://github.com/WildBamaBoy/minecraft-comes-alive/issues/596

**Comment by RebelProudGaming** [comment]
So because he says it's the zombie AI and not the mod hes not going to fix it?

**Comment by WildBamaBoy** [comment]
It's the zombie AI, not really much I can do. You'd have to disable infection if it's causing this issue.

**Comment by RebelProudGaming** [comment]
It must have worked before if you added this function into the game. Is there an alternative to zombies that infects villagers instead of killing them right off?
