### ISSUE TITLE
Villager Trading does not level-up

### ISSUE THREAD

**Issue by Sabelo2000** [WildBamaBoy/minecraft-comes-alive#599]
MCA Villagers do not open new trades after interactions.  Specifically, I tried three separate "blacksmith"-class villagers, maxxed-out their Coal trades several times each and then purchased their initial goods 8 or 9 times each.  None of the 3 villagers opened any further offerings after all of these trades.

This was a brand-new world, with only RadixCore and MCA running.  I deleted the Config file since that has fixed issues with other mods, and tried again with another new world using only RadixCore and MCA, and received the same results.

**Comment by WildBamaBoy** [comment]
MCA and Minecraft version

**Comment by Sabelo2000** [comment]
RadixCore 1.8 2.1.0-universal
MCA 1.8.5.1.1.1
MC 1.9
Forge 11.14.3.1450

**Comment by Sabelo2000** [comment]
As a tangent to the above issue: when the villager's trade "maxxed-out" and the red X appeared (in this case, Coal for Emeralds), I clicked the Coal to remove it from the UI, and the villager automatically completed as many trades as it could using the remaining balance.  For instance, 18 coal for 1 emerald, I have 40 coal left when the red X appears.  I click my 40 coal, the villager automatically concludes 2 more trades (36 coal for 2 emeralds) and I am holding 4 coal to return to my inventory.

**Comment by Galindorf** [comment]
I had this problem until I told a villager to "move freely." I was setting up shops with different types of villagers, so I told them "stay here" to keep them safe and in the house I wanted. I couldn't figure out what was going on. Telling them to "stay here" seems to freeze them in a way, including updating trades. See if that helps you!

**Comment by Febilian** [comment]
Just gonna say, my villager's trades don't update, and they've been set to "move freely" most of the time, so I don't think them staying in one place is entirely the issue. I'm using the 1.8.9 version.

**Comment by Galindorf** [comment]
Yep, I updated to the new version and can confirm the won't update or open for me either. (1.8.9)

**Comment by Galindorf** [comment]
*the trades

**Comment by WildBamaBoy** [comment]
Fixed in 5a5d3a452ca76cfd56d7a4857517be9ae063d0dd
