### ISSUE TITLE
Add option to remove genders? :)

### ISSUE THREAD

**Issue by magnusjjj** [WildBamaBoy/minecraft-comes-alive#600]
Hi!

We are currently running a crundeecraftserver for a very, uhm, trans-inclusive community. Is there any possibility of being able to remove genders? :)

It's just a bit iffy inviting trans people to join the server and instantly ask them their gender and sexual orientation ;). Granted, its the characters gender, but still. 

I found the setting to disable the crystal balls, and you are able to disable the breasts of villagers, which kindof almost solves the problem? :)

Is it possible to set all NPC's, players, to a certain gender and mark them all as bisexual? I could code a server-side plugin for it if there are, say, any proper API's for interacting with the new villagers? :)

**Comment by magnusjjj** [comment]
Oh, and it looks like https://github.com/WildBamaBoy/minecraft-comes-alive/blob/eadeed01fdb7df8ad836ba2914e2e8d3d5a580a1/src/main/java/mca/util/MarriageHandler.java on line 99 might have an issue if both players are female? :)
Can't really find any reference to code relating to the dominant flag though?

**Comment by WildBamaBoy** [comment]
The line you're referring to sets the dominant progressor for the story progression AI. If no male is involved, it's not even necessary for the AI to run as it simulates the couple having children. There would be no dominant progressor (the male)

Unfortunately, I'm not willing to just remove the genders from all players and NPCs, or create an "either one" gender.  Being male or female is an integral part of the mod and how it behaves both now and in future versions.

**Comment by magnusjjj** [comment]
Just curious, but why? :). I get that you still want genders in there, since its obvious from the source that you put in a ton of work into it (and villagers can have boobs! yay!). But what would it break? The cows are genderless. The chickens are genderless. The horses are genderless. Heck, even Steve was supposed to be genderless (http://www.engadget.com/2012/07/29/notch-minecraft-occupies-a-genderless-world-even-for-that-guy/). And the villager pairs off into couples..

Also, the code listed still runs? I can't actually find a line that compares the genders when going player -> player.

Eh, might take a stab at it regardless. Fork away~.

**Comment by WildBamaBoy** [comment]
Any fork that removes genders will not be merged. The basis of MCA is to add genders...sorry! It's not happening.

Just an example, soon you'll be able to specify  villagers as being related to you, like making them your mother, brother, uncle, whatever you want. That doesn't really work well in a genderless/100% bisexual world. MCA also relies on the gender for a few different functions now, and as above more soon.

Finally, the gender is also a boolean, true or false. I can't make it something in between, nor am I willing to make the numerous changes necessary to support that.

**Comment by magnusjjj** [comment]
I couldn't actually find anything except those lines referencing either the gender, or the dominant variable apart from a 'questline' thing, a few strings, and skin selection.

So me and a few other players tested it out. Turns out, males can have kids with males. Males can even have kids with players that have not selected a gender yet. So, apart from some.. strings... its already gender-neutral player-wise. So... yay, i guess? Adding a new translation that is gender neutral is way easier than actually needing to fork or bytecode inject :').
