### ISSUE TITLE
License prohibits forking for non-paying users...

### ISSUE THREAD

**Issue by magnusjjj** [WildBamaBoy/minecraft-comes-alive#601]
"Neither it, its source code, nor its byte code may be modified and recompiled for public use by anyone except us"

This part actually prohibits public forks via the fork button, which for non-paying github users makes it a bit more difficult to contribute :). Might consider adding an exception? :)

**Comment by WildBamaBoy** [comment]
This means that while you CAN create forks and submit pull requests, you can't recompile and distribute your changes to the public.

**Comment by magnusjjj** [comment]
"However, modified code that has not been merged into the publically available build cannot be redistributed to the public in any form with no exceptions."

From the LICENSE file :)

**Comment by WildBamaBoy** [comment]
Redistribution constitutes compiling the mod and uploading it for the public to use. It can sit in your forked repository for eternity, but if you want to release it, submit a pull request.

**Comment by magnusjjj** [comment]
The second line, that i quoted there, is *only* about source code. If i fork your repository (and i have), and its public (which it is, since i don't pay for github, and thus can't make it private), the source is released to the public per default :). Will come up in a google.

Probably not an issue? :)

**Comment by WildBamaBoy** [comment]
^ should make it clearer now.
