### ISSUE TITLE
villagers won't spawn on a sponge server

### ISSUE THREAD

**Issue by kboney11** [WildBamaBoy/minecraft-comes-alive#602]
Not sure if this is MCA's issue or spongeforge's issue. I have a server with MCA (version 1.8.5.1.1.1) and Radix core 1.8.2.1.0. plus several more mods. When I have sponge installed (version 3.1.0BETA 1025) the babies won't grow nor can I place male or female villagers. When I take sponge off everything works fine. Could this issue be one that needs to be fixed on your end or sponge's end?

snippet from log: skipping entitiy MCA-humand with id EntityHuman [java.lang.Throwable$WrappedPrintStream.printIn:748]

startup log pastebin: http://pastebin.com/z64TqzkP

**Comment by WildBamaBoy** [comment]
Looks like something on Sponge's end, but I can't be certain. Unfortunately I don't have plans to support Sponge at this time.

**Comment by simon816** [comment]
Just commenting here to say that this was a Sponge issue that I have now fixed

https://github.com/SpongePowered/SpongeCommon/commit/d07457a7b552919581595649bb7e2767d8e92e88
https://github.com/SpongePowered/SpongeForge/commit/38925a90ce6ad417abd45a0d71b5eee2bbd9f32e

@kboney11 SpongeForge 1297 and later should work,
