### ISSUE TITLE
villagers won't spawn on a sponge server

### ISSUE THREAD

**Issue by kboney11** [WildBamaBoy/minecraft-comes-alive#603]
Not sure if this is a MCA issue or spongforge issue. I have a server with MCA ( version 1.8.5.1.1.1) (radix core version 1.8.2.1.0) and several other mods. When I have spongeforge ( version 3.1.0 beta 1025) installed I can't spawn villagers and babies won't grow up. When I take sponge off I am able to spawn them and the babies are able to grow. 

snippet from startup log : 08.01 09:43:55 [Server] Server thread/WARN Skipping Entity with id MCA.EntityHuman
pastebin of log http://pastebin.com/z64TqzkP

**Comment by WildBamaBoy** [comment]
Answered in #602
