### ISSUE TITLE
Fatal Error has Occured

### ISSUE THREAD

**Issue by ccmarshall** [WildBamaBoy/minecraft-comes-alive#604]
My daughter is playing a game of minecraft and opens the lan so my son can join on his computer but my son gets a message of A Fatal Error has occurred.  We just added these mods to their computers today and they were able to play multiplayer before.  Any suggestions?  If you tell me what you need and how to find it on the computer then I can probably figure it out. Thanks!

**Comment by WildBamaBoy** [comment]
MCA does have issues on LAN. These will hopefully be resolved in the next update.
