### ISSUE TITLE
Villagers disappearing

### ISSUE THREAD

**Issue by Dvx105** [WildBamaBoy/minecraft-comes-alive#605]
Hello,

I have noticed that my villagers have been constantly disappearing over the last several days. They don't seem to die, or just wander off - they just vanish without a trace. This seems to happen especially when I am away from the village. Additionally, for some reason, every time a villager disappears, a new guard just shows up out of the blue.

For example, I first noticed this when I was trying to get one villager's popularity up so I could marry them. I went away to do some chores, and when I came back, they had disappeared and a new guard had reappeared. A while later, I left again, and when I returned, four other villagers had disappeared and several new guards had replaced them.

**Comment by Dvx105** [comment]
This happened again, on a different world. I left a village for several hours, and when I returned the village was populated almost entirely with guards. The gamemode was set on peaceful so it was unlikely that they were killed, and that would not explain the huge increase in guards.

I use Minecraft version 1.8 and MCA version 5.1.1.1.

**Comment by Krhymez** [comment]
I am also having this issue on a server. The NPC just seem to disappear.

**Comment by WildBamaBoy** [comment]
Will review this, though I'm not seeing any reasons why they would despawn other than death.
