### ISSUE TITLE
Feature Request: Block/Item meta on Villager Gifting list

### ISSUE THREAD

**Issue by PitchBright** [WildBamaBoy/minecraft-comes-alive#609]
Can you please make it possible to customize the Villager Gifting list, utilizing block/item metadata? (It seems that the gifts in fact do not support metadata, as per my confusion in #528 )

Thanks, Bama!
-Pitch

**Comment by MentalMouse** [comment]
Also:  Where can I *find* the default gift list?  I've been poking through the source to no avail.

**Comment by mezzodrinker** [comment]
@MentalMouse https://github.com/WildBamaBoy/minecraft-comes-alive/blob/master/src/main/java/mca/core/MCA.java#L371-505

**Comment by WildBamaBoy** [comment]
Withdrawing this for an overhaul soon.
