### ISSUE TITLE
Sleepwalking guards

### ISSUE THREAD

**Issue by Dvx105** [WildBamaBoy/minecraft-comes-alive#610]
Hello,

I've noticed that over time, my guards start to fall asleep at night. Their eyes close in the "sleeping" animation and their weapons disappear. However, they still continue to walk around the area. This has happened in all of my MCA worlds so far.

This turns out to be a huge problem since the guards are unable to attack mobs and their weapons do not reappear when they wake up.

**Comment by WildBamaBoy** [comment]
MCA version?

**Comment by Dvx105** [comment]
Currently I use Minecraft version 1.8 and MCA version 5.1.1.1.

**Comment by WildBamaBoy** [comment]
This is caused when they get married due to story progression. Will review it.

**Comment by Kastafall** [comment]
Seems this issue is still somewhat here for MCA 1.10.2 version 5.2.3.  Even though im married to a guard, at night she slowly inches her way to the door even though asleep.
