### ISSUE TITLE
Feature - Pregnancy

### ISSUE THREAD

**Issue by Firestar311** [WildBamaBoy/minecraft-comes-alive#612]
Something that I would wish to see in this mod, is a "pregnancy" feature where after you procreate, there is a time for the baby to develop, and have it rendered on the correct spouse

**Comment by mezzodrinker** [comment]
So you basically want another stage which modifies the appropriate villager's model in addition to the baby (item) stage and the youth (growing) stage?

**Comment by Firestar311** [comment]
Essentially, is this possible or not? If not you can close this
If it is possible, maybe make it configurable

**Comment by mezzodrinker** [comment]
I'm not entirely sure if it's possible. By the way, I'm not even part of the development team.

**Comment by Firestar311** [comment]
I get confused, we will see what the dev team has to say though. I have seen some interesting things pulled off with mods, and some things I though impossible

**Comment by RebelProudGaming** [comment]
Seems like a good idea.

**Comment by WildBamaBoy** [comment]
Definitely possible, yeah, but as for actually rendering it and making it look nice (not to mention fitting in with all 200+ skins in the mod) would be the challenge. We're not very good modelers, so it would be up to someone else to try and make the model.

**Comment by Firestar311** [comment]
@WildBamaBoy How do you do the female breast renders? They work with normal player skins. Could you implement something like that in the code? or how do you do that? Is it a render and the code adapts?

**Comment by McChantel** [comment]
This sounds like a great idea. I'm just curious, what if the player is the mother? Would the pregnancy still alter the player model? I love the idea!

**Comment by Febilian** [comment]
I simply request, if this happens, that the visuals and/or feature itself are able to be disabled via config.

**Comment by MentalMouse** [comment]
Perhaps you should consider that it's entirely possible for two "males" to have a child in this mod.  (See also the complaint about reporting same-gender parents as "mother" and "father".)  Gender is purely cosmetic, and attempting a visible pregnancy is an unnecessary complication.

**Comment by WildBamaBoy** [comment]
This is no longer being considered due to required visuals.
