### ISSUE TITLE
NPC despawning on Server

### ISSUE THREAD

**Issue by Krhymez** [WildBamaBoy/minecraft-comes-alive#615]
Players on the server i play on are having issues with the NPC just randomly despawning.
This has caused issues with marrages and Children.

Are there any commands to get divorced/find child?

**Comment by Dvx105** [comment]
The Whistle will immediately teleport all members of your family to you, and the Divorce Papers will allow you to divorce a villager. However, if they have despawned, that's a problem. 

I am having a similar issue, the developers have not replied yet.

**Comment by Krhymez** [comment]
It appears they have despawned. Wish there was a command to divorce/remove family.

**Comment by WildBamaBoy** [comment]
#605
