### ISSUE TITLE
a suggestion about monarchy system

### ISSUE THREAD

**Issue by Anghelos92** [WildBamaBoy/minecraft-comes-alive#616]
I love your mod and I can't wait to see it completely developed. Recently I played a very good mod called "Ancient Warfare" so I thought that if you watch a video about Ancient warfare 2 you could take some ideas and inspiration from that mod For the monarchy System, I am talking about the way you can command the recruit Soldiers and archers... :) it would be awesome. Thank you For your mod and keep going!

**Comment by WildBamaBoy** [comment]
We've got plenty of ideas, no worries. :)
