### ISSUE TITLE
What about a relation system between the villagers?

### ISSUE THREAD

**Issue by oblisgr** [WildBamaBoy/minecraft-comes-alive#617]
For now...
Is it possible that you can build a simple relation system between the villagers?
I mean right jow the player can make 2 villagers marry each other in order to make children.
What is they deside by themselves if they like or dislike someone?
It may be done using the traits and the behaviour of each villager to give + / - among them.
So there will be villager who like others, others who may love others and some who may dislike their neightbours (why not harm them).

And even more...
This can be a future plan if you deside to add different races. 
Villagers who get the maximum + (maybe if they share the same trait) to love and marry. If they are from the same race they can get the +++ that will allow them to make family. And their children will get thats race's texture.

**Comment by WildBamaBoy** [comment]
I can't see this having a big enough effect on the gameplay to warrant its implementation. Good idea though.
