### ISSUE TITLE
NCP babies not growing up?

### ISSUE THREAD

**Issue by Arielgp2010** [WildBamaBoy/minecraft-comes-alive#618]
Hi there! I need help about a problem/bug I noticed today. To keep the village progress with my game, I made villagers get married and have babies but the problem is that NCP babies wont grow up! The babies that I have with my wife grow up well, but the NCP babies are just in their hands and never grow  up! Can anybody help me please?

**Comment by WildBamaBoy** [comment]
Ensure story progression is enabled in your configuration.
