### ISSUE TITLE
java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by JonMaker050** [WildBamaBoy/minecraft-comes-alive#620]
Crash ocassional

MCA 5.1.1.1

Minecraft 1.7.10-Forge10.13.4.1558-1.7.10

http://pastebin.com/ihkSrBhs

**Comment by mezzodrinker** [comment]
Does this issue persist if you remove MCA?

Also,  this may be related to #210 (Minecraft 1.7.10, Forge 10.13.2.1286, MCA 4.1.5) and #576 (unknown versions).

**Comment by JonMaker050** [comment]
MCA cause this crash, i remove MCA and no crash (Sorry Bad English)

**Comment by AmmolS** [comment]
Same issue as https://github.com/WildBamaBoy/minecraft-comes-alive/issues/596 and https://github.com/WildBamaBoy/minecraft-comes-alive/issues/598
Unfortunately, there's no fix for it as it's caused by the zombie AI. A workaround is to disable Infected Villagers in the MCA config file.

**Comment by WildBamaBoy** [comment]
^

**Comment by SvEgiiVEteR** [comment]
http://hastebin.com/zoturidimo.md
a similar problem
but in the log
