### ISSUE TITLE
Invisible Children?

### ISSUE THREAD

**Issue by Ginger60** [WildBamaBoy/minecraft-comes-alive#621]
I love this mod. I can't play with out it. I recently got married in the game and had a child.  They have no skin texture.  So I had another child, and the same thing happened.  When I go to try and change the skin with the Village editor, the game crashes.  How can I fix this without killing them and starting over?

**Comment by mezzodrinker** [comment]
Would you mind posting the crash report to [pastebin](https://pastebin.com)?

**Comment by Ginger60** [comment]
http://pastebin.com/8NfWYp7K

**Comment by WildBamaBoy** [comment]
Have you modified MCA in any way?

**Comment by Ginger60** [comment]
I added and replaced some skins.  But I made sure the names were in the correct format.

**Comment by Ginger60** [comment]
It seems that the child skins do not work.  However, they become visible again when I changed them from a child skin to another type of skin, like a farmer, miner, or ect.

**Comment by WildBamaBoy** [comment]
Sounds like a problem with the skins you added. Not getting any issues with unmodified MCA.
