### ISSUE TITLE
Compatibility Issue Crash

### ISSUE THREAD

**Issue by TheTimeLord161** [WildBamaBoy/minecraft-comes-alive#625]
I tried loading your mod with Optifine, Weather2, CoroUtil, and of course, RadixCore(All of the additional ones are part of the CoroUtil). Before the menu screen shows up, the mod crashes. I included the crash report so you can view it and try to find out where the compatibility lies.
[crash-2016-02-04_12.08.41-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/117882/crash-2016-02-04_12.08.41-client.txt)

**Comment by WildBamaBoy** [comment]
Are you able to run MCA and RadixCore by theirself?

**Comment by TheTimeLord161** [comment]
No. Would you like the crash report to see if you can find the issue there?

**Comment by WildBamaBoy** [comment]
Are you using the default Minecraft launcher, or something else?

**Comment by TheTimeLord161** [comment]
The regular launcher.

**Comment by WildBamaBoy** [comment]
If you change the start location, that may be your issue. Download fresh with no launcher arguments changed - should work fine.
