### ISSUE TITLE
local Lan Server?

### ISSUE THREAD

**Issue by UniqueAlien** [WildBamaBoy/minecraft-comes-alive#626]
I don't know how to make one can you tell me how to make one for free or point me in the right direction?

**Comment by mezzodrinker** [comment]
Are you talking about a LAN ("Open to LAN" in the in-game menu) or dedicated server (server running as separate program)?

**Comment by mezzodrinker** [comment]
Also, this is not MCA-related, you're better off asking Google or any other search machine (like [DuckDuckGo](https://lmddgtfy.net/?q=minecraft%20create%20lan%20server)) or the Minecraft Forums.

**Comment by UniqueAlien** [comment]
No I'm not talking about the in game lan I can't play the 1.7.10 version with friends on that one it doesn't work I need to make a local lan server on 1.7.10 MCA but I can't find out how.

**Comment by WildBamaBoy** [comment]
Install a Forge server (http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html), install MCA, start it using the Forge JAR, connect.
