### ISSUE TITLE
Russian and Ukrainian locales are mashed are mixed

### ISSUE THREAD

**Issue by yanpalis** [WildBamaBoy/minecraft-comes-alive#627]
Here is screenshot
![2016-02-05_18 54 28](https://cloud.githubusercontent.com/assets/15308404/12849612/99aa13be-cc31-11e5-92c5-0c9c800d3165.png)

**Comment by WildBamaBoy** [comment]
I cannot read either language - do you mean that Russian and Ukrainian are mixed together?

**Comment by yanpalis** [comment]
Yes

**Comment by yanpalis** [comment]
Im fixed it by myself(i replaced every ukrainain line that i found
). Here is it: https://www.dropbox.com/s/tlwshxh16p1em3n/ru_RU.lang?dl=0

**Comment by WildBamaBoy** [comment]
Thank you, I've updated the language files accordingly. They will be available with the next minor update.
