### ISSUE TITLE
Guards Swords suddenly dissapear

### ISSUE THREAD

**Issue by thebeast5268** [WildBamaBoy/minecraft-comes-alive#629]
Using 1.8.9 and running optifine along side.

**Comment by McChantel** [comment]
Are you sure it isn't just because the guard got married?

**Comment by thebeast5268** [comment]
All but two of my original guards suddenly lost their swords and now "sleep walk" at night. One of them spawned in that way. Is there any way I can get them to arm themselves again?

**Comment by WildBamaBoy** [comment]
Intentional when a guard gets married, but will make sure they're not sleep walking.
