### ISSUE TITLE
MCA Set Home, Follow and Stay Here Buttons are Missing

### ISSUE THREAD

**Issue by amaharra** [WildBamaBoy/minecraft-comes-alive#632]
Pretty much what the title says, I'm running a custom mod pack with MCA 1.7.10, and for some reason I'm unable to get my villagers/family to set home points/follow/stay put, as the buttons are completely missing. I'll include a screenshot for example:

![bug report](https://cloud.githubusercontent.com/assets/17240510/13037146/274d509a-d340-11e5-939c-b9effca5d5b2.png)

Could it be a compatibility issue?

**Comment by SethNations** [comment]
I'm having the same issue, MY WIFE WON'T LEAVE ME ALONE! xD

**Comment by WildBamaBoy** [comment]
Did you happen to change your username while using the same world?
