### ISSUE TITLE
My reputation and the bar to show who's married doesn't show. Help!

### ISSUE THREAD

**Issue by ScarletDogs** [WildBamaBoy/minecraft-comes-alive#634]
Please help me!

**Comment by PalomaAguirre** [comment]
That happends to me too! Help us please :(

**Comment by Selexur** [comment]
I have the same problem D:

**Comment by WildBamaBoy** [comment]
I need to know the Minecraft version and MCA version before I can do anything about it.

**Comment by RealGrep** [comment]
I have the same issue. Minecraft 1.8.9 with Forge 1755, and MCA 5.1.1.2. It has not shown up in other Forge versions either, including at least 1727, 1746, and 1754. Let me know if you need anything more. :)

**Comment by Selexur** [comment]
My minecraft version is 1.8.9    
MCA 5.1.1.2   
Forge 11.15.1.1722

If you need more information please let me know to :3

**Comment by WildBamaBoy** [comment]
:anguished: I'm dumb - a broken version of RadixCore was uploaded to Curse. Fixing that now. In the meantime, download RadixCore from our website and it'll work for you.

**Comment by WildBamaBoy** [comment]
Fix'd : http://minecraft.curseforge.com/projects/radixcore/files/2283147

**Comment by RealGrep** [comment]
Yep, that fixes it. Thanks! Much appreciated.

**Comment by ScarletDogs** [comment]
Thank you so much!!
