### ISSUE TITLE
IDEA! ~ Revamp Personalities, 

### ISSUE THREAD

**Issue by TheLunarArtemis** [WildBamaBoy/minecraft-comes-alive#635]
Revamp the Personalities!
I have no idea if this is possible or not, but... the villagers should say different things per personality.
and certain interactions should improve your relationship with certain personality types.
[The first interaction listed should be their main interaction they prefer, the 2nd is a secondary interaction]

Etc, Greedy ones by gifting, and chatting
Witty ones by joking or flirting.
Peaceful ones by chatting or telling a story. 
Athletic by telling a story, 
Friendly ones by shake hands, or chatting
Sensitive ones by hugging, or joke
Confident ones by 
Strong ones by
Curious ones by 

For an idea on Gifting, 
Different Villager types should prefer different gifts, like giving crops to farmers, ore to miners, swords and armor to guards, tools to smiths, books, bookshelves, etc to librarians and so on, so forth.

Also, make an option to upload your own skin file from your computer to villagers, via the villager editor.

And make it possible to train your child to become a certain type of villager by making them doing the certain specific chore of that job, and more xp earned, everytime they do it.
Higher the level, the more accurate the child becomes at doing that job.
Like the old chore system, except, whichever class they have the most xp in, when they grow into an adult, they should become that class, or a similar class.

**Comment by mezzodrinker** [comment]
> Also, make an option to upload your own skin file from your computer to villagers, via the villager editor.
You can already do that (read the [FAQ](http://www.radix-shock.com/mca--faq.html), heading "How do I add my own skins to the mod?"), even though it's not by using the Villager Editor.

**Comment by WildBamaBoy** [comment]
For #712
