### ISSUE TITLE
Cannot cut uncolored diamonds

### ISSUE THREAD

**Issue by xaviergmail** [WildBamaBoy/minecraft-comes-alive#636]
There currently doesn't appear to be any crafting recipe to cut the regular Minecraft diamonds using the gem cutter and a mold. All the colored diamonds work fine, however.

**Comment by mezzodrinker** [comment]
Which version of MCA, RadixCore and Forge are you using? Are you using any other mods along with MCA and RadixCore?

**Comment by xaviergmail** [comment]
I'm on Forge 10.13.4.1614  with
MCA-1.7.10-5.1.1.2-universal
RadixCore-1.7.10-2.1.1-universal

Other mods I have installed:
`aether-1.7.10-1.6
AppleCore-mc1.7.10-1.3.0
appliedenergistics2-rv2-stable-10
ArchimedesShips-1.7.1
BiomesOPlenty-1.7.10-2.1.0.1826-universal
Carpenter's Blocks v3.3.7 - MC 1.7.10
Chisel2-2.5.1.44
CodeChickenCore-1.7.10-1.0.7.47-universal
CoFHCore-[1.7.10]3.1.1-324
ComputerCraft1.75
CustomNPCs_1.7.10d
Decocraft-2.2.1_1.7.10
DrZharks MoCreatures Mod v6.3.1
Enchiridion 2-1.7.10-2.0.2a
EnderIO-1.7.10-2.2.8.381
ExtraCells-1.7.10-2.3.9b188
extrautilities-1.2.12
fastcraft-1.21
FlatSigns-1.7.10-universal-2.1.0.19
forestry_1.7.10-4.2.8.56
GardenStuff-1.7.10-1.7.0
gilded-games-util-1.7.10-1.9
TwoGraves-1710.1.1
growthcraft-1.7.10-2.4.0-complete
HungerOverhaul-1.7.10-1.0.0
industrialcraft-2-2.2.811-experimental
InventoryTweaks-1.59-dev-152
ironchest-1.8-6.0.99.749-universal
Jabba-1.2.1a_1.7.10
journeymap-1.7.10-5.1.3-unlimited
Mantle-1.7.10-0.3.2b
Mariculture-Deluxe-1.7.10-1.2.4.2a
natura-1.7.10-2.2.0.1
neiaddons-1.12.13.38-mc1.7.10
NEIIntegration-MC1.7.10-1.1.1
NotEnoughItems-1.7.10-1.0.5.120-universal
OptiFine_1.7.10_HD_U_C1
Pam's DesertCraft 1.7.10a
zPam's Harvest the Nether 1.7.10a
Pam's HarvestCraft 1.7.10Lb
ProjectRed-1.7.10-4.7.0pre12.95-Compat
ProjectRed-1.7.10-4.7.0pre12.95-Base
ProjectRed-1.7.10-4.7.0pre12.95-Mechanical
ProjectRed-1.7.10-4.7.0pre12.95-Lighting
ProjectRed-1.7.10-4.7.0pre12.95-Integration
SimplyJetpacks-MC1.7.10-1.5.3
StorageDrawers-1.7.10-1.8.0
Thaumcraft-1.7.10-4.2.3.0
twilightforest-1.7.10-2.3.7
ThermalExpansion-[1.7.10]4.1.1-237
ThermalFoundation-[1.7.10]1.2.2-111
TiCTooltips-mc1.7.10-1.2.5
TConstruct-1.7.10-1.8.8
TMechworks-1.7.10-0.2.15.106
Waila-1.5.10_1.7.10
WailaHarvestability-mc1.7.10-1.1.6
Ztones-1.7.10-2.2.1`

**Comment by mezzodrinker** [comment]
Indeed, I can confirm this. With the above setup, there is an uncolored version of the shaped diamonds but no crafting recipe for it. I do not know if this was intended (probably not).

**Comment by WildBamaBoy** [comment]
Just to make sure, is this what you mean? http://puu.sh/nC2SG/0b69cc501a.png

It does work.
