### ISSUE TITLE
Blue world bug.

### ISSUE THREAD

**Issue by Chilledsock** [WildBamaBoy/minecraft-comes-alive#638]
Dose anyone know how to fix a bug ware the world goes blue and all blocks are transparent except chests when I hover over a villager ?

**Comment by mezzodrinker** [comment]
Could it be that you also have Damage Indicators installed?

**Comment by Chilledsock** [comment]
I did not realise that would be a problem but that could be it thank you.

**Comment by mezzodrinker** [comment]
It most likely is the problem. There's quite a few reports of it causing visual bugs.

**Comment by WildBamaBoy** [comment]
^
