### ISSUE TITLE
Too many skins?

### ISSUE THREAD

**Issue by Ginger60** [WildBamaBoy/minecraft-comes-alive#640]
I like to edit my villages.  Meaning changing their skins.  Since I've played this mod for so long, I have added many skins.  In the mod, I have a total of 451 skins. I have recently just added a few more.  But now the game wont show all of them.  So my question is, how many is too many for the game to handle?
It doesn't crash my game, they just don't show up.

**Comment by WildBamaBoy** [comment]
There isn't a limit on the number of skins you can add. Make sure you've named them all correctly according to the format the rest of the files use.
