### ISSUE TITLE
Unable to Access Children's Inventory 1.8.9.

### ISSUE THREAD

**Issue by PyrxMagi** [WildBamaBoy/minecraft-comes-alive#642]
When using MCA 1.8.9 I noticed I can't access my son's inventory to give him seeds or the likes. I thought I needed to gift the item, but that's not the case.

In any way, I can't make him do any chores because I can't gie him anything to have him do chores. PLUS, the server crashes every time I try to get him to "Create a Farm."

Thanks for reading this.

**Comment by WildBamaBoy** [comment]
Did you happen to change your username?

**Comment by WildBamaBoy** [comment]
Closing for lack of information
