### ISSUE TITLE
Intangable support

### ISSUE THREAD

**Issue by mrgreaper** [WildBamaBoy/minecraft-comes-alive#645]
at the minute the mca villagers dont have souls and that makes an issue with intangable. i did report it to the intangable developer who is at this minute fixing it his end but was hoping maybe support could come in mca too so they fit seamlessly...yep i know its a lot to ask but as 1.8.9 gains popularity the two mods are gonna be used a lot, support would no doubt help

intangable issue report: http://minecraft.curseforge.com/projects/intangible/issues/48

**Comment by Firestar311** [comment]
I would also love to see this implemented, I love both mods, and again the problem with MCA replacing vanilla villagers is the no souls part. This would really help both mods

**Comment by WildBamaBoy** [comment]
Will take a look at this

**Comment by WildBamaBoy** [comment]
According to Eminoph the issue is resolved. Will take a look at more official support once he releases an API for it
