### ISSUE TITLE
[possible issue] inquiry about starvation ahoy

### ISSUE THREAD

**Issue by kotoroshinoto** [WildBamaBoy/minecraft-comes-alive#647]
http://minecraft.curseforge.com/projects/starvation-ahoy

this would impact the farming in both crops AND meat. It is likely the AI of MCA will not be able to handle the changes. I will be testing this for problematic mod interactions as soon as the starvation ahoy dev fixes his server-side meat prep crash.

**Comment by kotoroshinoto** [comment]
1. crops need to be washed to restore them to the vanilla items. (to make them use-able in recipes or cooking)

2. Animal corpses need to be hung to be skinned and then roasted on a spit. I'm not sure whether the MCA villagers will simply pick up the corpse, or if the AI would become confused at the total lack of meat items. (obviously they wouldn't know to utilize the hanger or spit)

**Comment by WildBamaBoy** [comment]
Unless the actual vanilla items are replaced (highly unlikely) there won't be a problem.
