### ISSUE TITLE
New crystal ball appears in inventory with each load

### ISSUE THREAD

**Issue by AngleWyrm** [WildBamaBoy/minecraft-comes-alive#651]
Something has gone wonky -- I have chosen to live in a village, which seems to have created just fine as far as I can tell. There's people and children have grown up to adults, so I've been playing for a while on this save.

But every time I start the game it gives me a new crystal ball, which I've resorted to creating a trash can in-game to dispose of as my first task when I play.

Is there some way to tell the mod that it's somehow forgotten or got confused?

**Comment by WildBamaBoy** [comment]
MCA version? Minecraft version? Are you playing on a server or single player?

**Comment by AngleWyrm** [comment]
MCA Version 1.5.2 for Minecraft 1.7.10, and I found out something more about this:
A new crystal ball is generated every time I restore a game in which I have not yet used a crystal ball. As soon as I use it, the duplicate crystal balls stop appearing.

**Comment by mezzodrinker** [comment]
Did you mean MCA 5.1.2 for Minecraft 1.7.10?

**Comment by WildBamaBoy** [comment]
Probably. Just to make sure, do you end up with two or more crystal balls? If you never use it, it's supposed to give you one if you don't already have one. You _must_ use the crystal ball in order to properly start the mod.
