### ISSUE TITLE
It Doesnt show Who The NPCs Are Married Do 

### ISSUE THREAD

**Issue by buddy12847** [WildBamaBoy/minecraft-comes-alive#652]
In The Old Version You  Could See Whos The NPCS Parent Or Who They are married to but now I cant see that Help

**Comment by mezzodrinker** [comment]
Which version of MCA and Minecraft are you using?

**Comment by WildBamaBoy** [comment]
You can see both in current versions by hovering over the icons that appear below their mood and personality. If they're not present, no information is available.
