### ISSUE TITLE
Crystal Ball causes problems on LAN

### ISSUE THREAD

**Issue by LeafyClone** [WildBamaBoy/minecraft-comes-alive#653]
Me and my friend have the exact same versions of MCA/RadixCore/Forge, and he can join my LAN server just fine. But as soon as someone uses the Crystal Ball, either the game will crash, or the other players will appear to not move from my perspective, but they will be moving from their perspective and Vice-Versa.

**Comment by mezzodrinker** [comment]
Which versions of MCA and Minecraft are you using?

**Comment by LeafyClone** [comment]
I am using 1.8.0, MCA 5.1.1.2 and Forge 11.14.3.1446

**Comment by mezzodrinker** [comment]
This looks like a new issue. Would you mind adding the appropriate Minecraft log and (if available) crash report?

**Comment by LeafyClone** [comment]
Here's the Log Crash-Report I got when trying to use the Crystal Ball on his LAN server.
[crash-2016-03-09_12.06.26-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/165998/crash-2016-03-09_12.06.26-client.txt)
[Game Log.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/166004/Game.Log.txt)

**Comment by mezzodrinker** [comment]
Ouch. Looks like networking madness... I doubt there's anything you can do from your side.

**Comment by LeafyClone** [comment]
Oh, I should have mentioned that in this particular Log, I started a LAN server, and when he tried to join, he got a "Fatal Error" message and was immediatly kicked. So He then decided to Host a LAN server, and I then joined without issue, but crashed when using the Crystal Ball.

**Comment by WildBamaBoy** [comment]
There's known issues using LAN at this time. Workaround would be to set up a local server instead.
