### ISSUE TITLE
Crashy Crashy Crash!

### ISSUE THREAD

**Issue by WarriorRenamon** [WildBamaBoy/minecraft-comes-alive#654]
I'm using 1.7.10 and when I used the recommended version of forge, it still crashed on the mojang screen. RadixCore version is 2.1.1. Please help!

**Comment by mezzodrinker** [comment]
Please add a crash report so that we can actually do anything about that and/or help you.

**Comment by WarriorRenamon** [comment]
[crash-2016-03-12_14.44.54-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/170598/crash-2016-03-12_14.44.54-client.txt)

**Comment by WarriorRenamon** [comment]
Just one of the crashes.

**Comment by mezzodrinker** [comment]
Did you, by any chance, extract MCA's .jar archive?

**Comment by WarriorRenamon** [comment]
No. I use Magic Launcher to load my modules.

**Comment by WildBamaBoy** [comment]
Probably caused by MagicLauncher setting a strange working directory. Not looking to add support just yet, so I'd say use an alternative like the default launcher or MultiMC.
