### ISSUE TITLE
Problems with Grandchildren

### ISSUE THREAD

**Issue by wolfie2902** [WildBamaBoy/minecraft-comes-alive#655]
So, I wanted to try and form a huge family tree, getting lots of great grandchildren, but, I got stuck at the first grandchild. I was in creative mode and I married and 'procreated' with my husband and had a girl. I changed the settings so it would take only 1 minute for the baby to grow and 3 minutes for the child to grow into an adult. She grew into an adult and I spawned in a male villager and had them get married and have a child and it all went well, apart from the fact that there is no baby. I believe that when npcs breed you can go into their inventory and take the baby out, however, although my daughter was holding the baby in her hand, when I go into her inventory, there is no baby. I orginally tried this on 1.7.10 because that's the version of forge that I had but I then tried 1.8.9 instead to see if it was just a bug, although, the problem remained in both versions. I have tried this in a survival world (Although I did change it to creative to grab rings e.t.c) and a creative world and on both, there is no baby. I have also tried with different characters too, waiting for the one minute to be up and then checking as well as checking right away. Am I doing something completely wrong or is it a bug? Also, villagers that I am not related to will hold their babies, but they won't age up. Can someone please tell me what I need to do!

**Edit: I am playing on a single player map**

**Comment by WildBamaBoy** [comment]
Villagers will not hold their children in the inventory. If having a baby was successful, they will be holding it until it grows into a child.

**Comment by TIMTOM123** [comment]
How long will it take?
