### ISSUE TITLE
Rendering When Looking at Villagers

### ISSUE THREAD

**Issue by shadycroissant** [WildBamaBoy/minecraft-comes-alive#656]
When I look at villagers, the world shows through the ground and the villagers:

![2016-03-19_17 48 35](https://cloud.githubusercontent.com/assets/17955631/13901725/fe9d7f32-edfa-11e5-856c-5f3b76e75834.png)
![2016-03-19_17 48 50](https://cloud.githubusercontent.com/assets/17955631/13901727/038a908e-edfb-11e5-92dc-6cea422bdc21.png)
![2016-03-19_17 48 44](https://cloud.githubusercontent.com/assets/17955631/13901729/0914051c-edfb-11e5-985a-6e2edcd0e460.png)

and so on. It's really distracting and quite annoying to look at a villager and the world messes up. No crashing, just this. I'm using 1.8.0 minecraft and 1.8 recommended forge. I'm using mods TooManyItems, Damage Indicators, Treecapitator, Backpack, Mr. Crayfish, Inventory Tweaks, and Xaeros Minimap. And no, it is not the texture pack, I've checked. Please help.

**Comment by WildBamaBoy** [comment]
Caused by Damage Indicators
