### ISSUE TITLE
malformed response when child can't build a farm.

### ISSUE THREAD

**Issue by MentalMouse** [WildBamaBoy/minecraft-comes-alive#660]
"Dina the Child:  I don't have enough 44.  I will need at least %a2% to create a farm."  No mention of water issues....  Version 5.1.2 on 1.8.9

**Comment by zizzle212** [comment]
Same happened with a Villager i hired in my world, Exact same versions as well

**Comment by zizzle212** [comment]
Just tested it with the 1.9 version of 5.1.2 as well. Its the same response every time i ask a villager i hire to make a farm, however they still harvest crops with no problem.
