### ISSUE TITLE
cant marry

### ISSUE THREAD

**Issue by BoomerMax** [WildBamaBoy/minecraft-comes-alive#662]
my wife died and when i try to marry someone else i cant

**Comment by Galindorf** [comment]
You may have to talk to a priest and "Divorce Spouse." If there is no priest, I'm not entirely sure what you do. My village hasn't generated a priest yet, so there's not always one available!

Also, are you SURE she's dead? She may be "lost." I lost my spouse one time while trying to travel from one area to another, I forgot to set her home point to the new village and she transported allll the way back to our house when it got dark. I had to go find her, she was too far away for the Whistle to work. 

Also, have you tried to use the Whistle to find her?

**Comment by BoomerMax** [comment]
thanks
