### ISSUE TITLE
Villager trades still not opening up? 

### ISSUE THREAD

**Issue by Galindorf** [WildBamaBoy/minecraft-comes-alive#664]
Hey all--

Just installed the newest version (MCA-1.8.9-5.1.2) and I was trying out the trades... and found they are still not leveling-up. 

Minecraft 1.8.9
Optifine 1.8.9_HD_U_H2
RadixCore-1.8.9-2.1.0
Forge 1.8.9-11.15.1.1722

I tried a few different Villagers, I got the XP, and the New Trade particles, but not the new trades. Just to be sure, I generated a fresh villager with a Female Villager Spawn Egg, same thing. I also started a fresh world with a generated MCA village, the villagers also did not open up new trades.

**Comment by chris9149** [comment]
Same thing for me. 

I tried with just MCA 1.8.9 5.1.2 and radixcore 1.8.9 2.1.0 installed and a fresh world.

Trades go through, get the swirly particles, but no new trades and after a trade is closed I can't unlock it to trade again.

**Comment by Awkanic** [comment]
This can probably be fixed by backporting the fix from #687 .
