### ISSUE TITLE
Dogs Kill Villagers!

### ISSUE THREAD

**Issue by Galindorf** [WildBamaBoy/minecraft-comes-alive#666]
Whoops, while trying to duplicate a different bug I accidentally punched a villager. 
And then my puppy killed her!  Is there a way to stop that from happening? 

(BTW I absolutely adore this mod... my hubby and I are playing on a LAN server and having a blast)
Minecraft 1.8.9
Optifine 1.8.9_HD_U_H2
RadixCore-1.8.9-2.1.0
Forge 1.8.9-11.15.1.1722

![screen shot 2016-03-27 at 7 06 48 pm](https://cloud.githubusercontent.com/assets/17105217/14068634/2da45242-f44f-11e5-8394-56399011408d.png)

**Comment by MentalMouse** [comment]
That's a problem with vanilla Minecraft as well.

**Comment by Galindorf** [comment]
Ah, so I guess I have to be extra careful! Thanks Mouse~
