### ISSUE TITLE
Interaction

### ISSUE THREAD

**Issue by shadycroissant** [WildBamaBoy/minecraft-comes-alive#667]
When I ask a villager to follow me, it works, but sometimes when I try to click on them, it says 'This Villager is Being Interacted With'. I'm not sure if it's a mod conflict or what, but I have 

Better Furnaces, Treecapitator, Bibliocraft, Biomes O'Plenty, Carpenter's Blocks, Chisel 2, Mo'Creatures, Decocraft, Fossil Archeology, Inventory Tweaks, Malisis Doors, Mr Crayfish, Not Enough Items, Optifine, Pam's Harvestcraft, Rei's Minimap, Storage drawers, TConstruct.

And I am playing 1.7.10. Anything would be helpful! Thanks!

**Comment by WildBamaBoy** [comment]
Make sure you're using the latest version of the mod for 1.7.10. This has been removed and will no longer be an issue.
