### ISSUE TITLE
Married gard rendered completely useless

### ISSUE THREAD

**Issue by LordVladneutral** [WildBamaBoy/minecraft-comes-alive#669]
Using linux and latest stable forge and latest MCA.

I'm quite deceived that once married, gards aren't gards anymore, they are just normal villagers... My village is very well protected, but if it wasn't all my villagers would be dead. Iron golems just aren't enough... I could make the villagers themselves do 30 damage each hit, killing even a witch, but that just removes all the fun of it.

I used to go around with my large familly and some gards and kill a ton of mobs all night, but that's so hard now... your familly doesn't seem to fight by your side either...

Even an hired gard doesn't do anything anymore... I really like the story progression, though...

Add an option to turn off that feature please. Or to exclude the gards from story progression... please. For now, can I do it by editing something in the mod file ?

**Comment by Galindorf** [comment]
Agreed! I have a very small village, and it seems the ladies only want to marry those rugged guard-types... leaving my village defenseless. It would be nice if the guards would still go on patrol. (Their spouses just have to understand... it's a dangerous life!)

**Comment by MentalMouse** [comment]
I've spawned with a guard for a wife, and seen two guards get married.  In those cases, the guards do fight monsters, but they still don't patrol effectively:  They seem to pick a spot outside my fence and take on all comers there.  (And I have set indoor home points.)

**Comment by MentalMouse** [comment]
Addendum:  The most obvious problem with guards is that they work like wolves, but more so:

They don't even wait for something to attack you -- if a mob comes in range, they go looking for it *even if they'd been told to stay put*.  If it's a skeleton behind a fence, they'll stay there while it chips away at their hit points, and even if they kill it, they don't go back:  They revert to "Stay Here", at their new location.  And they don't seem to bother with their home points, much less sleeping.

**Comment by MentalMouse** [comment]
I also recently got an Archer kid spawning.  Those still go looking for monsters, but at least they don't let skeletons kill them off.
