### ISSUE TITLE
[1.8.9] AI causing server lag

### ISSUE THREAD

**Issue by bloodmc** [WildBamaBoy/minecraft-comes-alive#670]
mca.entity.EntityHuman.func_70071_h_()7.28%205000ms
mca.ai.AIManager.onUpdate()5.00%
mca.ai.AIPatrol.onUpdateServer()4.72%
radixcore.util.RadixLogic.getNearbyBlocks()4.72%
radixcore.util.BlockHelper.getBlock()4.71%

http://i.imgur.com/k74AhMZ.png

It seems the AIPatrol call to getNearybyBlocks is causing some lag on our server.

https://github.com/WildBamaBoy/minecraft-comes-alive/blob/1.8.9-master/src/main/java/mca/ai/AIPatrol.java#L47

Currently using latest 1.8.9 build.

**Comment by WildBamaBoy** [comment]
Update scheduled for next major release 5.2.0.
