### ISSUE TITLE
Feature: Cheating

### ISSUE THREAD

**Issue by MartialArtsMan** [WildBamaBoy/minecraft-comes-alive#671]
I wonder if your wife gets to -5 hearts she will cheat on you???? Can you implement that?

**Comment by HillustratedMike36** [comment]
Betrayal...? Seems more realistic...if this mod is aiming on how to deal with a boyfriend/girlfriend or husband/wife relationship, they shouldn't have to rely on a mod for it, but just to show there are consequences, this could be interesting...

**Comment by DraksterAU** [comment]
Feature: Player dies instantly via fire upon trying to marry another villager? :P

**Comment by MentalMouse** [comment]
Looks to me like you cannot in fact procreate with someone unless you're married to them -- if you can't do that, then the NPCs shouldn't be able to.

I'd say it would be reasonable that if your spouse goes below the gold-hearts range, their messages stop being "loving", and if they get down to, say 3 red hearts, they might divorce *you* (with some given chance each game day).

**Comment by WildBamaBoy** [comment]
At most we'll probably make it where they just end the marriage the next time you speak to them - provided their hearts are low enough.
