### ISSUE TITLE
The Death of a Village -- Biomes'O'Plenty incompatibility

### ISSUE THREAD

**Issue by AngleWyrm** [WildBamaBoy/minecraft-comes-alive#673]
So ended another village, with the death of everyone in it:
![theend](https://cloud.githubusercontent.com/assets/2841453/14412727/a2a36a78-ff1d-11e5-96e9-085cfb96fcb5.png)

The reason? A failure to understand the nature of death and where to walk:
![thefailedpath](https://cloud.githubusercontent.com/assets/2841453/14412734/d8295428-ff1d-11e5-8744-5f9095564b87.png)

**Comment by WildBamaBoy** [comment]
Blame Mojang AI - I will be replacing it in a future update.
