### ISSUE TITLE
Four villagers for one zombie...

### ISSUE THREAD

**Issue by MentalMouse** [WildBamaBoy/minecraft-comes-alive#676]
So, I was curing zombies to restock my zombie-slaughtered village... the first two got ordinary male villagers, but then the third produced a married couple in the cage, while two guards spawned outside the cage!  The guards were one of each gender, but happily not married.

**Comment by Galindorf** [comment]
That's pretty interesting that you got two villagers from one zombie! I wonder if they get sort of randomly created like your family members do when you begin... you know, when you start with a spouse and 0-3 kids? 
As for the guards, they will generate per number of villagers. If you look in the config file, you can set how many villagers there have to be before a guard will spawn. I found I had too many guards hanging about so I turned the number up a bit. That's probably what happened.

**Comment by Awkanic** [comment]
Yup, probably due to doOverwriteVillager resulting the spawning a spouse. This will also happen in 1.9.
