### ISSUE TITLE
No colored diamonds in 1.8.9?  Optional replacement feature.

### ISSUE THREAD

**Issue by MentalMouse** [WildBamaBoy/minecraft-comes-alive#677]
Playing  1.8.9-1.5.2, I'm not seeing the recipes (in JIT) for diamond dust and recolored diamonds, and indeed I can't craft diamonds into dust.

I can understand why you might not want to have 16 colored diamonds (and blocks thereof), but perhaps instead the gem cutter could work on other minerals?  Emeralds and Lapis are obvious, redstone a maybe, metals and even mod gems/metals could be a possibility.  (From what I've seen, you'd need to reorganize the ring code so that "gemstone rings" are variations of a single item, instead of testing for all variations.)

**Comment by WildBamaBoy** [comment]
They are removed from that version - I'm not willing to create 100+ different JSON files for each variant. I will look into expanding the gem cutter though.

**Comment by WildBamaBoy** [comment]
We've decided not to go through with this.
