### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by tayladoh** [WildBamaBoy/minecraft-comes-alive#678]
I installed forge. I place the MCA and Radix mod in the mods folder. I started my game up and changed it to the right version and changed it to forge. I go into the game and the mod doesn't show up or nothing.

**Comment by mezzodrinker** [comment]
Define "the mod doesn't show up or nothing".

**Comment by tayladoh** [comment]
![capture](https://cloud.githubusercontent.com/assets/18429004/14475059/f9495da2-00f7-11e6-86c5-3ba9f017afdc.PNG)
None of the command thingy's come up on the side.

**Comment by mezzodrinker** [comment]
Please install Forge correctly.

**Comment by tayladoh** [comment]
Can you tell me how because I thought I only had to click the icon then press okay?

**Comment by mezzodrinker** [comment]
https://is.gd/kRCrMx

**Comment by WildBamaBoy** [comment]
If you have trouble installing the mod, we have an automatic installer at the bottom of this page: http://www.radix-shock.com/mca--download.html
