### ISSUE TITLE
Villager Generation Override

### ISSUE THREAD

**Issue by Kismette** [WildBamaBoy/minecraft-comes-alive#682]
Tried to create a villager with custom trade using command block. Here is what I added:

`/summon Villager ~5 ~ ~ {Profession:0,CustomName:"Derpy",CustomNameVisible:1,Offers:{Recipes:[{buy:{id:"stone",Count:1},maxUses:10,sell:{id:"red_flower",Count:1,Damage:4}},{buy:{id:"stone",Count:1,Damage:1},maxUses:10,sell:{id:"red_flower",Count:1,Damage:2}}]}}`

Using this does generate random MCA villagers and doesn't specify the name and trade from what I added in the code.

**Comment by WildBamaBoy** [comment]
Will look into this.

**Comment by Awkanic** [comment]
This is a result of doOverwriteVillager in EventHooksFML.java. I have a partial solution which works by passing the entity through the constructor (and rigging all uses of it to be null safe). This works but it cannot disable api and every so often the name displayed desyncs with the name given until the game is reloaded.
