### ISSUE TITLE
Slightly homophobic parental system.

### ISSUE THREAD

**Issue by MissMuffinButton** [WildBamaBoy/minecraft-comes-alive#684]
My friend and I had children together and when we looked who their parents were it said "mother and father" even though we are both female. Later I had more children with a MCA villager and one of our daughters married her daughter's. Her children parents were also "mother and father". It's kind of annoying to see that because it kind of shows kids and teens that having a mother and father is the default instead of having two mothers and two fathers included too.
![2016-04-19_05 45 11](https://cloud.githubusercontent.com/assets/18545081/14628465/4ea5528a-05f6-11e6-9b1a-07d69f3d574d.png)

**Comment by WildBamaBoy** [comment]
Acknowledged, will look into fixing that.
