### ISSUE TITLE
What does Superuser do?

### ISSUE THREAD

**Issue by jkhero73** [WildBamaBoy/minecraft-comes-alive#686]
My apologies, this may not be a bug, but I have activated myself as a superuser, and it seems to have no difference from regular gameplay.

**Comment by mezzodrinker** [comment]
I have no idea if you're just trolling or if you really have completely no idea about what a superuser is but I'm telling you, this is not the right place for your issue/trolling attempt/whatever.

**Comment by jkhero73** [comment]
I legitimately have no idea what superuser does. Sorry!

**Comment by WildBamaBoy** [comment]
Right now it just allows you to control villagers who are related to other players, when normally you would not be able to do so.
