### ISSUE TITLE
MCA Villagers Spawning as Duplicates

### ISSUE THREAD

**Issue by MokahTGS** [WildBamaBoy/minecraft-comes-alive#688]
##MCA Version: 1.7.10 5.1.2
RadixCore 1.7.10 2.1.1

The Villagers and Guards are spawning duplicates of themselves all over a village.

**Comment by WildBamaBoy** [comment]
Are you running any other mods alongside MCA?

**Comment by WildBamaBoy** [comment]
Closing for lack of info
