### ISSUE TITLE
MCA server down?

### ISSUE THREAD

**Issue by Liana-Walter** [WildBamaBoy/minecraft-comes-alive#689]
I'm running the newest MCA for version 1.7.10, and I go to get on the server and it says "Can't connect to server" is the server down?  This has been going on for about a week now.

**Comment by mezzodrinker** [comment]
"the server"? Which one are you talking about?

**Comment by Liana-Walter** [comment]
The Official MCA Server
play.shewolfdeadly.com
I was able to get on it until about a week ago.  I don't know what's changed from the last time I was able to log onto the server.  I'm running the correct version of the mod, I checked to make sure.  The only other mods I'm running are a map and inventory sorting mod, both of which were compatible with the server the last time I was able to log on.

**Comment by WildBamaBoy** [comment]
It is currently down for maintenance.
