### ISSUE TITLE
All players treated as one on LAN MCA1.7.10-5.1.1.2

### ISSUE THREAD

**Issue by Billeh007** [WildBamaBoy/minecraft-comes-alive#691]
On my LAN server for MCA, the players are being treated as one player. When giving gifts, the villagers call us all by one of the player's names, and only one of us could get married. The rest get a "you already have a ring on your finger" message.

**Comment by WildBamaBoy** [comment]
MCA has known issues with LAN at this time. The alternative would be to start a local server instead of using LAN.
