### ISSUE TITLE
Server crash when hiring guards 1.9

### ISSUE THREAD

**Issue by GSValore** [WildBamaBoy/minecraft-comes-alive#692]
#### Steps to reproduce:
1. Dedicated Server only (single player instance will not display the bug)
2. Find a guard and attempt to hire them.
3. Upon accepting the hire, the server will crash and the client is unaffected.

#### Crash Log & Findings
The server appears to call a client-side only method in the packet handling. The crash log is attached.

[crash-2016-04-26_23.22.26-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/239386/crash-2016-04-26_23.22.26-server.txt)

I traced the call to *InventoryPlayer::getSlotFor()* which is tagged client side only.

#### Forge & Minecraft versions
Forge #1865
Minecraft 1.9

**Comment by Awkanic** [comment]
Investigation:
This only occurs when playing on a server with MCA. func_184429_b is getSlotFor(...) and this method is @SideOnly(Side.CLIENT) which causes the unhandled Exception.
