### ISSUE TITLE
mca 1.8

### ISSUE THREAD

**Issue by xXRedPlaysMcXx** [WildBamaBoy/minecraft-comes-alive#695]
When you attack a villager it will chase you like normal. But if you switch to a weapon that would make them beg for their lives they will stop chasing you and beg even if you initially punched them. This has happened with mod weapons too, suggesting it is MCA and not vanilla weapons/mod weapons.

CustomNPC weapons
My plasma sword mod
The knife in CFM

**Comment by WildBamaBoy** [comment]
This is intentional.
