### ISSUE TITLE
Trouble with kids? (1.7.10 - CrundeeCraft Modpack)

### ISSUE THREAD

**Issue by Eltrafix** [WildBamaBoy/minecraft-comes-alive#696]
Hi there,

I've recently married a man in a village and had adopted two kids before having four more afterwards. The first thing I noticed was that the first child I didn't adopt dissapear. The first adopted child was gone and had married as well, but the second adopted child still lived in our home. It didn't die and the whistle did nothing, and this also happened to a pair of twins, the younger twin dissapeared and the older one lived. Also, after my kids had married/reached age 14, they'd stop moving and they wouldn't accept cakes. I'm sorry if this has already been covered, but thanks for looking :)

**Comment by WildBamaBoy** [comment]
Can't really support issues from a modpack, however villagers will only disappear if they have died.
