### ISSUE TITLE
[Bug] MCA Villager crashes server

### ISSUE THREAD

**Issue by DigitalSniperz** [WildBamaBoy/minecraft-comes-alive#697]
**Crash-Report:** http://pastebin.com/y2GAiUj0
**Forge version:** 1.7.10-1614.46

Whenever someone clicks a MCA villager it instantly crashes the server.

**Comment by mezzodrinker** [comment]
This seems to be caused by a mod by SpitefulFox, not MCA. Which mods are you using apart from MCA and RadixCore?

**Comment by DigitalSniperz** [comment]
All mods on this modpack: https://www.atlauncher.com/pack/CrundeeCraft

**Comment by mezzodrinker** [comment]
The cause is most likely Forbidden Magic, SpitefulFox's Tinker's Construct 4 plugin.

Please notify the author of your mod pack about this.

**Comment by WildBamaBoy** [comment]
Yup, not MCA.
