### ISSUE TITLE
SheWolf's MCA server says fatally missing blocks and item?

### ISSUE THREAD

**Issue by Cloud567818** [WildBamaBoy/minecraft-comes-alive#700]
I tried to get help at places like minecraft forums, planet minecraf, etc. Neither of them helped.

**Comment by mezzodrinker** [comment]
Could it be that you just went here without going anywhere else? I don't remember anyone complaining about connection issues with SheWolfDeadly's server in the past month.

Also, this is most likely the wrong place. Please post a detailed description of what you tried to do as well as your current Minecraft, MCA and RadixCore version on the [Minecraft Forums](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-1-2-mc-1-9-1-8-9-1-7-10).

**Comment by WildBamaBoy** [comment]
It is now running a modpack, as shown on its MOTD when you try to connect: http://www.technicpack.net/modpack/alphacraft-together.846852

**Comment by Cloud567818** [comment]
Thanks for telling me! I feel like a giant idiot now.
