### ISSUE TITLE
Curing zombie villagers

### ISSUE THREAD

**Issue by zlyfire** [WildBamaBoy/minecraft-comes-alive#701]
I might've done something wrong, but  
One of my villagers went zombie at some point during my game, and I finally got to the point where I can apply the weakness effect. I put the zombie villager in a hole, applied weakness, and then gifted a gold apple. Right clicking, even with the golden apple in hand, brought the interact menu up. I've been staring at the villager for over a day now and it hasn't been cured yet. Is this the correct way to cure a villager with this mod, or did I do something wrong? Or is it broken?

**Comment by mezzodrinker** [comment]
Did you gift the golden apple to the zombie villager via the "Gift" interaction option or did you just throw it at it?

**Comment by zlyfire** [comment]
Gifted via the "Gift" option

**Comment by WildBamaBoy** [comment]
MCA version? Minecraft version?

**Comment by zlyfire** [comment]
MCA 1.5.2  
Minecraft 1.9

**Comment by mezzodrinker** [comment]
You surely meant 5.1.2 as MCA's version, right?

**Comment by zlyfire** [comment]
Oh yes, sorry.  
It also seems trying again worked. Weird, but ti did work (instantly I might add).

**Comment by FaiqGaming** [comment]
Its bug? you already have baby pls i kill this my mother on comes alive how
