### ISSUE TITLE
Crashing when connecting to server?

### ISSUE THREAD

**Issue by Cloud567818** [WildBamaBoy/minecraft-comes-alive#702]
I don't think this is the modpacks fault since it works perfectly fine of single player. Also, sorry if I shouldn't post about the server and stuff here. I tried to get help from other places again and haven't gotten any replies that help too.

**Comment by WildBamaBoy** [comment]
Make sure you've updated the pack via the Technic launcher.

**Comment by Cloud567818** [comment]
I am using the latest version, ill try  reinstalling it.

**Comment by Cloud567818** [comment]
that didnt work either.

**Comment by Cloud567818** [comment]
Just found it was becuase i was in the tainted (purple) biome.

**Comment by WildBamaBoy** [comment]
Were you able to log on?
