### ISSUE TITLE
Stashing the crystal ball gets a new one on reload, ad infinitum.

### ISSUE THREAD

**Issue by MentalMouse** [WildBamaBoy/minecraft-comes-alive#703]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
Forge 1901 (1.9)
MCA-1.9-5.1.2-BETA-universal
RadixCore-1.9-2.1.0-BETA-universal

## Issue Description
If the crystal ball is stored instead of used, it gets supplied anew on game reload.

## Reproduce Steps
1. Create new world with MCA.  
2. Stash the crystal ball in a chest
3. Save the game
4. Reload the game
5. You now have another crystal ball.

**Comment by WildBamaBoy** [comment]
Intentional - use the crystal ball to properly set up the mod and prevent this.

**Comment by Orange1861** [comment]
Why is this intentional?

**Comment by WildBamaBoy** [comment]
So that you can properly configure MCA without the risk of another mod's configuration page showing on world join (you choose when to set up MCA), and to remove the possibility of the crystal ball being lost.

**Use it.** It takes less than 10 seconds to set up and goes away forever once you do.
