### ISSUE TITLE
Villagers die from sleeping in a bed with foot at a wall.

### ISSUE THREAD

**Issue by MentalMouse** [WildBamaBoy/minecraft-comes-alive#704]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

Forge 1901 (1.9)
MCA-1.9-5.1.2-BETA-universal.jar  
RadixCore-1.9-2.1.0-BETA-universal.jar

## Issue Description

When a villager bed is placed next to a wall (but with open space on the other side), the villager shortly dies, either of InWall or silently.

## Reproduce Steps

Set up with family house.  Place a villager bed with its foot to a wall.  Place your spouse's home point near bed.  Switch between time 24000 and 12000 until villager tries to use the bed.  (Ahem... that's pretty unreliable in itself).  Villager will stand at foot of bed and suffocate in wall.

Really, villagers should be better able to find and _use_ beds, avoid moving into walls, and for that matter, take the few steps to walk out of a wall if they find themselves in one.  Their own beds don't even suffocate them, why do they consider a bed on the floor with plenty of headroom, an invalid home point anyway?

**Comment by JohnRohner** [comment]
I can confirm this.  On a LAN Server based set up, you can even set the bed in the middle of the room, and watch the villages "spin" for like a range of six blocks around the bed.  This is with 1.10.2 and latest mca.  If the side of the bed is against a wall, they can suffocate.

Solution is to not use beds.  Although even then the hit areas seem odd--a lot of combat going on through walls both between the mobs and the guards.
