### ISSUE TITLE
Possible Relationship System?

### ISSUE THREAD

**Issue by DRULES679** [WildBamaBoy/minecraft-comes-alive#706]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

**Comment by WildBamaBoy** [comment]
Suggestions go on the forums.
