### ISSUE TITLE
Children Disappear without death notice.

### ISSUE THREAD

**Issue by wesb1** [WildBamaBoy/minecraft-comes-alive#707]
Hello,
I run a modded server with my friend and I and every time we try to procreate with our wives, our children end up disappearing. This has happened multiple times. The wives never despawn but the children vanish without notice. My MCA/Radiax Core is on 1.7.10, and the server is on 1.7.10 as well of course. 

Pls Help

**Comment by mezzodrinker** [comment]
What version of MCA are you using?

**Comment by wesb1** [comment]
let me check

**Comment by wesb1** [comment]
4.1.5
(1.7.10)

**Comment by mezzodrinker** [comment]
Please check if updating to the latest version (5.1.2) solves the issue.

**Comment by wesb1** [comment]
will the villagers stay in the world when i update?

**Comment by mezzodrinker** [comment]
They won't. The update from 4.x.x to 5.x.x was a big one, so the villagers will not be "converted".

**Comment by wesb1** [comment]
ok, do i update my Radiax core as well? its version 1.3.4

**Comment by mezzodrinker** [comment]
Yes. The latest version for 1.7.10 is 2.1.1.

**Comment by wesb1** [comment]
wow man, thanks for the speedy response. I have had this problem for a while and it means alot. Thanks

**Comment by mezzodrinker** [comment]
I take it the update resolved your issue?

**Comment by wesb1** [comment]
i have not tried it yet, as i must download the new mods

**Comment by mezzodrinker** [comment]
At least not on purpose. I'm not sure what happens if you push a villager into a Nether portal, but I think they will just get there fine. No guarantees about them staying alive, though.

**Comment by wesb1** [comment]
Lol thanks again sir
I will try to play around with the server and possibly comment later

**Comment by wesb1** [comment]
All the villagers are gone :(

**Comment by wesb1** [comment]
is there anything i can do

**Comment by mezzodrinker** [comment]
> They won't. The update from 4.x.x to 5.x.x was a big one, so the villagers will not be "converted".
