### ISSUE TITLE
Is there a way to retexture MCA?

### ISSUE THREAD

**Issue by CiaoMeow** [WildBamaBoy/minecraft-comes-alive#708]
I'm running MCA 1.8 and I'm really enjoying the mod. I wanted to retexture the villagers to suit my style a little better.  When I open the .jar file as a folder everything is fine, but when I go to turn it back a .jar file it stops the mod from working. Is there any way to fix the problem?

**Comment by mezzodrinker** [comment]
Why do you edit the `.jar` directly? AFAIK, you can edit a mod's textures by creating a texture pack.

**Comment by CiaoMeow** [comment]
Oh ok, I already have a custom texture pack. How do I make one for a mod?

**Comment by CiaoMeow** [comment]
Nevermind I figured it out!!! Thank you so much!!Ｏ(≧▽≦)Ｏ

**Comment by mezzodrinker** [comment]
If you managed to resolve the issue, please close it.
