### ISSUE TITLE
Crash MC server 1.7.10 MCA-1.7.10-5.1.2-universal

### ISSUE THREAD

**Issue by ternsip** [WildBamaBoy/minecraft-comes-alive#709]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
MCA-1.7.10-5.1.2-universal

## Issue Description

Crases when village becomes zombie ! Or something similar.
http://pastebin.com/szLwLvAx

**Comment by WildBamaBoy** [comment]
Malformed issue, reported previously. Closing
