### ISSUE TITLE
1.9 MCA broken Crystal Ball on SMP server.

### ISSUE THREAD

**Issue by RebeccaRedstone** [WildBamaBoy/minecraft-comes-alive#711]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
Minecraft 1.9
Forge-1.9.12.16.1.1934
MCA-1.9-5.1.3
 

## Issue Description

Crystal Ball not going to the enchantment table stage in SMP. The configuration files on both server and client have building spawning set to true. I have tried running it with no other mods as requested and it still gives same issue. 

## Reproduce Steps

1. Create multiplayer server with current versions MCA and RadixCore. 
2. Log on to server
3. Right click crystal ball 
4. Follow steps 
5. Wait for enchantment table and bookcases to appear.
6. They never do.....D: (and Crystal ball disappears)

## Additional Information

I looked in my fml and latest logs on both client and server - the only reference to MCA I can find is this 

[15:29:12] [Client thread/INFO] [MCA/]: Received and applied server-side configuration.
[15:29:31] [Client thread/INFO] [MCA/]: Downloading supporters list...

which is from the client side fml-client-latest.log

Thanks for your help! Let me know if I can provide anymore information :)

**Comment by WildBamaBoy** [comment]
When on a server, the room with the enchantment table will not appear.
