### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by ClockworkWorker** [WildBamaBoy/minecraft-comes-alive#714]
I can't download it. Whenever I try to goto either downloads it doesn't work. When I goto curse I wait the 3 seconds and it goes to a white browser. On radix or whatever, it just counts down and then it says thank you for waiting and then it doesn't download. Please respond quickly.

**Comment by WildBamaBoy** [comment]
Sounds like an issue with your browser or an addon it's running. Try a different browser, disable antivirus software, etc.
