### ISSUE TITLE
Villager are still despawning in MCA version 5.1.2

### ISSUE THREAD

**Issue by Jibuban** [WildBamaBoy/minecraft-comes-alive#715]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

**Comment by WildBamaBoy** [comment]
Reproduce the issue with just MCA and RadixCore.
