### ISSUE TITLE
Update glitch

### ISSUE THREAD

**Issue by wesb1** [WildBamaBoy/minecraft-comes-alive#718]
I updated to the latest mca and radiax core yet in my world every villager dissapeared pls help

**Comment by wesb1** [comment]
??

**Comment by supernewts** [comment]
This should be easy. What destiny did you choose? If it was "I live alone" or "None of these", you might not see any villagers.

**Comment by wesb1** [comment]
I am not sure, how can i fix this? i backed up the world before i did this

**Comment by wesb1** [comment]
like there was no villagers in the world at all, and i had a wife and kids before the update and my friend as well

**Comment by WildBamaBoy** [comment]
If you were using a version of MCA before 5.x, villagers will disappear. Otherwise, it would be an issue I was not made aware of after an update and it wouldn't be possible to recover any lost villagers.
