### ISSUE TITLE
Villagers Won't Have Babies

### ISSUE THREAD

**Issue by Kay-Minecraft** [WildBamaBoy/minecraft-comes-alive#721]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Issue Description I marry two villagers, give one cake and in the chat it says the 'what is this feeling' thing, then she has a baby in her arms but the baby never leaves her arms. I let my minecraft sit for at least 30 minutes and the baby is still in her arms. I tried this on a different world and with different Villagers but it always happens.

 Marry 2 villagers(mine were female and male) give one cake, she pops out a baby. The baby never actually spawns just stays in her arms.

## Additional Information
I am playing in 1.7.10 because the other mods i use only run 1.7.10. (I removed the other mods and the issue still happens)

**Comment by WildBamaBoy** [comment]
Please resubmit and provide your MCA version.
