### ISSUE TITLE
Villagers gone

### ISSUE THREAD

**Issue by wesb1** [WildBamaBoy/minecraft-comes-alive#723]
when i update my world to the newest version of 1.7.10 MCA and Radiax core, i says there are missing items and every villager vanishes. I installed the mod correctly and my issues keep getting closed so i cant see much help :/

**Comment by wesb1** [comment]
and in the old version children vanished so i dont know what to do

**Comment by wesb1** [comment]
Is there a way i can update and keep all of my family progress, fix the children vanish glitch, and all the villagers wont vanish

**Comment by WildBamaBoy** [comment]
You cannot keep any progress when updating from a version of MCA below 5.x.
You **must** start over.
