### ISSUE TITLE
MCA custom villager issue

### ISSUE THREAD

**Issue by Liana-Walter** [WildBamaBoy/minecraft-comes-alive#725]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [n/a] I am crashing and can provide my crash report.

1.7.10 Versions [MCA 5.1.1.1 and RadixCore 2.1.1]

every time I try and add in a new skin the skin renders except for the head. I have tried this multiple times, and usually just edit an existing skin and rename it to fit the numbering theme. I also make sure to make a sleeping skin.  I'm not sure if this is an issue or if I'm doing something wrong.  Any advice would be greatly appreciated.

Extract Child Skin from .jar folder
Edit Child Skin and rename
Put the Skin back in the .jar folder in the proper folder
Load the game and look for the skin under its name in the villager editor

![wth](https://cloud.githubusercontent.com/assets/18637836/16368924/a7d2fb94-3bf9-11e6-9a66-0f54da5c5394.png)

**Comment by Ginger60** [comment]
What program are you using to edit the skins?

**Comment by Liana-Walter** [comment]
I'm editing it directly from the texture in the .jar.
but I just pull it up on paint

**Comment by WildBamaBoy** [comment]
Paint doesn't save with transparency, it just turns any uncolored areas white, which is why the texture ends up like that.

Use a different graphics editor like GIMP or Paint.net, one that supports transparency.
