### ISSUE TITLE
Kicked while trying to connect to Official server

### ISSUE THREAD

**Issue by Ginger60** [WildBamaBoy/minecraft-comes-alive#726]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
RadixCore-1.8-2.1.0-universal
MCA-1.8-5.1.1.2-universal.jar

## Issue Description
![connection lost](https://cloud.githubusercontent.com/assets/16965463/16386442/a7c8e338-3c45-11e6-8ad3-dc245ba3ff3d.png)

## Reproduce Steps
Just attempting to log in to play.shewolfdeadly.com

**Comment by Ginger60** [comment]
Now I've tried logging into the Techit server too, and it won't let me.  What am I doing wrong?
![alphacraft server connection fail](https://cloud.githubusercontent.com/assets/16965463/16537797/708d348e-3fc2-11e6-961f-633ca4211286.png)

**Comment by WildBamaBoy** [comment]
It's currently down.
