### ISSUE TITLE
Villagers babys not growing up

### ISSUE THREAD

**Issue by Tiaan127** [WildBamaBoy/minecraft-comes-alive#728]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

1.9
## Versions

The villigers babys do not grow up they keep holding it in their hands waited for hours still nothing keeps happening not a one time oucurins
## Issue Description

use arrangement rings feed cake they have a baby but baby wont grow up

**Comment by WildBamaBoy** [comment]
Unable to reproduce this issue.

**Comment by Tiaan127** [comment]
What setting coud cause this to happen
