### ISSUE TITLE
Crystal Ball Crashing My LAN Game

### ISSUE THREAD

**Issue by TempXIV** [WildBamaBoy/minecraft-comes-alive#729]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

## Versions
Minecraft Version 1.9 and MCA-1.9-5.1.3

It's just when I try to play with my friend but when I create a LAN server for us to play on, the crystal ball just crashes my game. It works just fine in Singleplayer but just with LAN it crashes on me.

Um... Not 100% sure. I downloaded Forge 1.9-12.16.1.1887, MCA 1.9-5.1.3 and RadixCore 1.9-2.1.0 and as I stated before, it works in singleplayer but I can't seem to get it to work in multiplayer.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/5/16 9:00 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mca.core.MCA.getPlayerData(MCA.java:709)
	at mca.client.gui.GuiSetup.<init>(GuiSetup.java:58)
	at mca.core.forge.GuiHandler.getClientGuiElement(GuiHandler.java:52)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:266)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:102)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2462)
	at mca.items.ItemCrystalBall.func_77659_a(ItemCrystalBall.java:58)
	at mca.items.ItemCrystalBall.func_180614_a(ItemCrystalBall.java:39)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:443)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1512)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2171)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1743)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.core.MCA.getPlayerData(MCA.java:709)
	at mca.client.gui.GuiSetup.<init>(GuiSetup.java:58)
	at mca.core.forge.GuiHandler.getClientGuiElement(GuiHandler.java:52)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:266)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:102)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2462)
	at mca.items.ItemCrystalBall.func_77659_a(ItemCrystalBall.java:58)
	at mca.items.ItemCrystalBall.func_180614_a(ItemCrystalBall.java:39)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:142)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:443)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1512)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2171)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TimBrough'/2458, l='MpServer', x=25.50, y=71.00, z=247.50]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (16,64,252), Chunk: (at 0,4,12 in 1,15; contains blocks 16,0,240 to 31,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2224 game time, 2224 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 80 total; [EntityBat['Bat'/3980, l='MpServer', x=-39.75, y=29.10, z=324.75], EntityBat['Bat'/3981, l='MpServer', x=-40.25, y=25.10, z=319.49], EntityItem['item.tile.doublePlant.paeonia'/4238, l='MpServer', x=35.76, y=72.00, z=192.52], EntityBat['Bat'/3734, l='MpServer', x=-40.25, y=32.10, z=217.25], EntityPlayerSP['TimBrough'/2458, l='MpServer', x=25.50, y=71.00, z=247.50], EntityCreeper['Creeper'/3871, l='MpServer', x=-2.70, y=15.00, z=188.69], EntityZombie['Zombie'/2976, l='MpServer', x=-29.50, y=23.00, z=204.25], EntityCreeper['Creeper'/3872, l='MpServer', x=-4.18, y=15.00, z=187.52], EntityZombie['Zombie'/4512, l='MpServer', x=-29.50, y=22.00, z=206.50], EntityCreeper['Creeper'/3874, l='MpServer', x=3.99, y=15.00, z=190.30], EntityZombie['Zombie'/3876, l='MpServer', x=-54.50, y=53.00, z=240.50], EntityCreeper['Creeper'/3878, l='MpServer', x=-50.50, y=53.00, z=244.50], EntityCreeper['Creeper'/2983, l='MpServer', x=-53.50, y=19.00, z=300.50], EntitySkeleton['Skeleton'/3879, l='MpServer', x=-51.18, y=53.00, z=240.82], EntitySquid['Squid'/4393, l='MpServer', x=58.79, y=53.00, z=278.49], EntityZombie['Zombie'/4526, l='MpServer', x=-8.50, y=20.00, z=223.50], EntityZombie['Zombie'/4527, l='MpServer', x=-8.50, y=20.00, z=226.50], EntityBat['Bat'/2611, l='MpServer', x=4.75, y=53.34, z=327.48], EntityCreeper['Creeper'/3510, l='MpServer', x=-4.50, y=22.00, z=200.50], EntitySheep['Sheep'/59, l='MpServer', x=-26.50, y=78.00, z=203.50], EntitySheep['Sheep'/60, l='MpServer', x=-29.50, y=76.00, z=206.50], EntitySheep['Sheep'/61, l='MpServer', x=-27.50, y=76.00, z=207.50], EntitySheep['Sheep'/62, l='MpServer', x=-26.18, y=76.00, z=211.49], EntityRabbit['Rabbit'/63, l='MpServer', x=-41.42, y=70.00, z=307.61], EntityRabbit['Rabbit'/64, l='MpServer', x=-27.70, y=72.00, z=318.39], EntityRabbit['Rabbit'/65, l='MpServer', x=-37.19, y=70.00, z=315.49], EntityRabbit['Rabbit'/66, l='MpServer', x=-29.60, y=72.00, z=313.40], EntityZombie['Zombie'/4162, l='MpServer', x=-26.50, y=19.00, z=204.50], EntityPig['Pig'/75, l='MpServer', x=-2.54, y=75.00, z=240.06], EntitySkeleton['Skeleton'/4171, l='MpServer', x=5.50, y=21.00, z=221.50], EntityPig['Pig'/76, l='MpServer', x=1.55, y=77.00, z=232.87], EntityPig['Pig'/77, l='MpServer', x=-4.50, y=74.00, z=234.50], EntityPig['Pig'/78, l='MpServer', x=-4.50, y=74.00, z=234.50], EntityPig['Pig'/79, l='MpServer', x=1.50, y=77.00, z=327.50], EntityPig['Pig'/80, l='MpServer', x=4.50, y=77.00, z=324.50], EntityPig['Pig'/81, l='MpServer', x=3.50, y=77.00, z=325.50], EntityItem['item.item.seeds'/3665, l='MpServer', x=-23.05, y=71.00, z=279.07], EntityWitch['Witch'/3282, l='MpServer', x=19.50, y=33.00, z=305.50], EntityItem['item.tile.flower2.poppy'/3666, l='MpServer', x=-12.33, y=72.00, z=243.65], EntityWitch['Witch'/3283, l='MpServer', x=17.50, y=33.00, z=304.50], EntityZombie['Zombie'/3029, l='MpServer', x=-20.50, y=18.00, z=170.50], EntityItem['item.tile.flower2.poppy'/3669, l='MpServer', x=-11.03, y=72.00, z=241.78], EntityCreeper['Creeper'/4053, l='MpServer', x=-34.50, y=22.00, z=185.50], EntityItem['item.item.seeds'/3674, l='MpServer', x=-34.35, y=71.00, z=275.60], EntityItem['item.item.seeds'/3675, l='MpServer', x=-23.19, y=71.00, z=282.75], EntityItem['item.item.seeds'/3676, l='MpServer', x=64.29, y=72.00, z=248.33], EntityCreeper['Creeper'/4445, l='MpServer', x=52.50, y=17.00, z=318.50], EntityCreeper['Creeper'/4573, l='MpServer', x=1.50, y=23.00, z=296.50], EntitySheep['Sheep'/95, l='MpServer', x=21.19, y=72.00, z=211.56], EntitySheep['Sheep'/96, l='MpServer', x=9.50, y=72.00, z=212.69], EntitySheep['Sheep'/97, l='MpServer', x=9.51, y=72.00, z=211.20], EntitySkeleton['Skeleton'/4321, l='MpServer', x=27.50, y=49.00, z=322.50], EntityCreeper['Creeper'/4577, l='MpServer', x=-1.50, y=16.00, z=189.50], EntitySheep['Sheep'/98, l='MpServer', x=7.68, y=72.00, z=206.83], EntityPig['Pig'/99, l='MpServer', x=3.53, y=71.00, z=256.76], EntityCreeper['Creeper'/4579, l='MpServer', x=-13.50, y=23.00, z=201.50], EntityPig['Pig'/100, l='MpServer', x=-0.36, y=71.00, z=273.23], EntitySkeleton['Skeleton'/4580, l='MpServer', x=11.50, y=36.00, z=202.50], EntityPig['Pig'/101, l='MpServer', x=8.77, y=71.00, z=265.49], EntitySkeleton['Skeleton'/4581, l='MpServer', x=89.50, y=40.00, z=224.50], EntityPig['Pig'/102, l='MpServer', x=11.72, y=69.97, z=259.28], EntityBat['Bat'/3561, l='MpServer', x=-41.22, y=26.15, z=214.39], EntityZombie['Zombie'/3306, l='MpServer', x=-51.91, y=53.00, z=240.09], EntityItem['item.item.seeds'/4588, l='MpServer', x=-33.13, y=71.00, z=273.82], EntitySkeleton['Skeleton'/4207, l='MpServer', x=-47.50, y=22.00, z=177.50], EntityBat['Bat'/4079, l='MpServer', x=-50.80, y=16.10, z=176.17], EntityBat['Bat'/3952, l='MpServer', x=-52.25, y=30.07, z=186.83], EntityBat['Bat'/4080, l='MpServer', x=-48.33, y=26.66, z=178.68], EntitySkeleton['Skeleton'/4208, l='MpServer', x=-49.50, y=22.00, z=175.50], EntityBat['Bat'/4081, l='MpServer', x=-50.36, y=22.00, z=178.75], EntityBat['Bat'/3698, l='MpServer', x=-2.48, y=60.50, z=323.13], EntityPig['Pig'/115, l='MpServer', x=59.50, y=71.00, z=209.50], EntityBat['Bat'/3699, l='MpServer', x=-46.57, y=35.11, z=290.31], EntityPig['Pig'/116, l='MpServer', x=60.50, y=70.00, z=208.50], EntityPig['Pig'/117, l='MpServer', x=58.50, y=71.00, z=207.50], EntityPig['Pig'/118, l='MpServer', x=59.50, y=71.00, z=209.50], EntityBat['Bat'/4086, l='MpServer', x=-8.38, y=21.75, z=182.96], EntityBat['Bat'/4088, l='MpServer', x=-12.50, y=23.00, z=203.53], EntitySkeleton['Skeleton'/4477, l='MpServer', x=-10.50, y=15.00, z=199.50], EntityCreeper['Creeper'/2814, l='MpServer', x=4.70, y=15.00, z=190.95]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 548650824 bytes (523 MB) / 1378816000 bytes (1314 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.1.1887 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1887.jar) 
	UCHIJAAAAAA	Forge{12.16.1.1887} [Minecraft Forge] (forge-1.9-12.16.1.1887.jar) 
	UCHIJAAAAAA	RadixCore{1.9-2.1.0} [RadixCore] (RadixCore-1.9-2.1.0-universal.jar) 
	UCHIJAAAAAA	MCA{1.9-5.1.3} [Minecraft Comes Alive] (MCA-1.9-5.1.3-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.2211.0' Renderer: 'AMD Radeon HD 7900 Series'
	Launched Version: 1.9-forge1.9-12.16.1.1887
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7900 Series GL version 4.5.13431 Compatibility Profile Context 16.150.2211.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ChromaHills128x-1.9-v.1.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

Thank you for the help and I appreciate all of your work. If it's a simple solution then I apologize for bringing this too you guys but I've been getting an absolute headache trying to figure it out. All versions of MCA and MC that I have downloaded all fail to work LAN Play and idk what exactly is wrong as a few months ago it was working just fine.

Thanks for the help!

**Comment by WildBamaBoy** [comment]
Known issues on LAN with most previous versions. Should be back to normal with the next update (coming in the next couple of days)
