### ISSUE TITLE
Crashing on attacking entities with villager override off.

### ISSUE THREAD

**Issue by Andre-Maartens** [WildBamaBoy/minecraft-comes-alive#734]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions
Minecraft 1.7.10
Forge 10.13.4.1566-1.7.10
RadixCore 1.7.10-2.1.2
MCA 1.7.10-5.2.0

## Issue Description
Everytime I try to punch a Iron Golem, I crash. Your mod is doing something weird to vanilla villagers and golems when not overiding the vanilla villagers

## Reproduce Steps
Turn off MCA villager override. Spawn in a Iron Golem. Spawn in a MCA Villager. Punch Golem, nothing happens. Spawn in a Vanilla Villager. Punch golem, crash.

## Additional Information
[crash-2016-07-08_10.36.46-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/353816/crash-2016-07-08_10.36.46-client.txt)

MCA Crash Log: https://pastebin.com/2ExWsQHy
MCA + RADIXCORE Only Crash Log:https://pastebin.com/q0TYLgDS

**Comment by Andre-Maartens** [comment]
Refined the issue. It only happens when turning OFF the villager overide and attacking a iron golem close to a vanilla villager.

**Comment by SniZupGun** [comment]
Having the same issue as stated, normal vanilla villagers such as those added in by mods that MCA does not override will crash the game after hitting mobs if in the vicinity.
In my case I crashed from hitting a lycanite mob inside a villages walls, although with a tinkers construct broadsword. 
[crash-2016-07-08_22.39.40-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/355320/crash-2016-07-08_22.39.40-server.txt)
