### ISSUE TITLE
Game crashes when walking near gravestones

### ISSUE THREAD

**Issue by EnderCreeper15** [WildBamaBoy/minecraft-comes-alive#738]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  LoadingPlugin (Quark-beta-41.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 7/9/16 1:01 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1936)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1330)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1936)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1330)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['EC_'/1057, l='MpServer', x=225.93, y=76.00, z=253.99]]
	Chunk stats: MultiplayerChunkCache: 541, 541
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (196,64,248), Chunk: (at 4,4,8 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3626 game time, 3626 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 113 total; [EntityCrackedPigZombie['Cracked PigZombie'/8287, l='MpServer', x=229.50, y=64.00, z=228.75], EntityCrackedPigZombie['Cracked PigZombie'/8300, l='MpServer', x=162.50, y=22.00, z=179.50], EntityCow['Cow'/117, l='MpServer', x=201.50, y=76.00, z=199.50], EntityCow['Cow'/118, l='MpServer', x=202.82, y=75.00, z=200.48], EntityCow['Cow'/119, l='MpServer', x=202.50, y=78.00, z=195.50], EntityCow['Cow'/120, l='MpServer', x=204.50, y=77.00, z=195.50], EntityPig['Pig'/121, l='MpServer', x=212.50, y=69.00, z=292.50], EntityPig['Pig'/122, l='MpServer', x=213.50, y=69.00, z=292.50], EntityPig['Pig'/123, l='MpServer', x=208.50, y=70.00, z=293.50], EntityPig['Pig'/124, l='MpServer', x=214.50, y=68.00, z=290.50], EntityPig['Pig'/127, l='MpServer', x=228.50, y=63.00, z=192.50], EntityPig['Pig'/128, l='MpServer', x=228.50, y=64.00, z=189.50], EntityPig['Pig'/129, l='MpServer', x=225.50, y=65.00, z=188.50], EntityPig['Pig'/130, l='MpServer', x=222.50, y=68.00, z=189.50], EntityPig['Pig'/147, l='MpServer', x=218.50, y=67.00, z=196.67], EntityPig['Pig'/148, l='MpServer', x=216.74, y=63.00, z=235.38], EntityPig['Pig'/149, l='MpServer', x=231.37, y=66.00, z=222.68], EntityPig['Pig'/150, l='MpServer', x=241.49, y=69.00, z=219.70], EntityItem['item.tile.mushroom0'/151, l='MpServer', x=235.13, y=13.00, z=250.13], EntityWolf['Wolf'/152, l='MpServer', x=246.47, y=65.00, z=242.56], EntityWolf['Wolf'/153, l='MpServer', x=234.50, y=64.00, z=261.63], EntityWolf['Wolf'/154, l='MpServer', x=231.56, y=65.00, z=226.65], EntityWolf['Wolf'/155, l='MpServer', x=233.55, y=64.00, z=243.73], EntityPig['Pig'/156, l='MpServer', x=246.50, y=70.00, z=292.50], EntityPig['Pig'/157, l='MpServer', x=244.27, y=70.00, z=296.51], EntityPig['Pig'/158, l='MpServer', x=240.50, y=69.00, z=289.01], EntityPig['Pig'/159, l='MpServer', x=237.50, y=69.00, z=292.50], EntityPig['Pig'/160, l='MpServer', x=233.50, y=69.00, z=289.50], EntityPig['Pig'/161, l='MpServer', x=232.50, y=68.00, z=291.50], EntityPig['Pig'/162, l='MpServer', x=235.50, y=69.00, z=290.50], EntityPig['Pig'/163, l='MpServer', x=237.50, y=69.00, z=289.50], EntityPig['Pig'/165, l='MpServer', x=263.50, y=70.00, z=226.50], EntityPig['Pig'/166, l='MpServer', x=263.50, y=70.00, z=225.50], EntityPig['Pig'/167, l='MpServer', x=263.50, y=70.00, z=226.50], EntityPig['Pig'/168, l='MpServer', x=260.50, y=71.00, z=224.50], EntityPig['Pig'/184, l='MpServer', x=264.77, y=69.00, z=266.43], EntityPig['Pig'/185, l='MpServer', x=274.65, y=68.00, z=262.80], EntityPig['Pig'/186, l='MpServer', x=269.99, y=68.00, z=262.45], EntityPig['Pig'/187, l='MpServer', x=275.25, y=68.00, z=266.30], EntityPig['Pig'/192, l='MpServer', x=293.50, y=70.00, z=322.50], EntityPig['Pig'/193, l='MpServer', x=292.50, y=70.00, z=323.50], EntityPig['Pig'/194, l='MpServer', x=299.30, y=69.00, z=317.51], EntityPig['Pig'/195, l='MpServer', x=290.50, y=69.00, z=321.50], EntityCrackedPigZombie['Cracked PigZombie'/8424, l='MpServer', x=280.50, y=78.00, z=203.50], EntityCrackedPigZombie['Cracked PigZombie'/8434, l='MpServer', x=214.30, y=76.00, z=242.70], EntityCrackedZombie['Cracked Zombie'/8440, l='MpServer', x=302.50, y=68.00, z=318.50], EntityBat['Bat'/8480, l='MpServer', x=209.75, y=33.10, z=313.37], EntityCrackedZombie['Cracked Zombie'/8656, l='MpServer', x=267.50, y=69.00, z=229.50], EntityAshen['Ashen'/8839, l='MpServer', x=270.50, y=16.00, z=229.50], EntityItem['item.tile.gravel'/4797, l='MpServer', x=237.15, y=14.00, z=203.92], EntityItem['item.tile.gravel'/4902, l='MpServer', x=237.99, y=14.00, z=203.82], EntitySpider['Spider'/8998, l='MpServer', x=211.50, y=39.00, z=263.50], EntityCrackedZombie['Cracked Zombie'/9029, l='MpServer', x=152.50, y=68.00, z=245.50], EntityBat['Bat'/9064, l='MpServer', x=240.62, y=37.11, z=256.57], EntityConcussionCreeper['Concussion Creeper'/9102, l='MpServer', x=251.50, y=18.00, z=214.50], EntityCrackedPigZombie['Cracked PigZombie'/9177, l='MpServer', x=202.50, y=78.00, z=190.50], EntityHuman['Danielle'/9227, l='MpServer', x=208.00, y=76.00, z=236.00], EntityBat['Bat'/9247, l='MpServer', x=232.52, y=32.96, z=265.51], EntityBat['Bat'/9270, l='MpServer', x=252.76, y=22.31, z=224.75], EntityCrackedZombie['Cracked Zombie'/9295, l='MpServer', x=170.50, y=64.00, z=255.50], EntityBat['Bat'/9333, l='MpServer', x=250.25, y=44.05, z=192.39], EntityCrackedPigZombie['Cracked PigZombie'/9362, l='MpServer', x=176.50, y=64.00, z=226.50], EntityCrackedZombie['Cracked Zombie'/9364, l='MpServer', x=186.50, y=35.00, z=324.50], EntityConcussionCreeper['Concussion Creeper'/9392, l='MpServer', x=194.50, y=39.00, z=263.50], EntityItem['item.item.rottenFlesh'/9402, l='MpServer', x=226.05, y=77.00, z=231.13], EntityItem['item.tile.doublePlant.syringa'/5368, l='MpServer', x=246.44, y=69.00, z=221.28], EntityHuman['Alfred'/5371, l='MpServer', x=225.00, y=77.00, z=237.00], EntityHuman['Dewayne'/5374, l='MpServer', x=209.00, y=76.00, z=242.00], EntityHuman['Malika'/5375, l='MpServer', x=207.47, y=76.00, z=249.50], EntityHuman['Quentin'/5376, l='MpServer', x=210.81, y=76.00, z=247.45], EntityHuman['Claudie'/5377, l='MpServer', x=198.72, y=76.00, z=243.48], EntityHuman['Jeramy'/5378, l='MpServer', x=214.63, y=76.00, z=257.22], EntityCrackedZombie['Cracked Zombie'/9480, l='MpServer', x=162.50, y=68.00, z=272.50], EntityBat['Bat'/9494, l='MpServer', x=236.75, y=15.00, z=237.75], EntityItem['item.item.apple'/5400, l='MpServer', x=184.68, y=72.00, z=273.13], EntityItem['item.item.blackcurrant'/5401, l='MpServer', x=182.65, y=72.00, z=273.68], EntityItem['item.item.blackcurrant'/5407, l='MpServer', x=183.60, y=73.00, z=273.88], EntityConcussionCreeper['Concussion Creeper'/9511, l='MpServer', x=198.50, y=33.00, z=242.50], EntityBat['Bat'/9533, l='MpServer', x=253.25, y=24.99, z=179.75], EntityCrackedPigZombie['Cracked PigZombie'/9692, l='MpServer', x=164.79, y=63.00, z=241.61], EntityBat['Bat'/9742, l='MpServer', x=158.91, y=61.85, z=329.37], EntityBat['Bat'/9760, l='MpServer', x=234.52, y=37.13, z=250.47], EntityItem['item.tile.doublePlant.syringa'/5668, l='MpServer', x=219.75, y=64.00, z=271.45], EntityBat['Bat'/9767, l='MpServer', x=170.56, y=40.99, z=172.52], EntityWitherWitch['Wither Witch'/9794, l='MpServer', x=281.50, y=20.00, z=229.50], EntityPlayerSP['EC_'/1057, l='MpServer', x=225.93, y=76.00, z=253.99], EntityWitherCat['Wither Cat'/9796, l='MpServer', x=280.50, y=20.00, z=229.50], EntitySpider['Spider'/9849, l='MpServer', x=235.50, y=64.00, z=239.50], EntityCrackedZombie['Cracked Zombie'/9894, l='MpServer', x=292.50, y=68.00, z=245.50], EntitySpider['Spider'/9901, l='MpServer', x=217.50, y=33.00, z=298.50], EntityBat['Bat'/9932, l='MpServer', x=171.33, y=33.10, z=294.56], EntityBat['Bat'/9933, l='MpServer', x=238.10, y=23.10, z=235.18], EntityCrackedPigZombie['Cracked PigZombie'/9982, l='MpServer', x=198.79, y=76.00, z=260.38], EntityCrackedZombie['Cracked Zombie'/9998, l='MpServer', x=179.50, y=20.00, z=172.50], EntityCrackedPigZombie['Cracked PigZombie'/10008, l='MpServer', x=182.50, y=70.00, z=320.50], EntityConcussionCreeper['Concussion Creeper'/10052, l='MpServer', x=204.50, y=36.00, z=250.50], EntityCrackedZombie['Cracked Zombie'/10054, l='MpServer', x=273.50, y=70.00, z=222.50], EntitySpider['Spider'/10137, l='MpServer', x=167.50, y=32.00, z=291.50], EntityCrackedZombie['Cracked Zombie'/10165, l='MpServer', x=148.50, y=67.00, z=328.50], EntityWitch['Witch'/10194, l='MpServer', x=245.50, y=13.00, z=225.50], EntityBat['Bat'/6586, l='MpServer', x=205.68, y=38.14, z=248.72], EntityItem['item.tile.torch'/6853, l='MpServer', x=209.89, y=76.00, z=229.88], EntityCrackedPigZombie['Cracked PigZombie'/6884, l='MpServer', x=176.50, y=68.00, z=279.50], EntitySpider['Spider'/7258, l='MpServer', x=232.08, y=67.25, z=245.07], EntityBat['Bat'/7296, l='MpServer', x=163.31, y=41.58, z=187.60], EntityItem['item.tile.flower2.tulipRed'/7311, l='MpServer', x=217.89, y=62.00, z=292.14], EntityCrackedZombie['Cracked Zombie'/3372, l='MpServer', x=186.65, y=64.00, z=228.70], EntityBat['Bat'/7492, l='MpServer', x=196.16, y=43.66, z=260.70], EntityItem['item.item.feather'/7504, l='MpServer', x=190.37, y=78.00, z=190.43], EntityHuman['Zackary'/7580, l='MpServer', x=221.65, y=76.00, z=239.29], EntityItem['item.item.rottenFlesh'/7659, l='MpServer', x=232.43, y=77.00, z=244.88], EntityCrackedZombie['Cracked Zombie'/7729, l='MpServer', x=157.50, y=72.00, z=290.50], EntityItem['item.item.rottenFlesh'/7786, l='MpServer', x=237.69, y=77.00, z=244.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1009625208 bytes (962 MB) / 2220359680 bytes (2117 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.0.2007 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2007-1.10.0.jar) 
	UCHIJAAAA	Forge{12.18.0.2007} [Minecraft Forge] (forge-1.10.2-12.18.0.2007-1.10.0.jar) 
	UCHIJAAAA	ArrowFix{1.1} [Tipped Arrow Fixer] (ArrowFix-1.1.jar) 
	UCHIJAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10-3.0.2a.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	BetterHorseHud{1.0} [Better Horse Hud] (BetterHorseHud-[1.9-1.10.2]-1.0.jar) 
	UCHIJAAAA	JEI{3.7.5.227} [Just Enough Items] (jei_1.10.2-3.7.5.227.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.2-50} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-50.jar) 
	UCHIJAAAA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9.4-1.4.1.jar) 
	UCHIJAAAA	Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-1.9.4-2.1.5.jar) 
	UCHIJAAAA	ChestTransporter{2.5.0} [Chest Transporter] (ChestTransporter-1.10-2.5.0.jar) 
	UCHIJAAAA	chiselsandbits{11.5} [Chisels & Bits] (chiselsandbits-11.5.jar) 
	UCHIJAAAA	combathelp{1.0.3} [Combat Help] (combathelp-1.9.4-1.0.3.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.10.2-v1} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v1.jar) 
	UCHIJAAAA	crackedzombiemod{3.5.2} [CrackedZombie Mod] (crackedzombiemod-1.10.2-3.5.2-75.jar) 
	UCHIJAAAA	enchiridion{3.1.6} [Enchiridion] (Enchiridion-1.9.4-3.1.6.jar) 
	UCHIJAAAA	endores{1.0-a.011} [End Ores] (End Ores-1.0-a.011.jar) 
	UCHIJAAAA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJAAAA	fastleafdecay{v10} [Fast Leaf Decay] (FastLeafDecay-v10.jar) 
	UCHIJAAAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAA	IronChest{7.0.6.794} [Iron Chest] (ironchest-1.10.2-7.0.6.794.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.6.41} [Just Enough Resources] (JustEnoughResources-1.10.2-0.4.6.41.jar) 
	UCHIJAAAA	levels{r4.1.2} [Levels] (Levels-1.10.2-r4.1.2.jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.2} [RadixCore] (RadixCore-1.10.2-2.1.2-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.0} [Minecraft Comes Alive] (MCA-1.10.2-5.2.0-universal.jar) 
	UCHIJAAAA	miab{1.4.2} [Meme in a bottle] (MemeInABottle-1.4.2-1.10.2.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-4.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJAAAA	nethercore{1.10.2-2.0.2} [Nether Core] (nethercore-1.10.2-2.0.2.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCHIJAAAA	Pillar{1.0-3} [Pillar] (Pillar-1.0-3.jar) 
	UCHIJAAAA	Quark{beta-41} [Quark] (Quark-beta-41.jar) 
	UCHIJAAAA	reap{1.3.0} [Reap Mod] (ReapMod 1.3.0.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.2.419} [Reliquary] (Reliquary-1.10.2-1.3.2.419.jar) 
	UCHIJAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	roots{0.107} [Roots] (roots-0.107.jar) 
	UCHIJAAAA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.3-1.10.2.jar) 
	UCHIJAAAA	Souls{1.0.2} [Souls] (Souls-1.10.2-1.0.2.jar) 
	UCHIJAAAA	soulshardstow{1.10-2.5.0-34} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10-2.5.0-34.jar) 
	UCHIJAAAA	StellarAPI{0.5.4.1.2} [Stellar API] (Stellar API-0.5.4.1.2.jar) 
	UCHIJAAAA	stellarsky{0.5.5.1.6} [Stellar Sky] (Stellar Sky-0.5.5.1.6.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.1.11} [Storage Drawers] (StorageDrawers-1.9.4-3.1.11.jar) 
	UCHIJAAAA	supercraftingframe{1.2.0.85} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.0.85.jar) 
	UCHIJAAAA	totemic{1.9.4-0.7.6} [Totemic] (Totemic-1.9.4-0.7.6.jar) 
	UCHIJAAAA	underphangables{1.0.2} [Underp Hangables] (underphangables-1.10.2-1.0.2.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCHIJAAAA	xlib{r2.0.1} [xLib] (xLib-1.10-r2.0.1.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (Quark-beta-41.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.82' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: forge-12.18.0.2007
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz

**Comment by WildBamaBoy** [comment]
#733
