### ISSUE TITLE
Completely Repro-able crash looking at tombstones

### ISSUE THREAD

**Issue by archonsd** [WildBamaBoy/minecraft-comes-alive#739]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions
MC version 1.10.2
MCA version 5.20

## Issue Description
Completely reproducible crash with just MCA 5.20, RadixCore, Forge and MC 1.10.2

## Reproduce Steps
 1] Launch client
 2] Create world with 'default' biome type on Survival
 3] Right click the crystal ball
 4] Right click the crafting table
 5] Select 'I am male'
 6] Select 'I prefer females'
 7] Select 'I live in a village'
 8] Walk through the village to the graveyard on the right.
 9] Turn toward *any* of the headstone's faces that contain text
10] Enjoy cyan-blue crash screen.
11] Repeat unlimitedly.  It's 100% reproducible.

## Additional Information
Crash report with just MCA, RADIX, Forge and MC:  http://pastebin.com/3xbvAFpm

**Comment by WildBamaBoy** [comment]
#738 #733. Check for the issue before posting.
