### ISSUE TITLE
dead person

### ISSUE THREAD

**Issue by billydefsffvVerb** [WildBamaBoy/minecraft-comes-alive#740]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Additional Information
Read this!! when ever i right clicked on a dead baby to place it, it crashes my game and now i cant get into my world compleatly i just wann a play on it again. please help and please fix!!!!!

**Comment by mezzodrinker** [comment]
Is this supposed to be a joke? You used the template but didn't even fill in the information that was asked. It even provides you with descriptions of what you need to do or fill in.
