### ISSUE TITLE
Trapped and Forever alone!

### ISSUE THREAD

**Issue by DPxKnightxZero** [WildBamaBoy/minecraft-comes-alive#743]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
Minecraft Version: 1.10.2
{U}-MCA-1.10.2-5.2.0-universal.jar
{U}-RadixCore-1.10.2-2.1.2-universal.jar

## Issue Description
I used in orb in my house next to a chest and essentially cannot escape the orb room in single player!

 
## Reproduce Steps
Grab or make sure your in-front of a chest about 3 blocks away or less ... and use it. The table with the book on it will always open your chest immediately after using the book table.

## Additional Information
I think just add are you sure you want to use this here? (Warning near chests or items that can be activated may cause you to be trapped in a selection room!)

**Comment by WildBamaBoy** [comment]
You can simply exit the game and log in again to get rid of the orb room and move to a better location.
