### ISSUE TITLE
Crash with Whistle

### ISSUE THREAD

**Issue by mrdeadlocked** [WildBamaBoy/minecraft-comes-alive#745]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Additional Information

Here is the error message teh server console shows. The client just gets disconnected on item use.
http://pastebin.com/2K4fnuaY

**Comment by WildBamaBoy** [comment]
Please provide the client log too

**Comment by WildBamaBoy** [comment]
Found the issue.
