### ISSUE TITLE
Ticking entity crash in 1.7.10, resulting in the disappearance of all villager

### ISSUE THREAD

**Issue by tanto259** [WildBamaBoy/minecraft-comes-alive#746]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions
Minecraft 1.7.10
MCA 1.7.10-5.2.0

## Issue Description
Updating the map from an older version of MCA cause a Ticking Entity crash. After the crash, the world could load successfully, but all MCA villager disappear.

## Reproduce Steps
1. Update the mod to the latest version.
2, Load an older version savegame.

## Additional Information
Crash report: [https://paste.ee/p/DKPsd](https://paste.ee/p/DKPsd)
Full log: [https://paste.ee/p/t8tnu](https://paste.ee/p/t8tnu)

EDIT: The crash only remove villager in a few chunks, teleporting to another village far away resulted in the same crash.
EDIT2: Seems similar with #731 but on different Minecraft version.

**Comment by WildBamaBoy** [comment]
Fixed in 5.2.1
