### ISSUE TITLE
Not really an issue more of a question

### ISSUE THREAD

**Issue by tyler489** [WildBamaBoy/minecraft-comes-alive#748]
Using minecraft 1.7.10 is it possible to give Diferent weapons to guards like a diamond sword with enchants?

**Comment by Andre-Maartens** [comment]
yes, but with mcedit, + NBTExplorer

**Comment by Andre-Maartens** [comment]
well that's how i did it

**Comment by WildBamaBoy** [comment]
^ Would be the only way. No built-in way to do this.

**Comment by tyler489** [comment]
could u add a config by chance that says guards will spawn with this item
localized item name

or is that not possible
