### ISSUE TITLE
Crash when looking at Choo Choo train.

### ISSUE THREAD

**Issue by SimplyStars** [WildBamaBoy/minecraft-comes-alive#749]
- [Yes] I am running the latest mod versions of MCA and RadixCore.
- [No] I can reproduce this issue with just MCA and RadixCore installed.
- [Yes] I can provide my Minecraft version and MCA version.
- [Yes] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [Yes] I am crashing and can provide my crash report.

## Versions
1.10.2 Minecraft, MCA-1.10.2-5.2.0-universal.jar

## Issue Description
So I uh, I look at a choo-choo train on the ground. And I freeze, then crash.
Pretty simple.

## Reproduce Steps
Have a son, let it spawn a choo-choo. Look at choo-choo. results.

## Additional Information
Note I am running with multiple mods.
Heres is the crash report,
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.6.jar)
  LoadingPlugin (Quark-beta-41.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.38-beta.jar)
  CorePlugin (FluxedRedstone-2.2.1.44.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10-2.0.13.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/11/16 8:30 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1936)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1330)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1936)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1330)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['starcatcher77'/147, l='MpServer', x=-261.61, y=68.00, z=1280.05]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 639116 game time, 218603 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 41 total; [EntityMinecartChest['Minecart with Chest'/256, l='MpServer', x=-236.50, y=21.06, z=1314.50], EntityMinecartChest['Minecart with Chest'/257, l='MpServer', x=-249.50, y=27.06, z=1331.50], EntityHuman['Rest in peace I AM SWEG'/3075, l='MpServer', x=-260.10, y=68.00, z=1279.50], EntityHuman['Linda'/273, l='MpServer', x=-253.32, y=65.00, z=1279.17], EntityMinecartChest['Minecart with Chest'/275, l='MpServer', x=-276.50, y=26.06, z=1307.50], EntityOtherPlayerMP['darkskull8'/350, l='MpServer', x=-261.83, y=68.00, z=1279.26], EntityOtherPlayerMP['darkskull8'/350, l='MpServer', x=-256.27, y=36.00, z=1325.72], EntitySkeleton['Skeleton'/52013, l='MpServer', x=-258.31, y=36.00, z=1288.51], EntityOtherPlayerMP['darkskull8'/350, l='MpServer', x=-260.11, y=65.94, z=1284.03], EntityHuman['Daniel'/66894, l='MpServer', x=-255.72, y=64.94, z=1285.50], EntityOtherPlayerMP['darkskull8'/350, l='MpServer', x=-259.99, y=66.00, z=1290.65], EntityHuman['Kenda'/129, l='MpServer', x=-246.46, y=69.00, z=1268.83], EntityHuman['Jamaal'/130, l='MpServer', x=-241.51, y=69.00, z=1266.73], EntityMinecartChest['Minecart with Chest'/131, l='MpServer', x=-235.50, y=26.06, z=1292.50], EntityHuman['Gabriela'/132, l='MpServer', x=-246.07, y=65.00, z=1301.25], EntityHuman['Lucey'/134, l='MpServer', x=-262.52, y=68.00, z=1274.94], EntityHuman['Rhianna'/135, l='MpServer', x=-268.18, y=71.00, z=1261.50], EntityHuman['Rhianna II'/136, l='MpServer', x=-260.41, y=66.00, z=1288.02], EntityHuman['Adrienne'/137, l='MpServer', x=-252.34, y=69.86, z=1263.77], EntityHuman['Maryjane'/138, l='MpServer', x=-257.58, y=68.94, z=1259.94], EntityHuman['Lewis'/139, l='MpServer', x=-258.48, y=68.00, z=1281.22], EntityHuman['Tesha'/140, l='MpServer', x=-244.56, y=65.00, z=1286.69], EntityHuman['Ena'/141, l='MpServer', x=-236.50, y=65.94, z=1270.29], EntityHuman['Wilford'/142, l='MpServer', x=-262.00, y=66.00, z=1288.44], EntityHuman['Norberto'/143, l='MpServer', x=-254.93, y=66.00, z=1286.70], EntityHuman['Nettie'/144, l='MpServer', x=-264.08, y=66.00, z=1286.70], EntityHuman['Lanny'/145, l='MpServer', x=-230.74, y=64.00, z=1288.46], EntityHuman['Clemencia'/146, l='MpServer', x=-242.81, y=66.50, z=1279.39], EntityPlayerSP['starcatcher77'/147, l='MpServer', x=-261.61, y=68.00, z=1280.05], EntityOtherPlayerMP['darkskull8'/66986, l='MpServer', x=-261.83, y=68.00, z=1279.26], EntityMinecartChest['Minecart with Chest'/208, l='MpServer', x=-253.50, y=22.06, z=1353.51], EntityMinecartChest['Minecart with Chest'/223, l='MpServer', x=-222.50, y=41.06, z=1355.50], EntityMinecartChest['Minecart with Chest'/224, l='MpServer', x=-201.50, y=20.06, z=1340.50], EntityHuman['Krystle'/239, l='MpServer', x=-246.66, y=69.00, z=1268.48], EntityHuman['Jerold'/240, l='MpServer', x=-247.42, y=66.00, z=1279.08], EntityHuman['Cristobal'/241, l='MpServer', x=-224.68, y=64.00, z=1287.52], EntityHuman['Napoleon'/242, l='MpServer', x=-262.25, y=70.00, z=1261.26], EntityHuman['Louis'/243, l='MpServer', x=-256.50, y=65.00, z=1278.33], EntityMinecartChest['Minecart with Chest'/244, l='MpServer', x=-275.50, y=33.06, z=1337.50], EntityHuman['Lavina'/245, l='MpServer', x=-245.50, y=64.94, z=1291.67], EntityHuman['Bertram'/246, l='MpServer', x=-263.28, y=66.00, z=1296.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 830297912 bytes (791 MB) / 2954944512 bytes (2818 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 1, allocated: 0, tallocated: 92
	FML: MCP 9.32 Powered by Forge 12.18.0.2010 83 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2010.jar) 
	UCHIJAAAA	Forge{12.18.0.2010} [Minecraft Forge] (forge-1.10.2-12.18.0.2010.jar) 
	UCHIJAAAA	backpacks16840{3.1.1} [Backpacks!] (zz-backpacks 1.10.2 - 3.1.1.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r49} [Actually Additions] (ActuallyAdditions-1.10.2-r49.jar) 
	UCHIJAAAA	JEI{3.7.4.224} [Just Enough Items] (jei_1.10.2-3.7.4.224(1).jar) 
	UCHIJAAAA	AppleCore{1.3.5} [AppleCore] (AppleCore-mc1.10.2-1.3.5.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	BetterAchievements{0.3.0.28} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.28.jar) 
	UCHIJAAAA	BetterFoliage{2.0.13} [Better Foliage] (BetterFoliage-MC1.10-2.0.13.jar) 
	UCHIJAAAA	bettertitlescreen{1.2e} [Better Title Screen] (BetterTitleScreen-1.10.2-1.2e.jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2033} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2033-universal.jar) 
	UCHIJAAAA	Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.6} [Chameleon] (Chameleon-1.9.4-2.1.6.jar) 
	UCHIJAAAA	mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-1.2.0-universal.jar) 
	UCHIJAAAA	CharsetLib{0.3.0-pre12} [â€½] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetAudio{0.3.0-pre12} [â™«] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetCarts{0.3.0-pre12} [U] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetDecoration{0.3.0-pre12} [âš?] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetDrama{0.3.0-pre12} [!] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetFarming{0.3.0-pre12} [;] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetGates{0.3.0-pre12} [&] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetPipes{0.3.0-pre12} [|] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetStorage{0.3.0-pre12} [#] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetTweaks{0.3.0-pre12} [*] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetWires{0.3.0-pre12} [+] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	CharsetWrench{0.3.0-pre12} [/] (Charset-0.3.0-pre12(1).jar) 
	UCHIJAAAA	ChatFlow{ANT:VERSION} [ChatFlow] (ChatFlow-1.2-5(1).jar) 
	UCHIJAAAA	chiselsandbits{11.5} [Chisels & Bits] (chiselsandbits-11.5.jar) 
	UCHIJAAAA	cyclopscore{0.7.1} [Cyclops Core] (CyclopsCore-1.9.4-0.7.1.jar) 
	UCHIJAAAA	Ding{MC1.9.0v2} [Ding] (Ding-1.10.2-1.0.0.jar) 
	UCHIJAAAA	DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.38-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.38-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.67_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.67_beta.jar) 
	UCHIJAAAA	evilcraft{0.10.5} [EvilCraft] (EvilCraft-1.9.4-0.10.5.jar) 
	UCHIJAAAA	reborncore{2.5.5.3} [RebornCore] (RebornCore-1.10.2-2.5.5.3-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.5.5.3} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.5.5.3-universal.jar) 
	UCHIJAAAA	Tesla{1.1.0.24} [TESLA] (Tesla-1.9.4-1.1.0.24.jar) 
	UCHIJAAAA	fluxedredstone{2.2.1.44} [FluxedRedstone] (FluxedRedstone-2.2.1.44.jar) 
	UCHIJAAAA	forestry{5.1.10.192} [Forestry] (forestry_1.10.2-5.1.10.192.jar) 
	UCHIJAAAA	gravestone{1.5.0} [Gravestone] (Gravestone Mod 1.5.0.jar) 
	UCHIJAAAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHIJAAAA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.6.41} [Just Enough Resources] (JustEnoughResources-1.10.2-0.4.6.41.jar) 
	UCHIJAAAA	kleeslabs{3.3.1} [KleeSlabs] (KleeSlabs-mc1.10-3.3.1.jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.2} [RadixCore] (RadixCore-1.10.2-2.1.2-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.0} [Minecraft Comes Alive] (MCA-1.10.2-5.2.0-universal.jar) 
	UCHIJAAAA	mfs{4.0.0} [Minecraft Flight Simulator] (Minecraft Flight Simulator-1.10.2-4.0.0.jar) 
	UCHIJAAAA	minemenu{1.4.4} [MineMenu] (MineMenu-1.10.X-1.4.4.B9-universal.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	morefood{1.15d} [More Foods] (morefood-1.9.4-1909-1.16.jar) 
	UCHIJAAAA	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-4.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.2-beta.4} [OpenComputers] (OpenComputers-MC1.10-1.6.0.2-beta.4.jar) 
	UCHIJAAAA	packingtape{0.5.2} [Packing Tape] (PackingTape-1.9.4-0.5.2.jar) 
	UCHIJAAAA	progressiveautomation{1.6.48} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.48.jar) 
	UCHIJAAAA	Quark{beta-41} [Quark] (Quark-beta-41.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.2.419} [Reliquary] (Reliquary-1.10.2-1.3.2.419.jar) 
	UCHIJAAAA	shadowmc{3.4.1} [ShadowMC] (ShadowMC-1.10.2-3.4.1.jar) 
	UCHIJAAAA	SleepingBag{1.2.1} [Sleeping Bag] (SleepingBag-1.9.4-1.2.1.jar) 
	UCHIJAAAA	soulshardstow{1.10.2-2.5.2-36} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.5.2-36.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.3} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.3.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAA	techreborn{1.3.2.1} [TechReborn] (TechReborn-1.10.2-1.3.2.1-universal.jar) 
	UCHIJAAAA	lteleporters{1.1.3} [Lemon's Simple Teleporters] (teleporters-1.1.3.jar) 
	UCHIJAAAA	ToughAsNails{1.0.6} [Tough As Nails] (ToughAsNails-1.9.4-1.0.6.jar) 
	UCHIJAAAA	vending{1.3.4} [vending] (vending-1.9.4-1.3.4.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCHIJAAAA	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAA	wawla{2.3.0.193} [What Are We Looking At] (Wawla-1.10-2.3.0.193.jar) 
	UCHIJAAAA	xlfoodmod{1.10.2-0.1.1} [XL Food Mod] (XL Food Mod-1.10.2-0.1.1.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  squeek.applecore.asm.TransformerModuleHandler
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.6.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
LoadingPlugin (Quark-beta-41.jar)
  vazkii.quark.base.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.38-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CorePlugin (FluxedRedstone-2.2.1.44.jar)
  
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.10-2.0.13.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
BCModPlugin (zz-backpacks 1.10.2 - 3.1.1.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5450'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/ActuallyAdditions-1.10.2-r49.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/ActuallyAdditions-1.10.2-r49.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/ActuallyAdditions-1.10.2-r49.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/ActuallyAdditions-1.10.2-r49.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/ActuallyAdditions-1.10.2-r49.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/ActuallyAdditions-1.10.2-r49.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/ActuallyAdditions-1.10.2-r49.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/ActuallyAdditions-1.10.2-r49.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/EnderIO-1.10.2-3.0.1.67_beta.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/starc/AppData/Roaming/.minecraft/modpacks/survivalplus/mods/EnderIO-1.10.2-3.0.1.67_beta.jar!/cofh/api/energy/TileEnergyHandler.class

	Launched Version: 1.10.2-forge1.10.2-12.18.0.2010
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz

**Comment by tanto259** [comment]
In my opinion this looks similar to #733 if it is so, then it should be fixed in the next version.

**Comment by SimplyStars** [comment]
Your quite right, I hadn't seen that. Do you know when that update is coming out?

**Comment by tanto259** [comment]
Unfortunately I don't.

**Comment by WildBamaBoy** [comment]
#733
