### ISSUE TITLE
Crash when player attacks hostile mob

### ISSUE THREAD

**Issue by Cat-McCatface** [WildBamaBoy/minecraft-comes-alive#751]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions
MC: 1.10.2
Forge: 2010
MCA-1.10.2-5.2.0
RadixCore-1.10.2-2.1.2

## Issue Description
When player attacks a hostile mob game has chance of crashing. Seems limited to a server that doesn't support MCA. Suspected Better Combat was interacting but still crashes when it's removed.

## Reproduce Steps
Find something hostile and hit it.
_Important step may be to be on a spigot server/no MCA support_.
May be triggered within proximity if village.

## Additional Information
[crash-2016-07-13_04.59.55-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/361226/crash-2016-07-13_04.59.55-client.txt)
[crash-2016-07-13_05.35.51-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/361280/crash-2016-07-13_05.35.51-client.txt)

**Comment by WildBamaBoy** [comment]
#734
