### ISSUE TITLE
MCA 1.10.2 crash to white screen in villager interactions

### ISSUE THREAD

**Issue by Jgking876** [WildBamaBoy/minecraft-comes-alive#753]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

Minecraft Version 1.10.2
Forge Version 12.18.1.2013
MCA Version 5.2.0
RadixCore Version 2.1.2

After starting a new world and summoning a village, the game ran for a few moments until trading with a villager. Then the screen went gray/white and the game crashed. Now when I reload the world the world starts to load (I see the game cursor but a black screen) then it goes to the white screen and crashes.

Don't really know here, since the issue presents itself almost immediately after starting a village. After multiple attempts, it seems to be something revolving around the spawned village and interacting with villagers.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
Time: 7/13/16 11:46 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1936)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1330)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1936)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1330)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['tizzizight876'/311, l='MpServer', x=-313.11, y=67.00, z=-188.36]]
	Chunk stats: MultiplayerChunkCache: 328, 328
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-244,64,-72), Chunk: (at 12,4,8 in -16,-5; contains blocks -256,0,-80 to -241,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 7253 game time, 7253 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 109 total; [EntityBat['Bat'/15, l='MpServer', x=-387.36, y=15.00, z=-265.43], EntityPig['Pig'/16, l='MpServer', x=-384.74, y=70.00, z=-257.22], EntityPig['Pig'/18, l='MpServer', x=-389.72, y=70.00, z=-252.50], EntityBat['Bat'/27, l='MpServer', x=-389.16, y=19.45, z=-188.11], EntityBat['Bat'/32, l='MpServer', x=-387.48, y=38.87, z=-170.60], EntityBat['Bat'/34, l='MpServer', x=-384.45, y=36.03, z=-157.31], EntityItem['item.item.seeds'/56, l='MpServer', x=-364.74, y=68.00, z=-227.76], EntityItem['item.item.seeds'/57, l='MpServer', x=-362.27, y=67.00, z=-231.03], EntityItem['item.item.seeds'/58, l='MpServer', x=-359.42, y=67.00, z=-229.05], EntityItem['item.item.seeds'/59, l='MpServer', x=-361.47, y=67.00, z=-228.72], EntityItem['item.tile.sapling.acacia'/60, l='MpServer', x=-364.95, y=68.00, z=-226.89], EntityItem['item.item.seeds'/61, l='MpServer', x=-362.09, y=67.00, z=-223.90], EntityItem['item.item.porkchopRaw'/62, l='MpServer', x=-338.72, y=67.00, z=-210.04], EntityItem['item.item.porkchopRaw'/63, l='MpServer', x=-347.90, y=67.00, z=-221.21], EntityItem['item.item.porkchopRaw'/64, l='MpServer', x=-339.31, y=67.00, z=-217.41], EntityItem['item.item.porkchopRaw'/65, l='MpServer', x=-340.95, y=67.00, z=-208.35], EntityBat['Bat'/66, l='MpServer', x=-344.36, y=50.10, z=-205.57], EntityItem['item.item.porkchopRaw'/67, l='MpServer', x=-337.23, y=67.00, z=-193.24], EntityItem['item.item.porkchopRaw'/68, l='MpServer', x=-339.74, y=67.00, z=-202.78], EntityPig['Pig'/74, l='MpServer', x=-325.72, y=67.00, z=-239.37], EntityPig['Pig'/75, l='MpServer', x=-332.50, y=67.00, z=-238.25], EntityPig['Pig'/76, l='MpServer', x=-330.50, y=67.00, z=-231.75], EntityItem['item.item.seeds'/77, l='MpServer', x=-322.87, y=67.00, z=-231.88], EntityItem['item.item.seeds'/78, l='MpServer', x=-322.22, y=67.00, z=-229.40], EntityItem['item.item.porkchopRaw'/79, l='MpServer', x=-333.83, y=67.00, z=-230.70], EntityItem['item.item.seeds'/80, l='MpServer', x=-326.90, y=67.00, z=-217.07], EntityItem['item.item.seeds'/81, l='MpServer', x=-329.06, y=67.00, z=-222.93], EntityItem['item.item.seeds'/82, l='MpServer', x=-321.56, y=67.00, z=-214.77], EntityItem['item.item.seeds'/83, l='MpServer', x=-322.49, y=68.50, z=-221.70], EntityHuman['Emelia'/84, l='MpServer', x=-330.00, y=67.00, z=-216.00], EntityItem['item.item.seeds'/85, l='MpServer', x=-327.40, y=67.00, z=-223.49], EntityItem['item.item.seeds'/86, l='MpServer', x=-335.25, y=67.00, z=-196.12], EntityItem['item.item.seeds'/87, l='MpServer', x=-330.13, y=68.00, z=-198.40], EntityHuman['Dorsey'/88, l='MpServer', x=-326.76, y=67.00, z=-205.42], EntityHuman['Pei'/89, l='MpServer', x=-321.23, y=67.00, z=-197.56], EntityHuman['Cleveland'/90, l='MpServer', x=-323.71, y=67.00, z=-195.49], EntityHuman['Sam'/91, l='MpServer', x=-326.49, y=67.00, z=-191.76], EntityHuman['Clarita'/92, l='MpServer', x=-333.00, y=67.00, z=-187.00], EntityHuman['Jone'/93, l='MpServer', x=-321.00, y=67.00, z=-187.00], EntityPig['Pig'/100, l='MpServer', x=-307.46, y=68.00, z=-263.00], EntityPig['Pig'/101, l='MpServer', x=-308.82, y=68.00, z=-256.25], EntityBat['Bat'/102, l='MpServer', x=-313.25, y=23.22, z=-255.36], EntityPig['Pig'/103, l='MpServer', x=-304.78, y=68.00, z=-254.25], EntityPig['Pig'/104, l='MpServer', x=-316.22, y=68.00, z=-253.78], EntityPig['Pig'/105, l='MpServer', x=-317.77, y=68.00, z=-243.26], EntityPig['Pig'/106, l='MpServer', x=-311.58, y=69.00, z=-237.01], EntityItem['item.item.seeds'/107, l='MpServer', x=-316.13, y=67.00, z=-226.19], EntityItem['item.tile.flower2.poppy'/108, l='MpServer', x=-315.88, y=67.00, z=-225.13], EntityItem['item.item.seeds'/109, l='MpServer', x=-315.12, y=67.00, z=-226.02], EntityItem['item.tile.flower2.poppy'/110, l='MpServer', x=-315.08, y=68.00, z=-233.25], EntityItem['item.item.seeds'/111, l='MpServer', x=-307.50, y=67.00, z=-227.83], EntityItem['item.item.seeds'/112, l='MpServer', x=-318.65, y=67.00, z=-226.29], EntityItem['item.item.seeds'/113, l='MpServer', x=-316.84, y=68.00, z=-233.35], EntityItem['item.item.seeds'/114, l='MpServer', x=-308.44, y=69.00, z=-234.32], EntityPig['Pig'/115, l='MpServer', x=-311.94, y=69.00, z=-235.92], EntityItem['item.item.seeds'/116, l='MpServer', x=-319.35, y=67.00, z=-216.63], EntityItem['item.item.seeds'/117, l='MpServer', x=-319.82, y=67.00, z=-223.14], EntityItem['item.tile.flower2.poppy'/118, l='MpServer', x=-316.33, y=67.00, z=-223.20], EntityItem['item.item.seeds'/119, l='MpServer', x=-319.66, y=67.00, z=-219.00], EntityHuman['Isreal'/120, l='MpServer', x=-306.70, y=68.00, z=-218.70], EntityCow['Cow'/121, l='MpServer', x=-306.77, y=68.00, z=-217.52], EntityCow['Cow'/122, l='MpServer', x=-310.50, y=67.00, z=-223.20], EntityHuman['Darron'/123, l='MpServer', x=-315.52, y=67.00, z=-203.66], EntityHuman['Willis'/124, l='MpServer', x=-311.38, y=67.00, z=-184.93], EntityChicken['Chicken'/125, l='MpServer', x=-309.86, y=69.00, z=-163.68], EntityItem['item.item.egg'/126, l='MpServer', x=-312.73, y=67.00, z=-171.89], EntityPig['Pig'/129, l='MpServer', x=-299.69, y=67.00, z=-266.44], EntityItem['item.item.seeds'/130, l='MpServer', x=-301.88, y=67.00, z=-226.08], EntityItem['item.item.seeds'/131, l='MpServer', x=-299.55, y=67.00, z=-225.36], EntityItem['item.item.seeds'/132, l='MpServer', x=-300.54, y=68.00, z=-232.62], EntityItem['item.item.seeds'/133, l='MpServer', x=-299.84, y=68.00, z=-216.61], EntityItem['item.item.seeds'/134, l='MpServer', x=-297.31, y=67.00, z=-220.22], EntityCow['Cow'/135, l='MpServer', x=-291.73, y=67.00, z=-223.81], EntityItem['item.item.seeds'/136, l='MpServer', x=-298.08, y=67.00, z=-207.84], EntityPlayerSP['tizzizight876'/311, l='MpServer', x=-313.11, y=67.00, z=-188.36], EntityHuman['Temeka'/137, l='MpServer', x=-293.54, y=67.00, z=-205.69], EntityHuman['Mercy'/138, l='MpServer', x=-297.15, y=67.00, z=-201.45], EntityItem['item.tile.flower2.houstonia'/139, l='MpServer', x=-296.20, y=67.00, z=-182.03], EntityItem['item.tile.flower2.houstonia'/140, l='MpServer', x=-294.66, y=67.00, z=-187.03], EntityItem['item.item.seeds'/141, l='MpServer', x=-303.49, y=67.00, z=-173.97], EntityItem['item.item.seeds'/142, l='MpServer', x=-299.02, y=69.00, z=-167.56], EntityChicken['Chicken'/143, l='MpServer', x=-288.53, y=68.00, z=-174.18], EntityItem['item.item.egg'/144, l='MpServer', x=-296.41, y=67.00, z=-170.54], EntityPig['Pig'/145, l='MpServer', x=-291.75, y=67.00, z=-116.46], EntityPig['Pig'/146, l='MpServer', x=-294.50, y=67.00, z=-116.50], EntityPig['Pig'/147, l='MpServer', x=-292.50, y=67.00, z=-112.50], EntityPig['Pig'/148, l='MpServer', x=-299.34, y=66.00, z=-111.52], EntitySquid['Squid'/156, l='MpServer', x=-280.60, y=52.29, z=-230.60], EntitySquid['Squid'/157, l='MpServer', x=-281.47, y=53.00, z=-229.36], EntityCow['Cow'/158, l='MpServer', x=-280.18, y=67.00, z=-201.44], EntityItem['item.tile.flower2.oxeyeDaisy'/159, l='MpServer', x=-286.92, y=67.00, z=-187.13], EntityItem['item.tile.flower2.oxeyeDaisy'/160, l='MpServer', x=-287.57, y=67.00, z=-184.59], EntityChicken['Chicken'/161, l='MpServer', x=-284.87, y=69.00, z=-171.63], EntityChicken['Chicken'/162, l='MpServer', x=-275.87, y=69.00, z=-169.68], EntitySheep['Sheep'/163, l='MpServer', x=-272.32, y=68.00, z=-134.18], EntityBat['Bat'/172, l='MpServer', x=-272.76, y=52.81, z=-178.73], EntitySheep['Sheep'/173, l='MpServer', x=-264.50, y=68.00, z=-132.21], EntitySheep['Sheep'/174, l='MpServer', x=-266.50, y=68.00, z=-126.50], EntitySheep['Sheep'/175, l='MpServer', x=-265.50, y=68.00, z=-126.50], EntityCow['Cow'/176, l='MpServer', x=-260.53, y=68.00, z=-113.02], EntityCow['Cow'/177, l='MpServer', x=-270.19, y=68.00, z=-118.37], EntityCow['Cow'/178, l='MpServer', x=-263.09, y=68.00, z=-112.12], EntityCow['Cow'/179, l='MpServer', x=-261.67, y=68.00, z=-111.89], EntityBat['Bat'/195, l='MpServer', x=-248.00, y=40.76, z=-186.51], EntityBat['Bat'/196, l='MpServer', x=-250.20, y=54.40, z=-170.27], EntityCow['Cow'/197, l='MpServer', x=-240.35, y=70.00, z=-116.17], EntityPig['Pig'/199, l='MpServer', x=-239.50, y=93.00, z=-178.50], EntityPig['Pig'/201, l='MpServer', x=-236.50, y=101.00, z=-176.50], EntityPig['Pig'/202, l='MpServer', x=-238.50, y=87.00, z=-172.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:414)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 275561600 bytes (262 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.1.2013 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2013.jar) 
	UCHIJAAAA	Forge{12.18.1.2013} [Minecraft Forge] (forge-1.10.2-12.18.1.2013.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.2} [RadixCore] (RadixCore-1.10.2-2.1.2-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.0} [Minecraft Comes Alive] (MCA-1.10.2-5.2.0-universal.jar) 
	UCHIJAAAA	XaeroMinimap{1.9.7} [Xaero's Minimap] (Xaeros_Minimap_1.9.7_Forge_1.10.2.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
	Launched Version: 1.10.2-forge1.10.2-12.18.1.2013
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft  64x MC110.zip

**Comment by Jgking876** [comment]
It looks like it may be an issue with the Resource Pack I was using (Pure BD Craft for Minecraft 1.10.2). Disabling seems to allow the village to summon and operate correctly, will try trading and villager interactions to see if the issue occurs again with the resource pack disabled.

**Comment by Jgking876** [comment]
After some testing it does seem to be the resource pack. Ran great when disabled, but when activated it glitched out after a few moments.

**Comment by WildBamaBoy** [comment]
Really weird, but glad it ended up working out.
