### ISSUE TITLE
spouse bug

### ISSUE THREAD

**Issue by wesb1** [WildBamaBoy/minecraft-comes-alive#755]
version 1.7.10

my wife says she is married to me but It doesnt let me interact with her as if im her husband

**Comment by mezzodrinker** [comment]
Are you sure you're using the latest version (5.2.1)?

**Comment by WildBamaBoy** [comment]
Quoting the issue template: "DO NOT DELETE THE CONTENT ON THIS PAGE. FILL OUT ENTIRELY"
