### ISSUE TITLE
Village overun by MCA guards & Crash sometimes when villager AIProgressStory.doAgeBaby

### ISSUE THREAD

**Issue by MarikuJunrei** [WildBamaBoy/minecraft-comes-alive#763]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

# Versions minecraft 1.7.10  MCA-1.7.10-5.2.1-universal  RadixCore-1.7.10-2.1.2-universal

## Issue Description there seems to be an issue with villagers having babies. it doesnt seem to happen all the time but it has happend 3 times @ mca.ai.AIProgressStory.doAgeBaby
im not sure if this is directly realated but i have poseted on the forum my unique situation with a village being completely overrun by mca guards literally hundreds of them and i have gone and used butcher with world edit mutiple times to completely wipe out the village population but every time i come back there are more 

## Reproduce Steps
 i would assume have a village with a bunch of guards and see if it happens i dont exactly know how to reproduce this as i have yet to interact with this particular village this is on a freshly made server 

## Additional Information   
[crash-2016-07-30_05.44.21-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/391921/crash-2016-07-30_05.44.21-server.txt)
[crash-2016-07-30_07.15.06-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/391922/crash-2016-07-30_07.15.06-server.txt)
[crash-2016-07-27_01.18.27-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/391923/crash-2016-07-27_01.18.27-server.txt)
![2016-07-29_22 38 29](https://cloud.githubusercontent.com/assets/20741298/17271108/424d6fe0-5628-11e6-8bf5-d49a44f5261d.png)
![2016-07-29_22 42 32](https://cloud.githubusercontent.com/assets/20741298/17271112/51432170-5628-11e6-8c22-51dca60c9559.png)
![2016-07-28_16 57 40](https://cloud.githubusercontent.com/assets/20741298/17271115/6a828fb8-5628-11e6-90bb-83c48d3f1aee.png)
![image](https://cloud.githubusercontent.com/assets/20741298/17271129/b6bbd8b2-5628-11e6-89f1-85c820d81b34.png)

**Comment by WildBamaBoy** [comment]
Guard issue will be fixed with upcoming RadixCore update.
