### ISSUE TITLE
(Oversight?) Update to Vanilla Villages Roads in 1.9, MCA change to remain consistent?

### ISSUE THREAD

**Issue by Orange1861** [WildBamaBoy/minecraft-comes-alive#765]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
1.10.2
Latest MCA

## Issue Description
In Minecraft 1.9 vanilla village roads changed from gravel to dirt paths. MCA's crystal ball spawns structures that use gravel for roads. For consistent's sake the MCA roads should change to the (arguably) the more appealing dirt path.

## Additional Information
I believe this to be an oversight but if it isn't, I'll gladly move this to the MCA forum.

**Comment by WildBamaBoy** [comment]
I will keep that in mind, but it's not really a priority.
