### ISSUE TITLE
Villagers not sleeping in beds

### ISSUE THREAD

**Issue by Louhbo** [WildBamaBoy/minecraft-comes-alive#766]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

MCA Version 
MCA-1.10.2-5.2.1-universal.jar

Radix Core Version:
RadisCore-1.10.2-2.1.2-universal.jar

Minecraft Version:
Minecraft 1.10.2-forge1.10.2-12.18.1.2043

## Issue Description
Villagers will not sleep in villager beds.  

## Reproduce Steps
I have setup my own minecraft server with forge, the problem shows on the server as well as the singleplayer version.  I only used radixcore and mca mods.

**Comment by Orange1861** [comment]
Split this into two different issues:
1: Villagers don't sleep in beds.
2 Children fishing get stuck.

Don't put two issues in one.

**Comment by Louhbo** [comment]
lets just concentrate on the more annoying issue first

**Comment by Louhbo** [comment]
I did.

**Comment by Orange1861** [comment]
Thank you. I can confirm this issue.
