### ISSUE TITLE
Villagers address the player as "none"

### ISSUE THREAD

**Issue by Louhbo** [WildBamaBoy/minecraft-comes-alive#767]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

MCA Version 
MCA-1.10.2-5.2.1-universal.jar

Radix Core Version:
RadixCore-1.10.2-2.1.2-universal.jar

Minecraft Version:
Minecraft 1.10.2-forge1.10.2-12.18.1.2043

## Issue Description

Villagers address the player as "none" in interactions.  I notice this most with the wife, but other villagers also use it.  

## Reproduce Steps

I can reproduce this on the server version and single player version.  I only used radixcore and mca mods.

**Comment by WildBamaBoy** [comment]
Have you used the crystal ball before attempting to talk to a villager?

**Comment by Orange1861** [comment]
I can confirm this issue, I have used the crystal ball.

**Comment by Louhbo** [comment]
Yes, I have...this happens with multiple players

**Comment by A-Vladimir** [comment]
I am having the same issue. Playing single player using MCA-1.10.2-5.2.3-universal and RadixCore-1.10.2-2.1.3-universal.

**Comment by MinecraftMinun** [comment]
This happened to me too, I turned structure generation back on and it was fixed

**Comment by WildBamaBoy** [comment]
Should be fixed in next update.
