### ISSUE TITLE
Pressed Q while Holding a Baby, Crashed

### ISSUE THREAD

**Issue by Lisyre** [WildBamaBoy/minecraft-comes-alive#769]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions

MCA version 5.2.1, Minecraft version 1.10.2

## Issue Description

I pressed Q when I was holding a baby on a friend's multiplayer server and crashed.  When I try to log back in, my hotbar loads (no terrain) and I crash.  I found someone with the same problem in issue #741 , and modder said that the issue was fixed and provided a screenshot of some code.  Do I insert this into the mod somehow?  

## Reproduce Steps

-Logged onto friend's multiplayer server 
-Got married
-Adopted a baby
-Pressed Q while holding baby in primary hand
-Crashed
-Tried to log into the server again
-Crashed

## Additional Information
[I threw the baby and crashed.pdf](https://github.com/WildBamaBoy/minecraft-comes-alive/files/416367/I.threw.the.baby.and.crashed.pdf)     Crash report

**Comment by WildBamaBoy** [comment]
Acknowledged the issue still happening. Will fix that.

**Comment by bloodmc** [comment]
@WildBamaBoy This issue is still present on client-side for 1.10.2

http://pastebin.com/raw/5ebSm2aX

FMLCommonHandler.instance().getMinecraftServerInstance() is getting called on client side while connected to a dedicated server. The method being called on client is shown below

``` java
    @Nullable
    public IntegratedServer getIntegratedServer()
    {
        return this.theIntegratedServer;
    }
```

It is annotated as Nullable. A simple fix is to just add a isRemote check as this code should only be running on server side.

```
if (!world.isRemote) 
```

**Comment by WildBamaBoy** [comment]
Oops, acknowledged.
