### ISSUE TITLE
More flaws in village generation

### ISSUE THREAD

**Issue by MentalMouse** [WildBamaBoy/minecraft-comes-alive#776]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

MCA-1.10.2-5.2.2-universal.jar, RadixCore-1.10.2-2.1.3-universal.jar, Forge 2065

I chose "You live in a village", and had a couple of problems with the generated buildings.
1) Some of the roofs have full blocks on top, which can and do spawn mobs at night.  Yes, so do the vanilla villages, but MCA is otherwise much better about lighting things up and building to avoid spawns.
2) At the graveyard end of the village, there is a short ramp up to a higher area.  The buildings there have small gardens in front bordered by fences; unfortunately the ramp is next to those fences, which allows villagers to wander in and be trapped inside the fences.

**Comment by Galindorf** [comment]
I second this! The flower bed trap is particularly irksome; every time I start a new village I take the fences off the little flower beds, put torches on rooftops, and also take the "porch fences" off from the conjoined apartment buildings (people have a tendency to get stuck in them... especially those dang guards, whose main goal in life seems to be stuffing themselves into doorways and fence corners whenever possible)

**Comment by MentalMouse** [comment]
There's also a bit of cobble-wall near the graveyard that traps folks ina one-block spot -- I tried putting slabs in there, but eventually I realized I could move one post to eliminate the enclosure and reduce it to a decorative border for the higher bit.

**Comment by kilomonk** [comment]
Houses don't spawn in multiplayer LAN except for main player. goes from player gender and gender preference to wavy purple then to world - bypasses house type choices and enchantment table. Otherwise, seems to work great. Thanks. 1.10.2 on a macbook pro

**Comment by MentalMouse** [comment]
kilomonk:  I would guess this is an extension of the crystal ball not working for multiplayer, which is purposeful because of griefing issues.

**Comment by ThomasAunvik** [comment]
Would like to add an issue to any land generation:
When generating a place/village it will generate where you are. For example if you are inside a cave and you start MCA there. It will generate underground. It would be nice to generate the structure above the land, not inside.

**Comment by Galindorf** [comment]
Actually, I love that the village generates where you are! I made a cool 
underground bunker that way. And my "dwarf village" where I made everybody 
really short. haha :D

Sent with AquaMail for Android
http://www.aqua-mail.com
