### ISSUE TITLE
Villagers don't get Tier 1 trades, and don't advance trades correctly.

### ISSUE THREAD

**Issue by MentalMouse** [WildBamaBoy/minecraft-comes-alive#777]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

MCA-1.10.2-5.2.2-universal.jar, RadixCore-1.10.2-2.1.3-universal.jar, Forge 2065

I realized that while there's been discussion of this issue on the forums, it doesn't seem to be on github, so I'm putting it here for the record.

MCA villagers (possibly excepting a starting spouse) appear to begin with tier 2 trades, shutting players out from most of the staple trades needed to accumulate emeralds.  Further, when trading with them, they tend to add more tier 2 trades, including duplicates of their current trades.  

This forum poster (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-2-2-mc-1-10-2-1-9-4-1-9-1?comment=17120) discovered that they only advance to Tier 3 if their last offer is traded.

**Comment by Iteries** [comment]
Noted example to this thread, that the cleric or priest only do redstone and lapis trading, without MCA running you get to sell rotten flesh for emeralds.  As playing extends there been no other progress to have Villager editor to add/remove trades for customization.  At least in what I can figure out.
