### ISSUE TITLE
Crash version 1.10.2  near tombstone

### ISSUE THREAD

**Issue by TigeressMama9** [WildBamaBoy/minecraft-comes-alive#778]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

## Versions

1.10.2

## Issue Description

Game crashes near tombstone.  Now cannot open since child ended last game near tombstone
Go near the tombstone
## Reproduce Steps

[crash-2016-08-21_08.24.13-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/428869/crash-2016-08-21_08.24.13-client.txt)

**Comment by WildBamaBoy** [comment]
You are not using the latest version of MCA.
