### ISSUE TITLE
Children's hitboxes shrink after a while

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#781]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

Minecraft: 1.10.2 Forge
Forge: 12.18.1.2030
MCA 5.2.3
RadixCore: 2.1.3

## Issue Description

I've noticed after loading a world, my children's hitboxes start to shrink until they are hidden between the legs. After reloading the world, the hitboxes return to normal.

## Reproduce Steps
- Start a Singleplayer world. It does not have to have any specific settings.
- Use the crystal ball as you normally would.
- Have a child spawned, either through procreation, adoption, or the "I have a family button during MCA setup.
- Watch the hitbox starts to shrink, (I recommend watching using the F3 + B debug)

**Comment by ghost** [comment]
Tested and confirmed to happen to any child, including ones naturally spawned in villages.

**Comment by SDPhantom** [comment]
I believe this is caused by part of the code that handles scaling the child up as they age. This is a constant process until they are full grown.
