### ISSUE TITLE
Unable to run MCA in dev environment

### ISSUE THREAD

**Issue by UpcraftLP** [WildBamaBoy/minecraft-comes-alive#782]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

## Versions

MCA-1.10.2-5.2.3-universal (added as external JAR)
RadixCore-1.10.2-2.1.3-universal (added as external JAR)
Forge-1.10.2-12.18.1.2068 in a decompiled workspace

## Issue Description

I wanted to unlock additional features in my mod when MCA is installed, so I triedadding it to my dev workspace for testing purposes.

I tried adding mca and radixcore as external JARs.

## Reproduce Steps

set up a clean workspace and add mca and radixcore to your build path.

## Additional Information

relevant part of the log:
`java.io.FileNotFoundException: Unable to locate MCA assets! This may be due to an issue with your launcher (if made by a third party), or your MCA installation. Try reinstalling the mod, or try a different launcher.
    at mca.util.SkinLoader.findModDataFile(SkinLoader.java:61) [SkinLoader.class:?]
    at mca.util.SkinLoader.loadSkins(SkinLoader.java:31) [SkinLoader.class:?]
    at mca.core.MCA.init(MCA.java:176) [MCA.class:?]`

**Comment by WildBamaBoy** [comment]
Place MCA's archive with just the _assets_ folder within into the mods folder in your development environment.
