### ISSUE TITLE
Villagers take armor off after short while

### ISSUE THREAD

**Issue by BrennieBoo** [WildBamaBoy/minecraft-comes-alive#784]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

Minecraft: 1.10.2
MCA: 5.2.2

## Issue Description

After giving a few villagers some armor and weapons, they seem to take it off after a certain amount of time. In order for me to put it back on, I have to go into their inventory and exit. Because they remove their armor they are more prone to dying.

**Comment by ghost** [comment]
It's something to do with the loading/unloading of chunks.

**Comment by BrennieBoo** [comment]
Is there something I can do in the options, and change the loading/unloading of chunks, that can fix it?

**Comment by ghost** [comment]
I have no idea, i'm having the same issue.

**Comment by BrennieBoo** [comment]
Dang. I've had 2 husbands die already. Lol

**Comment by ghost** [comment]
If you want a temporary solution that will prevent the NPC's from dying, you can try this:

Go up to the NPC you want to protect, within 3 blocks or closer preferably.
Make sure there are no other entities within a 4x4x4 area, this includes armor stands, mobs, item frames, minecarts etc.
Run the command: /entitydata @e[r=3] {Invulnerable:1}
This will make that entity invulnerable from all damage. This will stay until you either remove them from the world with commands, or you make them vulnerable again.

If you want to make them vulnerable again, you can do the same thing, but run the command:
/entitydata @e[r=3] {Invulnerable:0}

This is if you have cheats enabled, if you need to enable cheats, press Esc, click "Open to LAN" change "Game Mode" to "Survival", and "Allow Cheats" to true. Cheats will last until you exit and reload your world.

**Comment by WildBamaBoy** [comment]
Problem acknowledged - related to unloading/loading chunks. I'll see what I can do about it. Just by guessing, I'll probably have to periodically send info about the villager's armor to all connected clients to make sure everything stays synced.

**Comment by EnderiumSmith** [comment]
@WildBamaBoy just insert the armor/sword into the equipment slots every entityLiving has. this way it wont break and does not use inventory space.

**Comment by sowby911** [comment]
Experienced same issue. Could be due to Optifine?
