### ISSUE TITLE
I keep crashing.

### ISSUE THREAD

**Issue by DittoMinecraft** [WildBamaBoy/minecraft-comes-alive#785]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Reproduce Steps I'm not sure, I'm not good at programming.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 9/3/16 2:16 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2721)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:2721)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Ditto_132'/529, l='MpServer', x=121.74, y=82.00, z=346.51]]
    Chunk stats: MultiplayerChunkCache: 49, 49
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (118,82,333), Chunk: (at 6,5,13 in 7,20; contains blocks 112,0,320 to 127,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 20762912 game time, 31063 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 28 total; [EntityPlayerSP['Ditto_132'/529, l='MpServer', x=121.74, y=82.00, z=346.51], EntityPainting['Painting'/350, l='MpServer', x=125.03, y=84.50, z=339.00], EntityPainting['Painting'/351, l='MpServer', x=118.50, y=89.50, z=344.03], EntityPainting['Painting'/352, l='MpServer', x=121.50, y=89.50, z=344.03], EntityPainting['Painting'/353, l='MpServer', x=124.50, y=89.50, z=344.03], EntityPainting['Painting'/354, l='MpServer', x=118.00, y=88.50, z=349.97], EntityPainting['Painting'/355, l='MpServer', x=121.03, y=84.00, z=345.00], EntityPainting['Painting'/357, l='MpServer', x=118.50, y=84.00, z=358.97], EntityPainting['Painting'/364, l='MpServer', x=133.00, y=84.50, z=335.03], EntityPainting['Painting'/365, l='MpServer', x=132.03, y=84.50, z=348.50], EntityPainting['Painting'/366, l='MpServer', x=132.03, y=84.50, z=345.50], EntityPainting['Painting'/350, l='MpServer', x=125.03, y=84.50, z=339.00], EntityPainting['Painting'/367, l='MpServer', x=133.97, y=85.00, z=339.00], EntityPainting['Painting'/351, l='MpServer', x=118.50, y=89.50, z=344.03], EntityPainting['Painting'/368, l='MpServer', x=133.00, y=84.50, z=342.97], EntityPainting['Painting'/352, l='MpServer', x=121.50, y=89.50, z=344.03], EntityPainting['Painting'/369, l='MpServer', x=130.50, y=84.00, z=358.97], EntityPainting['Painting'/353, l='MpServer', x=124.50, y=89.50, z=344.03], EntityPainting['Painting'/354, l='MpServer', x=118.00, y=88.50, z=349.97], EntityPainting['Painting'/355, l='MpServer', x=121.03, y=84.00, z=345.00], EntityHuman['Britt'/356, l='MpServer', x=125.51, y=82.00, z=340.27], EntityPainting['Painting'/357, l='MpServer', x=118.50, y=84.00, z=358.97], EntityPainting['Painting'/364, l='MpServer', x=133.00, y=84.50, z=335.03], EntityPainting['Painting'/365, l='MpServer', x=132.03, y=84.50, z=348.50], EntityPainting['Painting'/366, l='MpServer', x=132.03, y=84.50, z=345.50], EntityPainting['Painting'/367, l='MpServer', x=133.97, y=85.00, z=339.00], EntityPainting['Painting'/368, l='MpServer', x=133.00, y=84.50, z=342.97], EntityPainting['Painting'/369, l='MpServer', x=130.50, y=84.00, z=358.97]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 627898472 bytes (598 MB) / 1128255488 bytes (1075 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2011 Optifine OptiFine_1.10.2_HD_U_C2 11 mods loaded, 11 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJAAAA   Forge{12.18.1.2011} [Minecraft Forge](forge-1.10.2-12.18.1.2011.jar) 
    UCHIJAAAA   torohealthmod{1.10.2-1} [ToroHealth Damage Indicators](damage-indicators-mod-by-torocraft-1.10.2.jar) 
    UCHIJAAAA   xlib{1.0.0} [xlib](HaloCraft-Mod-by-HassanS6000-1.10.2.jar) 
    UCHIJAAAA   halocraft{1.6} [HaloCraft 2.0](HaloCraft-Mod-by-HassanS6000-1.10.2.jar) 
    UCHIJAAAA   airix{1.0.0} [airix](HaloCraft-Mod-by-HassanS6000-1.10.2.jar) 
    UCHIJAAAA   JEI{3.7.3.221} [Just Enough Items](Just-Enough-Items-Mod-1.10.2.jar) 
    UCHIJAAAA   RadixCore{1.10.2-2.1.2} [RadixCore](RadixCore-1.10.2-2.1.2-universal.jar) 
    UCHIJAAAA   MCA{1.10.2-5.2.0} [Minecraft Comes Alive](MCA-1.10.2-5.2.0-universal.jar) 
    UCHIJAAAA   XaeroMinimap{1.9.6} [Xaero's Minimap](Xaeros-Minimap-Mod-1.10.2.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2011
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Flows HD (1.10) 64x (1).zip
Current Language: English (United Kingdom)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
OptiFine Version: OptiFine_1.10.2_HD_U_C2
Render Distance Chunks: 2
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 3.1.0 - Build 9.17.10.4229
OpenGlRenderer: Intel(R) HD Graphics 3000
OpenGlVendor: Intel
CpuCount: 4
```

**Comment by TheRandomLabs** [comment]
I am also getting this error.

**Comment by TheRandomLabs** [comment]
I am also getting this, but only when I create/join a world for the first time.

**Comment by ghost** [comment]
Update to MCA 5.2.3 and RadixCore 2.1.3.

**Comment by WildBamaBoy** [comment]
Yup, update please and come back if the problem still happens. :smile:
