### ISSUE TITLE
Twins not working on LAN Server setup

### ISSUE THREAD

**Issue by JohnRohner** [WildBamaBoy/minecraft-comes-alive#786]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- x[] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

1.10.2 and latest 5.2.3 mca

Has been occurring for at least a few minor releases that I've been using.

## Issue Description

Even with "twins percentage" set to 99 in config file, twins don't occur.

## Reproduce Steps

Set "twins percentage" in mca.cfg file to 99 and do Procreate.  You get one child.

## Additional Information

How do I turn on the logger?  It would be helpful for confirming to me that it's even reading the config file correctly.

Thanks,
John

**Comment by WildBamaBoy** [comment]
Any useful information will automatically be logged. Are you connecting via LAN as the host, or a client?

**Comment by JohnRohner** [comment]
Both.  Host is on it's own laptop in a VM, I am a client on another laptop, and my daughter is a client on a third laptop.  Simple home setup.
