### ISSUE TITLE
After update from 5.1.1.2 to 5.2.0 villagers vanish, server crash on first load

### ISSUE THREAD

**Issue by SkyBlade1978** [WildBamaBoy/minecraft-comes-alive#788]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

5.2.0

Updated from 5.1.1.2 to 5.2.0, the first time the server loads it crashes creating an error report, after that it will load but the villagers have vanished, I'm testing the update on a backup of my primary server so I can reproduce by re-copying the world folder and running again.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.5.6.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 12/09/16 22:28
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at mca.ai.AIWorkday.onUpdateServer(AIWorkday.java:62)
    at mca.ai.AIManager.onUpdate(AIManager.java:45)
    at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:361)
    at net.minecraft.world.World.func_72866_a(World.java:1860)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
    at net.minecraft.world.World.func_72870_g(World.java:1829)
    at net.minecraft.world.World.func_72939_s(World.java:1661)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mca.ai.AIWorkday.onUpdateServer(AIWorkday.java:62)
    at mca.ai.AIManager.onUpdate(AIManager.java:45)
    at mca.entity.EntityHuman.func_70071_h_(EntityHuman.java:361)
    at net.minecraft.world.World.func_72866_a(World.java:1860)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
    at net.minecraft.world.World.func_72870_g(World.java:1829)

-- Entity being ticked --
Details:
    Entity Type: MCA.EntityHuman (mca.entity.EntityHuman)
    Entity ID: 132
    Entity Name: Jade
    Entity's Exact location: -326.53, 57.00, 287.12
    Entity's Block location: -327.00,57.00,287.00 - World: (-327,57,287), Chunk: (at 9,3,15 in -21,17; contains blocks -336,0,272 to -321,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Entity's Momentum: 0.00, -0.08, 0.00
    Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1661)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
    Level name: world
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: -6738292633650397043
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: -228.00,64.00,228.00 - World: (-228,64,228), Chunk: (at 12,4,4 in -15,14; contains blocks -240,0,224 to -225,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 294973201 game time, 298613155 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 95158 (now: false), thunder time: 97204 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows Server 2012 R2 (amd64) version 6.3
    Java Version: 1.8.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1044910224 bytes (996 MB) / 1412956160 bytes (1347 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 2 total; -Xmx4096M -Xms1024M
    IntCache: cache: 13, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1722 15 mods loaded, 15 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1722-universal.jar) 
    UCHIJAAAA   Forge{11.15.1.1722} [Minecraft Forge](forge-1.8.9-11.15.1.1722-universal.jar) 
    UCHIJAAAA   AutoSapling{1.0} [Auto Sapling](AutoSapling 1.2 MC1.8.9.jar) 
    UCHIJAAAA   basemetals{1.8.0} [Base Metals](BaseMetals_1.8.9-1.8.0.jar) 
    UCHIJAAAA   cfm{3.6} [MrCrayfish's Furniture Mod](cfm-3.6.1-mc1.8.9.jar) 
    UCHIJAAAA   lootablebodies{1.4.1} [DrCyano's Lootable Bodies](CyanosLootableBodies-1.4.1.jar) 
    UCHIJAAAA   dsurround{2.0.5.6} [Dynamic Surroundings](DynamicSurroundings-1.8.9-2.0.5.6.jar) 
    UCHIJAAAA   RadixCore{1.8.9-2.1.2} [RadixCore](RadixCore-1.8.9-2.1.2-universal.jar) 
    UCHIJAAAA   MCA{1.8.9-5.2.0} [Minecraft Comes Alive](MCA-1.8.9-5.2.0-FINAL-universal.jar) 
    UCHIJAAAA   mineralogy{2.6.1} [Mineralogy](mineralogy_1.8.9-2.6.1.jar) 
    UCHIJAAAA   poweradvantage{1.5.6} [Power Advantage](PowerAdvantage_1.8.9-1.5.6.jar) 
    UCHIJAAAA   steamadvantage{1.5.3} [Steam Advantage](SteamAdvantage-1.5.3.jar) 
    UCHIJAAAA   thelittlethings{1.2.4} [The Little Things](The Little Things-v.1.2.4-mc1.8.9.jar) 
    UCHIJAAAA   zc_villages{0.11.4} [ZC Villages](ZC Villages-0.11.4-1.8.9.jar) 
    Loaded coremods (and transformers): 
dsurroundcore (DynamicSurroundings-1.8.9-2.0.5.6.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
    Profiler Position: N/A (disabled)
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by WildBamaBoy** [comment]
I believe this is already fixed in 1.10.2, unfortunately I'm not supporting 1.8.9 anymore.

**Comment by SkyBlade1978** [comment]
Oh, is there any safe way to update to 5.2.0, even if it means a bit of manual work fixing the save files?  Also if I can update the server to 1.9 would that solve the issue?

I'm stuck on 1.8.9 until 'crayfish furniture' and 'the little things' go up to 1.9....

Thanks
