### ISSUE TITLE
Mod villagers replaced by McA villagers

### ISSUE THREAD

**Issue by ManMan36** [WildBamaBoy/minecraft-comes-alive#789]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed. (Due to being related to mod villagers, this obviously isn't the case)
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

Minecraft 1.10.2
MCA 5.2.3

## Issue Description

The curseforge article claims that mod villagers are not replaced, however, my testing proves this is not the case. This is a problem because I no longer have access to mod villager trades.'

## Reproduce Steps
1. A mod that adds its own villagers (such as Forestry, ExU2, or Evilcraft)
2. Use the spawn villager egg until you get a non-vanilla villager
3. Wait, and watch it change

**Comment by EnderiumSmith** [comment]
that was in 1.7. you can disable overriding in config but then they wont spawn at all

**Comment by Iteries** [comment]
I am having the same issue as well and priest/cleric do not have the current trades in buying rotten flesh  Plus, another mod adds two new villagers (sage & druid) and I have yet see them spawn at all after dozens of spawn eggs changes.

EnderiumSmith, its the current 1.10.2 

Cheers,
Itty

**Comment by WildBamaBoy** [comment]
Mod villagers are not replaced as long as they define their own unique profession IDs. If they don't I can't do anything about it unfortunately.

**Comment by mezz** [comment]
Forge has a villager registry, are you using it?
