### ISSUE TITLE
Children suffocate passing though spaces that they both visually fit and pathfind through

### ISSUE THREAD

**Issue by MentalMouse** [WildBamaBoy/minecraft-comes-alive#790]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

MCA-1.10.2-5.2.3-universal.jar
RadixCore-1.10.2-2.1.3-universal.jar
Minecraft 1.10.2
Forge 2088

## Issue Description

A small child appears to be a block tall, or not much larger.  They will happily pathfind and walk over a slab with a block spaced above it (that is, 1.5 blocks space), but appear to take damage when doing so.

## Reproduce Steps

My example case was a player-style farm, with a slab over its water block, and a jack-o-lantern suspended above that, with a space in between (for placing water).  Ordering the child to "Follow Me" and leading her across the center of the plot, she walked over the slab but flashed red when doing so.

**Comment by WildBamaBoy** [comment]
Should be fixed in next update.
