### ISSUE TITLE
Server crash with MCA-1.9-5.2.0-FINAL-universal on Minecraft 1.9

### ISSUE THREAD

**Issue by thm726** [WildBamaBoy/minecraft-comes-alive#791]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed. - NA
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

Minecraft server 1.9, MCA-1.9-5.2.0-FINAL-universal

Already have world setup and running with MCA version MCA-1.9-5.1.3-universal. Updated MCA and Radixcore to latest for Minecraft 1.9 on my Minecraft 1.9 server. The server crashes when I try to start it. Crash log indicates that there's a NULL value for one of the villagers. Reloaded world with old version and killed the villager mentioned in crash report. Attempted to upgrade again. Server crashed again, and the crash report indicated a different villager. 

Had 1.9 world already created with previous version of MCA characters in it. Installed latest version on the server and attempted to start it up. Got as far as the world generation stage... after 100% of the world was generated, server crashed.

crash report attached
[crash-2016-09-19_05.33.18-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/479724/crash-2016-09-19_05.33.18-server.txt)

**Comment by WildBamaBoy** [comment]
Unfortunately MCA for 1.9 is no longer supported. You must use 1.7.10 or 1.10.2 before I can apply any fixes to crashes.
