### ISSUE TITLE
Crash when Deconstruction Table is installed.

### ISSUE THREAD

**Issue by Faedelity** [WildBamaBoy/minecraft-comes-alive#792]
- [X] I am running the latest mod versions of MCA and RadixCore. (as relevant for 1.7.10)
- [] I can reproduce this issue with just MCA and RadixCore installed. (N/A)
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions

Minecraft 1.7.10
FML 7.99.40.1614
MCA 1.7.10-2.2.7
Deconstruction Mod 2.2.7

## Issue Description

When using this mod with Destruction Table mod in 1.7.10, putting any item into the personal crafting grid causes the game to crash. No village structures, villagers, or deconstruction tables need to be spawned in the world, and this works in a fresh world where the crystal ball has not yet been used or after using it, even if "none of these" is selected, and if the crystal ball is destroyed without being used.

Removing either MCA or the Deconstruction mod removes the problem (Radix Core does not cause the bug with MCA not present).

## Reproduce Steps

Install the items listed in Versions. Deconstruction Mod is available from thread http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288946-1-8-1-7-10-1-7-2-1-6-4-1-5-2-forge-deconstruction.
Open Minecraft.
Open a world.
Open personal inventory.
Place any item in the crafting grid of personal inventory.
Crash.

## Additional Information

These have been redacted slightly- usernames have been replaced with {User} and {MCUser}
[fml-client-latest-log.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/492281/fml-client-latest-log.txt)
[crash-2016-09-25_23.21.25-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/492283/crash-2016-09-25_23.21.25-client.txt)

**Comment by Faedelity** [comment]
Ah, should have noted, I tested with only the relevant mods installed, and got the crash. I then tried with every other mod I had been using when I discovered the mod- no crash. It's definitely this specific combination.

**Comment by WildBamaBoy** [comment]
I do believe this is going to be an issue with Deconstruction. MCA doesn't hook into anything relating to placing items in the crafting grid, only _after_ they're crafted does MCA do anything, which only consists of unlocking achievements.
