### ISSUE TITLE
Feature Request: More configuration options for Gifts, Mining, Farming, Cooking, ...

### ISSUE THREAD

**Issue by Guinaro** [WildBamaBoy/minecraft-comes-alive#793]
Feature Request: More configuration options for Gifts, Mining, Farming, Cooking, Trading...

I'm currently creating a custom minecraft modpack and I really like MCA. However it really still lacks a lot of configuration options.
You can only add more gift options.
I would love to be able to do the following:
1. Setting hearts requirements for marrying, trading, hiring, ...
2. Add gifts, remove gifts, change hearts value.
    With use of meta data.
    Seperate feature: maybe expand the gifting with positive/negative modifiers for:
        child, adult
        male, female
        mentality: playful, serious, standard
        mood: bored, entertained, interested, angry, annoyed, happy, sad
        profession: farmer, butcher, guard, priest, ...
3. Add wedding gifts, removing wedding gifts, set gifts value: Bad, Good, Better, Best rating
4. Add mining blocks from other mods, removing mining blocks
5. Add farming crops, remove farming crops, if possible with support for agricraft right click style crops(leaving a plant to grow again)
6. Add cooking items, remove cooking items: if possible integration with cooking for blockheads mod: kitchen appliances and harvestcraft recipes.
Would be fun: to go hunting/farming and bringing back items into a specific chest or set of chests so that your wife/husband can cook recipes with them.
Maybe a way to set which recipes get preference via config (standard settings).
Even better would be if the game could learn from you. So like I craft a specific item: a Hearty Breakfast from Pam's Harvestcraft and gift it to my "beloved". So he/she learns to I like that food item.
A Hearty Breakfast needs: Cooked Porkchop or Tofu, Fried Egg, Potato Cakes, Toast and Juice or Chocolate Milk. So now the game can check if this food item can be crafted with the ingredients in a nearby chest or fridge or freezer or ... .
If something is missing: a check can be made if any of the ingredients consist of subrecipes which can be crafted. Or maybe you first need to learn your wife/husband to cook the sub recipes, and eventually it can learn the more advanced versions.
...
In this way cooking would become a nice suprise each time you come home for breakfast, dinner, supper. It would be great if you could via config files even assign proper food for the proper time.
Pizza for dinner, Fried Egg for breakfast, ... .
7. Adding/removing trades from the standard trades. Per profession.
If at all possible even something like a town square with market stalls would be really bringing even more life to the game.
8. To configure this all:
Since I have delved deep into the bowels of minetweaker: using zenscripts would provide a great way to alter the mod even further to your liking for all of the above changes. And/Or we could implement JSON Config files.

A lot of features which would enhance this mod tremendously. Oh and please also for 1.7.10, as a lot of mods are still not updated to 1.10. But I assume most of this should stay compatible between the different versions.

Guinaro

**Comment by WildBamaBoy** [comment]
Adding/removing gifts, trades, mining targets, etc. would be very low priority, but I have added specifying hearts values required for marriage, trade, and hiring at this time.
