### ISSUE TITLE
Having grown baby in off hand causes infinite kids

### ISSUE THREAD

**Issue by alittlepeace** [WildBamaBoy/minecraft-comes-alive#794]
- [*] I am running the latest mod versions of MCA and RadixCore.
- [*] I can reproduce this issue with just MCA and RadixCore installed.
- [*] I can provide my Minecraft version and MCA version. 
- [*] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions

Minecraft 1.10.2 
MCA-1.10.2-5.2.3
RadixCore-1.10.2-2.1.3-universal.jar

## Issue Description

Right clicking while having the baby in the offhand that is ready to grow up will cause a kid to spawn without consuming the baby item. This causes multiple kids to spawn if accidentally held down.

## Reproduce Steps

1) Put Baby who is ready to grow in off hand
2) Right click the ground with an empty main hand

**Comment by WildBamaBoy** [comment]
Fixed in next update
