### ISSUE TITLE
I have a question about handling authorization

### ISSUE THREAD

**Issue by h1398123** [WildBamaBoy/minecraft-comes-alive#795]
I am a chinese.I like minecraft,and I like this mod.Can I Reprint this MOD on MCBBS.I hope you can give me an authorization.thank you.

**Comment by WildBamaBoy** [comment]
If posting about the mod on a different forum/website, you must provide a link back to the original forum page here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-2-3-mc-1-10-2-1-9-4-1-9-1

**Comment by h1398123** [comment]
OK,URL:http://www.mcbbs.net/forum.php?mod=viewthread&tid=363455。you can see it.
