### ISSUE TITLE
Placed Doll item causes Crash

### ISSUE THREAD

**Issue by MagpieMaydin** [WildBamaBoy/minecraft-comes-alive#796]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

MCA-1.9.4-5.2.0-FINAL-universal.jar
RadixCore-1.9.4-2.1.2-universal.jar
Minecraft 1.9.4
Forge 12.17.0.1976
## Versions

If i right-click the ground with a doll (dead child item) I crash out in both single and multiplayer. (server stays running in Multiplayer) I can then log back in, and if I swing my vision around before rendering I am ok; but if I turn and look at the the doll or the block it is on, I crash out. On our Multiplayer server dropping a baby item also crashed us. Very similar issues look to have been fixed in 1.10.2, But can I use the newer versions on a 1.9.4 server?
## Issue Description

Kill a daughter, and Place doll item from dead daughter on ground with right-click.
## Reproduce Steps

---- Minecraft Crash Report ----
// Sorry :(

Time: 10/4/16 7:09 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1938)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1331)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1039)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.client.renderer.RenderGlobal.func_72731_b(RenderGlobal.java:1938)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1331)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['MagpieMaydin'/1039, l='MpServer', x=-223.49, y=66.00, z=239.93]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-212,64,256), Chunk: (at 12,4,0 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 13351 game time, 11951 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 81 total; [EntityCreeper['Creeper'/12359, l='MpServer', x=-217.16, y=63.00, z=288.60], EntityItem['item.item.egg'/10322, l='MpServer', x=-251.84, y=66.00, z=234.71], EntityPig['Pig'/87, l='MpServer', x=-300.50, y=67.00, z=226.78], EntityPig['Pig'/88, l='MpServer', x=-293.68, y=66.00, z=234.50], EntitySheep['Sheep'/97, l='MpServer', x=-283.99, y=65.00, z=171.45], EntitySheep['Sheep'/98, l='MpServer', x=-287.50, y=66.00, z=170.50], EntitySheep['Sheep'/99, l='MpServer', x=-280.51, y=65.00, z=181.21], EntitySheep['Sheep'/100, l='MpServer', x=-282.51, y=63.00, z=177.26], EntitySheep['Sheep'/101, l='MpServer', x=-287.78, y=64.00, z=301.89], EntitySheep['Sheep'/102, l='MpServer', x=-286.50, y=64.00, z=304.50], EntitySheep['Sheep'/103, l='MpServer', x=-288.50, y=64.00, z=303.50], EntitySheep['Sheep'/104, l='MpServer', x=-284.62, y=64.00, z=297.80], EntitySheep['Sheep'/123, l='MpServer', x=-244.25, y=68.00, z=268.58], EntitySheep['Sheep'/124, l='MpServer', x=-224.51, y=65.00, z=246.71], EntitySheep['Sheep'/125, l='MpServer', x=-201.28, y=68.00, z=244.93], EntitySheep['Sheep'/126, l='MpServer', x=-270.17, y=65.00, z=242.53], EntitySheep['Sheep'/139, l='MpServer', x=-244.34, y=66.00, z=200.79], EntitySheep['Sheep'/140, l='MpServer', x=-266.29, y=67.00, z=208.80], EntitySheep['Sheep'/141, l='MpServer', x=-233.26, y=65.00, z=228.48], EntitySheep['Sheep'/142, l='MpServer', x=-225.13, y=66.00, z=237.13], EntitySheep['Sheep'/143, l='MpServer', x=-264.29, y=67.00, z=208.54], EntitySheep['Sheep'/144, l='MpServer', x=-218.26, y=66.00, z=273.46], EntitySheep['Sheep'/145, l='MpServer', x=-208.49, y=67.00, z=234.18], EntitySheep['Sheep'/146, l='MpServer', x=-262.27, y=65.00, z=242.50], EntityChicken['Chicken'/147, l='MpServer', x=-271.14, y=65.00, z=241.52], EntityChicken['Chicken'/148, l='MpServer', x=-259.54, y=67.00, z=203.84], EntityChicken['Chicken'/149, l='MpServer', x=-259.49, y=66.00, z=243.46], EntityChicken['Chicken'/150, l='MpServer', x=-265.13, y=66.00, z=234.45], EntitySheep['Sheep'/151, l='MpServer', x=-219.55, y=64.00, z=198.45], EntitySheep['Sheep'/152, l='MpServer', x=-218.48, y=64.00, z=199.19], EntitySheep['Sheep'/153, l='MpServer', x=-216.50, y=64.00, z=197.50], EntitySheep['Sheep'/154, l='MpServer', x=-216.50, y=65.00, z=198.50], EntitySheep['Sheep'/155, l='MpServer', x=-228.21, y=66.00, z=203.75], EntitySheep['Sheep'/156, l='MpServer', x=-207.84, y=67.00, z=236.28], EntitySheep['Sheep'/157, l='MpServer', x=-237.83, y=66.00, z=221.63], EntitySheep['Sheep'/158, l='MpServer', x=-208.60, y=66.00, z=198.81], EntitySheep['Sheep'/159, l='MpServer', x=-254.26, y=66.00, z=253.49], EntitySheep['Sheep'/160, l='MpServer', x=-199.46, y=68.00, z=246.22], EntitySheep['Sheep'/161, l='MpServer', x=-214.38, y=65.00, z=258.55], EntitySheep['Sheep'/162, l='MpServer', x=-210.54, y=68.00, z=272.26], EntitySheep['Sheep'/169, l='MpServer', x=-203.79, y=66.00, z=208.79], EntitySheep['Sheep'/170, l='MpServer', x=-247.73, y=67.00, z=269.49], EntitySheep['Sheep'/171, l='MpServer', x=-183.53, y=69.00, z=237.81], EntitySheep['Sheep'/172, l='MpServer', x=-189.70, y=67.00, z=224.55], EntitySheep['Sheep'/179, l='MpServer', x=-190.99, y=65.00, z=267.75], EntitySheep['Sheep'/180, l='MpServer', x=-185.73, y=67.00, z=264.51], EntitySheep['Sheep'/181, l='MpServer', x=-198.51, y=69.00, z=276.27], EntitySheep['Sheep'/182, l='MpServer', x=-198.50, y=70.00, z=279.21], EntitySheep['Sheep'/183, l='MpServer', x=-200.29, y=71.00, z=280.49], EntitySheep['Sheep'/184, l='MpServer', x=-192.50, y=71.00, z=282.50], EntitySheep['Sheep'/185, l='MpServer', x=-194.50, y=71.00, z=282.50], EntitySheep['Sheep'/186, l='MpServer', x=-197.50, y=71.00, z=281.50], EntitySheep['Sheep'/199, l='MpServer', x=-157.49, y=73.00, z=302.27], EntitySheep['Sheep'/200, l='MpServer', x=-153.50, y=68.00, z=296.50], EntitySheep['Sheep'/201, l='MpServer', x=-152.04, y=69.00, z=297.50], EntitySheep['Sheep'/202, l='MpServer', x=-152.50, y=70.00, z=299.50], EntityChicken['Chicken'/207, l='MpServer', x=-141.50, y=66.00, z=182.50], EntityChicken['Chicken'/209, l='MpServer', x=-143.50, y=67.00, z=178.50], EntityChicken['Chicken'/210, l='MpServer', x=-151.50, y=67.00, z=171.50], EntityChicken['Chicken'/211, l='MpServer', x=-144.50, y=67.00, z=178.50], EntitySheep['Sheep'/212, l='MpServer', x=-149.50, y=70.00, z=305.50], EntitySheep['Sheep'/213, l='MpServer', x=-148.50, y=70.00, z=306.50], EntitySheep['Sheep'/214, l='MpServer', x=-149.50, y=70.00, z=306.50], EntitySheep['Sheep'/215, l='MpServer', x=-149.50, y=70.00, z=303.50], EntityZombie['Zombie'/12563, l='MpServer', x=-164.50, y=44.00, z=182.50], EntityZombie['Zombie'/12579, l='MpServer', x=-189.50, y=43.00, z=221.50], EntitySpider['Spider'/12583, l='MpServer', x=-202.50, y=47.00, z=205.50], EntityBat['Bat'/12606, l='MpServer', x=-225.61, y=62.08, z=317.28], EntityCreeper['Creeper'/12648, l='MpServer', x=-277.50, y=27.00, z=214.50], EntityWitch['Witch'/12699, l='MpServer', x=-207.50, y=55.00, z=180.50], EntityZombie['Zombie'/12706, l='MpServer', x=-191.50, y=47.00, z=187.50], EntitySpider['Spider'/12716, l='MpServer', x=-299.50, y=16.00, z=235.50], EntityZombie['Zombie'/12820, l='MpServer', x=-291.50, y=52.00, z=221.50], EntityCreeper['Creeper'/10907, l='MpServer', x=-243.50, y=43.00, z=320.50], EntityItem['item.item.egg'/11273, l='MpServer', x=-252.56, y=66.00, z=233.70], EntityFallingBlock['Falling Block'/1380, l='MpServer', x=-109.50, y=35.34, z=280.50], EntityFallingBlock['Falling Block'/1384, l='MpServer', x=-111.50, y=4.00, z=306.50], EntityItem['item.item.egg'/10009, l='MpServer', x=-259.02, y=67.00, z=203.98], EntitySkeleton['Skeleton'/3866, l='MpServer', x=-222.27, y=62.00, z=210.57], EntityZombie['Zombie'/12238, l='MpServer', x=-290.50, y=49.00, z=188.50], EntityPlayerSP['MagpieMaydin'/1039, l='MpServer', x=-223.49, y=66.00, z=239.93]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 186311848 bytes (177 MB) / 1592786944 bytes (1519 MB) up to 4772593664 bytes (4551 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx5120m
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.28 Powered by Forge 12.17.0.1976 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1976-universal.jar) 
    UCHIJAAAA   Forge{12.17.0.1976} [Minecraft Forge](forge-1.9.4-12.17.0.1976-universal.jar) 
    UCHIJAAAA   RadixCore{1.9.4-2.1.2} [RadixCore](RadixCore-1.9.4-2.1.2-universal.jar) 
    UCHIJAAAA   MCA{1.9.4-5.2.0} [Minecraft Comes Alive](MCA-1.9.4-5.2.0-FINAL-universal.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.90' Renderer: 'GeForce GTX 1060/PCIe/SSE2'
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 1060/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.90, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: net.minecraft.client.Minecraft$15@495fdbe0
```

**Comment by WildBamaBoy** [comment]
You'll need to update to 1.7.10 or 1.10.2. Other versions are not supported.
