### ISSUE TITLE
Villager Hired Jobs 

### ISSUE THREAD

**Issue by icehound99** [WildBamaBoy/minecraft-comes-alive#797]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

minecraft- 1.10.2
Mod- v1.10.2 File: MCA-1.10.2-5.2.3-universal.jar

## Issue Description

Only some villagers can be hired for work, miners can mine, warriors can combat but rest of the villagers that can be hired will only do farm work regardless of profession (example: fisher can only make a farm or harvest.)
no other options would be available, although your child would be able to do any of the chores.

## Reproduce Steps

in the version that i downloaded at least they simply stay dark and unclickable

**Comment by ltkeko** [comment]
The same here, we play on our server, the villagers only can farm :( pls fix this

**Comment by WildBamaBoy** [comment]
Intentional.
