### ISSUE TITLE
Villager's babys will not grow up

### ISSUE THREAD

**Issue by LeftoverFlea312** [WildBamaBoy/minecraft-comes-alive#798]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

**Comment by LeftoverFlea312** [comment]
I love MCA. I play it all the time. However, I have found an issue that occurs with many different versions of the game. 1.8, 1.8.9, 1.9, 1.10.2. Villagers (Not my children) will have a baby normally, without the use of cake, and will hold that baby for HOURS. I once was in a world and a villager was holding the villager in her hand for at least 4 hours. Is there any way to fix this glitch? It is VERY annoying to see a villager hold a baby for hours at a time. Also I have encountered a few times that if you kill a villager with a baby, you will get that baby. But when you spawn it in, it says it is your child. Is there any chance when you kill a villager you take that baby and spawn in a villager that does not refer to you as their parent? Sorry for the long whined post and I hope you can fix this annoying glitch soon.

**Comment by MinecraftMinun** [comment]
I've being having this issue too, I must admit, it annoys me to no end. Do you have story progression on? I've tried with it on and off, both times it babies don't grow up. I've also tried with using cake, that doesn't work either

**Comment by LeftoverFlea312** [comment]
Yes I do have story progression on, is there a certain setting that must be on?

**Comment by MinecraftMinun** [comment]
I dunno, It doesn't work for me. However, if you want to get rid of the baby, stand close to the Villager holding the baby and use the following command: `/entitydata @e[r=5] {babyState:0}`

**Comment by LeftoverFlea312** [comment]
Thank you so much. This may not fix the problem, but at least I don't have to stare at the mother holding the baby for hours on end, it pisses me off.

**Comment by WildBamaBoy** [comment]
Fixed in next update
