### ISSUE TITLE
Blurry villager textures and a glitchy head model?

### ISSUE THREAD

**Issue by MechanosG** [WildBamaBoy/minecraft-comes-alive#799]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [ ] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report.

## Versions
Minecraft version 1.10.2
MCA version 1.10.2-5.2.3-universal
RadixCore version 1.10.2-2.1.3-universal

## Issue Description
All villagers have really blurry textures, and partial boxes floating around their heads only visible on the edges and corners.

## Reproduce Steps
Walk into village, look at someone.  (lol)

## Additional Information
Nothing crashes, it just looks weird.  I do have a bunch of other mods though..  could it be an oddball conflict?

![screenshot 2016-11-01 18 18 22](https://cloud.githubusercontent.com/assets/4360512/19913575/1c1dd0ac-a061-11e6-8546-a6dd83d6fcd9.png)

**Comment by 4milZ** [comment]
I'm having the exact same issue.
![2016-11-07_18 30 15](https://cloud.githubusercontent.com/assets/23318915/20068332/9a8476a6-a518-11e6-9ce4-c423a30cf88f.png)

**Comment by TheRealDadbeard** [comment]
Here the same :)

edit: my son doesnt has this issue oddly

![2016-11-09_17 28 15](https://cloud.githubusercontent.com/assets/23340600/20145861/eac220f2-a6a1-11e6-9eea-f6ead129dea0.png)

Edit2:

Magically fixed itself?

![2016-11-10_02 25 33](https://cloud.githubusercontent.com/assets/23340600/20161260/7faea316-a6ed-11e6-97b5-0eb8b23994c2.png)

**Comment by SlackerDao** [comment]
This might be caused by JourneyMap.

I tested this with _just_ MCA/RadixCore, and the issue didn't occur.

I tested this with a variety of mods, and when JourneyMap is in the loaded mods, the blurry textures occur. 

[Update]: The version of JourneyMap that causes this is 1.10.2-5.3.0b2. Reverting to the last release (1.10.2-5.2.4) seems to have fixed the issue.

**Comment by MechanosG** [comment]
> [Update]: The version of JourneyMap that causes this is 1.10.2-5.3.0b2. Reverting to the last release (1.10.2-5.2.4) seems to have fixed the issue.

Nice catch, gonna try that and report back soon as I find a village again.
