### ISSUE TITLE
Warriors don't spawn / are always married.

### ISSUE THREAD

**Issue by IWolfy** [WildBamaBoy/minecraft-comes-alive#800]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
1.7.10 & 1.10.2

## Issue Description
In 1.7.10 (mca version 5.2.2) Villagers with a warrior profession don't spawn naturally.
In 1.10.2 (mca version 5.2.3) Warriors do spawn but they're always married.
I don't know about the other versions (1.9, 1.9.4 & 1.8)

**Comment by WildBamaBoy** [comment]
Can't seem to reproduce this one. Try turning off story progression and see if they still appear as married. It's in MCA's configuration.
