### ISSUE TITLE
JEI compatibility issues

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#801]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore (and JEI) installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report.

## Versions
- Forge: 1.10.2-12.18.2.2120
- MCA: 5.2.3
- RadixCore: 2.1.3
- JEI: 3.13.2.360

## Issue Description
The following items are listed twice in the JEI item list with the second one missing its texture and name:
- Red Villager Bed
- Blue Villager Bed
- Green Villager Bed
- Pink Villager Bed
- Purple Villager Bed

There are also two "tile.null.name" items listed with no texture.

## Reproduce Steps
1. Install listed mods
2. Create a new world
3. Check items in JEI item list

**Comment by ghost** [comment]
The-Fireplace [fixed the issue](https://github.com/The-Fireplace/Adobe-Blocks/issues/7), maybe he can help.

**Comment by ghost** [comment]
I worked around the issue by putting the items on the JEI blacklist.

**Comment by WildBamaBoy** [comment]
Fixed in next update.
