### ISSUE TITLE
MCA Skins are warped 

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#803]
Good day,

I am running the latest mod versions of MCA and RadixCore.

I can reproduce this issue with just MCA and RadixCore installed.

 I have searched for the issue previously and it was previously reported, but not fixed and I'm having the same problem.

The problem is that the skins that I uploaded come up in game all warped, I have no idea why.

I have everything installed correctly, I have placed and renamed the skins correctly,

Here is one of the skins I added in:

![skin_201611120403092130](https://cloud.githubusercontent.com/assets/13189806/20235724/1639ebee-a868-11e6-9803-b223f200d637.png)

Here is the result

:
![2016-11-11_23 37 01](https://cloud.githubusercontent.com/assets/13189806/20235723/f9542f58-a867-11e6-8d4e-a246b7c9c4c4.png)

If we could get this fixed as soon as possible, that would be great!

**Comment by WildBamaBoy** [comment]
MCA only supports the original "Steve" format skins right now, so you'd need to convert your skin to that format and it'll show properly.

**Comment by ghost** [comment]
Thank you, but how would I convert my skins ?
Here are two of the skins I would like to convert:
![lennox](https://cloud.githubusercontent.com/assets/13189806/20247773/75ba0c5c-a9a3-11e6-92d2-d4422415ffe6.png)
![macbeth](https://cloud.githubusercontent.com/assets/13189806/20247775/75badb46-a9a3-11e6-9fbb-3e6dfdee497b.png)
![priestf16](https://cloud.githubusercontent.com/assets/13189806/20247774/75ba5ff4-a9a3-11e6-810c-e498f3bd2817.png)
![priestf17](https://cloud.githubusercontent.com/assets/13189806/20247776/75bba468-a9a3-11e6-8536-17b9b1ea7976.png)

**Comment by WildBamaBoy** [comment]
Any sort of graphics editor. You _can_ just chop off the bottom so it's a 64x32 image, not 64x64. Though you might have to move around some pieces of the bottom half so that they're in the right location for the "Steve" format in order for it to look right again, but that's the process.

This would be your first (quickly) converted skin:
![75ba0c5c-a9a3-11e6-92d2-d4422415ffe6](https://cloud.githubusercontent.com/assets/749179/20247895/1a881b94-a99e-11e6-900e-6bc5d5c54679.png)

**Comment by ghost** [comment]
Thank you very much!
But when I do this, my skins faces become pure white now, I know why this is, it is because the picture of the skin looses its transparency.

So if I may ask, how would you convert the skin without loosing transparancy ?
Photoshop does not work, Paint does not work, Paint.NET does not work. so how
did you manage do change the skin without loosing transparancy?

Thank you for taking the time to help me out with this!

Please reply as soon as possible!

Kind regards,
Cole

**Comment by ghost** [comment]
Nevermind, I figured it out, http://www194.lunapic.com/editor/ will make any picture parts transparent
