### ISSUE TITLE
Feature Suggestions - Improved Villager Customisation

### ISSUE THREAD

**Issue by MinecraftMinun** [WildBamaBoy/minecraft-comes-alive#806]
- Instead of using arrow buttons to change a villager's height/girth player is able to manually type in a number (That or you can use the arrow keys to do this.)

- Players can set a guard's weapon (Possibly just by giving them a weapon that does 5+ attack damage)

- Player can make villagers with gold hearts hold items (Maybe a new option in special)

- Player can have an option to see hearts as a number like in the older versions. (In config)

- Villagers have a chance to be left handed (Please, I don't want to be the only left-handed on in my village, Although, you can use a command to accomplish this: /entitydata @e[r=3,rm=1,c=1] {LeftHanded:1} )

- Player is able to remove/add breasts using villager editor to female villagers, (Random chance for them to have them or not, probably 5%/1 in 20 chance not to? Player can change female villager's breast size (e.g: small, normal, large, none))

- Default Villager turned in to MCA Villagers will keep their trades. (Or you can you /summon to get villagers with custom trades and even armor and items?)

- You can see how your family member died in chat (Like a wolf)

**Comment by Iteries** [comment]
This might be old but still good even today!

- Pretty nice suggestions!  The one for Player on ''breast size" there is a mod on Curse called Gender that does add in female parts, even on zombies!  
- Default Villager Trades.  Yeah I am having a tough one with that too and wondering if a bug.  When using VillageEditor and you change their profession it does not change what they have for trading to that new profession.   Going to post it up as a bug or suggestion in how to redo their trades to the new 'job'

Great ideas
Itty
