### ISSUE TITLE
(SERVER) Crashing when setting gender on MCA 1.7.10

### ISSUE THREAD

**Issue by sapziiiii** [WildBamaBoy/minecraft-comes-alive#807]
Hi! So I decided to make a server with some mods on it for my friend and I but when we tried to use the crystal ball to set our gender, we'd click on the gender we wanted and it would crash. We have tried it with just MCA and with all the mods and it's the same. Googled every possible thing and nothing helped. We are running forge-1.7.10-10.13.4.1558-1.7.10-universal and MCA-1.7.10-5.2.2-universal. 

Crash Report:
 ---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 16/11/16 6:37 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at mca.client.gui.GuiSetup.func_146284_a(GuiSetup.java:271)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at mca.client.gui.GuiSetup.func_73864_a(GuiSetup.java:231)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at mca.client.gui.GuiSetup.func_146274_d(GuiSetup.java:113)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.client.gui.GuiSetup.func_146284_a(GuiSetup.java:271)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
	at mca.client.gui.GuiSetup.func_73864_a(GuiSetup.java:231)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at mca.client.gui.GuiSetup.func_146274_d(GuiSetup.java:113)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: mca.client.gui.GuiSetup

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['httpsapling'/292, l='MpServer', x=999920.24, y=65.62, z=1000036.45]]
	Chunk stats: MultiplayerChunkCache: 426, 426
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (999911,64,1000044), Chunk: (at 7,4,12 in 62494,62502; contains blocks 999904,0,1000032 to 999919,255,1000047), Region: (1952,1953; contains chunks 62464,62496 to 62495,62527, blocks 999424,0,999936 to 999935,255,1000447)
	Level time: 94361 game time, 123361 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 56 total; [EntityClientPlayerMP['httpsapling'/292, l='MpServer', x=999920.24, y=65.62, z=1000036.45], EntitySheep['Sheep'/135, l='MpServer', x=999951.84, y=63.00, z=999977.09], EntitySheep['Sheep'/136, l='MpServer', x=999943.25, y=63.00, z=999982.34], EntityHorse['Horse'/137, l='MpServer', x=999948.13, y=64.00, z=1000004.63], EntitySheep['Sheep'/138, l='MpServer', x=999938.13, y=64.00, z=1000081.22], EntitySheep['Sheep'/139, l='MpServer', x=999940.66, y=64.00, z=1000086.75], EntityChicken['Chicken'/140, l='MpServer', x=999930.59, y=64.00, z=1000096.56], EntityChicken['Chicken'/141, l='MpServer', x=999945.41, y=65.00, z=1000103.56], EntityChicken['Chicken'/142, l='MpServer', x=999950.59, y=66.00, z=1000108.44], EntitySheep['Sheep'/143, l='MpServer', x=999949.28, y=65.00, z=1000105.84], EntitySheep['Sheep'/144, l='MpServer', x=999950.50, y=66.00, z=1000115.50], EntityChicken['Chicken'/147, l='MpServer', x=999945.44, y=65.00, z=1000104.56], EntitySheep['Sheep'/148, l='MpServer', x=999942.78, y=66.00, z=1000116.19], EntityChicken['Chicken'/149, l='MpServer', x=999940.44, y=66.00, z=1000113.56], EntityCow['Cow'/153, l='MpServer', x=999955.25, y=67.00, z=999960.41], EntityCow['Cow'/154, l='MpServer', x=999952.63, y=67.00, z=999964.56], EntitySheep['Sheep'/155, l='MpServer', x=999960.66, y=66.00, z=999976.50], EntitySheep['Sheep'/156, l='MpServer', x=999960.88, y=65.00, z=999982.09], EntitySheep['Sheep'/157, l='MpServer', x=999962.47, y=64.00, z=999981.63], EntityChicken['Chicken'/158, l='MpServer', x=999959.41, y=66.00, z=1000008.56], EntityChicken['Chicken'/159, l='MpServer', x=999953.63, y=64.00, z=1000084.38], EntitySheep['Sheep'/160, l='MpServer', x=999954.84, y=64.00, z=1000064.41], EntityChicken['Chicken'/161, l='MpServer', x=999966.56, y=65.00, z=1000093.47], EntityChicken['Chicken'/162, l='MpServer', x=999956.44, y=66.00, z=1000108.47], EntitySheep['Sheep'/163, l='MpServer', x=999966.66, y=68.00, z=1000100.56], EntityChicken['Chicken'/169, l='MpServer', x=999956.66, y=65.00, z=1000115.41], EntitySheep['Sheep'/174, l='MpServer', x=999982.44, y=68.00, z=999996.66], EntitySheep['Sheep'/175, l='MpServer', x=999984.47, y=64.00, z=999985.22], EntitySheep['Sheep'/176, l='MpServer', x=999973.03, y=68.00, z=999999.06], EntityHorse['Horse'/177, l='MpServer', x=999972.84, y=72.00, z=1000020.38], EntityChicken['Chicken'/72, l='MpServer', x=999847.47, y=63.00, z=1000101.53], EntityChicken['Chicken'/73, l='MpServer', x=999859.41, y=64.00, z=1000088.63], EntitySheep['Sheep'/74, l='MpServer', x=999844.47, y=63.00, z=1000098.59], EntitySheep['Sheep'/76, l='MpServer', x=999841.88, y=66.00, z=1000114.13], EntityChicken['Chicken'/77, l='MpServer', x=999841.56, y=65.00, z=1000113.44], EntityChicken['Chicken'/82, l='MpServer', x=999866.59, y=74.00, z=999962.53], EntityChicken['Chicken'/83, l='MpServer', x=999867.56, y=63.00, z=1000066.44], EntityChicken['Chicken'/89, l='MpServer', x=999872.47, y=73.00, z=1000028.38], EntitySheep['Sheep'/90, l='MpServer', x=999878.53, y=63.00, z=1000038.22], EntityChicken['Chicken'/91, l='MpServer', x=999878.13, y=63.00, z=1000051.75], EntityChicken['Chicken'/92, l='MpServer', x=999878.56, y=64.00, z=1000074.47], EntityChicken['Chicken'/98, l='MpServer', x=999896.47, y=65.00, z=1000089.53], EntityChicken['Chicken'/99, l='MpServer', x=999893.41, y=66.00, z=1000086.44], EntityChicken['Chicken'/103, l='MpServer', x=999915.56, y=63.00, z=1000002.56], EntityVillager['Villager'/104, l='MpServer', x=999910.63, y=64.00, z=1000021.78], EntityVillager['Villager'/105, l='MpServer', x=999906.66, y=64.00, z=1000059.28], EntitySheep['Sheep'/106, l='MpServer', x=999908.91, y=64.00, z=1000076.91], EntityChicken['Chicken'/107, l='MpServer', x=999904.41, y=65.00, z=1000075.53], EntityChicken['Chicken'/108, l='MpServer', x=999916.56, y=68.00, z=1000100.53], EntityChicken['Chicken'/109, l='MpServer', x=999910.66, y=64.00, z=1000098.44], EntitySheep['Sheep'/120, l='MpServer', x=999922.53, y=66.00, z=999959.66], EntityChicken['Chicken'/121, l='MpServer', x=999930.56, y=62.42, z=1000002.44], EntityChicken['Chicken'/122, l='MpServer', x=999930.53, y=63.00, z=1000027.53], EntityVillager['Villager'/123, l='MpServer', x=999923.22, y=64.00, z=1000036.38], EntityChicken['Chicken'/124, l='MpServer', x=999935.47, y=65.00, z=1000079.44], EntitySheep['Sheep'/125, l='MpServer', x=999932.13, y=64.00, z=1000094.06]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1854530432 bytes (1768 MB) / 2033188864 bytes (1939 MB) up to 2033188864 bytes (1939 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms2048M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.3.0' Renderer: 'GeForce GT 620/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 620/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by WildBamaBoy** [comment]
Try with latest Forge and only MCA and RadixCore installed.
