### ISSUE TITLE
MCA crashes and corrupts world on looking at gravestone

### ISSUE THREAD

**Issue by DireWolfSkull** [WildBamaBoy/minecraft-comes-alive#808]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions
Minecraft 1.9.4, LWJGL 2.9.1, Forge 1.9.4-12.17.0.1990, MCA 1.9.4-5.2.0-FINAL, RadixCore 1.9.4-2.1.2

## Issue Description
I get a crash when I create a new game, create a village, walk into the graveyard and look at a gravestone. The crash corrupts the game world so that it will no longer load, it crashes on a colored screen before any terrain spawns in.
Tested it three times: twice with additional mods and once without. Got the crash and corrupted world every time.

## Reproduce Steps
- Create a new world
- Use the crystal ball
- Select "I live in a village". I also selected female and either, not sure if that matters.
- Leave the house you spawn into, walk to the graveyard, and look directly at a gravestone

## Additional Information
First crash report: crashed in a modded world
[crash-2016-11-20_22.22.11-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/612489/crash-2016-11-20_22.22.11-client.txt)

Second crash report: Attempting to reload the modded world
[crash-2016-11-20_23.27.21-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/612491/crash-2016-11-20_23.27.21-client.txt)

Third crash report: crashed in a vanilla world
[crash-2016-11-22_00.00.52-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/612492/crash-2016-11-22_00.00.52-client.txt)

**Comment by WildBamaBoy** [comment]
1.9.4 is no longer supported.
