### ISSUE TITLE
Villagers Disappear in front of me 1.7.10

### ISSUE THREAD

**Issue by asdfca123** [WildBamaBoy/minecraft-comes-alive#809]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
MC: 1.7.10 MCA: 5.2.2 RadixCore: 2.1.3

## Issue Description
I told a villager to follow me around to get them into one safe place, but I did it one at a time. The first villager I asked to follow, I forgot to lead to the safe place. They kept following me, so I exited my game, and when I came back, she Disappeared right before me. As in, I saw her when my game was still warming up, but she stood still. All other villagers were moving, so my game wasn't lagging. Then she just vanished.

## Reproduce Steps
Get a villager to follow you around
Exit the game
Rejoin the same world
Look for villager you told to follow you, they should not be there

**Comment by XanaRaquel** [comment]
Does that villager has a home? Was it night time when it happened? If so it sounds like that the villager got teleported to his/her home to sleep when you rejoined.

**Comment by WildBamaBoy** [comment]
The above is likely what happened.
