### ISSUE TITLE
Excessive number of villagers generated

### ISSUE THREAD

**Issue by xenoflot** [WildBamaBoy/minecraft-comes-alive#810]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
RadixCore-1.10.2-2.1.3-universal
mca-1.10.2-5.2.3-universal
rtg-1.10.2-4.1.1.8
terrariacraft-1.10.2-17a

## Issue Description
Playing in a pack with a few mods which (may) affect world gen. I came across a village with ~4000 villagers at x218 z1155  Seed "3065272"
It had my fps at zero. I've encountered a couple of spots with 0 fps but this is the first time I've found the cause. I'll be doing some more testing and will update this ticket in due course.
http://i.imgur.com/7QJgFTf.png

**Comment by xenoflot** [comment]
I played with this for about 2 hours. Unfortunately I wasn't able to track it down definitively and with the chunk-creation lag, I'm afraid my patience ran out. My guess though is that it happens when RTG is in the pack in addition to MCA. When they were both in, I would frequently get an error "Last tick took 60s, assuming something has crashed. Shutting down the server."

**Comment by WildBamaBoy** [comment]
I would only be able to fix an issue like this if it were local to MCA. Unfortunately it sounds like RTG may be causing this problem in some way.

Closing for now, but if you find anything definitive respond here and it will come to me.
