### ISSUE TITLE
duplicate crystal balls 1.10.2-2151( MCA-1.10.2-5.2.3-universal)

### ISSUE THREAD

**Issue by SDUBZ** [WildBamaBoy/minecraft-comes-alive#811]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
minecraft version:1.10.2-2151
mca version: MCA-1.10.2-5.2.3-universal

everytime i join my world i get a crystal ball

## Reproduce Steps
use minecraft version listed and mca listed

## Additional Information
the pack used were its occuring
https://minecraft.curseforge.com/projects/sdubzskycraft
and it happens on the default world set

**Comment by WildBamaBoy** [comment]
Use the crystal ball first, and it will stop appearing each time you log in.
