### ISSUE TITLE
[Feature Request] Underground Biomes Constructs compatibility

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#812]
Minecraft version: 1.10.2

The mod Underground Biomes Constructs replaces the vanilla stone with different stone types like rhyolite, soapstone, marble etc. As these different stone types contain the ores, the textures of the ores have to be changed when UBC is installed. UBC provides an API for this task.

Short: Please make rose gold ore fit the UBC stone textures.

**Comment by WildBamaBoy** [comment]
Unfortunately this sort of compatibility will not be considered at this time.
