### ISSUE TITLE
java.lang.NullPointerException mca:1.10.2-5.2.3

### ISSUE THREAD

**Issue by SDUBZ** [WildBamaBoy/minecraft-comes-alive#819]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
minecraft 1.10.2-build2185
mca:1.10.2-5.2.3
radixcore:1.10.2-2.1.3

## Issue Description
i gave a baby girl or boy as a reward fro doing a quest and my client set her to follow him and then walked away a bit and it crashed

## Reproduce Steps
give self a baby girl and wait for it to be grown then place in world and set to follow you and then start walking away
this was triggered to my openeye tag as sdubzskycraft
giving the following crash info:https://openeye.openmods.info/crashes/42d3238a51c18bdb3cdff4b3c2a10099

**Comment by WildBamaBoy** [comment]
Should be fixed in next update.
