### ISSUE TITLE
LoaderExceptionModCrash caused by java.lang.RuntimeException

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#821]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## I'm using a custom profile inside .minecraft/modded/1_10_2/ because I like to divide 1.10.2 mods from 1.11 mods + I can have different modpack installed in different folders. I'm using the new beta launcher and 4GB of ram are reserved to the game. edit: I just tried using these mods in the technic launcher (with no custom profiles like I did in the new minecraft launcher and everything works fine)

[crash-2016-12-18_15.46.37-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/659472/crash-2016-12-18_15.46.37-client.txt)

**Comment by WildBamaBoy** [comment]
Place in just the `mods` folder and you should be good to go.
