### ISSUE TITLE
Villagers stay frozen in one spot

### ISSUE THREAD

**Issue by thablueprint786** [WildBamaBoy/minecraft-comes-alive#822]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

MC 1.10.2 MCA 5.2.3 RadixCore 2.1.3

Almost every villager that is spawned - whether through egg or naturally - are stuck in one spot and wont move around unless they get hit or I request them to follow me.

Either spawn in a village or spawn a villager yourself, they most likely won't move

**Comment by WildBamaBoy** [comment]
Fixed in upcoming update.
