### ISSUE TITLE
Game Crashes When Crystal Ball is Used on 1.8 Server

### ISSUE THREAD

**Issue by ZeIrishDood** [WildBamaBoy/minecraft-comes-alive#825]
- [] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

## Versions
Minecraft - 1.8 MCA - 5.0.6.1-1.8

## Issue Description
I started a modded server that includes MCA. When I went to start off, I right clicked on the crystal ball, and the entire game crashed! I've tried uninstalling every other mod, but the problem will not stop.

## Reproduce Steps
1. Make a 1.8 Modded Server
2. Install MCA v5.0.6.1-1.8
3. Install RadixCore v2.0.3-1.8
4. Run server w/ MCA & RadixCore
5. Join Server
6. Use the Crystal Ball
Time: 1/1/17 5:56 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mca.core.MCA.getPlayerData(MCA.java:616)
	at mca.client.gui.GuiSetup.<init>(GuiSetup.java:58)
	at mca.core.forge.GuiHandler.getClientGuiElement(GuiHandler.java:35)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:266)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:102)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2295)
	at mca.items.ItemCrystalBall.func_77659_a(ItemCrystalBall.java:55)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:150)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:438)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1519)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2041)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mca.core.MCA.getPlayerData(MCA.java:616)
	at mca.client.gui.GuiSetup.<init>(GuiSetup.java:58)
	at mca.core.forge.GuiHandler.getClientGuiElement(GuiHandler.java:35)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:266)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:102)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2295)
	at mca.items.ItemCrystalBall.func_77659_a(ItemCrystalBall.java:55)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:150)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:438)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1519)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ZeIrishDood'/262, l='MpServer', x=654.02, y=64.00, z=447.33]]
	Chunk stats: MultiplayerChunkCache: 432, 432
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 208.00,64.00,252.00 - World: (208,64,252), Chunk: (at 0,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 27943 game time, 13385 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 86 total; [EntityPlayerSP['ZeIrishDood'/262, l='MpServer', x=654.02, y=64.00, z=447.33], EntityItem['item.item.egg'/6400, l='MpServer', x=661.19, y=64.00, z=482.78], EntityBat['Bat'/5639, l='MpServer', x=722.97, y=20.18, z=383.92], EntityItem['item.item.egg'/3608, l='MpServer', x=700.03, y=63.00, z=493.69], EntityCreeper['Creeper'/6690, l='MpServer', x=674.50, y=71.00, z=401.50], EntityZombie['Zombie'/5930, l='MpServer', x=721.50, y=92.00, z=384.50], EntitySkeleton['Skeleton'/6201, l='MpServer', x=703.50, y=48.00, z=370.50], EntitySkeleton['Skeleton'/6202, l='MpServer', x=703.50, y=48.00, z=368.50], EntitySkeleton['Skeleton'/6203, l='MpServer', x=701.50, y=48.00, z=370.50], EntitySkeleton['Skeleton'/6715, l='MpServer', x=711.50, y=26.00, z=378.50], EntitySkeleton['Skeleton'/6204, l='MpServer', x=703.50, y=48.00, z=371.50], EntitySkeleton['Skeleton'/6716, l='MpServer', x=713.50, y=26.00, z=380.50], EntityCreeper['Creeper'/6718, l='MpServer', x=688.50, y=21.00, z=398.50], EntityZombie['Zombie'/6719, l='MpServer', x=731.50, y=12.00, z=436.50], EntityZombie['Zombie'/6720, l='MpServer', x=730.50, y=12.00, z=436.50], EntityZombie['Zombie'/6722, l='MpServer', x=730.50, y=12.00, z=435.50], EntityCreeper['Creeper'/6723, l='MpServer', x=729.00, y=12.00, z=439.34], EntitySkeleton['Skeleton'/6471, l='MpServer', x=715.88, y=51.00, z=383.50], EntitySheep['Sheep'/338, l='MpServer', x=579.97, y=63.00, z=475.50], EntitySheep['Sheep'/339, l='MpServer', x=577.19, y=64.00, z=475.50], EntityPig['Pig'/340, l='MpServer', x=573.22, y=70.00, z=481.50], EntitySkeleton['Skeleton'/6231, l='MpServer', x=713.50, y=26.00, z=376.50], EntityZombie['Zombie'/6487, l='MpServer', x=716.50, y=63.00, z=395.50], EntityItem['item.item.egg'/6745, l='MpServer', x=636.34, y=64.00, z=499.91], EntityBat['Bat'/6236, l='MpServer', x=685.21, y=51.07, z=501.79], EntityBat['Bat'/6237, l='MpServer', x=684.99, y=54.07, z=497.97], EntityItem['item.item.egg'/2654, l='MpServer', x=639.56, y=64.00, z=499.41], EntityItem['item.item.egg'/3680, l='MpServer', x=640.75, y=64.00, z=487.66], EntityChicken['Chicken'/353, l='MpServer', x=603.50, y=63.00, z=526.50], EntityChicken['Chicken'/354, l='MpServer', x=604.50, y=63.00, z=527.50], EntityItem['item.item.egg'/5221, l='MpServer', x=637.69, y=64.00, z=503.66], EntityCreeper['Creeper'/6757, l='MpServer', x=701.54, y=77.00, z=414.50], EntityChicken['Chicken'/371, l='MpServer', x=641.34, y=64.00, z=487.31], EntityChicken['Chicken'/372, l='MpServer', x=630.66, y=64.00, z=481.44], EntityItem['item.item.egg'/2932, l='MpServer', x=715.19, y=64.00, z=502.88], EntityItem['item.item.egg'/4468, l='MpServer', x=716.88, y=65.00, z=501.41], EntityChicken['Chicken'/373, l='MpServer', x=634.53, y=64.00, z=484.34], EntityChicken['Chicken'/374, l='MpServer', x=637.44, y=63.00, z=510.19], EntityChicken['Chicken'/375, l='MpServer', x=624.31, y=64.00, z=506.22], EntityChicken['Chicken'/376, l='MpServer', x=637.09, y=64.00, z=499.78], EntityChicken['Chicken'/377, l='MpServer', x=623.59, y=64.00, z=498.69], EntityChicken['Chicken'/378, l='MpServer', x=638.38, y=64.00, z=503.59], EntityItem['item.item.egg'/2938, l='MpServer', x=658.66, y=64.00, z=492.44], EntityChicken['Chicken'/379, l='MpServer', x=639.31, y=64.00, z=498.53], EntityChicken['Chicken'/380, l='MpServer', x=627.50, y=63.00, z=516.50], EntityChicken['Chicken'/381, l='MpServer', x=629.41, y=63.00, z=517.34], EntityRabbit['Rabbit'/390, l='MpServer', x=646.59, y=70.00, z=369.59], EntityZombie['Zombie'/6023, l='MpServer', x=700.59, y=45.00, z=389.84], EntitySkeleton['Skeleton'/393, l='MpServer', x=651.56, y=52.00, z=425.97], EntityBat['Bat'/394, l='MpServer', x=653.25, y=53.10, z=459.38], EntityZombie['Zombie'/6794, l='MpServer', x=639.50, y=70.02, z=372.50], EntityZombie['Zombie'/6795, l='MpServer', x=702.50, y=54.02, z=387.50], EntitySkeleton['Skeleton'/396, l='MpServer', x=631.91, y=55.00, z=469.44], EntityWitch['Witch'/4748, l='MpServer', x=633.50, y=51.00, z=484.50], EntitySkeleton['Skeleton'/6796, l='MpServer', x=699.50, y=54.02, z=386.50], EntityChicken['Chicken'/401, l='MpServer', x=645.00, y=64.00, z=482.38], EntityChicken['Chicken'/405, l='MpServer', x=667.53, y=70.00, z=375.66], EntityChicken['Chicken'/406, l='MpServer', x=661.50, y=67.00, z=376.50], EntityChicken['Chicken'/408, l='MpServer', x=671.34, y=72.00, z=369.44], EntityChicken['Chicken'/410, l='MpServer', x=653.63, y=66.00, z=380.56], EntitySkeleton['Skeleton'/411, l='MpServer', x=671.84, y=62.47, z=469.72], EntitySkeleton['Skeleton'/412, l='MpServer', x=671.59, y=61.72, z=471.63], EntityChicken['Chicken'/415, l='MpServer', x=668.50, y=64.00, z=483.50], EntityChicken['Chicken'/417, l='MpServer', x=661.44, y=64.00, z=483.31], EntityChicken['Chicken'/418, l='MpServer', x=658.56, y=64.00, z=492.38], EntityChicken['Chicken'/419, l='MpServer', x=665.31, y=64.00, z=483.81], EntityItem['item.item.egg'/3747, l='MpServer', x=637.44, y=63.00, z=510.59], EntityItem['item.item.egg'/4261, l='MpServer', x=664.56, y=64.00, z=483.06], EntityBat['Bat'/5036, l='MpServer', x=682.05, y=56.72, z=408.36], EntityZombie['Zombie'/5293, l='MpServer', x=678.50, y=27.00, z=390.50], EntityCreeper['Creeper'/4284, l='MpServer', x=645.69, y=48.00, z=474.81], EntityCreeper['Creeper'/4286, l='MpServer', x=644.47, y=49.00, z=474.63], EntityChicken['Chicken'/450, l='MpServer', x=688.34, y=64.00, z=455.47], EntityChicken['Chicken'/451, l='MpServer', x=692.56, y=64.00, z=473.56], EntityChicken['Chicken'/452, l='MpServer', x=699.34, y=63.00, z=494.31], EntityChicken['Chicken'/455, l='MpServer', x=699.31, y=63.00, z=483.44], EntityCreeper['Creeper'/5328, l='MpServer', x=732.50, y=32.00, z=500.50], EntityChicken['Chicken'/471, l='MpServer', x=716.28, y=65.00, z=501.66], EntityChicken['Chicken'/472, l='MpServer', x=721.41, y=64.00, z=499.66], EntityChicken['Chicken'/473, l='MpServer', x=715.50, y=64.00, z=503.50], EntityBat['Bat'/6377, l='MpServer', x=706.71, y=31.08, z=379.65], EntityItem['item.item.egg'/5868, l='MpServer', x=688.63, y=64.00, z=456.00], EntityCow['Cow'/495, l='MpServer', x=717.16, y=75.00, z=373.03], EntityBat['Bat'/6385, l='MpServer', x=677.63, y=19.16, z=400.71], EntityZombie['Zombie'/4338, l='MpServer', x=701.50, y=44.00, z=384.50], EntityChicken['Chicken'/503, l='MpServer', x=721.50, y=64.00, z=501.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:374)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 221970824 bytes (211 MB) / 431763456 bytes (411 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
	UCHIJA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
	UCHIJA	RadixCore{2.0.3-1.8} [RadixCore] (RadixCore-2.0.3-1.8-universal.jar) 
	UCHIJA	MCA{5.0.6.1-1.8} [Minecraft Comes Alive] (Minecraft-Comes-Alive-1.8-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8787 FireGL' Renderer: 'ATI Mobility FireGL V5725'
	Launched Version: 1.8-forge1.8-11.14.4.1577
	LWJGL: 2.9.1
	OpenGL: ATI Mobility FireGL V5725 GL version 2.1.8787 FireGL, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
## Additional Information
I've even tried uninstalling it and reinstalling it! Both MCA and RadixCore!

**Comment by ZeIrishDood** [comment]
Please help! My friends and I have been wanting to do a modded survival for a while now, including MCA, but this is getting us really upset!

**Comment by XanaRaquel** [comment]
The version you are using is from Jun 14, 2015! It's outdated and unsupported. You have to update your game to a newer version or downgrade to 1.7.10.

**Comment by ZeIrishDood** [comment]
Alright! Thank you for pointing that out for me!

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 6, 2017 at 3:39 PM, XanaRaquel<notifications@github.com> wrote:   
The version you are using is from Jun 14, 2015! It's outdated and unsupported. You have to update your game to a newer version or downgrade to 17.10.

**Comment by WildBamaBoy** [comment]
1.8 is not supported.
