### ISSUE TITLE
Unable to marry two villagers together.

### ISSUE THREAD

**Issue by MrPandaBird** [WildBamaBoy/minecraft-comes-alive#827]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

**Comment by WildBamaBoy** [comment]
Cannot reproduce this issue.
