### ISSUE TITLE
My skins won't  work properly when I put them in the assets\mca\textures\skins 

### ISSUE THREAD

**Issue by imsupergood1** [WildBamaBoy/minecraft-comes-alive#829]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem

**Comment by WildBamaBoy** [comment]
Use the original "Steve" skin format. Not the new skin format.
