### ISSUE TITLE
Archers one-shot kill villagers & players

### ISSUE THREAD

**Issue by GameRKade** [WildBamaBoy/minecraft-comes-alive#831]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
Minecraft 1.10.2
MCA 5.2.3

## Issue Description
This issue was found when my granddaughter killed my daughter-in-law fighting off a giant.

As you may know, archers will shoot arrows at any mob that comes their way. However, they will one-shot kill any villager that walks in their way during this process. This makes archers dangerous to be around in areas where mobs are still lurking, as they can kill your friends or family if you walk into the archer's line of sight while you're being followed.

As well as that, if you're fighting off an enemy, and just so happen to back into their line of sight, you will be killed on the spot, losing your items and exp.

## Reproduce Steps
(1) Spawn Archer
(2) Spawn a villager in front of the archer
(3) Spawn a hostile mob in front of the villager, putting the villager in the archer's line of sight

**Comment by WildBamaBoy** [comment]
Fixed in latest update.
