### ISSUE TITLE
Crystal Ball will not work on my server

### ISSUE THREAD

**Issue by jkilcoin** [WildBamaBoy/minecraft-comes-alive#833]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

MCA-1.7.10-5.2.2-universal 1.7.10-Forge10.13.4.1558-1.7.10

On my server with node craft i try to use the crstal ball and it doesnt work it doesnt take me to the room or anything and it is with my friends. I want to be able to play with them while using this mods.

**Comment by WildBamaBoy** [comment]
Cannot reproduce this issue.
