### ISSUE TITLE
Way to add extra ores to villager work menu?

### ISSUE THREAD

**Issue by mobro09** [WildBamaBoy/minecraft-comes-alive#834]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
Minecraft 1.7.10
MCA 5.2.2

## Issue Description
Hello, I was wondering if there was any possible way to add extra ore definitions to the work menu for modded ores to be searchable/mineable by villagers.
The only selections are vanilla/MCA ore types and I was just curious if there was any way I could edit it.

## Reproduce Steps
Hire a mining villager and search through the choices for ore.

**Comment by WildBamaBoy** [comment]
If you're a mod developer, this is possible by using MCA's API package available on Curse.
