### ISSUE TITLE
My children's babies won't grow up from their hands???

### ISSUE THREAD

**Issue by isayhao** [WildBamaBoy/minecraft-comes-alive#836]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

**Comment by isayhao** [comment]
I'm doing the 100 Baby Challenge in MC, and I cannot figure out why the heck my children's babies don't grow up from their hands! The other villagers that aren't related to me, their babies grow up just fine and don't take long at all. But **my** children's babies have been in their hands FOREVER! Don't hate me for this, but I just said I use the latest version of the mod, but I use 1.7.10. But trust me, I HAVE used it in the newest version before, still doesn't work. I have story progression rate at 2 minutes cause I like to have things progress faster, but maybe that's causing the problem..? I'm not sure. I've searched all over the internet, no answer. So I finally thought I'd make an account here and post. 

Thanks.

**Comment by LeftoverFlea312** [comment]
I have the same problem, the creator is working on it for the next update but it still sucks they wont grow up.

**Comment by isayhao** [comment]
Aw. I was hoping it would'a bee fixed. Will it be available for 1.7.10? Or is it gonna be for 10. blah blah blah...--? 
Oh wait that was a stupid question, your not the developer XD

**Comment by LeftoverFlea312** [comment]
I'm not sure, but my guess is that it will be for 11.2 when it come out.

**Comment by isayhao** [comment]
Crap! That's bad. I do not go above 1.7.10, most mods are best in that version. (my opinion.) I mean, it just doesn't make sense to me cause I have the latest version, just in 1.7.10. Maybe I don't? I have everything that other players have and they're on higher versions than 1.7.10. I've seen HeyImBee on Youtube, and her children's babies grow up fine. But she is on the latest version.
May I ask what version you're playing on?

**Comment by LeftoverFlea312** [comment]
I'm playing on 1.10.2. Sometimes the baby grows into a child but most of the time they just hold it in their hand.

**Comment by isayhao** [comment]
😞  Ah. Its definitely 1.7.10 then. Maybe my mod isn't updated? I have been using the same download for sometime in 2016 to right now. I will check.

**Comment by isayhao** [comment]
No, I have the latest version in 1.7.10 . 5.2.3 is the latest version, its for 1.10.2 . Ughhh this sucks. 😒 1.10.2 sucks. I'll keep this issue open, in case it ever gets fixed for 1.7.10.

**Comment by WildBamaBoy** [comment]
Tested on 1.12, works normally.

Unfortunately 1.7.10 and 1.10.2 are no longer supported. :(

**Comment by jinxclinator** [comment]
> Tested on 1.12, works normally.
> 
> Unfortunately 1.7.10 and 1.10.2 are no longer supported. :(

i've got version 1.12.2 and i'm having a similar problem :( I've tried other versions and its the same, i'm thinking it might be something to do with anything on my side? I've had this problem before but i remember revisiting my mods again and having it run perfectly normal. The problem i'm facing now is that villager babies and MY babies won't grow up (from the baby item thingy), no matter how many minutes. I've changed the mods settings as well to see if that bugged it but its still the same (however i did notice that some of the mod settings repeated themselves? not sure if that indicates anything). I've tried everything i can think of :( if you have any information please let me know.

**Comment by jinxclinator** [comment]
also when an NPC has a baby and i leave the game and come back into the game, the baby is gone. I should also say that i have other mods installed as well but i have tried playing with just MCA and no luck still.
