### ISSUE TITLE
EntityChoreFishHook - Server Crash

### ISSUE THREAD

**Issue by SkyBlade1978** [WildBamaBoy/minecraft-comes-alive#837]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

MC 1.10.2 MCA 5.2.3

Server crashes shortly after restarting, from the crash log I beleive the error originates within mca.entity.EntityChoreFishHook

Start the server (I have a small server instance as I recently made a new one using my usual set of mods), I can zip up the server instance and provide it.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.2.7.0.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.13.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/12/17 5:47 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.enchantment.Enchantment.func_185260_a(Enchantment.java:55)
	at net.minecraft.enchantment.EnchantmentHelper.func_185284_a(EnchantmentHelper.java:200)
	at net.minecraft.enchantment.EnchantmentHelper.func_151387_h(EnchantmentHelper.java:256)
	at mca.entity.EntityChoreFishHook.func_70071_h_(EntityChoreFishHook.java:470)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.enchantment.Enchantment.func_185260_a(Enchantment.java:55)
	at net.minecraft.enchantment.EnchantmentHelper.func_185284_a(EnchantmentHelper.java:200)
	at net.minecraft.enchantment.EnchantmentHelper.func_151387_h(EnchantmentHelper.java:256)
	at mca.entity.EntityChoreFishHook.func_70071_h_(EntityChoreFishHook.java:470)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: MCA.EntityChoreFishHook (mca.entity.EntityChoreFishHook)
	Entity ID: 2342
	Entity Name: entity.MCA.EntityChoreFishHook.name
	Entity's Exact location: -740.73, 62.77, -75.14
	Entity's Block location: World: (-741,62,-76), Chunk: (at 11,3,4 in -47,-5; contains blocks -752,0,-80 to -737,255,-65), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Entity's Momentum: 0.45, -0.17, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['SkyBlade1978'/257, l='world', x=-729.94, y=70.00, z=200.19], EntityPlayerMP['StarCraft2010'/2104, l='world', x=-761.45, y=101.23, z=61.25]]
	Chunk stats: ServerChunkCache: 863 Drop: 0
	Level seed: -6738292633650397043
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: BIOMESOP
	Level spawn location: World: (0,64,61), Chunk: (at 0,4,13 in 0,3; contains blocks 0,0,48 to 15,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 15774380 game time, 13066091 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 10603 (now: false), thunder time: 93678 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_11, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 894166720 bytes (852 MB) / 1755316224 bytes (1674 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	buildingbrickshooks{1.10.2-2.0.13} [Building Bricks Hooks] (minecraft.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	AutoSapling{1.3.3} [AutoSapling] (Autosapling-1.3.3-MC1.10.jar) 
	UCHIJAAAA	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	buildingbricks{1.10.2-2.0.13} [Building Bricks] (BuildingBricks-1.10.2-2.0.13.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	cyclopscore{0.9.1} [Cyclops Core] (CyclopsCore-1.9.4-0.9.1.jar) 
	UCHIJAAAA	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCHIJAAAA	dsurround{3.2.7.0} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.2.7.0.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJAAAA	mineralogy{3.2.0} [Mineralogy] (Mineralogy_1.10.2-3.2.0.jar) 
	UCHIJAAAA	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	poweradvantage{2.3.0} [Power Advantage] (PowerAdvantage_1.10.2-2.3.0.jar) 
	UCHIJAAAA	steamadvantage{2.2.0} [Steam Advantage] (SteamAdvantage_1.10.2-2.2.0.jar) 
	UCHIJAAAA	structuredcrafting{0.1.7} [Structured Crafting] (StructuredCrafting-1.9.4-0.1.7.jar) 
	UCHIJAAAA	zc_villages{0.11.4} [ZC Villages] (ZC Villages-0.11.4-1.10.2.jar) 
	Loaded coremods (and transformers): 
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.2.7.0.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.13.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
	Profiler Position: N/A (disabled)
	Player Count: 2 / 20; [EntityPlayerMP['SkyBlade1978'/257, l='world', x=-729.94, y=70.00, z=200.19], EntityPlayerMP['StarCraft2010'/2104, l='world', x=-761.45, y=101.23, z=61.25]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by WildBamaBoy** [comment]
Reproduce the issue with just MCA and RadixCore.
