### ISSUE TITLE
Hearts disappear when I close the game and open it again

### ISSUE THREAD

**Issue by LittleKaraChan** [WildBamaBoy/minecraft-comes-alive#838]
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.

## Versions
Minecraft version: 1.8
MCA version: 1.8 (5.1.1.2)

## Issue Description
When I increase/decrease the amount of hearts in one session, MCA works just fine. Yet, when I close Minecraft and open it up again, all the hearts will have disappeared and I have to gift them things and chat non-stop.

**Comment by WildBamaBoy** [comment]
1.8 is not supported.
