### ISSUE TITLE
(1.10.2) Family wont follow me

### ISSUE THREAD

**Issue by deadlord87** [WildBamaBoy/minecraft-comes-alive#839]
- [] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

1.10.2 Versions

After I got married and got twins, I tried to make one of my children to follow me. He could follow me but after that, I left the game to install a resource pack. With the pack installed, I tried to make him follow me but there was no option, I removed the resource pack and still the option didn't appear. After that, I checked if I could make other villagers to follow me and I could. This issue also made it so that I could only chat with them. (only happens to family, villagers are fine) ((sorry fo bad grammar, I'm Spanish))

## Reproduce Steps

I also tried chatting wit my son but it caused the game to crash.

**Comment by WildBamaBoy** [comment]
Please provide any relevant crash reports.
