### ISSUE TITLE
[1.7.2] Unable to have babies with other players

### ISSUE THREAD

**Issue by AgentTexas** [WildBamaBoy/minecraft-comes-alive#84]
Everything was working fine, another player and I were playing a game through LAN, we got married and had a baby. I had the baby in my inventory, and when it was time to grow up I put her on the ground and she grew up. Everything was working great---then zombies spawned inside the house randomly(which NEVER happened before) and killed her before we could even get near them. All in a split second.

So we were just going to have another baby but...we can't. For me, we're married, we can have a baby, we can divorce but for them, the mod repeatedly tells them they're not married. We tried divorcing but it doesn't work. Even after getting remarried. Still, everything appears fine for me, I send them a "Have Baby" and it says to accept, but it tells them "You're not married" no matter what. They can ask me to marry them, I can ask them to marry me--it will say "You are now married to ___" but still tells them they're not married.

We also tried using the console commands with no luck.

So sad :( Your mod is great, but it won't work.

We're playing in 1.7.2 with the version you just put out.

These are the mods we're using:
forge-1.7.2-10.12.0.1024
DrZharks MoCreatures Mod v6.2.0-DEV-R2
CustomMobSpawner 3.2.0-DEV-R2
[1.7.2] ChickenShed (v1.1.3)
DynamicLights-1.7.2
FamiliarsAPI-1.7.2b
FamiliarsDefaultMobPack-1.7.2a
FamiliarsExtendedFamPack-1.7.2a
FamiliarsHerobrineFamPack-1.7.2a
InfernalMobs-1.7.2
More Swords Mod 2.6.1 For 1.7.2
MorePlayerModels_1.7.2
Necromancy-1.7.2
OptiFine_1.7.2_HD_U_D1
PetBat-1.7.2
TF2Teleporter-1.7.2
weaponmod-1.14.2
yafm-1.0.1
MCA-4.0.0 MC-1.7.2
RadixCore-1.0.0 MC-1.7.2

I would say it's a conflict, but we've been playing this whole time with these mods and it worked fine. :<

**Comment by Godlike3** [comment]
I was having a issue simmilar to this, but instead, I was married to a NPC and when I tried to procreate, the LAN world would crash (it was my friends hosting it) I had him go into my player properties and set babyExists to true, saved it, and then set it to false again. That fixed the issue perfectly.
