### ISSUE TITLE
Render Crash

### ISSUE THREAD

**Issue by Farronox** [WildBamaBoy/minecraft-comes-alive#840]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [X] I am crashing and can provide my crash report.

MC: 1.10.2 MCA 5.2.3

Crash when looking at Any Villager

Load game, Look at villager

Other mods installed, crash report doesn't seem to point at anything else. Will correct if others notice something I miss. 
Crash Report: https://pastebin.com/1TJFmrGQ

**Comment by WildBamaBoy** [comment]
Looks like it goes through `killerofcubes.rpgracemod.render.CustomRenderManager` first and that's your RPG Race Mod.

**Comment by Farronox** [comment]
Welp, my bad, while testing I Thought i'd completely removed that mod thinking it was the problem. Removed the module I missed and it works fine. Sorry for bothering you.
