### ISSUE TITLE
wife and golden lasso

### ISSUE THREAD

**Issue by superon** [WildBamaBoy/minecraft-comes-alive#847]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

## Versions
mc 1.10.2
MCA-1.10.2-5.2.3-universal

## Issue Description
got a wife an tried to golden lasso her, crashed the client

**Comment by WildBamaBoy** [comment]
No crash report provided.
