### ISSUE TITLE
MCA AI Farming

### ISSUE THREAD

**Issue by OttoOttoman** [WildBamaBoy/minecraft-comes-alive#849]
[Yes] I am running the latest mod versions of MCA and RadixCore.
[NO] I can reproduce this issue with just MCA and RadixCore installed.
[Yes] I can provide my Minecraft version and MCA version.
- [YES] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [YES] I am crashing and can provide my crash report.

Versions
Minecraft 1.10.2
MCA 1.10.2 5.2.3

ISSUE DESCRIPTION
The server will crash or shutdown to players giving gifts to there children or interacting with npcs like priest or pastor funny huh. Also keeps saying AI farming in crash report can't figure out the cause.

ADDITIONAL INFORMATION
[crash-2017-06-29_11.11.05-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1112663/crash-2017-06-29_11.11.05-server.txt)
[crash-2017-06-29_11.52.05-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1112664/crash-2017-06-29_11.52.05-server.txt)

**Comment by WildBamaBoy** [comment]
SpongeForge isn't officially supported at this time.
