### ISSUE TITLE
Custom Skins not working

### ISSUE THREAD

**Issue by BrutalKey** [WildBamaBoy/minecraft-comes-alive#850]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [X] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions Minecraft Version- 1.7.10   MCA 5.2.2
![2017-06-26_18 04 15](https://user-images.githubusercontent.com/29717829/27563915-fdbaf736-5a99-11e7-9309-e02ac26e966b.png)

## Issue Description 
 I have been trying to use custom skins for the villagers but the skins continue to come out wrong.
Here's a picture. I downloaded a image of GuardM11's skin off of Skindex. 

![2017-06-26_18 04 15](https://user-images.githubusercontent.com/29717829/27563915-fdbaf736-5a99-11e7-9309-e02ac26e966b.png) 

## Reproduce Steps
Download MCA 5.2.2 and RadixCore
Download and run Forge 
Download a skin off Skindex
Open the MCA jar folder with Archive Utility
Insert skins into the assets/mca/textures/skins folder with their name changed to their profession and next ID number
Insert a sleeping skin into the sleeping folder
Exit the folder and compress the 6 files inside
Rename the folder .jar
Insert the MCA jar file and RadixCore file into minecraft mods folder
Start Minecraft
Create a Villager and use the villager editor to change it to the custom skin

## Additional Information
  I have tried this with different skins and both Alex and Steve type skins. I have noticed that the skins I download are bigger than the original MCA skins which could be the cause, but I have no idea how to fix it.

**Comment by BrutalKey** [comment]
Never mind. I found out that i was using 64 by 64 skins when i needed to be using 64 by 32 skins.

**Comment by Hunterballard** [comment]
Hi, I have a similar problem. I download a skin off skindex then edit the same one to be sleeping. Rename the 2 (ex bakerf14) then put one into my textures with the other skins and the other into the sleeping folder. They always end up looking all jumbled. I tried searching 64x32 skins on skindex and put the one I found in Minecraft but the same thing happens. Can someone help me, please?

**Comment by MasonBlood9696** [comment]
> Hi, I have a similar problem. I download a skin off skindex then edit the same one to be sleeping. Rename the 2 (ex bakerf14) then put one into my textures with the other skins and the other into the sleeping folder. They always end up looking all jumbled. I tried searching 64x32 skins on skindex and put the one I found in Minecraft but the same thing happens. Can someone help me, please?

Find the skin you want to change. Edit with Paint. Zoom in so you can see clearly the skin. On the down below says 64x64. What you need to do is resize it untill you get 64x32. (You can see down below). And That's it. 

Don't forget to make the white background transparent!
