### ISSUE TITLE
zombie villager 1.10.2

### ISSUE THREAD

**Issue by creeperswag799** [WildBamaBoy/minecraft-comes-alive#851]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
1.10.2

## Issue Description
I have found that when a zombie pigman kills/infects a villager they will either die or become an normal infected vanilla minecraft zombie villager and when you cure them you lose all of your hearts with them and they become a whole new villager I believe that one zombie pigman should turn villagers into infected villagers but the mca version I am currently playing on 1.10.2  

## Reproduce Steps
spawn a villager and a zombie pigman also I have found that its a chance for them to turn into zombie villagers so it may take a couple trys may need to try in dark

**Comment by WildBamaBoy** [comment]
This should be fixed in 1.12
