### ISSUE TITLE
Server crash - java.lang.RuntimeException: Error while interacting with block minecraft:air with null. Method:ENTITY  Button:RIGHT_CLICK

### ISSUE THREAD

**Issue by ProsperCraft** [WildBamaBoy/minecraft-comes-alive#852]
- [X] I am running the latest mod versions of MCA and RadixCore.
- [Tolkiencraft3] I can reproduce this issue with just MCA and RadixCore installed.
- [X] I can provide my Minecraft version and MCA version.
- [X] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report.

## Versions
1.10.2  
MCA{1.10.2-5.2.3}

## Issue Description
Server crashes on player login.

## Reproduce Steps
Player logs in.

## Additional Information
https://github.com/rwtema/extrautilities/issues/1165

More then one mod in the stacktrace, including you both.

**Comment by WildBamaBoy** [comment]
Player data is handled differently in 1.12, try again on 1.12 and report again.
