### ISSUE TITLE
Build.gradle compile errors

### ISSUE THREAD

**Issue by Tsoccerguy3** [WildBamaBoy/minecraft-comes-alive#854]
Some issues in build.gradle for 1.12 Java should be updated to 8 
after compiling RadixCore-1.12-2.1.9-deobf.jar and moving it to mca/lib 
Then running Gradlew setupdecompworkspace build , I get the following errors
I also tried updating Forge and mappings , to current as of today 

`#################################################
         ForgeGradle 2.3-SNAPSHOT-effc52c        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:sourceApiJava
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJavaC:\Users\ASUS\Dev\mca\build\sources\main\java\mca\entity\EntityVillagerMCA.java:8: error: package com.sun.istack.internal does not exist
import com.sun.istack.internal.NotNull;
                              ^
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\entity\VillagerAttributes.java:15: error: package com.sun.istack.internal does not exist
import com.sun.istack.internal.NotNull;
                              ^
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\actions\ActionProcreate.java:20: error: cannot find symbol
import net.minecraft.stats.Achievement;
                          ^
  symbol:   class Achievement
  location: package net.minecraft.stats
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\client\render\RenderFishHook.java:6: error: cannot find symbol
import net.minecraft.client.renderer.VertexBuffer;
                                    ^
  symbol:   class VertexBuffer
  location: package net.minecraft.client.renderer
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\forge\client\MCAGuiFactory.java:30: error: cannot find symbol
	public RuntimeOptionGuiHandler getHandlerFor(RuntimeOptionCategoryElement element) 
	       ^
  symbol:   class RuntimeOptionGuiHandler
  location: class MCAGuiFactory
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:5: error: cannot find symbol
import net.minecraft.stats.Achievement;
                          ^
  symbol:   class Achievement
  location: package net.minecraft.stats
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:6: error: cannot find symbol
import net.minecraftforge.common.AchievementPage;
                                ^
  symbol:   class AchievementPage
  location: package net.minecraftforge.common
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:14: error: cannot find symbol
	public static final Achievement fullGoldHearts = new Achievement("fullGoldHearts", "fullGoldHearts", 0, 0, Blocks.YELLOW_FLOWER, null);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:15: error: cannot find symbol
	public static final Achievement engagement = new Achievement("engagement", "engagement",  2, 0 + 2, ItemsMCA.engagementRing, fullGoldHearts);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:16: error: cannot find symbol
	public static final Achievement marriage = new Achievement("marriage", "marriage",4, 0, ItemsMCA.weddingRing, engagement);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:17: error: cannot find symbol
	public static final Achievement babyBoy = new Achievement("babyBoy", "babyBoy", 6, middle + 1, ItemsMCA.babyBoy, marriage);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:18: error: cannot find symbol
	public static final Achievement babyGirl = new Achievement("babyGirl", "babyGirl", 6, middle - 1, ItemsMCA.babyGirl, marriage);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:19: error: cannot find symbol
	public static final Achievement twins = new Achievement("twins", "twins", 6, middle, ItemsMCA.toyTrain, marriage);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:20: error: cannot find symbol
	public static final Achievement babyToChild = new Achievement("babyToChild", "babyToChild", 8, middle, Items.CAKE, marriage);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:21: error: cannot find symbol
	public static final Achievement hunting = new Achievement("hunting", "hunting", 9, middle + 1, Items.BOW, babyToChild);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:22: error: cannot find symbol
	public static final Achievement mining = new Achievement("mining", "mining", 10, middle + 1, Items.IRON_PICKAXE, babyToChild);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:23: error: cannot find symbol
	public static final Achievement woodcutting = new Achievement("woodcutting", "woodcutting", 9, middle - 1, Items.IRON_AXE, babyToChild);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:24: error: cannot find symbol
	public static final Achievement farming = new Achievement("farming", "farming", 10, middle - 1, Items.IRON_HOE, babyToChild);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:25: error: cannot find symbol
	public static final Achievement childToAdult = new Achievement("childToAdult", "childToAdult", 11, middle, Items.IRON_SWORD, babyToChild);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:26: error: cannot find symbol
	public static final Achievement childMarried = new Achievement("childMarried", "childMarried", 13, middle, ItemsMCA.matchmakersRing, childToAdult);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\core\minecraft\AchievementsMCA.java:27: error: cannot find symbol
	public static final Achievement childHasChildren = new Achievement("childHasChildren", "childHasChildren", 15, middle, ItemsMCA.babyBoy, childMarried);
	                    ^
  symbol:   class Achievement
  location: class AchievementsMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\data\PlayerDataCollection.java:10: error: cannot find symbol
import net.minecraft.world.WorldSavedData;
                          ^
  symbol:   class WorldSavedData
  location: package net.minecraft.world
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\data\PlayerDataCollection.java:13: error: cannot find symbol
public class PlayerDataCollection extends WorldSavedData 
                                          ^
  symbol: class WorldSavedData
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\packets\PacketInteractWithPlayerS.java:19: error: cannot find symbol
import net.minecraft.stats.Achievement;
                          ^
  symbol:   class Achievement
  location: package net.minecraft.stats
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\entity\EntityVillagerMCA.java:483: error: cannot find symbol
	public void startMarriage(@NotNull Either<EntityVillagerMCA, EntityPlayer> either)
	                           ^
  symbol:   class NotNull
  location: class EntityVillagerMCA
C:\Users\ASUS\Dev\mca\build\sources\main\java\mca\entity\VillagerAttributes.java:240: error: cannot find symbol
	public void setFiancee(@NotNull EntityPlayer player) 
	                        ^
  symbol:   class NotNull
  location: class VillagerAttributes
26 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.669 secs
`

**Comment by WildBamaBoy** [comment]
When you tried this, MCA was not updated to 1.12 which is why you were seeing these errors. You were compiling 1.10.2/1.11 code.
