### ISSUE TITLE
With the left hand, the baby can be infinitely generated

### ISSUE THREAD

**Issue by StarchierOrb** [WildBamaBoy/minecraft-comes-alive#855]
I am running the latest mod versions of MCA and RadixCore.
I can reproduce this issue with just MCA and RadixCore installed.
 I can provide my Minecraft version and MCA version.
 I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.

**Versions**

1.10.2
MCA{1.10.2-5.2.3}

**Issue Description**

With the left hand, the baby can be infinitely generated

**Reproduce Steps**

 1.Hold the baby in your right hand until the baby can be place
2. and use left hand，the baby can be infinitely generated

**Additional Information**
None

**Comment by WildBamaBoy** [comment]
Tested on 1.12, issue does not occur.
