### ISSUE TITLE
MCA Families

### ISSUE THREAD

**Issue by Log01234** [WildBamaBoy/minecraft-comes-alive#856]
My brother and i play mca alot and every time we get a wife and kids and everything a few hours into the game our families just switch. calling him dear instead of me. it has been a problem for a while now and iv only recently tried to fix it. curently i am using orespawn with MCA 1.7.10 but in the past we have played using only this mod and the same problem has occured. please help. its tiresome to have to deal with this so many times and for seamingly no reason.

**Comment by WildBamaBoy** [comment]
1.7.10 is no longer supported. 1.12 should not have this problem.
