### ISSUE TITLE
[1.10.2] Villagers disappear when going out of range in "home" village.

### ISSUE THREAD

**Issue by Tezorian** [WildBamaBoy/minecraft-comes-alive#861]
MCA Version: 5.2.3

Now with the third world, i am seeing the same thing happen again.

Whenever i go out of range of my home location some villagers disappear. The current village had 14 villagers and is now down to 2. One is a tinkerer who sits on a chair and the other one is a clerk whom i have yet to interact with. Everyone else just disappeared. Even the bankers are gone, who were in a closed and lit up bank.

A thing to note is, they only disappear if i go out of chunkload range for at least a full minecraft day.
They also disappear after they turn invisible. The entity is there, but isn't shown. Upon "save and quit to title" and reload, in the hopes of them showing again, they were gone.

Edit: worth noting. The entire village is fenced off and entirely lit. I will also try running MC with just MCA, see if that results in the same issue.

Edit: Tested with just MCA. The problem does not occur. Neither do villagers appear invisible. As such, i can't reproduce the issue.  (i'll continue to see if i can figure out what/when/if)

**Comment by WildBamaBoy** [comment]
Closing as the issue was not reproducible with just MCA.
