### ISSUE TITLE
Clonecraft crashes MCA [1.7.10]

### ISSUE THREAD

**Issue by TheLastSpectre** [WildBamaBoy/minecraft-comes-alive#862]
- [x] I am running the latest mod versions of MCA and RadixCore.

- [x]  I can reproduce this issue with just MCA and RadixCore installed.

- [x] I can provide my Minecraft version and MCA version.

- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.

- [x] I am crashing and can provide my crash report.

When a human clone from the Clonecraft mod attacks pretty any mob, animal, villager, etc. while an MCA villager is in the same area, the game crashes. I have only Clonecraft and MCA installed, using MCA version 5.2.2 and RadixCore 2.1.3.

Crash report: https://pastebin.com/Gzv7PTty
Log: https://pastebin.com/e8t2GawH

**Comment by WildBamaBoy** [comment]
1.7.10 is no longer supported
