### ISSUE TITLE
Can I revive my family members in version 5.2.2?

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#864]
If you need more details or already knew about this is okay

I have been trying several versions of MCA to see in which could revive my relatives, and I saw that if I wear an engagement ring and procreated with my fiancee but she died, only my son released the object to revive it but my fiance did not

When I gave her a wedding ring and procreated with her being my wife if I gave both my wife and my son the object to revive them with the "Staff of life"

All this is in the version of MCA 5.2.2 for minecraft 1.7.10 in which I saw that they had only corrected the problem in the minecraft 1.10.2 according to the changelogs, but it works for me

I think the problem is that at the time of compromise or marriage did not work when I gave the engagement ring to an NPC, but if I gave the wedding ring to an NPC and with both rings if the children died give me objects to Revive them

Also when playing on a server I am not sure but unlike the NPC if a player marries another player, and their children die these did not release objects to revive them

What happens is that a friend married another player and when the children died did not leave the coffers with the object to revive it

PS: if I find another mistake I will let them know

**Comment by ghost** [comment]
Translate with google excuse the errors if there are

**Comment by WildBamaBoy** [comment]
All versions with the "Staff of Life" allow reviving family members. To revive your spouse, you must be married, not engaged.
