### ISSUE TITLE
Grim Reaper feels on the "unfair" side

### ISSUE THREAD

**Issue by Darkmega18** [WildBamaBoy/minecraft-comes-alive#866]
This is mostly a suggestion on how to make the grim reaper possibly a funner fight without him being super salty. I was attempting to fight him and the first time he smoked me pretty hard with the prescribed diamond armor, shield and sword. The main issue is that his attack isn't blockable or avoidable unless you're moving super fast or get lucky with Tinker battlesign blocking or don't give him a chance to hit at all (cheese him out with PlusTIC laser beams) but he'll probably just hit you anyway cause it tracks.

I like the mindgames he plays where he flies up and either readies the scythe or prepares a block. But even after he tries to juke you out with a block, he still goes straight slapping you, usually multiple times. Or if he was gonna slap you anyway, occasionally you can hit him hard enough to knock him well away and he'll stop and come out of the telegraph pose, but usually he'll just slash you and get stuck infront of you instead of continuing on through and hit you again, then come back the other way if he didn't end far enough.

So my suggestion is this:

Reaper flies towards player. when reaper gets close:
a. prepare a block for 2 seconds then either prepare the attack or port away.
or b. telegraph an attack for 1 second. 
If you hit him while he's telegraphing he teleports away and keeps coming at you. If you hit the block instead, port him 3 spaces behind the player and prepare the dash telegraph from there.
If he fully readies the attack, proceed to dash through the player (and try not to get stuck) and then he flies off and comes back around to do you again but never dash immediately again flurrying you on the spot cause thats salty even with armor. but if he impacts a shield make him disappear and either:

a. Port to the side and charge up a stronger attack for 2 seconds that uses the same animation but makes him flash at the one second charge time cannot be canceled but he remains stationary and penetrates shields dealing big magic damage (produce a big black slash effect coming downwards ontop of the player that signifies where the attack landed and possibly a nondamaging explosion and particle effects).
b. port backwards from the player and continue his assault.

I like the healing phase but in packs where you have some extreme high jump or even pseudo/proper flight you can easily fly up to him and slap him. So perhaps if you get too close to him he should produce a blast of energy to knock you away then teleport somewhere else. But if you find another way to damage him he should also port away.

Alternatively another "ability" could be that when below half health no matter what he will summon mobs every 6-8 seconds that not only act as distractions but he can search for nearby undead minions and proceeds to teleport to them and absorb them (instagib) for some slight heals other than the major healing ability or instead use their dark energy to throw a dark energy ball at you that acts like a ghast ball with a larger explosion but doesn't destroy blocks and can be knocked away with timing (and even back at him for bonus damage)

... Anyway, despite my tangent, TL:DR, Reaper sometimes gets stuck and spam attacks you, and I find it really annoying that it tracks, comes out so fast and can't atleast be blocked for the "smart fighter" who doesn't want it to devolve into basically a DPS/stay healed potion all day everyday style fight. :V (mind you, I could've just been using some modded shields and they could just not be implemented right to actually defend or my reaction time isn't amazing, or the block takes a moment to occur which is also very salty cause I'm a very perfect timing blocker. :V)

**Comment by WildBamaBoy** [comment]
We won't be changing the fundamentals of the battle, but it was intended that when he blocks, he will not continue to attack but rather teleport away _unless_ you hit him. If you hit him while he's blocking, he'll teleport _behind_ you and attack. If he uses the pre-attack animation (scythe drawn back) instead of blocking, you're free to hit him without consequences.

We'll check over this and make sure this is working properly. :)
