### ISSUE TITLE
MCA Villager profession not matching trades

### ISSUE THREAD

**Issue by Giskard13** [WildBamaBoy/minecraft-comes-alive#868]
Currently testing the mod on 1.12. I haven't found this listed anywhere else yet so I thought I would mention it. Regardless of what the MCA villagers profession is they always have one of the vanilla farmer profession variations of trades

**Comment by WildBamaBoy** [comment]
Thanks for the report.

**Comment by Setsuna6002** [comment]
I am having the same problem where the name of profession does not match and also the only professions I could trade with are shepherd, fletcher and farmer.

**Comment by Setsuna6002** [comment]
Another one is that whenever I try to get engaged or married, it says that I already have someone when that's not the case.

**Comment by WildBamaBoy** [comment]
@Setsuna6002 That would belong in a different issue, however I have found that particular problem and patched it, pending release.

**Comment by Gabby2805** [comment]
I'm using version 5.3.1 on 1.12.2 and I still have this problem. The MCA careers do not match the minecraft careers shown by HWYLA, and their trading inventories would suggest that hwyla is correct. I'm making my own village and I tried to use the [Villager Generator](https://www.digminecraft.com/generators/villager_trade_1_12.php) to spawn villagers with specific professions and inventories but they immediately get overwritten by MCA and mostly set to farmers (some fishermen and shepherds but no others) regardless of what MCA says their job is.
