### ISSUE TITLE
MCA 1.12 Villager Zombies turn into ghosts!!

### ISSUE THREAD

**Issue by foomasa** [WildBamaBoy/minecraft-comes-alive#869]
Villager Zombies don't have a skin when they are de-zombied.  You are left with shadows running around on the ground.  While it is incredibly funny and cool it is almost absolutely a bug.

**Comment by WildBamaBoy** [comment]
Unable to reproduce this - if it consistently seems to occur please upload the world in which this is occurring and I can try it out there.

**Comment by foomasa** [comment]
Unfortunately I cannot get the ghost but I will keep trying.  Possibly due to them being spawned in using an villager zombie egg but they do all come up missing a skin and with the name Steve the Farmer.  This is the same name/profession as in my main world.  No other mods.  Forge 1.12-14.21.1.2413.  Java build 1.8.0_144-b01.  
[MCA_villagerZombie_issue.zip](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1282755/MCA_villagerZombie_issue.zip)
![mca_villagerzombie_issue](https://user-images.githubusercontent.com/31578300/30135763-3eb13228-932a-11e7-9339-8f17a4f24539.png)
