### ISSUE TITLE
All Npcs are messed up.

### ISSUE THREAD

**Issue by renjirocks** [WildBamaBoy/minecraft-comes-alive#871]
Now, that may not be very explanatory, so i will elaborate. None of the npcs have names, the gui for talking to the npcs is messed up.. And just about everything is messed up, at least for me.
Included is a picture i took of myself talking to an npc, and what exactly i mean by "They are messed up." I have tried everything. Uninstalled the mod, reinstalled, even used the no hands needed pre installer on your website! It was working fine just a few days ago, i stopped to play some other games, and when i come back its all messed up. 
Also, I am running the latest version, on 1.12.
![wtf](https://user-images.githubusercontent.com/31382518/30135822-13afb656-9322-11e7-8a03-3ec34a855c3f.PNG)

**Comment by WildBamaBoy** [comment]
If you are using any language other than US English, this might occur. Working on a fix.

**Comment by WildBamaBoy** [comment]
Confirmed issue fixed with new language system
