### ISSUE TITLE
Rose Gold missing texture

### ISSUE THREAD

**Issue by FrostBite565** [WildBamaBoy/minecraft-comes-alive#874]
Using optifind in 1.12 and the rose gold texture is missing., if you need any other info then ask

**Comment by Catoptrix** [comment]
same for me using optifine 1.12.1 c5

**Comment by Mophise** [comment]
I'm not using optifine, I'm getting the missing texture bug in MC 1.12

**Comment by dragon3025** [comment]
I'm also having this problem.

**Comment by whovian1331** [comment]
Im also having the same problem

**Comment by WildBamaBoy** [comment]
So I kind of forgot to apply the texture to it. Whoops.
