### ISSUE TITLE
crash on server start(1.12.1-2467)

### ISSUE THREAD

**Issue by SDUBZ** [WildBamaBoy/minecraft-comes-alive#877]
forge: 1.12.1-2467
mca: MCA-1.12-5.3.0-universal
radix core: RadixCore-1.12-2.2.0-universal

[crash-2017-09-12_16.39.04-server.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1294955/crash-2017-09-12_16.39.04-server.txt)

**Comment by OttoOttoman** [comment]
Dude really lol. MCA 1.12 is for 1.12 not 1.12.1 they are different versions.

**Comment by SDUBZ** [comment]
funny thing @OttoOttoman that mca in 1.12.1 single player runs just fine :P

**Comment by Demodian** [comment]
Likely the same basic issue as #867 with just 1.12.

**Comment by OttoOttoman** [comment]
@SDUBZ Yes but the release states version 1.12 so there will be some errors trying to run it in a version higher.

**Comment by P3rf3ctXZer0** [comment]
I too have this issue.

**Comment by WildBamaBoy** [comment]
Known issue, working on a fix.

**Comment by P3rf3ctXZer0** [comment]
I am not on 1.12.1 anymore moved unto 1.12.2 for much needed farming fix.

**Comment by WildBamaBoy** [comment]
Fixed in 8506f4353e0efe4c3e8f0c3fe5aa46fd4d931376
