### ISSUE TITLE
Marriage won't work!

### ISSUE THREAD

**Issue by GoldInvestor1006** [WildBamaBoy/minecraft-comes-alive#878]
Whenever I gift someone an engagement ring, she says I have I spouse when I don't!

**Comment by QuiqueJara** [comment]
Same here. I'm using 1.12 and no other mods btw.

**Comment by WildBamaBoy** [comment]
Known issue, to be fixed in the next update. Run the command `/mca rm username` ingame, replacing `username` with your Minecraft username, and your marriage will be reset.
