### ISSUE TITLE
Gentleman's Relationship Guide has invalid book tag

### ISSUE THREAD

**Issue by Lorsieab2** [WildBamaBoy/minecraft-comes-alive#881]
When I open the Gentleman's Guide to Relationships, it only shows *invalid book tag* on all the pages. All the other books are fine, it's just this one that has that problem. I'm on version 1.12-5.3.0.

**Comment by WildBamaBoy** [comment]
~Did you pick up the book from a dungeon or villager in-game or pull it from the creative menu?~
Found the issue.
