### ISSUE TITLE
The game crashed whilst ticking entity (due to villagers)

### ISSUE THREAD

**Issue by omega015** [WildBamaBoy/minecraft-comes-alive#883]
I am testing the mod running on a remote server. Multicraft running forge-1.12-14.21.1.2387-universal.jar I have the mods MCA-1.12.x-5.3.1-universal & RadixCore-1.12-2.2.0-universal in both server and client mod folders. Also running the forge-1.12... on client.

Issue seems to be when I summon a villager or get anywhere near a village the game crashes (see attached for crash report)

[crash-2017-09-25_10.45.04-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1329019/crash-2017-09-25_10.45.04-client.txt)

**Comment by omega015** [comment]
Updated crash report (now using all the specified versions in the downloads page)

**Comment by PokerfaceCactus** [comment]
occurring on my server aswel, 3 of us,  2 of us crash out due to this same error when getting near a village, yet 1 of us can walk around villages without trouble.

**Comment by Demodian** [comment]
Needs (Boolean) typecast on return value on line 112 of ActionProcreate.java?

**Comment by ghost** [comment]
+1

Same here. We are 4 people playing on a server and the game crashes as soon as we get near a village.

**Comment by SARankDirector-Minecraft** [comment]
+1

I have experienced a similar crash on a public server me and a few friends play on, whenever I approach a village, or spawn in a villager, my game crashes.

I would really appreciate it if you could help.
