### ISSUE TITLE
Multi-player Client crash versus 1.12.2/14.23.0.2491 Server on Rendering entity

### ISSUE THREAD

**Issue by Demodian** [WildBamaBoy/minecraft-comes-alive#884]
Does not happen on single-player.  Only running Forge, MCA, and Radix Core mods.

Site didn't want to attach file.  Here's crash report.
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/25/17 6:56 PM
Description: Rendering entity in world

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
	at mca.actions.AbstractToggleAction.getIsActive(AbstractToggleAction.java:41)
	at mca.entity.VillagerBehaviors.isToggleActionActive(VillagerBehaviors.java:139)
	at mca.client.render.RenderVillagerMCA.doRenderEffects(RenderVillagerMCA.java:172)
	at mca.client.render.RenderVillagerMCA.doRender(RenderVillagerMCA.java:367)
	at mca.client.render.RenderVillagerMCA.func_76986_a(RenderVillagerMCA.java:34)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mca.actions.AbstractToggleAction.getIsActive(AbstractToggleAction.java:41)
	at mca.entity.VillagerBehaviors.isToggleActionActive(VillagerBehaviors.java:139)
	at mca.client.render.RenderVillagerMCA.doRenderEffects(RenderVillagerMCA.java:172)
	at mca.client.render.RenderVillagerMCA.doRender(RenderVillagerMCA.java:367)
	at mca.client.render.RenderVillagerMCA.func_76986_a(RenderVillagerMCA.java:34)

-- Entity being rendered --
Details:
	Entity Type: mca:villagermca (mca.entity.EntityVillagerMCA)
	Entity ID: 4213
	Entity Name: Steve
	Entity's Exact location: -188.08, 65.42, 527.66
	Entity's Block location: World: (-189,65,527), Chunk: (at 3,4,15 in -12,32; contains blocks -192,0,512 to -177,255,527), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: 0.01, 0.33, 0.04
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: mca.client.render.RenderVillagerMCA@4c8372f4
	Location: -8.22,2.42,49.81 - World: (-9,2,49), Chunk: (at 7,0,1 in -1,3; contains blocks -16,0,48 to -1,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 22.050968
	Delta: 0.98004305
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Demodian'/2137, l='MpServer', x=-179.87, y=63.00, z=477.86]]
	Chunk stats: MultiplayerChunkCache: 372, 372
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-140,64,252), Chunk: (at 4,4,12 in -9,15; contains blocks -144,0,240 to -129,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2642 game time, 2642 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 108 total; [EntityPlayerSP['Demodian'/2137, l='MpServer', x=-179.87, y=63.00, z=477.86], EntityCreeper['Creeper'/4357, l='MpServer', x=-131.50, y=50.00, z=417.50], EntitySkeleton['Skeleton'/4869, l='MpServer', x=-171.48, y=59.00, z=528.74], EntitySkeleton['Skeleton'/5133, l='MpServer', x=-171.50, y=59.00, z=527.50], EntitySkeleton['Skeleton'/5134, l='MpServer', x=-173.50, y=59.00, z=527.50], EntityEnderman['Enderman'/5148, l='MpServer', x=-213.50, y=46.00, z=502.50], EntityCow['Cow'/3615, l='MpServer', x=-251.50, y=63.00, z=434.50], EntityCow['Cow'/3616, l='MpServer', x=-251.50, y=63.00, z=434.50], EntityCow['Cow'/3617, l='MpServer', x=-249.50, y=64.00, z=433.50], EntityCow['Cow'/3618, l='MpServer', x=-253.50, y=64.00, z=435.50], EntityCreeper['Creeper'/4907, l='MpServer', x=-170.25, y=54.00, z=535.55], EntityZombie['Zombie'/4908, l='MpServer', x=-192.71, y=42.05, z=413.73], EntityZombie['Zombie'/4909, l='MpServer', x=-188.50, y=44.00, z=404.50], EntitySkeleton['Skeleton'/5167, l='MpServer', x=-152.50, y=16.00, z=409.50], EntityItem['item.item.seeds'/5168, l='MpServer', x=-224.50, y=63.00, z=475.45], EntityItem['item.tile.flower2.tulipRed'/5169, l='MpServer', x=-224.04, y=64.00, z=474.13], EntityCreeper['Creeper'/3895, l='MpServer', x=-226.50, y=52.00, z=425.50], EntityBat['Bat'/4151, l='MpServer', x=-133.93, y=50.24, z=409.20], EntityCreeper['Creeper'/3896, l='MpServer', x=-220.51, y=50.00, z=432.16], EntityBat['Bat'/4152, l='MpServer', x=-134.54, y=50.00, z=413.46], EntityCreeper['Creeper'/3897, l='MpServer', x=-224.00, y=52.00, z=427.16], EntityZombie['Zombie'/5177, l='MpServer', x=-155.50, y=24.00, z=486.50], EntityBat['Bat'/4154, l='MpServer', x=-189.41, y=43.06, z=410.13], EntityZombie['Zombie'/5178, l='MpServer', x=-154.50, y=24.00, z=486.50], EntitySkeleton['Skeleton'/3903, l='MpServer', x=-146.50, y=33.00, z=432.50], EntityWitch['Witch'/4415, l='MpServer', x=-176.23, y=38.34, z=441.60], EntitySkeleton['Skeleton'/3904, l='MpServer', x=-145.50, y=33.00, z=433.50], EntityWitch['Witch'/4416, l='MpServer', x=-176.46, y=38.00, z=443.78], EntitySkeleton['Skeleton'/4417, l='MpServer', x=-249.50, y=52.00, z=422.50], EntitySkeleton['Skeleton'/3910, l='MpServer', x=-169.50, y=18.00, z=401.50], EntitySkeleton['Skeleton'/3911, l='MpServer', x=-165.50, y=18.00, z=399.50], EntitySkeleton['Skeleton'/5193, l='MpServer', x=-181.50, y=47.00, z=398.50], EntitySkeleton['Skeleton'/5194, l='MpServer', x=-181.50, y=47.00, z=397.50], EntityCreeper['Creeper'/5199, l='MpServer', x=-171.50, y=59.00, z=524.50], EntityZombieVillager['Zombie Villager'/4944, l='MpServer', x=-245.50, y=33.00, z=537.50], EntityCreeper['Creeper'/5202, l='MpServer', x=-226.50, y=24.00, z=489.50], EntitySkeleton['Skeleton'/5204, l='MpServer', x=-191.50, y=39.00, z=398.50], EntityCreeper['Creeper'/4951, l='MpServer', x=-163.50, y=52.00, z=556.50], EntitySkeleton['Skeleton'/4696, l='MpServer', x=-176.50, y=41.00, z=430.50], EntitySkeleton['Skeleton'/4697, l='MpServer', x=-178.50, y=41.00, z=428.50], EntityItem['item.tile.flower1.dandelion'/4452, l='MpServer', x=-229.27, y=63.00, z=507.07], EntityZombie['Zombie'/4969, l='MpServer', x=-202.22, y=25.02, z=405.50], EntityZombie['Zombie'/4970, l='MpServer', x=-206.50, y=23.00, z=397.50], EntitySquid['Squid'/4716, l='MpServer', x=-138.51, y=61.01, z=442.97], EntityCow['Cow'/4204, l='MpServer', x=-148.60, y=67.00, z=522.58], EntitySquid['Squid'/4717, l='MpServer', x=-142.31, y=62.19, z=445.66], EntityCow['Cow'/4205, l='MpServer', x=-147.50, y=66.00, z=526.50], EntitySquid['Squid'/4718, l='MpServer', x=-143.93, y=60.00, z=439.62], EntityCow['Cow'/4206, l='MpServer', x=-151.47, y=68.00, z=516.84], EntityItem['item.tile.flower2.tulipWhite'/4974, l='MpServer', x=-199.95, y=63.00, z=463.74], EntitySquid['Squid'/4719, l='MpServer', x=-146.30, y=61.42, z=443.83], EntityCow['Cow'/4207, l='MpServer', x=-148.50, y=66.00, z=527.50], EntityItem['item.tile.flower2.tulipWhite'/4976, l='MpServer', x=-198.10, y=63.00, z=461.46], EntityVillagerMCA['Steve'/4213, l='MpServer', x=-188.08, y=65.42, z=527.66], EntityEnderman['Enderman'/4983, l='MpServer', x=-231.37, y=17.00, z=534.50], EntitySkeleton['Skeleton'/4986, l='MpServer', x=-180.50, y=56.00, z=553.50], EntityCow['Cow'/3711, l='MpServer', x=-109.50, y=69.00, z=444.50], EntityCow['Cow'/3712, l='MpServer', x=-108.50, y=68.00, z=441.50], EntityCow['Cow'/3713, l='MpServer', x=-118.50, y=73.00, z=445.27], EntityItem['item.item.seeds'/4993, l='MpServer', x=-222.20, y=63.00, z=474.13], EntityCow['Cow'/3714, l='MpServer', x=-107.50, y=68.00, z=441.50], EntityChicken['Chicken'/3715, l='MpServer', x=-201.78, y=64.00, z=441.50], EntityChicken['Chicken'/3716, l='MpServer', x=-212.20, y=63.00, z=448.87], EntityChicken['Chicken'/3717, l='MpServer', x=-208.82, y=66.00, z=439.90], EntityBat['Bat'/5007, l='MpServer', x=-173.51, y=61.10, z=524.25], EntityBat['Bat'/5008, l='MpServer', x=-179.51, y=59.78, z=525.27], EntityBat['Bat'/5011, l='MpServer', x=-171.00, y=60.41, z=524.54], EntityBat['Bat'/5012, l='MpServer', x=-188.72, y=62.48, z=523.14], EntitySpider['Spider'/5026, l='MpServer', x=-199.50, y=38.00, z=430.50], EntityZombie['Zombie'/4517, l='MpServer', x=-216.50, y=28.00, z=403.50], EntityZombie['Zombie'/4518, l='MpServer', x=-215.25, y=29.00, z=400.54], EntityCow['Cow'/3751, l='MpServer', x=-122.50, y=64.00, z=465.50], EntityCow['Cow'/3752, l='MpServer', x=-123.50, y=64.00, z=464.50], EntityCow['Cow'/3753, l='MpServer', x=-124.50, y=70.00, z=466.50], EntityCow['Cow'/3754, l='MpServer', x=-120.22, y=63.00, z=463.43], EntitySheep['Sheep'/3755, l='MpServer', x=-164.31, y=64.00, z=468.91], EntityBat['Bat'/4779, l='MpServer', x=-215.82, y=39.08, z=528.68], EntitySheep['Sheep'/3756, l='MpServer', x=-164.39, y=64.00, z=467.64], EntityBat['Bat'/4780, l='MpServer', x=-220.49, y=39.99, z=531.75], EntitySheep['Sheep'/3757, l='MpServer', x=-163.45, y=64.00, z=467.91], EntitySheep['Sheep'/3758, l='MpServer', x=-163.30, y=64.00, z=469.79], EntityBat['Bat'/4783, l='MpServer', x=-216.41, y=49.05, z=496.07], EntityCow['Cow'/3761, l='MpServer', x=-100.50, y=66.00, z=470.50], EntityZombie['Zombie'/4530, l='MpServer', x=-205.50, y=47.00, z=417.50], EntityCow['Cow'/3762, l='MpServer', x=-101.14, y=62.47, z=468.50], EntitySpider['Spider'/4531, l='MpServer', x=-133.50, y=11.00, z=497.50], EntityEnderman['Enderman'/4532, l='MpServer', x=-128.50, y=11.00, z=497.50], EntitySkeleton['Skeleton'/4533, l='MpServer', x=-135.50, y=11.00, z=499.50], EntitySheep['Sheep'/3776, l='MpServer', x=-205.50, y=64.00, z=479.50], EntitySheep['Sheep'/4544, l='MpServer', x=-254.50, y=63.00, z=556.50], EntitySheep['Sheep'/3777, l='MpServer', x=-204.45, y=65.17, z=483.41], EntitySheep['Sheep'/3778, l='MpServer', x=-209.20, y=63.00, z=484.51], EntitySheep['Sheep'/3779, l='MpServer', x=-203.50, y=66.00, z=480.50], EntityZombie['Zombie'/5073, l='MpServer', x=-198.50, y=46.00, z=401.50], EntitySkeleton['Skeleton'/4307, l='MpServer', x=-203.70, y=36.00, z=404.49], EntityItem['item.tile.doublePlant.syringa'/4563, l='MpServer', x=-120.72, y=74.00, z=446.08], EntityZombie['Zombie'/4576, l='MpServer', x=-146.50, y=32.00, z=428.50], EntityChicken['Chicken'/3558, l='MpServer', x=-217.60, y=63.00, z=416.23], EntityChicken['Chicken'/3559, l='MpServer', x=-216.50, y=64.00, z=420.50], EntityCow['Cow'/4335, l='MpServer', x=-183.50, y=67.00, z=545.50], EntityCow['Cow'/4336, l='MpServer', x=-183.50, y=67.00, z=546.50], EntityCow['Cow'/4337, l='MpServer', x=-179.72, y=73.00, z=554.16], EntityPig['Pig'/4338, l='MpServer', x=-175.32, y=67.00, z=545.46], EntityPig['Pig'/4339, l='MpServer', x=-169.31, y=68.00, z=539.91], EntityPig['Pig'/4340, l='MpServer', x=-172.70, y=68.00, z=539.32], EntityPig['Pig'/4341, l='MpServer', x=-175.60, y=68.00, z=539.31], EntitySkeleton['Skeleton'/5117, l='MpServer', x=-165.50, y=29.00, z=479.50], EntityZombie['Zombie'/5119, l='MpServer', x=-165.50, y=29.00, z=480.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 383858584 bytes (366 MB) / 1307049984 bytes (1246 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.0.2491 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                               | Signature                                |
	|:------ |:--------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJA | minecraft | 1.12.2       | minecraft.jar                        | None                                     |
	| UCHIJA | mcp       | 9.42         | minecraft.jar                        | None                                     |
	| UCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.0.2491.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge     | 14.23.0.2491 | forge-1.12.2-14.23.0.2491.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | radixcore | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None                                     |
	| UCHIJA | mca       | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.162.4' Renderer: 'AMD Radeon(TM) R6 Graphics'
	Launched Version: forge-14.23.0.2491
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R6 Graphics GL version 4.5.13474 Compatibility Profile Context 22.19.162.4, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7400P Radeon R6, 10 Compute Cores 4C+6G

**Comment by WildBamaBoy** [comment]
Provide a crash report.

**Comment by Demodian** [comment]
Done.

**Comment by Demodian** [comment]
If you want to reproduce, used seed "Ulantris" and headed south into flower forest to the south.  As I got close to the village, the crash occured.

**Comment by SDUBZ** [comment]
same here crash: http://puu.sh/xIWe7/708d8edd66.txt

**Comment by SDUBZ** [comment]
@WildBamaBoy any news on this issue

**Comment by Demodian** [comment]
Would adding a (Boolean) typecast be sufficient on line 41 of AbstractToggleAction.java?

**Comment by Demodian** [comment]
Would adding a .intValue() to line 215 in VillagerAttributes.java help correct the issue that SDUBZ is reporting (similar to the use on line 220)?

**Comment by ZeWolfTah** [comment]
Having the same issue. Was working fine on singleplayer, but crashes anyone who goes near a village on multiplayer.

Crash report:
https://pastebin.com/acCVphWH

MCA Version: MCA-1.12.x-5.3.1-universal

Edit:
Forge Version: forge-1.12.2-14.23.0.2503
While you can figure that out in the crash report, thought it might be nice to have it in the open

**Comment by ghost** [comment]
Is it related to this issue?: https://github.com/WildBamaBoy/minecraft-comes-alive/issues/883

Also I got the same problem.
+1

**Comment by Demodian** [comment]
@DangularSkysitter:  Not the same failure point in the code.  #883 is during the villagers procreating code.  Similar issue with typecasting, I believe though.

**Comment by VirtualGaming1** [comment]
having the same issue on my server for my modpack but do not know about SP

**Comment by AsuraTakun** [comment]
This is still an issue with Forge 2560. On my multiplayer server it crashed as soon as I tried to use the crystal ball (choosing I live in a village). It works on single player using the same instance without issue.

**Comment by Renari** [comment]
Same issue here: 
Forge 14.23.1.2585

https://openeye.openmods.info/crashes/cc8939203a9e32553d5617ea7ce1730d

**Comment by VirtualGaming1** [comment]
any update? feels like the mod is dead.

**Comment by MxtressMyxx** [comment]
My issue was tagged as related - would also like to ask if there has been an update regarding this issue. I am willing to help out with testing / logs as needed as this mod would add some nice depth to a pack I am working on. Without client/server support, I can't add it. :<

**Comment by jimnordb** [comment]
any news?

**Comment by CosmicHikari** [comment]
Same issue. It's pissing me off. About to uninstall.

**Comment by Renari** [comment]
@Dovahkiin-Warrior Threatening to uninstall isn't going to get you anywhere.  If it bothers you that much the mod is open source so you can fix the issue, It seems the mod developer doesn't have the time to fix it right now.

**Comment by CosmicHikari** [comment]
Threatening to uninstall? It's not a threat, it's a promise. And second off, if the mod creator can't fix it then what makes you think anyone else can? They haven't fixed it for a good reason..

**Comment by CosmicHikari** [comment]
Mostly that nobody in this community either knows how to or has offered to fix it yet.

**Comment by Renari** [comment]
There's a wiki here explaining how to work on minecraft mods:
https://wiki.mcjty.eu/modding/index.php?title=Main_Page

Secondly the how bit is relatively easy.
```java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean```

So on this line of code:
https://github.com/WildBamaBoy/minecraft-comes-alive/blob/1.12-5.3.1/src/main/java/mca/actions/AbstractToggleAction.java#L41

A float is being cast to a boolean, all that needs to be done is fix this single line of code so that it stops doing that.

**Comment by CosmicHikari** [comment]
Suppose that was done, how would one compile this? I know eclipse is an option but I don't feel like waiting hours for eclipse to download.

**Comment by Renari** [comment]
You don't need anything else than what is in the repo, just run.

```gradlew build``` 

After that you should find the mod jar in `build/libs`.

**Comment by WildBamaBoy** [comment]
I believe this issue is actually going to be deeper than that, but haven't looked into it yet. Neither of these two properties being fetched from the data manager are supposed to be `float`s, I'm not sure why they're appearing as such.

It's being looked in to. I know this is a common issue and we're looking to get it solved ASAP.

**Comment by Kowantify** [comment]
any update on this issue? love this mod but this is really driving me insane (not really i love this mod) but seriously i really like love this mod

**Comment by Lycanite** [comment]
This issue has plagued my mod for a long time, in the end I threw a try catch around every use of the datawatcher to suppress the crash, it just means that sometimes the client will ignore packets from the server, I haven't noticed any issues come from that so it's a good workaround for now.
I think the main cause is mod x will add a new value to the datawatcher and another mod y will do the same but they sometimes get mixed up where the client mod x receives a message from server mod y instead of x which is an incorrect datatype causing this cast exception.
The true fix is to ensure that all mod datawatchers never clash but this is very hard to manage, so for now just catching the exception and moving on is a good enough workaround as eventually mod x will send a message to mod x and the client receives the correct update anyway.
I just hope that my mod isn't doing anything to clash with other mods, though all my datawatcher values should be unique only to my own entities.

Edit: Actually if you use only MCA and no other mods the crash should never happen and it could in fact be caused by another mod entirely, this is what makes this bug so tricky as one mod shouldn't be able to mess with another mod. Perhaps if forge wrapped up the datawatcher in some way to make each added value bind to a mod this issue to could entirely avoided, but I'm not sure if that's the best solution and it could also mean extra data going through the network.

**Comment by capnkirok** [comment]
@Renari I really wish it was as easy as not casting one data type to another. There's nothing in the code that does that. In fact, the code would never compile if this was the case, it would error out. This is super frustrating to any modder who adds a few entities.

So, I have the same issue with Animania, but it appears to have gotten worse lately. I am going to try @Lycanite 's method of try/catch. It's not a perfect fix, but it lets the game continue. 

Lycanite's Data Parameter Try/Catch Example found here:
https://github.com/Lycanite/LycanitesMobs/blob/29d85172fc2b87e3d1e3d741c11558bff8708204/src/main/java/com/lycanitesmobs/core/entity/EntityCreatureBase.java#L509

**Comment by Renari** [comment]
Has anyone brought this up with @MinecraftForge, this doesn't seem like intended behavior.

**Comment by Lurmey** [comment]
Any update on this issue? It's been plaguing the server I'm creating for my modpack and it appears that, unless I get into developing mods myself, I can't do anything about it. Does anyone have a copy of the mod on 1.12.2 with the try/catch or should I temporarily remove the mod from the modpack?

Crash report (pastebin + file):
https://pastebin.com/qXAyBnBY
[crash-2018-03-11_08.49.52-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/1800177/crash-2018-03-11_08.49.52-client.txt)

**Comment by williewillus** [comment]
this happens when mods add data watcher entries to classes they do not own, INCLUDING vanilla classes.
unfortunately, it's hard to pin down exactly which mod is the offending one.
if a mod needs to add metadata to entities they don't own, they should be using capabilities.

**Comment by Renari** [comment]
If everyone experiencing this issue would install openeye it would help to slim down the list below.

https://openeye.openmods.info/crashes/cc8939203a9e32553d5617ea7ce1730d

Thus finding the offending mod.

**Comment by Lurmey** [comment]
@Renari My modpack is on 1.12.2, the latest version of OpenEye is on 1.12.1. Do you know if it'd be compatible? If so, I can manually install it to the pack, which would help slim down that list. I can already see lots of mods there that aren't in my modpack, suggesting that they've got nothing to do with it.

**Comment by Lurmey** [comment]
Tested it, OpenEye 1.12.1 does work on 1.12.2. Here's the crash from my pack on OpenEye since it's not identical as above: https://openeye.openmods.info/crashes/ea816e7b10bedc5d04a42f46d4406453

**Comment by Renari** [comment]
@Lurmey your crash is likely a different mod entirely than the one that is causing the issue in my list

**Comment by AlexModGuy** [comment]
this is an easy fix hold on

**Comment by AlexModGuy** [comment]
put all the crap in VillagerAttributes inside EntityMCAVillager. Thats causing this. Primitive mobs had a similar issue

**Comment by epicslayer999** [comment]
Alex is right, you should listen to him. I showed him the crash report; took him 5 minutes to see the mistake. Anyone know when WildBamaBoy could see this?

**Comment by AlexModGuy** [comment]
Source: https://github.com/Daveyx0/PrimitiveMobs/issues/53

check this out if the previous suggestion doesnt work @WildBamaBoy @capnkirok

**Comment by capnkirok** [comment]
Hey @Alex-the-666 the I'm using Lycanite's solution (referenced above) as a defensive mechanism against mods that break the rules (and create crashes that get posted to Animania). All of my mobs create their own Data Parameters as described in this thread.

**Comment by NotsoluckyClover** [comment]
Hi! How would you move the stuff in VillagerAttributes to EntityMCAVillager? Is it in the coding or in the files? (If in the files, how would you get to them?) 
If it's in the coding how would you edit it before the server start?

**Comment by aceaway12** [comment]
Would anyone happen to have a copy of a corrected .jar file lying around? I can't for the life of me figure out gradle, so I'm having some trouble implementing the fix suggested by @Alex-the-666

**Comment by mightyjaffa12** [comment]
@Alex-the-666 "put all the crap in VillagerAttributes inside EntityMCAVillager" how?

**Comment by williewillus** [comment]
Alex means move all these dataparameter declarations into the class they're for: https://github.com/WildBamaBoy/minecraft-comes-alive/blob/1.11.2-master/src/main/java/mca/entity/VillagerAttributes.java#L48

The data parameter definition system is really fragile and you have to define these in the class they belong to to avoid issues.

**Comment by mightyjaffa12** [comment]
so how would i as a simple minded human, do this without without completely destroying the entire mod. very frustrating that this issue was never patched in an update :P
