### ISSUE TITLE
Invisable Villagers

### ISSUE THREAD

**Issue by Ginger60** [WildBamaBoy/minecraft-comes-alive#885]
X    I am running the latest mod versions of MCA and RadixCore.
X    I can reproduce this issue with just MCA and RadixCore installed.
X    I can provide my Minecraft version and MCA version.
X    I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
    [] I am crashing and can provide my crash report.

Versions

Minecraft: 1.12 Forge
Forge: 14.21.1.2387
MCA 5.3.1
RadixCore: 2.2.0
Issue Description:
I just downloaded the most recent version of MCA.  It loaded with almost no problem.  I say "almost" because when I encountered a village.  I only see the shadows of its occupants.  To test to see if another mod was the cause of the problem, I started a new world and logged in.  After it loaded, I selected the option of living in a village, but when I went to move, my screen went black.  My game didn't crash, and I can hear my footsteps when I moved around.  So I restarted my game and went to try the same world again.  The icon had a strange red tinge to it.  I logged in anyway. Everything seemed normal.  But the villagers were still invisible.

![2017-09-25_23 07 27](https://user-images.githubusercontent.com/16965463/30845025-670b6e2a-a246-11e7-962e-50e88002602c.png)

**Comment by Ginger60** [comment]
So I just tried to change the skin of a villager using the Villager Editor book that comes with the mod.  And the game crashed.  Thing is I closed it before it could give me a crash report.

**Comment by sawatari01** [comment]
I am experiencing the same phenomenon. In case
Moreover, it is red as it gets damaged.
![01](https://user-images.githubusercontent.com/32459477/31084076-6e0a11c6-a7ce-11e7-8095-ebb090b22b06.jpg)

**Comment by twitcj** [comment]
Before I upgraded 1.12.0 to 1.12.2, these exact things were happening.
Now, in 1.12.2 I get this:
![2017-10-05_23 11 23](https://user-images.githubusercontent.com/32562090/31264122-4f759156-aa24-11e7-9705-9b424fb8cd62.png)

If I do anything with the Villager Editor, I get this:
`---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/5/17 11:12 PM
Description: Exception in server tick loop

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at mca.packets.PacketEditVillager.processOnGameThread(PacketEditVillager.java:118)
	at mca.packets.PacketEditVillager.processOnGameThread(PacketEditVillager.java:23)
	at radixcore.modules.net.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:174)
	at radixcore.core.RadixEvents.serverTickEventHandler(RadixEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_RadixEvents_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:277)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 303397864 bytes (289 MB) / 690765824 bytes (658 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2503 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                               | Signature                                |
	|:--------- |:----------------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.0.2503.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.0.2503 | forge-1.12.2-14.23.0.2503.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar          | None                                     |
	| UCHIJAAAA | radixcore         | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None                                     |
	| UCHIJAAAA | mca               | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Twitcj'/236, l='New World', x=1131.95, y=64.00, z=-918.78]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by Ginger60** [comment]
I loaded the mod into the 1.12.1 minecraft version, redownloaded the Radixcore, and still no visible villagers.  Just floating names.  I did try the Village editor, and when I clicked to change the skin, it crashed.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 10/12/17 6:17 PM
Description: Exception in server tick loop

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at mca.packets.PacketEditVillager.processOnGameThread(PacketEditVillager.java:118)
	at mca.packets.PacketEditVillager.processOnGameThread(PacketEditVillager.java:23)
	at radixcore.modules.net.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:174)
	at radixcore.core.RadixEvents.serverTickEventHandler(RadixEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_46_RadixEvents_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 345974392 bytes (329 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.0.2447 Optifine OptiFine_1.12.1_HD_U_C5 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12.1} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12.1-14.22.0.2447.jar) 
	UCHIJAAAA	forge{14.22.0.2447} [Minecraft Forge] (forge-1.12.1-14.22.0.2447.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.1.jar) 
	UCHIJAAAA	crafttweaker{4.0.3} [CraftTweaker2] (CraftTweaker-Mod-1.12.1.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-Mod-1.12.1.jar) 
	UCHIJAAAA	jei{4.7.5.87} [Just Enough Items] (Just-Enough-Items-Mod-1.12.1.jar) 
	UCHIJAAAA	crafttweakerjei{2.0.0} [CraftTweaker JEI Support] (CraftTweaker-Mod-1.12.1.jar) 
	UCHIJAAAA	exnihilocreatio{0.1.2} [Ex Nihilo Creatio] (Ex-Nihilo-Creatio-Mod-1.12.1.jar) 
	UCHIJAAAA	fastleafdecay{v14} [Fast Leaf Decay] (FastLeafDecay-Mod-1.12.1.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-3.0.0.jar) 
	UCHIJAAAA	initialinventory{2.0.2} [InitialInventory] (Initial-Inventory-Mod-1.12.1.jar) 
	UCHIJAAAA	justenoughbuttons{1.12-1.2.1} [Just Enough Buttons] (Just-Enough-Buttons-Mod-1.12.1.jar) 
	UCHIJAAAA	keepinginventory{2.3} [Keeping Inventory] (Keeping-Inventory-Mod-1.12.1.jar) 
	UCHIJAAAA	lunatriuscore{1.2.0.41} [LunatriusCore] (LunatriusCore-1.12.1.jar) 
	UCHIJAAAA	mapwriter{2.8.0} [MapWriter] (MapWriter-1.12.1-2.8.0.jar) 
	UCHIJAAAA	radixcore{1.12.x-2.2.1} [RadixCore] (RadixCore-1.12.x-2.2.1-universal.jar) 
	UCHIJAAAA	mca{1.12.2-5.3.1} [Minecraft Comes Alive] (MCA-1.12.x-5.3.1-universal.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (Mouse-Tweaks-Mod-1.12.1.jar) 
	UCHIJAAAA	cfm{4.1.5} [MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.12.1.jar) 
	UCHIJAAAA	schematica{1.8.0.164} [Schematica] (Schematica-Mod-1.12.1.jar) 
	UCHIJAAAA	lostcities{0.0.20beta2} [The Lost Cities] (The-Lost-Cities-Mod-1.12.1.jar) 
	UCHIJAAAA	torohealthmod{1.12.1-11} [ToroHealth Damage Indicators] (ToroCrafts-Damage-Indicators-Mod-1.12.1.jar) 
	UCHIJAAAA	treechopper{1.2.2} [Tree Chopper] (Tree-Chopper-Mod-1.12.1.jar) 
	UCHIJAAAA	worldedit{6.1.8} [WorldEdit] (WorldEdit-1.12.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Ginger60'/208, l='Tabitha 1_12_2', x=-598.94, y=99.00, z=-828.31]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.1_HD_U_C5
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13401 Compatibility Profile Context 15.201.1301.0
	OpenGlRenderer: AMD Radeon(TM) R7 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by WildBamaBoy** [comment]
#917

**Comment by maxanier** [comment]
I do not have this issue myself, just want to note this is most likely not a duplicate of issue 917.
917 affects Forge 2538+ while this report uses Forge 2447.

Also the issue itself is slightly different. 
In 917 the villagers don't appear at all on client side  (except sounds which are different packets), because the EntitySpawnPacket is not correctly parsed


However, this issue describes villagers being present on client side (nametags and shadows render), but invisible.

**Comment by Bloom7777** [comment]
I have the exact same issue, and I am using forge 2562. At first the villagers weren't displayed at all (except the shadow and nametag) however now they have the balck & pink glitch but are still not displaying skins.
Edit: Downloaded a different version of forge, issue still occurs.
