### ISSUE TITLE
Villagers baby glitch

### ISSUE THREAD

**Issue by iucjeil** [WildBamaBoy/minecraft-comes-alive#886]
Okay I Love mca and I play ot all the time, I have started playing on V.12.1. I have build My own village and realised you Can make villager Marry each other and make babies but the mothers have hold the babies for 2 hours now, is IT a glitch and Can you fix IT?

**Comment by WildBamaBoy** [comment]
Try the command `/mca fsp` while near that villager and see if that resolves your issue. Try it multiple times if not.
