### ISSUE TITLE
cant marry

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#887]
i cant marry with my friend. we created a new world on LAN, then right click and click ask to marry but it says "x is already married" forever.
_using forge 14.22.1.2485, minecraft 1.12.1 and MCA 5.3.1_

please help it :( thanks.
you can reach my modpack [here](https://github.com/kenijey/Ezteria) if you need...

**Comment by WildBamaBoy** [comment]
If this wasn't a new world, it might be carried over from a previous version. Use the command `/mca rm username` replacing `username` with their username and their marriage status will be reset.

**Comment by ghost** [comment]
No it was, we created a new world.
I will try that today.

**Comment by WildBamaBoy** [comment]
#902
