### ISSUE TITLE
1.12.2 Server Crash (Attempted to set villager profession to unregistered profession)

### ISSUE THREAD

**Issue by Endmateria** [WildBamaBoy/minecraft-comes-alive#888]
I don't know how helpful this crash report is, given the amount of mods I have installed, but I wanted to post it anyways, in case it's something straightforward and obvious.  It occurred while I was flying around exploring a new world in creative.  I flew around for about 30 minutes, over 6 or 7 villages with no problems, and crashed when I flew over the 8th one or so. 

MC 1.12.2
Forge 14.23.0.2493
RadixCore-1.12.x-2.2.1
MCA-1.12.x-5.3.1

https://gist.github.com/Endmateria/5b3d23b220a300ac39ea46731c8db50a#file-crash-2017-09-27_04-57-30-server-txt

**Comment by SDPhantom** [comment]
I noticed the same in my test world. I had already been in the village for a while and it randomly crashed while I was browsing the creative inventory. Same error and stack trace. From the log, it seems to be related to the spawning of Zombie Villagers.

**Comment by Orbaku** [comment]
Any luck with this? I'm having the same error.

Edit: I managed to find a work around. Don't know if you're still having problems or nit, but I'll leave it here in case anyone else has the same problem and comes looking.
I used NBTExplorer to edit some stuff in the level.dat file. Basically, there was no tag for villager profession with, in the case of your particular crash, tag 17.

"Attempted to set villager profession to unregistered profession: 17 null"

I went to level.dat/Registries/minecraft:villagerprofessions/ids and a tag in that section via the Add Compound Tag button in NBTExplorer. In this tag I added an integer variable with the name "V" and a value of 17. Then I added a string variable with name "K" and a value of nitwit. In this value you can change it to any other villager profession that already exists, not just nitwit. I'm unsure if it will cause any other problems (spawning too many of a certain kind of villager) but it's been running for a few hours now with no other crashes, so hopefully it fixed the problem.

**Comment by CucoML17** [comment]
Hi, I had the same problem, I used the NBTExplorer to solve it, following the steps of Orbaku, but a new problem arose, which is the following ... (I try the same of Orbaku, but I change the value of the whole variable (int) from 17 to 5, but ... can not have 2 values ​​with the same name (minecraft: nitwit) or is 17 or 5, I do not know if I explained well).

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  wings (wings-1.1.0-1.12.2.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 1/2/19 6:04 PM
Description: Ticking entity

java.lang.RuntimeException: Attempted to set villager profession to unregistered profession: 5 null
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:346)
	at net.minecraft.entity.monster.EntityZombieVillager.func_184206_a(EntityZombieVillager.java:319)
	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(EntityDataManager.java:167)
	at net.minecraft.entity.monster.EntityZombieVillager.func_190733_a(EntityZombieVillager.java:55)
	at net.minecraft.entity.monster.EntityZombieVillager.func_180482_a(EntityZombieVillager.java:104)
	at net.minecraft.entity.monster.EntityZombie.func_70074_a(EntityZombie.java:408)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1174)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:536)
	at mca.entity.EntityVillagerMCA.func_70645_a(EntityVillagerMCA.java:262)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1016)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:294)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAIZombieAttack.func_75246_d(SourceFile:28)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.registry.VillagerRegistry.onSetProfession(VillagerRegistry.java:346)
	at net.minecraft.entity.monster.EntityZombieVillager.func_184206_a(EntityZombieVillager.java:319)
	at net.minecraft.network.datasync.EntityDataManager.func_187227_b(EntityDataManager.java:167)
	at net.minecraft.entity.monster.EntityZombieVillager.func_190733_a(EntityZombieVillager.java:55)
	at net.minecraft.entity.monster.EntityZombieVillager.func_180482_a(EntityZombieVillager.java:104)
	at net.minecraft.entity.monster.EntityZombie.func_70074_a(EntityZombie.java:408)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1174)
	at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:536)
	at mca.entity.EntityVillagerMCA.func_70645_a(EntityVillagerMCA.java:262)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1016)
	at net.minecraft.entity.monster.EntityMob.func_70652_k(EntityMob.java:99)
	at net.minecraft.entity.monster.EntityZombie.func_70652_k(EntityZombie.java:294)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)
	at net.minecraft.entity.ai.EntityAIAttackMelee.func_75246_d(EntityAIAttackMelee.java:167)
	at net.minecraft.entity.ai.EntityAIZombieAttack.func_75246_d(SourceFile:28)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:223)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.EntityZombie)
	Entity ID: 606
	Entity Name: Zombi
	Entity's Exact location: -23.78, 4.00, -584.53
	Entity's Block location: World: (-24,4,-585), Chunk: (at 8,0,7 in -2,-37; contains blocks -32,0,-592 to -17,255,-577), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: -0.04, -0.08, 0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Mundo nuevodfghjk
	All players: 1 total; [EntityPlayerMP['carlosml17'/178, l='Mundo nuevodfghjk', x=-25.40, y=6.12, z=-588.24]]
	Chunk stats: ServerChunkCache: 351 Drop: 0
	Level seed: 8603204785425370798
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-81,4,-605), Chunk: (at 15,0,3 in -6,-38; contains blocks -96,0,-608 to -81,255,-593), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 8175 game time, 2211 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 9318 (now: false), thunder time: 159075 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 558686288 bytes (532 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 61 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version                  | Source                                          | Signature                                |
	|:--------- |:----------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp               | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | uncraftingtable   | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar             | None                                     |
	| UCHIJAAAA | baubles           | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | bibliotheca       | 1.2.2-1.12.2             | bibliotheca-1.2.2-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | bookshelf         | 2.3.567                  | Bookshelf-1.12.2-2.3.567.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | chesttransporter  | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar               | None                                     |
	| UCHIJAAAA | codechickenlib    | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks     | 2.4.0.70                 | ChickenChunks-1.12-2.4.0.70-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | craftelytra       | 1.2                      | CraftableElytra-1.1.jar                         | None                                     |
	| UCHIJAAAA | craftstudioapi    | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCHIJAAAA | customnpcs        | 1.12                     | CustomNPCs_1.12.2(26aug18).jar                  | None                                     |
	| UCHIJAAAA | cyclopscore       | 0.11.10                  | CyclopsCore-1.12.2-0.11.10.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | dmonsters         | 1.7                      | Deadly+Monsters+1.71.jar                        | None                                     |
	| UCHIJAAAA | dungeonmobs       | 5.4.4                    | dungeonmobs-5.4.4-MC1.12.2.jar                  | None                                     |
	| UCHIJAAAA | durabilityviewer  | 1.4                      | DurabilityViewer-1.12-forge14.21.1.2387-1.4.jar | None                                     |
	| UCHIJAAAA | eplus             | 5.0.174                  | EnchantingPlus-1.12.2-5.0.174.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | evilcraft         | 0.10.64                  | EvilCraft-1.12.2-0.10.64.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | evilcraftcompat   | 1.0.0                    | EvilCraft-1.12.2-0.10.64.jar                    | None                                     |
	| UCHIJAAAA | golems            | 7.0.0-beta1              | ExtraGolems-1.12-7.0.0-beta1.4.jar              | None                                     |
	| UCHIJAAAA | gravestone        | 1.3.1                    | GraveStone-1.12.2-Graves-1.3.1.jar              | None                                     |
	| UCHIJAAAA | overlord          | 2.4.14                   | Overlord-1.12.2-2.4.14.jar                      | None                                     |
	| UCHIJAAAA | guideapi          | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                     | None                                     |
	| UCHIJAAAA | waila             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UCHIJAAAA | llibrary          | 1.7.15                   | llibrary-1.7.15-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | iceandfire        | 1.5.2                    | iceandfire-1.5.2.jar                            | None                                     |
	| UCHIJAAAA | infernalmobs      | 1.7.5                    | InfernalMobs-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | inventorytweaks   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironfurnaces      | 1.3.1                    | ironfurnaces-1.3.1.jar                          | None                                     |
	| UCHIJAAAA | jei               | 4.13.1.222               | jei_1.12.2-4.13.1.222.jar                       | None                                     |
	| UCHIJAAAA | journeymap        | 1.12.2-5.5.3             | journeymap-1.12.2-5.5.3.jar                     | None                                     |
	| UCHIJAAAA | justenoughbuttons | 1.12-1.2.1               | justenoughbuttons-1.12-1.2.1.jar                | None                                     |
	| UCHIJAAAA | mantle            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
	| UCHIJAAAA | radixcore         | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar            | None                                     |
	| UCHIJAAAA | mca               | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar                  | None                                     |
	| UCHIJAAAA | mobultion         | 0.4.4                    | mobultion-0.4.4.jar                             | 4fe096bf3ddb2da90a69bb82abd57398549af8a5 |
	| UCHIJAAAA | monsterswarm      | 2.0.1                    | MonsterSwarm-2.0.1.jar                          | None                                     |
	| UCHIJAAAA | mowziesmobs       | 1.4.2                    | mowziesmobs-1.4.2.jar                           | None                                     |
	| UCHIJAAAA | naturescompass    | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| UCHIJAAAA | roughmobs         | 2.0.0                    | roughmobs2-1.12.2_2.0.11.jar                    | None                                     |
	| UCHIJAAAA | silentlib         | 3.0.6                    | SilentLib-1.12.2-3.0.6-154.jar                  | None                                     |
	| UCHIJAAAA | simplehammers     | 2.0.0.2                  | simplehammers-1.12.2-2.0.0.2.jar                | 84b613cbdd3fb8075853522fdca046fd476ccd01 |
	| UCHIJAAAA | soulshardstow     | 1.12-2.7.6-56            | SoulShards-TOW-1.12-2.7.6-56.jar                | None                                     |
	| UCHIJAAAA | twilightforest    | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar     | None                                     |
	| UCHIJAAAA | tconstruct        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
	| UCHIJAAAA | tombstone         | 3.3.0                    | tombstone-3.3.0-1.12.jar                        | None                                     |
	| UCHIJAAAA | torohealthmod     | 1.12.2-11                | torohealth-1.12.2-11.jar                        | None                                     |
	| UCHIJAAAA | toroquest         | 1.12.2-5.2               | toroquest-1.12.2-5.2.jar                        | None                                     |
	| UCHIJAAAA | treechopper       | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
	| UCHIJAAAA | uteamcore         | 2.0.2.84                 | u_team_core-1.12.2-2.0.2.84.jar                 | None                                     |
	| UCHIJAAAA | usefulbackpacks   | 1.3.1.12                 | useful_backpacks-1.12.2-1.3.1.12.jar            | None                                     |
	| UCHIJAAAA | vampirism         | 1.4.7                    | Vampirism-1.12.2-1.4.7.jar                      | None                                     |
	| UCHIJAAAA | teamlapen-lib     | 1.4.7                    | Vampirism-1.12.2-1.4.7.jar                      | None                                     |
	| UCHIJAAAA | vanillafoodpantry | 4.2.0                    | vanillafoodpantry-mc1.12.1-4.2.jar              | None                                     |
	| UCHIJAAAA | wings             | 1.1.0                    | wings-1.1.0-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | bauble_wings      | 1.0.0                    | wings-1.1.0-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | worldedit         | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar           | None                                     |
	| UCHIJAAAA | xpbook            | 0.0.3-beta               | xpbook-1.12-0.0.3-beta.jar                      | None                                     |
	| UD        | mobends_wings     | 1.0.0                    | wings-1.1.0-1.12.2.jar                          | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
wings (wings-1.1.0-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['carlosml17'/178, l='Mundo nuevodfghjk', x=-25.40, y=6.12, z=-588.24]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
	OpenGlRenderer: AMD Radeon HD 6520G
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by ScathaIsTheBest101** [comment]
The game crashed whilst exception ticking world
Error: java.lang.RuntimeException: Attempted to set villager profession to unregistered profession: 5 null

Need Help!
