### ISSUE TITLE
I cant marry people

### ISSUE THREAD

**Issue by GoldenHusky** [WildBamaBoy/minecraft-comes-alive#892]
i tried to marry someone we had 5 full gold stars {single player game} but they told me that i was already married???? im confused please help me. I tried to do /mca rm and then did my username but it says i need a valid argument????/

**Comment by VictorFowler** [comment]
Find a cleric and under special chose to get divorced from current spouse.

**Comment by WildBamaBoy** [comment]
Please provide the version of MCA that you are using.

**Comment by PotatoComesAlive** [comment]
I have the exact same problem and im using the latest version 
**MCA-1.12.x-5.3.1**
I always have to find a cleric and get divorced from my spouse who btw does **NOT** exist.

**Comment by thakyZ** [comment]
I can confirm that is happens, there however is a way around it, and that is to use a wedding ring

**Comment by WildBamaBoy** [comment]
#902
