### ISSUE TITLE
Feature Suggestion: Ways to improve talking and interaction chances

### ISSUE THREAD

**Issue by Darkmega18** [WildBamaBoy/minecraft-comes-alive#894]
I was hoping this would be a thing by now this far along. but unfortunately not. I always find it annoying that a lot of interactions are generally unsafe and I get the most rotten luck due to RNG reasons when interacting which force me to twist their likes with presents which I kinda don't like doing cause it makes me feel like I'm buying everyone off.

So I was thinking about it and though I'd suggest ways to make the chatting options more effective.

1. Enchantment for helmet. Speechcraft 1-5. When using this enchantment on a helmet the game picks up on it and gives a 5-25% bonus luck chance to standard chatting interactions, like chat, story, flirt etc.

2. Enchantment for Chestplate: Smooth moves 1-5. Improves chances by 5-15% when using action based interactions unless they're already 0%. So hand shakes, hugs, kisses.

3. Potions. Potion effects from certain items with various durations. Such as speech and smooth moves in potion form that give 10% per level of the potion. and possibly certain potions you can use as splash potions to influence villagers for a little while to have better chances with certain interactions.

4. Artifacts found in chests that could be held in the hotbar that give these effects either indefinitely or strong versions that give them a set amount of times in some way or form from being on the hotbar or used.

Yeah... :)

**Comment by WildBamaBoy** [comment]
I like it 👍
