### ISSUE TITLE
Can't interact with Humans in LAN

### ISSUE THREAD

**Issue by VictorFowler** [WildBamaBoy/minecraft-comes-alive#895]
Hey, Started playing the mod recently on 1.12.2 and it's only mostly working. The two human players on a LAN world started as married, so we couldn't marry each other. When we finally found a cleric to divorce us from people who didn't exist, it wouldn't let us right click on each other to interact anymore. We can still interact with other NPC's but we cant marry or even see each others marital status. It let us at the beginning but now no dice! Started up a new world and we still cant interact with each other. We have both used orbs and can talk to NPC's but that's it.

**Comment by WildBamaBoy** [comment]
Please provide the version of MCA that you are using.
