### ISSUE TITLE
My spouse is moving when they are sleeping.

### ISSUE THREAD

**Issue by Nixxietail** [WildBamaBoy/minecraft-comes-alive#896]
I married a guard and they go to bed like normal, but they immediately start moving around the room while laying down. I have all the updates because I got this a day ago, is there any way to remedy this?

**Comment by WildBamaBoy** [comment]
MCA version? Minecraft version?

**Comment by Nixxietail** [comment]
5.3.1 on 1.12.2

**Comment by Galindorf** [comment]
I can add to this: All married guards will go to bed at night (or if you set a "home point" for them) and then go sleepwalking. I usually talk to them to wake them up so they'll get around to doing their job... defending the village!

**Comment by SDPhantom** [comment]
I'm digging through the AI code to see what I can do. I already tracked down a similar issue where the villagers would often turn to face the player while sleeping in a bed.

I'm by no means well versed in Java, but I know enough about different programming languages to follow. If I come up with a fix, I'll post a PR onto master.

**Comment by SDPhantom** [comment]
I did a small PR that should resolve this issue.
#913

**Comment by Nixxietail** [comment]
Thank you so much
