### ISSUE TITLE
can't marry :(

### ISSUE THREAD

**Issue by Fifiax** [WildBamaBoy/minecraft-comes-alive#898]
I can't marry villagers when I reach 5 gold stars with them because it says I'm already married? I am running a fairly new world and have not attempted to marry anyone in the past. I am running MCA version 1.12x-5.3.1, Forge 12.1, and I am playing in a single player server.
I've read a previous forum with this same issue and someone suggested to find a cleric? I can't seem to find one anywhere and there are about 4 villages near me? Is there a specific way to find/spawn one or?
Thank you! :D

**Comment by Lynx924** [comment]
If you have access to creative mode you can spawn one in using the male/female villager eggs and then edit their professions with the villager editor book. If you dont have access to creative mode you would probably have to wait for one to spawn or feed married villagers cake so they can procreate.

**Comment by WildBamaBoy** [comment]
#902
