### ISSUE TITLE
No Human Interaction

### ISSUE THREAD

**Issue by ChickenBr0** [WildBamaBoy/minecraft-comes-alive#899]
So I got off the world for about 20  seconds (literally) and I come back on and I go to one of my children. when I right click, it usually brings us the menu of Interaction, pick-up, etc. This time, when I got back on, I could only use the interact function which isn't what I needed at that time.
I was using MC 1.7.10. This is also in a LAN world with one of my friends.

So now, when I had another child, all the functions which I previously couldn't use on the other child, I can on this one but not the other. So now I have one child I can interact with and one I can't.

I can also interact with every other villager except the ones in my family. My friend can't interact with the child I can interact with but he can with every other child I have.

**Comment by WildBamaBoy** [comment]
1.7.10 is no longer supported.
