### ISSUE TITLE
Cant set new home point

### ISSUE THREAD

**Issue by SophiaThePanda** [WildBamaBoy/minecraft-comes-alive#900]
So I adopted children from the village Cleric and they grew up,got married and has babies of their own.
I built a house near the village for them and their wives BUT when I tried to set their new room as a home point they keep coming back to their old rooms in my house. 

What do?

**Comment by SophiaThePanda** [comment]
@ko2fan @WildBamaBoy @mraof @hanetzer @bloodmc 
Sorry to spam tag you but I know you probably wont see if I dont tag. Ive had this problem in two separate worlds and dont know what to do and no matter how much I google I cant find an answer

**Comment by WildBamaBoy** [comment]
Don't do that. 
Provide your MCA version, RadixCore version, Forge version.

**Comment by SophiaThePanda** [comment]
I have MCA version 1.7.10-2.1.3, RadixCore 1.7.10-2.1.3, and Forge 10.13.4.1558 (Forge Mod Loader 7.10.99.99)

P.S Sorry might be tmi but I wasnt sure as it gave me two different forge codes

**Comment by WildBamaBoy** [comment]
Unfortunately 1.7.10 is no longer supported. You'll have to upgrade to 1.12.2 and attempt to reproduce the issue.
