### ISSUE TITLE
Can't Marry In Multiplayer World

### ISSUE THREAD

**Issue by ChickenBr0** [WildBamaBoy/minecraft-comes-alive#901]
My friend and I are trying to marry in a lan world we share. This is a brand new world with MCA 1.7.10

It says my friend is married to my wife and I am not married. Even though I married the wife that the game says he is married to.

**Comment by WildBamaBoy** [comment]
Unfortunately MCA 1.7.10 is no longer supported. You can use the command `/mca rm username` replacing `username` with your username to reset your marriage.
