### ISSUE TITLE
Minecraft Comes Alive Marriage Issue

### ISSUE THREAD

**Issue by DeterminedFoxGamer1987** [WildBamaBoy/minecraft-comes-alive#902]
I just got this mod yesterday and I'm trying to get married to someone, but everytime I try to get engaged, he tells me I'm already married though I'm not?

**Comment by C0rn3j** [comment]
Forge 2515(started up on 2512), MCA-1.12.x-5.3.1-universal.jar, MC 1.12.2

Everyone on our server is already married to "?.".  The server is in offline mode.

@DeterminedFoxGamer1987 I'd probably rename the issue to "All players are married to ?" or similar

**Comment by DeterminedFoxGamer1987** [comment]
@C0rn3j I was playing in single player mode and I just started the mod up. When I proposed to one of the villagers, they'd say something along the lines of "just what do you think you're doing? I see a ring on that finger."

**Comment by PurpleHel** [comment]
Same problem on a server, on 1.12.1 and 1.12.2. The workaround we discovered is to use the crystal ball (cheat a new one in if needed), say 'I have a family', and then divorce that spouse. Be carefu where tho, cos it'll create a house, so either be someplace you want a house, or be someplace you can easily destroy the house after.

**Comment by Galindorf** [comment]
some more info: 

I am using forge 2491 and getting the same error. I started off with the "I have a family" option, already married with 2 children. Sadly my spouse was killed by a Manticore. My partner decided to play with me on a LAN server, so I figured we'd get married and go from there. Interestingly, I used a Cleric to divorce me and my partner playing on the same LAN server so we could marry each other, which worked. However, a few sessions later, I was going to ask my (human) partner on the LAN server to have a baby, but we were no longer married, and again married to other 'mystery' people. (Shows as " Married to ?" ) when you look. 

To verify, just now I reopened my world, got a single villager to 5 gold hearts, tried to gift them an engagement ring, they informed me I was already married. My partner logged into the server, it showed him and I as "Married to ?". We both got ourselves divorced from our mystery spouses, and re-married each other. 

Current mod list and versions:

forge1.12.2-14.23.0.2495

BetterFoliage-MC1.12-2.1.10
BiomesOPlenty-1.12.2-7.0.1.2298-universal.jar
chococraft_1.12.1-0.9.1.52.jar
CustomMobSpawner-3.11.3.jar
DrZharks MoCreatures Mod-12.0.3.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
journeymap-1.12-5.4.9.jar
JustAFewFish-1.7_for_1.12.jar
Mantle-1.12-1.3.1.21.jar
MCA-1.12.x-5.3.1-universal.jar
Natura-1.12-4.3.0.17.jar
PetBat-1.12.jar
RadixCore-1.12.x-2.2.1-universal.jar
SoundFilters-0.10_for_1.12.jar
TreeChopper-1.12.1-1.2.2.jar

**Comment by TabithaBlue** [comment]
Just spawn or find a priest and push the special button and their should be a button to get rid of any marriages you have. I tried it and it works 100%

**Comment by tigres810** [comment]
For us it fixed by typping this on the server: /mca rm (username) Hopefully it works for you guys 👍

**Comment by Charismara** [comment]
On a Server restart all Players are married to ? again. Is there a way to fix this?

**Comment by MentalMouse** [comment]
The bug recycles on a restart (including SSP save and load).  You'll need divorces (or commands) all around again.

**Comment by Charismara** [comment]
Will this mod be further developed?

**Comment by Paladyner** [comment]
i got the same problem as above shown but when i cheated the Crystal ball and chose "i have a family",it spawned in a normal wife and 2 NO-TEXTURE child then crash my game :) i know already that my laptop is weak as ballz like my FPS is always at about 10-15 (jump to 100 when put render distance to lowest) but those 2 no texture child just drop it down to 1 :/ i've tried to change texture for them but no use,as soon as i right click the villager editor on them the game just simply say "F off" :V

**Comment by PurpleHel** [comment]
Update to the new version of the mod. The dev isn't supporting the old version anymore. If you're using 6.0.0 or newer and having this problem, you'll have to make a new issue.
