### ISSUE TITLE
Crash On Loading Village

### ISSUE THREAD

**Issue by BuilderDan** [WildBamaBoy/minecraft-comes-alive#903]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SoundFixPatchingLoader (AmbientSounds v2.1.0 mc1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.7.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.b128.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1 (1).jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  LoadingPlugin (Quark-r1.3-111.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12-1.9 (1).jar)
  ComfortsLoadingPlugin (comforts-1.12.2-0.0.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2 (1).jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 10/25/17 8:37 AM
Description: Unexpected error

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at mca.entity.VillagerAttributes.getProfessionEnum(VillagerAttributes.java:215)
	at mca.entity.EntityVillagerMCA.func_184586_b(EntityVillagerMCA.java:678)
	at mca.entity.EntityVillagerMCA.func_184582_a(EntityVillagerMCA.java:800)
	at net.minecraft.entity.EntityLivingBase.func_184614_ca(EntityLivingBase.java:1607)
	at DynamicLights.getLightLevel(DynamicLights.java:336)
	at DynamicLights.updateMapDynamicLights(DynamicLights.java:121)
	at DynamicLights.update(DynamicLights.java:95)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1170)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1716)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mca.entity.VillagerAttributes.getProfessionEnum(VillagerAttributes.java:215)
	at mca.entity.EntityVillagerMCA.func_184586_b(EntityVillagerMCA.java:678)
	at mca.entity.EntityVillagerMCA.func_184582_a(EntityVillagerMCA.java:800)
	at net.minecraft.entity.EntityLivingBase.func_184614_ca(EntityLivingBase.java:1607)
	at DynamicLights.getLightLevel(DynamicLights.java:336)
	at DynamicLights.updateMapDynamicLights(DynamicLights.java:121)
	at DynamicLights.update(DynamicLights.java:95)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1170)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1716)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['BuilderDan1'/2503, l='MpServer', x=199.05, y=83.32, z=621.52]]
	Chunk stats: MultiplayerChunkCache: 371, 371
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (244,64,156), Chunk: (at 4,4,12 in 15,9; contains blocks 240,0,144 to 255,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10672 game time, 10672 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 140 total; [EntityMinecartChest['Minecart with Chest'/30756, l='MpServer', x=182.50, y=17.06, z=609.50], EntityItem['item.tile.mushroom'/30782, l='MpServer', x=151.49, y=24.00, z=593.29], EntityMinecartChest['Minecart with Chest'/30783, l='MpServer', x=225.50, y=10.06, z=614.50], EntityItem['item.tile.torch'/30784, l='MpServer', x=224.99, y=11.00, z=607.81], EntityEweFriesian['Friesian Ewe'/30786, l='MpServer', x=231.50, y=70.00, z=601.50], EntityConcussionCreeper['Concussion Creeper'/32840, l='MpServer', x=262.50, y=22.00, z=622.50], EntityHenLeghorn['Leghorn Hen'/30792, l='MpServer', x=259.82, y=79.00, z=601.53], EntityHenLeghorn['Leghorn Hen'/30795, l='MpServer', x=263.50, y=75.00, z=614.50], EntityPlayerSP['BuilderDan1'/2503, l='MpServer', x=199.05, y=83.32, z=621.52], EntityHallowitch['Hallowitch'/31861, l='MpServer', x=212.50, y=15.00, z=623.50], EntityHallowitch['Hallowitch'/31862, l='MpServer', x=212.50, y=15.00, z=626.50], EntityCreeperween['Creeperween'/32894, l='MpServer', x=223.50, y=30.00, z=585.50], EntitySowYorkshire['American Yorkshire Sow'/30854, l='MpServer', x=244.98, y=69.00, z=587.84], EntityItem['item.tile.torch'/30856, l='MpServer', x=251.41, y=5.00, z=597.09], EntityHallowitch['Hallowitch'/32917, l='MpServer', x=215.50, y=15.00, z=637.50], EntityFallenKnight['Fallen Knight'/32925, l='MpServer', x=233.50, y=9.00, z=602.50], EntityFallenKnight['Fallen Knight'/32926, l='MpServer', x=233.50, y=9.00, z=603.50], EntityVillagerMCA['Steve'/30888, l='MpServer', x=173.50, y=65.00, z=575.50], EntityVillagerMCA['Steve'/30889, l='MpServer', x=174.50, y=65.00, z=575.50], EntityZombie['Zombie'/31916, l='MpServer', x=224.19, y=48.00, z=652.01], EntityHallowitch['Hallowitch'/32951, l='MpServer', x=223.50, y=11.00, z=640.50], EntityHallowitch['Hallowitch'/32952, l='MpServer', x=225.50, y=11.00, z=640.50], EntitySkeleton['Skeleton'/31944, l='MpServer', x=198.50, y=22.00, z=632.50], EntityBabyWitch['Baby Witch'/32971, l='MpServer', x=184.50, y=20.00, z=636.50], EntityBabyOcelot['Cat'/32972, l='MpServer', x=184.50, y=20.00, z=636.50], EntityFishCod['Cod'/32973, l='MpServer', x=189.50, y=62.00, z=598.50], EntityFishCod['Cod'/32974, l='MpServer', x=188.94, y=62.00, z=599.61], EntityFishCod['Cod'/32975, l='MpServer', x=185.79, y=58.76, z=600.50], EntityFishCod['Cod'/32976, l='MpServer', x=185.47, y=60.80, z=605.24], EntityFishCod['Cod'/30929, l='MpServer', x=162.70, y=62.00, z=630.24], EntityCreeper['Creeper'/32979, l='MpServer', x=215.50, y=19.00, z=579.50], EntityCreeperween['Creeperween'/33009, l='MpServer', x=247.50, y=27.00, z=605.50], EntityConcussionCreeper['Concussion Creeper'/33014, l='MpServer', x=234.50, y=50.00, z=602.50], EntityConcussionCreeper['Concussion Creeper'/33015, l='MpServer', x=234.50, y=50.00, z=600.50], EntityFishCod['Cod'/30971, l='MpServer', x=201.27, y=23.20, z=682.68], EntityFishCod['Cod'/30973, l='MpServer', x=199.50, y=22.00, z=683.50], EntityConcussionCreeper['Concussion Creeper'/31997, l='MpServer', x=216.50, y=15.00, z=661.50], EntityConcussionCreeper['Concussion Creeper'/31998, l='MpServer', x=216.50, y=15.00, z=661.50], EntityConcussionCreeper['Concussion Creeper'/32000, l='MpServer', x=220.50, y=15.00, z=665.50], EntityCreeperween['Creeperween'/33053, l='MpServer', x=209.72, y=10.00, z=644.48], EntityEweFriesian['Friesian Ewe'/31016, l='MpServer', x=261.53, y=69.00, z=572.78], EntityEweFriesian['Friesian Ewe'/31020, l='MpServer', x=266.50, y=66.00, z=575.50], EntityBullFriesian['Friesian Bull'/31023, l='MpServer', x=266.50, y=66.00, z=580.50], EntityBabySkeleton['Baby Skeleton'/31029, l='MpServer', x=142.50, y=19.00, z=651.50], EntityCreeper['Creeper'/32068, l='MpServer', x=197.50, y=19.00, z=613.50], EntityZombieHands['ZombieHands'/32102, l='MpServer', x=217.50, y=13.00, z=653.50], EntityLambFriesian['Friesian Lamb'/30063, l='MpServer', x=205.57, y=75.00, z=688.65], EntityOwl['Owl'/30068, l='MpServer', x=196.46, y=77.00, z=680.33], EntityItem['item.tile.torch'/30082, l='MpServer', x=225.52, y=21.00, z=685.13], EntityItem['item.tile.torch'/30083, l='MpServer', x=219.13, y=16.00, z=681.41], EntityItem['item.tile.torch'/30084, l='MpServer', x=194.41, y=16.00, z=657.95], EntityItem['item.tile.torch'/30093, l='MpServer', x=206.13, y=19.00, z=661.42], EntityItem['item.tile.torch'/30094, l='MpServer', x=201.13, y=19.00, z=660.10], EntityCreeper['Creeper'/32163, l='MpServer', x=178.70, y=16.00, z=629.70], EntityFishCod['Cod'/33192, l='MpServer', x=221.07, y=58.00, z=592.83], EntitySkeleton['Skeleton'/33228, l='MpServer', x=238.50, y=9.00, z=640.50], EntitySkeleton['Skeleton'/33229, l='MpServer', x=239.50, y=9.00, z=640.50], EntityItem['item.tile.torch'/30177, l='MpServer', x=181.53, y=16.00, z=637.41], EntityItem['item.tile.torch'/30178, l='MpServer', x=180.82, y=16.00, z=632.87], EntitySquid['Squid'/32245, l='MpServer', x=209.57, y=57.00, z=597.40], EntitySquid['Squid'/32247, l='MpServer', x=205.12, y=57.02, z=602.68], EntitySquid['Squid'/32248, l='MpServer', x=208.10, y=60.94, z=604.25], EntityBabyZombie['Baby Zombie'/32249, l='MpServer', x=225.78, y=49.45, z=652.11], EntityZombieChicken['Zombie Chicken'/32250, l='MpServer', x=225.74, y=49.00, z=652.20], EntityBabySquid['Baby Squid'/32251, l='MpServer', x=208.35, y=57.65, z=603.05], EntityZombie['Zombie'/32263, l='MpServer', x=208.50, y=15.00, z=636.50], EntityFishCod['Cod'/31253, l='MpServer', x=160.18, y=62.00, z=634.50], EntityFishCod['Cod'/31254, l='MpServer', x=161.54, y=62.00, z=637.81], EntityFishCod['Cod'/31255, l='MpServer', x=164.10, y=62.00, z=638.67], EntityFishCod['Cod'/31256, l='MpServer', x=161.78, y=62.00, z=633.78], EntityHallowitch['Hallowitch'/33306, l='MpServer', x=180.50, y=16.00, z=633.50], EntityHallowitch['Hallowitch'/33307, l='MpServer', x=182.50, y=16.00, z=633.50], EntityHallowitch['Hallowitch'/33308, l='MpServer', x=179.50, y=16.00, z=632.50], EntityHallowitch['Hallowitch'/33309, l='MpServer', x=184.50, y=16.00, z=637.50], EntityBat['Bat'/32289, l='MpServer', x=159.86, y=53.00, z=587.36], EntityBat['Bat'/32290, l='MpServer', x=165.48, y=52.76, z=595.20], EntityBat['Bat'/32291, l='MpServer', x=150.16, y=52.57, z=597.23], EntityCreeper['Creeper'/32331, l='MpServer', x=177.50, y=16.00, z=652.50], EntityFishSalmon['Salmon'/33362, l='MpServer', x=182.50, y=60.80, z=601.21], EntityFishSalmon['Salmon'/33363, l='MpServer', x=184.30, y=59.81, z=602.84], EntityFishSalmon['Salmon'/33364, l='MpServer', x=186.50, y=62.00, z=604.50], EntityFishSalmon['Salmon'/33365, l='MpServer', x=182.10, y=60.80, z=609.30], EntityItem['item.tile.torch'/30297, l='MpServer', x=207.09, y=11.00, z=642.87], EntityItem['item.tile.flower_1.miners_delight'/30329, l='MpServer', x=215.27, y=13.00, z=650.13], EntityItem['item.item.string'/30338, l='MpServer', x=229.80, y=19.00, z=650.08], EntityItem['item.item.string'/30339, l='MpServer', x=229.13, y=19.00, z=651.83], EntityCreeperween['Creeperween'/31364, l='MpServer', x=183.50, y=12.00, z=643.50], EntityHat['unknown'/646, l='MpServer', x=199.05, y=83.32, z=621.52], EntityItem['item.item.string'/30342, l='MpServer', x=229.77, y=19.00, z=652.88], EntityLatchedRenderer['unknown'/647, l='MpServer', x=199.05, y=83.32, z=621.52], EntityCreeper['Creeper'/33419, l='MpServer', x=140.50, y=19.00, z=638.50], EntityHat['unknown'/5773, l='MpServer', x=220.50, y=15.00, z=665.50], EntityItem['item.tile.torch'/30352, l='MpServer', x=221.98, y=10.00, z=643.88], EntityItem['item.tile.torch'/30353, l='MpServer', x=225.57, y=15.00, z=643.88], EntityHogYorkshire['American Yorkshire Hog'/30355, l='MpServer', x=221.01, y=77.00, z=635.24], EntityHogYorkshire['American Yorkshire Hog'/30358, l='MpServer', x=236.16, y=76.00, z=639.91], EntityPigletYorkshire['American Yorkshire Piglet'/30360, l='MpServer', x=229.50, y=76.00, z=661.36], EntityBabyCreeper['Baby Creeper'/33433, l='MpServer', x=142.50, y=19.00, z=639.50], EntityItem['item.tile.torch'/30370, l='MpServer', x=207.57, y=15.00, z=620.58], EntityItem['item.tile.torch'/30371, l='MpServer', x=210.81, y=19.00, z=629.88], EntityItem['item.tile.torch'/30372, l='MpServer', x=246.55, y=19.00, z=639.04], EntityItem['item.tile.rail'/30373, l='MpServer', x=247.80, y=19.00, z=647.88], EntityItem['item.tile.rail'/30375, l='MpServer', x=244.75, y=19.00, z=647.88], EntityItem['item.tile.rail'/30376, l='MpServer', x=241.76, y=19.00, z=646.77], EntityHat['unknown'/5801, l='MpServer', x=177.50, y=16.00, z=652.50], EntitySkeleton['Skeleton'/32425, l='MpServer', x=204.30, y=15.00, z=697.74], EntityItem['item.tile.rail'/30378, l='MpServer', x=240.74, y=19.00, z=646.38], EntityItem['item.tile.rail'/30379, l='MpServer', x=242.13, y=10.00, z=639.78], EntityItem['item.tile.rail'/30382, l='MpServer', x=242.92, y=10.00, z=637.46], EntityBat['Bat'/33456, l='MpServer', x=165.50, y=54.82, z=595.46], EntityItem['item.tile.rail'/30385, l='MpServer', x=242.13, y=10.00, z=648.22], EntityItem['item.tile.rail'/30388, l='MpServer', x=242.74, y=10.00, z=649.00], EntityEweFriesian['Friesian Ewe'/30419, l='MpServer', x=258.45, y=78.00, z=663.30], EntityEweFriesian['Friesian Ewe'/30421, l='MpServer', x=256.81, y=78.00, z=665.22], EntityMinecartChest['Minecart with Chest'/30423, l='MpServer', x=227.50, y=5.06, z=622.50], EntityHat['unknown'/5869, l='MpServer', x=140.50, y=19.00, z=638.50], EntityItem['item.tile.torch'/30451, l='MpServer', x=244.12, y=6.00, z=621.88], EntityMinecartChest['Minecart with Chest'/30452, l='MpServer', x=241.50, y=6.06, z=622.50], EntityHat['unknown'/5877, l='MpServer', x=233.50, y=9.00, z=603.50], EntityHat['unknown'/5878, l='MpServer', x=225.75, y=34.00, z=587.95], EntityHat['unknown'/5879, l='MpServer', x=205.12, y=57.02, z=602.68], EntityHat['unknown'/5893, l='MpServer', x=266.50, y=66.00, z=580.50], EntityVillager['Villager'/31493, l='MpServer', x=168.50, y=65.00, z=556.50], EntityItemFrame['entity.ItemFrame.name'/31495, l='MpServer', x=183.50, y=67.50, z=562.97], EntityVillager['Villager'/31496, l='MpServer', x=183.50, y=65.00, z=566.50], EntityHat['unknown'/5898, l='MpServer', x=168.50, y=65.00, z=556.50], EntityBabyZombie['Baby Zombie'/33566, l='MpServer', x=176.50, y=16.45, z=627.40], EntityZombieChicken['Zombie Chicken'/33567, l='MpServer', x=176.50, y=16.00, z=627.50], EntityItem['item.tile.rail'/30500, l='MpServer', x=249.25, y=19.00, z=647.72], EntityBat['Bat'/32560, l='MpServer', x=268.24, y=17.71, z=650.19], EntityBat['Bat'/32561, l='MpServer', x=271.11, y=16.23, z=651.89], EntityBat['Bat'/32562, l='MpServer', x=268.35, y=16.23, z=650.79], EntityBat['Bat'/32563, l='MpServer', x=268.33, y=17.94, z=650.17], EntityZombie['Zombie'/32615, l='MpServer', x=257.50, y=39.00, z=659.50], EntityBat['Bat'/32665, l='MpServer', x=228.75, y=34.03, z=589.76], EntityBat['Bat'/32666, l='MpServer', x=225.75, y=34.00, z=587.95], EntityBat['Bat'/32667, l='MpServer', x=238.12, y=34.46, z=595.67], EntityItem['item.tile.rail'/30635, l='MpServer', x=253.26, y=19.00, z=646.53], EntityBabyEnderman['Baby Enderman'/32694, l='MpServer', x=187.50, y=9.00, z=604.50], EntityItem['item.tile.rail'/30673, l='MpServer', x=254.34, y=19.00, z=646.05]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by pauloelr** [comment]
Same here
