### ISSUE TITLE
Suggestion & Issue: Hire Villagers with Rose Gold

### ISSUE THREAD

**Issue by Galindorf** [WildBamaBoy/minecraft-comes-alive#905]
Title says it all! I'd like to use Rose Gold to be able to hire villagers for working. Also, if you try to give them rose gold ingots as a gift they hate it! Are blocks and rings the only thing that I can do with Rose Gold?

**Comment by WildBamaBoy** [comment]
This is intended - rose gold is only for crafting rings/blocks. You can always convert rose gold to regular gold though.

**Comment by Galindorf** [comment]
wait, you can convert rose gold to regular?? how?

**Comment by WildBamaBoy** [comment]
Rose Gold Ingot by itself in a crafting grid = Rose Gold Dust
Rose Gold Dust + Bucket of Water = 6 Gold Dust
9 Gold Dust in a full crafting grid = 1 gold nugget

And of course 9 gold nuggets = 1 gold ingot, a base Minecraft recipe
