### ISSUE TITLE
My Children are do-less

### ISSUE THREAD

**Issue by Galindorf** [WildBamaBoy/minecraft-comes-alive#906]
I started a new world with myself married to a guy, with no children. So, to populate the village, I started having children! However, none of my children had assigned 'jobs' after growing up; I can't hire them to do anything. (i.e. nothing appears under the 'special' menu). I had a whole bunch of kids, finally one of my grandchildren was born as a Cleric and I was able to use the Cleric commands with that one (after it grew up). 

Do I need to wait for grandchildren and great-grandchildren to have hire-able villagers, or is this a bug?

**Comment by WildBamaBoy** [comment]
Your children have abilities under the "Work" tab while interacting.

Grandchildren are regular villagers who can later be hired.

**Comment by Galindorf** [comment]
no I mean, there is nothing under the "work" tab after they grow up. I'll 
send screenshots later! I am unable to hire most of the people in my village.

**Comment by Galindorf** [comment]
So, the 'job title' designation and/or number of hearts of the villager does not seem to affect their hire-ability. All of the villagers are my own children, grandchildren, or generated guards. 

More info: In a nearby generated Minecraft Town, I was able to hire any of the people there, except the guards (I guess guards are not hire-able?)

Here are a couple of screen shots of my own grown child, unable to hire:

![screen shot 2017-11-16 at 1 05 36 pm](https://user-images.githubusercontent.com/17105217/32910550-2a7fce36-cacf-11e7-802d-9931b554d55d.png)
![screen shot 2017-11-16 at 1 05 28 pm](https://user-images.githubusercontent.com/17105217/32910551-2a962eb0-cacf-11e7-8740-a1b382a6e11f.png)

Screen Shots of a villager titled "Villager", unable to hire:
![screen shot 2017-11-16 at 1 10 30 pm](https://user-images.githubusercontent.com/17105217/32910919-2e3a7f02-cad0-11e7-9597-7ce657c5aab5.png)

Screen shot of a villager titled Fisherman who I AM able to hire (caught her blinking, whoops)
![screen shot 2017-11-16 at 1 11 11 pm](https://user-images.githubusercontent.com/17105217/32910947-402991ee-cad0-11e7-834a-4cf1586b2b20.png)

Screen Shot of an "Armorer" villager, unable to hire(blinking, lol):
![screen shot 2017-11-16 at 1 23 45 pm](https://user-images.githubusercontent.com/17105217/32911330-794cc53a-cad1-11e7-8a1e-530428ab5d13.png)


Screen shot of a guard, unable to hire:
![screen shot 2017-11-16 at 1 12 57 pm](https://user-images.githubusercontent.com/17105217/32911008-74f8a1f8-cad0-11e7-836a-095caeb9f4a6.png)
