### ISSUE TITLE
Villagers getting funky crashes client, not server

### ISSUE THREAD

**Issue by DVorriose** [WildBamaBoy/minecraft-comes-alive#910]
Issue started on first login to a new world on a server.

Lot of mods here, so it could be something else, but it looks like some Villagers are having too good a time. 

Server stays up, maybe they just want some privacy???

So I reset the server and created a new world, still near a village but Client didn't crash (maybe it wasn't a delightful morning?).  Unfortunately, I could only test the first 15-20 seconds, now back to java IO exceptions, but hopefully the crash report below will help you find/fix something freaky in the code.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.5a.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.4.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.0.20.jar)
  AstralCore (astralsorcery-1.12.2-1.7.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 11/5/17 4:13 PM
Description: Ticking entity

java.lang.ClassCastException: com.google.common.base.Present cannot be cast to java.lang.Boolean
	at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112)
	at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38)
	at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mca.actions.ActionProcreate.getIsProcreating(ActionProcreate.java:112)
	at mca.actions.ActionProcreate.onUpdateClient(ActionProcreate.java:38)
	at mca.entity.VillagerBehaviors.onUpdate(VillagerBehaviors.java:90)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:178)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.World.func_72870_g(World.java:1948)

-- Entity being ticked --
Details:
	Entity Type: mca:villagermca (mca.entity.EntityVillagerMCA)
	Entity ID: 64
	Entity Name: Steve
	Entity's Exact location: 266.46, 64.00, 124.81
	Entity's Block location: World: (266,64,124), Chunk: (at 10,4,12 in 16,7; contains blocks 256,0,112 to 271,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1755)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Vorriose'/2135, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 138, 138
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 128 game time, 128 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 59 total; [EntityFishCod['Cod'/1539, l='MpServer', x=176.71, y=38.15, z=167.72], EntityAncientGolem['Ancient Golem'/3, l='MpServer', x=220.50, y=27.00, z=93.78], EntityFishCod['Cod'/1540, l='MpServer', x=179.50, y=36.00, z=171.50], EntityHippocamp['entity.hippocamp.name'/6, l='MpServer', x=255.81, y=65.00, z=162.33], EntityHippocamp['entity.hippocamp.name'/9, l='MpServer', x=267.87, y=63.00, z=84.29], EntityHippocamp['entity.hippocamp.name'/10, l='MpServer', x=267.62, y=64.00, z=86.20], EntityHippocamp['entity.hippocamp.name'/11, l='MpServer', x=269.50, y=63.00, z=83.50], EntityCreeper['Creeper'/1934, l='MpServer', x=245.50, y=28.00, z=152.50], EntityZombie['Zombie'/1948, l='MpServer', x=218.50, y=5.00, z=91.50], EntityFishCod['Cod'/1437, l='MpServer', x=196.50, y=50.00, z=45.50], EntityZombie['Zombie'/1949, l='MpServer', x=219.50, y=5.00, z=91.50], EntityFishCod['Cod'/1438, l='MpServer', x=200.60, y=53.75, z=47.55], EntityFishCod['Cod'/1567, l='MpServer', x=188.24, y=53.20, z=36.59], EntityFishCod['Cod'/1439, l='MpServer', x=201.50, y=50.00, z=50.50], EntityFishCod['Cod'/1568, l='MpServer', x=181.50, y=49.80, z=37.20], EntityFishCod['Cod'/1440, l='MpServer', x=203.41, y=54.71, z=52.50], EntityFishCod['Cod'/1569, l='MpServer', x=184.52, y=61.68, z=32.57], EntityFishCod['Cod'/1441, l='MpServer', x=210.50, y=49.85, z=60.83], EntityFishCod['Cod'/1570, l='MpServer', x=189.23, y=54.20, z=33.50], EntityFishCod['Cod'/1442, l='MpServer', x=217.19, y=53.00, z=63.50], EntityFishCod['Cod'/1443, l='MpServer', x=202.83, y=50.80, z=59.63], EntityFishCod['Cod'/1444, l='MpServer', x=207.37, y=53.00, z=58.78], EntityZombie['Zombie'/1704, l='MpServer', x=198.50, y=28.00, z=149.50], EntityFishCod['Cod'/1321, l='MpServer', x=227.50, y=40.17, z=22.14], EntityFishCod['Cod'/1322, l='MpServer', x=226.50, y=36.00, z=19.50], EntityFishCod['Cod'/1323, l='MpServer', x=223.61, y=36.00, z=12.83], EntityFishCod['Cod'/1324, l='MpServer', x=226.52, y=37.69, z=16.50], EntityFishSalmon['Salmon'/1590, l='MpServer', x=193.47, y=56.67, z=29.47], EntityFishSalmon['Salmon'/1591, l='MpServer', x=198.50, y=52.00, z=31.50], EntityFishSalmon['Salmon'/1592, l='MpServer', x=198.25, y=55.23, z=32.25], EntityFishSalmon['Salmon'/1593, l='MpServer', x=197.50, y=52.00, z=26.50], EntityBat['Bat'/1341, l='MpServer', x=180.60, y=13.43, z=29.22], EntityFishCod['Cod'/1470, l='MpServer', x=201.50, y=42.15, z=94.80], EntityFishCod['Cod'/1471, l='MpServer', x=199.70, y=42.23, z=99.30], EntityFishCod['Cod'/1472, l='MpServer', x=198.50, y=39.00, z=102.50], EntityVillagerMCA['Steve'/64, l='MpServer', x=266.46, y=64.00, z=124.81], EntityFishCod['Cod'/1473, l='MpServer', x=201.43, y=43.19, z=111.27], EntityVillagerMCA['Steve'/65, l='MpServer', x=268.50, y=64.00, z=123.76], EntitySpider['Spider'/1985, l='MpServer', x=261.50, y=11.00, z=116.50], EntityCreeper['Creeper'/1859, l='MpServer', x=197.50, y=30.00, z=128.50], EntitySkeleton['Skeleton'/1860, l='MpServer', x=195.50, y=30.00, z=128.50], EntityPlayerSP['Vorriose'/2135, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySpider['Spider'/2001, l='MpServer', x=268.50, y=14.00, z=127.50], EntityZombie['Zombie'/1874, l='MpServer', x=238.50, y=23.00, z=116.50], EntityFishPufferfish['Pufferfish'/1362, l='MpServer', x=241.76, y=55.85, z=129.50], EntityFishClownfish['Clownfish'/1491, l='MpServer', x=176.50, y=47.80, z=73.32], EntityFishPufferfish['Pufferfish'/1363, l='MpServer', x=248.42, y=60.20, z=129.73], EntityFishClownfish['Clownfish'/1492, l='MpServer', x=178.50, y=49.00, z=75.50], EntityFishPufferfish['Pufferfish'/1364, l='MpServer', x=245.40, y=57.80, z=140.22], EntityFishPufferfish['Pufferfish'/1365, l='MpServer', x=242.40, y=53.99, z=133.55], EntityCreeper['Creeper'/2007, l='MpServer', x=179.50, y=25.00, z=28.50], EntityFishCod['Cod'/1369, l='MpServer', x=195.25, y=40.20, z=39.64], EntityFishCod['Cod'/1370, l='MpServer', x=187.65, y=34.83, z=38.65], EntityFishCod['Cod'/1371, l='MpServer', x=187.62, y=39.00, z=35.84], EntityFishCod['Cod'/1372, l='MpServer', x=183.75, y=41.20, z=47.33], EntityFishCod['Cod'/1390, l='MpServer', x=194.36, y=42.20, z=56.25], EntityFishCod['Cod'/1391, l='MpServer', x=195.24, y=39.80, z=49.70], EntityFishCod['Cod'/1392, l='MpServer', x=194.50, y=41.26, z=53.50], EntityFishCod['Cod'/1393, l='MpServer', x=192.46, y=47.71, z=56.41]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6180413592 bytes (5894 MB) / 10127147008 bytes (9658 MB) up to 10468982784 bytes (9984 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9984m -Xms256m -XX:PermSize=256m -Xms4G -XX:+UseG1GC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=7
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.0.2515 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version              | Source                                            | Signature                                |
	|:------ |:-------------------------------------------- |:-------------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                                    | 1.12.2               | minecraft.jar                                     | None                                     |
	| UCHIJA | mcp                                          | 9.42                 | minecraft.jar                                     | None                                     |
	| UCHIJA | FML                                          | 8.0.99.99            | forge-1.12.2-14.23.0.2515.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                                        | 14.23.0.2515         | forge-1.12.2-14.23.0.2515.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | advancedrocketrycore                         | 1                    | minecraft.jar                                     | None                                     |
	| UCHIJA | ivtoolkit                                    | 1.3.3-1.12           | minecraft.jar                                     | None                                     |
	| UCHIJA | com.elytradev.movingworld.common.asm.coremod |                      | minecraft.jar                                     | None                                     |
	| UCHIJA | opencomputers|core                           | 1.7.0.20             | minecraft.jar                                     | None                                     |
	| UCHIJA | movillages                                   | 1.5.4                | [1.12]MoVillages-1.5.4.jar                        | None                                     |
	| UCHIJA | libvulpes                                    | 0.2.6.               | LibVulpes-1.12.2-0.2.6-universal.jar              | None                                     |
	| UCHIJA | advancedrocketry                             | 1.2.5a.              | AdvancedRocketry-1.12.2-1.2.5a.jar                | None                                     |
	| UCHIJA | appliedenergistics2                          | rv5-stable-1         | appliedenergistics2-rv5-stable-1.jar              | None                                     |
	| UCHIJA | aroma1997core                                | 1.3.0.2              | Aroma1997Core-1.12.2-1.3.0.2.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJA | aroma1997sdimension                          | 1.3.0.0.b37          | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| UCHIJA | astralsorcery                                | 1.7.2                | astralsorcery-1.12.2-1.7.2.jar                    | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJA | baubles                                      | 1.5.1                | Baubles-1.12-1.5.1.jar                            | None                                     |
	| UCHIJA | betteragriculture                            | 1.2.1                | betteragriculture-1.12.2-1.2.1.jar                | None                                     |
	| UCHIJA | bibliocraft                                  | 2.4.3                | BiblioCraft[v2.4.3][MC1.12.0].jar                 | None                                     |
	| UCHIJA | biomesoplenty                                | 7.0.1.2302           | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar     | None                                     |
	| UCHIJA | botania                                      | r1.10-349            | Botania r1.10-349.jar                             | None                                     |
	| UCHIJA | ctm                                          | MC1.12-0.2.3.9       | CTM-MC1.12-0.2.3.9.jar                            | None                                     |
	| UCHIJA | chisel                                       | MC1.12-0.0.14.18     | Chisel-MC1.12-0.0.14.18.jar                       | None                                     |
	| UCHIJA | chunkpregenerator                            | 1.4                  | Chunk Pregenerator V-1.12-1.4.1.jar               | None                                     |
	| UCHIJA | codechickenlib                               | 3.1.3.313            | CodeChickenLib-1.12-3.1.3.313-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | redstoneflux                                 | 2.0.1                | RedstoneFlux-1.12-2.0.1.2-universal.jar           | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJA | cofhcore                                     | 4.3.6                | CoFHCore-1.12-4.3.6.14-universal.jar              | None                                     |
	| UCHIJA | cofhworld                                    | 1.0.1                | CoFHWorld-1.12-1.0.1.8-universal.jar              | None                                     |
	| UCHIJA | drpcore                                      | 0.3.4.1              | Dark Roleplay Core Alpha-0.3.4.1.jar              | None                                     |
	| UCHIJA | drpmedieval                                  | 0.2.3.1              | Dark Roleplay Medieval-0.2.3.1.jar                | None                                     |
	| UCHIJA | movingworld                                  | 1.12-6.342           | movingworld-1.12-6.342-full.jar                   | None                                     |
	| UCHIJA | davincisvessels                              | @DVESSELSVER@        | davincisvessels-1.12-6.337-full.jar               | None                                     |
	| UCHIJA | doggytalents                                 | 1.14.2.311           | DoggyTalents-1.12-1.14.2.311-universal.jar        | None                                     |
	| UCHIJA | dooglamoocitiesmod                           | 1.6.3                | dooglamoocitiesmod-1.12-1.6.3.jar                 | None                                     |
	| UCHIJA | duckcraft                                    | 3.0.5                | Duckcraft-1.12-3.0.5.jar                          | None                                     |
	| UCHIJA | dsurround                                    | 3.4.7.2              | DynamicSurroundings-1.12.2-3.4.7.2.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJA | presets                                      | 3.4.7.2              | DynamicSurroundings-1.12.2-3.4.7.2.jar            | None                                     |
	| UCHIJA | embers                                       | 0.230                | embers-0.230.jar                                  | None                                     |
	| UCHIJA | exnihilocreatio                              | 1.12-0.1.5           | exnihilocreatio-1.12-0.1.5.jar                    | None                                     |
	| UCHIJA | factorytech                                  | 1.1.5                | FactoryTech-1.12.2-1.1.6c.jar                     | None                                     |
	| UCHIJA | fairylights                                  | 2.1.1                | fairylights-2.1.1-1.12.jar                        | None                                     |
	| UCHIJA | ic2                                          | 2.8.16-ex112         | industrialcraft-2-2.8.16-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA | jei                                          | 4.8.0.111            | jei_1.12.2-4.8.0.111.jar                          | None                                     |
	| UCHIJA | mantle                                       | 1.12-1.3.1.21        | Mantle-1.12-1.3.1.21.jar                          | None                                     |
	| UCHIJA | natura                                       | 1.12-4.3.0.23        | natura-1.12-4.3.0.23.jar                          | None                                     |
	| UCHIJA | forestry                                     | 5.7.0.209            | forestry_1.12.2-5.7.0.209.jar                     | None                                     |
	| UCHIJA | forgelin                                     | 1.5.1                | Forgelin-1.5.1.jar                                | None                                     |
	| UCHIJA | gravestone                                   | 1.10.0               | gravestone-1.10.0.jar                             | None                                     |
	| UCHIJA | waila                                        | 1.8.22               | Hwyla-1.8.22-B37_1.12.jar                         | None                                     |
	| UCHIJA | tconstruct                                   | 1.12-2.7.4.34        | TConstruct-1.12-2.7.4.34.jar                      | None                                     |
	| UCHIJA | immersiveengineering                         | 0.12-74              | ImmersiveEngineering-0.12-74.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJA | immersivepetroleum                           | 1.1.3                | immersivepetroleum-1.12-1.1.3.jar                 | None                                     |
	| UCHIJA | immersivetech                                | 1.3.4                | immersivetech-1.12-1.3.4.jar                      | None                                     |
	| UCHIJA | teslacorelib                                 | 1.0.11               | tesla-core-lib-1.12-1.0.11.jar                    | None                                     |
	| UCHIJA | industrialforegoing                          | 1.12.2-1.12.1        | industrialforegoing-1.12.2-1.5.3-88.jar           | None                                     |
	| UCHIJA | industrialwires                              | 1.6-22               | IndustrialWires-1.6-22.jar                        | 7e11c175d1e24007afec7498a1616bef0000027d |
	| UCHIJA | journeymap                                   | 1.12.2-5.5.1         | journeymap-1.12.2-5.5.1.jar                       | None                                     |
	| UCHIJA | jaff                                         | 1.7_for_1.12         | JustAFewFish-1.7_for_1.12.jar                     | None                                     |
	| UCHIJA | jeresources                                  | 0.8.5.27             | JustEnoughResources-1.12.2-0.8.5.27.jar           | None                                     |
	| UCHIJA | radixcore                                    | 1.12.x-2.2.1         | RadixCore-1.12.x-2.2.1-universal.jar              | None                                     |
	| UCHIJA | mca                                          | 1.12.2-5.3.1         | MCA-1.12.x-5.3.1-universal.jar                    | None                                     |
	| UCHIJA | mist                                         | alpha_b_01           | MistWorld_1.12.1_alpha_b_01.jar                   | None                                     |
	| UCHIJA | morpheus                                     | 1.12-3.3.2           | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| UCHIJA | nuclearcraft                                 | 2.5a                 | NuclearCraft-2.5a--1.12.2.jar                     | None                                     |
	| UCHIJA | opencomputers                                | 1.7.0.20             | OpenComputers-MC1.12.1-1.7.0.20.jar               | None                                     |
	| UCHIJA | peacefulsurface                              | 1.12.2-v1            | PeacefulSurface-1.12.2-v1.jar                     | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJA | rainboaks                                    | 1.0.4                | RainbowOaks-1.12-1.0.4.jar                        | None                                     |
	| UCHIJA | randomthings                                 | 4.0.8                | RandomThings-MC1.12.2-4.0.8.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | reap                                         | 1.5.0                | reap-1.5.0.jar                                    | None                                     |
	| UCHIJA | reborncore                                   | 3.4.10.147           | RebornCore-1.12.2-3.4.10.147-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJA | reccomplex                                   | 1.4.5                | RecurrentComplex-1.4.5.1.jar                      | None                                     |
	| UCHIJA | roguelike                                    | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| UCHIJA | roots                                        | 0.103                | roots-2-0.103.jar                                 | None                                     |
	| UCHIJA | rustic                                       | 0.4.2.1              | rustic-0.4.3.jar                                  | None                                     |
	| UCHIJA | shetiphiancore                               | 3.5.4                | shetiphiancore-1.12.0-3.5.4.jar                   | None                                     |
	| UCHIJA | tatw                                         | 1.0.1.2              | Tatw-1.12.2-1.0.1.2.jar                           | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJA | techreborn                                   | 2.7.10.327           | TechReborn-1.12.2-2.7.10.327-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJA | terraqueous                                  | 1.4.4                | terraqueous-1.12.0-1.4.4.jar                      | None                                     |
	| UCHIJA | thermalfoundation                            | 2.3.6                | ThermalFoundation-1.12-2.3.6.16-universal.jar     | None                                     |
	| UCHIJA | tinkersaddons                                | 1.0.7                | Tinkers' Addons-1.12.1-1.0.7.jar                  | None                                     |
	| UCHIJA | twilightforest                               | 3.3.202              | twilightforest-1.12.2-3.3.202-universal.jar       | None                                     |
	| UCHIJA | ultimate_unicorn_mod                         | 1.5.14               | ultimate_unicorn_mod-1.12.2-1.5.14.jar            | None                                     |
	| UCHIJA | villagenames                                 | 2.0                  | VillageNames-1.12.2-2.0.jar                       | None                                     |
	| UCHIJA | waddles                                      | 0.5.6                | Waddles-1.12.2-0.5.6.jar                          | None                                     |
	| UCHIJA | wailaharvestability                          | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar             | None                                     |
	| UCHIJA | wanionlib                                    | 1.12.2-1.1           | WanionLib-1.12.2-1.1.jar                          | None                                     |
	| UCHIJA | wawla                                        | 2.5.246              | Wawla-1.12.2-2.5.246.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | wolfarmor                                    | 1.12.2-2.1.0-RELEASE | wolfarmor-1.12.2-2.1.0.24-RELEASE.jar             | None                                     |
	| UCHIJA | teslacorelib_registries                      | 1.0.11               | tesla-core-lib-1.12-1.0.11.jar                    | None                                     |
	| UCHIJA | unidict                                      | 1.12.2-1.1b          | UniDict-1.12.2-1.1b.jar                           | None                                     |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.5a.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
ForgelinPlugin (Forgelin-1.5.1.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.4.jar)
  shetiphian.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
TransformerLoader (OpenComputers-MC1.12.1-1.7.0.20.jar)
  li.cil.oc.common.asm.ClassTransformer
AstralCore (astralsorcery-1.12.2-1.7.2.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 630'
	AE2 Version: stable rv5-stable-1 for Forge 14.23.0.2491
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.4.10.147
		Runtime Debofucsation 1
		RenderEngine: 0
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF
	Launched Version: forge-14.23.0.2515
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 630 GL version 4.4.0 - Build 21.20.16.4550, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by Nekuromu** [comment]
Had this happen as well, plus another one related to the professions being given to newborns after the procreation. Something about the ids.

**Comment by Zareion** [comment]
Yeah, i'm getting the same issue on my end, client side crash upon rendering the villagers.

**Comment by VirtualGaming1** [comment]
Same here

**Comment by Maccool** [comment]
Just in case another example of this crash would help ... Happens on approach to a village. After several crashes by the client I was going to teleport them back to their home (as they couldn't move from that spot based on the immediate repeat of the crash), but before I did the teleport I: 

stopped the server
started the server
had the client re-enter the game. 

This allowed the client to continue on with the game without a crash (for the moment?) without moving them off the crash coordinates. I'm not sure what restarting the server had to do with the correction (if at all), but it seemed to work.

Log and crash report from the crash looked like:
https://pastebin.com/raw/xYWCPwCj (partial as the log was too big for free pastebin)
https://pastebin.com/raw/pgpaanVE

**Comment by Maccool** [comment]
Just as further FYI, I have subsequently:

re-approached the village that caused the earlier crash from a different direction with no problems

found a 2nd village and had no problems with crashing.

Seems that stopping the server reset the condition and/or this is primarily a first contact problem.

**Comment by recalcitrantQ** [comment]
Cause of crash is the OVERWRITE_KEY DataParameter being added to the base EntityVillager class as a check for converting squidwards into MCA villagers. Solution is to remove that parameter and instead check in EvenHooksFML if the entity is a EntityVillager but not an EntityVillagerMCA

Will submit a pull request when I have time

**Comment by minecrafter2334** [comment]
Does anybody have a temporary fix? Can't join a lan server when it renders a MCA villager

**Comment by minecrafter2334** [comment]
or simplify a fix

**Comment by JohnLouderback** [comment]
I'd like to know as well if there's an type of temporary fix, or when a resolution can be expected.

**Comment by shanebirley** [comment]
Any word on this? Any beer required?

**Comment by CrazyCowboy557** [comment]
Is this being worked on?

**Comment by Kio-td** [comment]
I have to +1 this, sorry @WildBamaBoy.

**Comment by kaaass** [comment]
Same problem occured with me. Fix it pls :)

**Comment by RocketManKian** [comment]
Any update on this? I'm still experiencing it....

**Comment by mightyjaffa12** [comment]
plz fix

**Comment by Nze25** [comment]
hey pls fix it

**Comment by mightyjaffa12** [comment]
It won't be fixed, they abandoned the mod ages ago. So basically. No one cares
