### ISSUE TITLE
Client crash on village load

### ISSUE THREAD

**Issue by aridhol** [WildBamaBoy/minecraft-comes-alive#912]
Consistent crash when entering a village on multiplayer server - can't log back in now because I'm in said village and it immediately crashes again...

`
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BCModPlugin (backpacks 1.12.2 - 3.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  AstralCore (astralsorcery-1.12.2-1.7.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 11/9/17 6:45 PM
Description: Ticking entity

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at mca.entity.VillagerAttributes.getProfessionEnum(VillagerAttributes.java:215)
	at mca.entity.EntityVillagerMCA.func_184586_b(EntityVillagerMCA.java:678)
	at mca.entity.EntityVillagerMCA.func_184582_a(EntityVillagerMCA.java:800)
	at net.minecraft.entity.EntityLivingBase.func_184614_ca(EntityLivingBase.java:1608)
	at com.lothrazar.cyclicmagic.enchantment.EnchantBase.getCurrentLevelTool(EnchantBase.java:18)
	at com.lothrazar.cyclicmagic.enchantment.EnchantMagnet.onEntityUpdate(EnchantMagnet.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_731_EnchantMagnet_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:554)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2083)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mca.entity.VillagerAttributes.getProfessionEnum(VillagerAttributes.java:215)
	at mca.entity.EntityVillagerMCA.func_184586_b(EntityVillagerMCA.java:678)
	at mca.entity.EntityVillagerMCA.func_184582_a(EntityVillagerMCA.java:800)
	at net.minecraft.entity.EntityLivingBase.func_184614_ca(EntityLivingBase.java:1608)
	at com.lothrazar.cyclicmagic.enchantment.EnchantBase.getCurrentLevelTool(EnchantBase.java:18)
	at com.lothrazar.cyclicmagic.enchantment.EnchantMagnet.onEntityUpdate(EnchantMagnet.java:28)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_731_EnchantMagnet_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:554)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2083)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at mca.entity.EntityVillagerMCA.func_70071_h_(EntityVillagerMCA.java:175)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.World.func_72870_g(World.java:1948)

-- Entity being ticked --
Details:
	Entity Type: mca:villagermca (mca.entity.EntityVillagerMCA)
	Entity ID: 329
	Entity Name: Steve
	Entity's Exact location: 105.50, 71.00, -143.50
	Entity's Block location: World: (105,71,-144), Chunk: (at 9,4,0 in 6,-9; contains blocks 96,0,-144 to 111,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1755)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['AridholGM'/4335, l='MpServer', x=154.77, y=64.00, z=-139.89]]
	Chunk stats: MultiplayerChunkCache: 508, 508
	Level seed: 0
	Level generator: ID 09 - lostcities_bop, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (182,64,-116), Chunk: (at 6,4,12 in 11,-8; contains blocks 176,0,-128 to 191,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 38631 game time, 38631 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 111 total; [EntityCreeper['Creeper'/3603, l='MpServer', x=224.50, y=13.00, z=-124.50], EntityBat['Bat'/3860, l='MpServer', x=189.83, y=38.87, z=-204.45], EntityCreeper['Creeper'/4383, l='MpServer', x=97.50, y=72.00, z=-161.50], EntityCreeper['Creeper'/4384, l='MpServer', x=98.50, y=72.00, z=-160.50], EntitySkeleton['Skeleton'/3115, l='MpServer', x=144.50, y=30.00, z=-159.50], EntityZombie['Zombie'/3884, l='MpServer', x=216.50, y=41.00, z=-189.50], EntitySkeleton['Skeleton'/3636, l='MpServer', x=114.70, y=34.00, z=-74.44], EntitySkeleton['Skeleton'/3637, l='MpServer', x=113.14, y=28.00, z=-76.30], EntityZombie['Zombie'/4411, l='MpServer', x=219.50, y=12.00, z=-185.50], EntityBat['Bat'/2876, l='MpServer', x=114.59, y=44.08, z=-111.75], EntityBat['Bat'/3390, l='MpServer', x=123.40, y=44.10, z=-113.25], EntitySkeleton['Skeleton'/4414, l='MpServer', x=89.50, y=53.00, z=-63.50], EntityBat['Bat'/3391, l='MpServer', x=129.48, y=47.04, z=-104.36], EntityPlayerSP['AridholGM'/4335, l='MpServer', x=154.77, y=64.00, z=-139.89], EntityPig['Pig'/71, l='MpServer', x=76.50, y=63.00, z=-117.50], EntitySpider['Spider'/2887, l='MpServer', x=107.50, y=11.00, z=-110.50], EntityVillagerMCA['Steve'/329, l='MpServer', x=105.50, y=71.00, z=-143.50], EntityPig['Pig'/75, l='MpServer', x=84.31, y=70.00, z=-82.50], EntityPig['Pig'/77, l='MpServer', x=76.50, y=70.00, z=-86.50], EntityCreeper['Creeper'/3661, l='MpServer', x=123.50, y=39.00, z=-76.50], EntityZombie['Zombie'/3662, l='MpServer', x=124.50, y=39.00, z=-78.50], EntityZombie['Zombie'/3663, l='MpServer', x=122.50, y=39.00, z=-75.50], EntityCreeper['Creeper'/3665, l='MpServer', x=81.50, y=36.00, z=-71.50], EntityZombie['Zombie'/3411, l='MpServer', x=124.50, y=39.00, z=-83.50], EntitySkeleton['Skeleton'/3926, l='MpServer', x=227.50, y=25.00, z=-124.50], EntityBat['Bat'/4188, l='MpServer', x=123.42, y=23.97, z=-136.25], EntityBat['Bat'/4189, l='MpServer', x=91.68, y=37.10, z=-64.32], EntityItem['item.tile.torch'/95, l='MpServer', x=103.88, y=75.50, z=-123.60], EntitySkeleton['Skeleton'/3935, l='MpServer', x=158.50, y=31.00, z=-84.50], EntityItem['item.tile.torch'/96, l='MpServer', x=103.88, y=72.00, z=-126.57], EntityItem['item.tile.torch'/97, l='MpServer', x=104.25, y=74.00, z=-125.88], EntityBat['Bat'/2921, l='MpServer', x=178.52, y=17.29, z=-104.31], EntityZombie['Zombie'/3178, l='MpServer', x=167.96, y=49.00, z=-99.17], EntityEnderman['Enderman'/4203, l='MpServer', x=105.50, y=38.00, z=-115.50], EntitySkeleton['Skeleton'/3179, l='MpServer', x=170.21, y=52.00, z=-111.50], EntityZombie['Zombie'/4204, l='MpServer', x=105.50, y=38.00, z=-113.50], EntitySkeleton['Skeleton'/3180, l='MpServer', x=162.50, y=55.00, z=-109.28], EntitySpider['Spider'/3181, l='MpServer', x=196.50, y=16.00, z=-210.50], EntityCreeper['Creeper'/3959, l='MpServer', x=148.50, y=17.00, z=-132.50], EntityCreeper['Creeper'/3960, l='MpServer', x=150.50, y=17.00, z=-135.50], EntityCreeper['Creeper'/3964, l='MpServer', x=82.50, y=46.00, z=-85.50], EntitySkeleton['Skeleton'/3967, l='MpServer', x=97.50, y=44.00, z=-98.50], EntitySheep['Sheep'/134, l='MpServer', x=144.25, y=74.00, z=-204.05], EntityZombie['Zombie'/3718, l='MpServer', x=170.50, y=21.00, z=-106.50], EntitySheep['Sheep'/135, l='MpServer', x=138.77, y=74.00, z=-202.64], EntitySheep['Sheep'/136, l='MpServer', x=147.50, y=74.00, z=-209.50], EntitySkeleton['Skeleton'/3720, l='MpServer', x=178.50, y=15.00, z=-84.50], EntitySheep['Sheep'/137, l='MpServer', x=142.38, y=74.00, z=-206.03], EntityZombie['Zombie'/4238, l='MpServer', x=127.50, y=62.00, z=-173.50], EntityBat['Bat'/3982, l='MpServer', x=119.47, y=32.93, z=-126.80], EntityItem['item.item.silentgems:FluffyPuffSeeds'/142, l='MpServer', x=153.20, y=73.00, z=-196.63], EntityItem['item.item.seeds'/143, l='MpServer', x=156.81, y=73.00, z=-195.50], EntityAncientGolem['Ancient Golem'/4240, l='MpServer', x=133.50, y=62.00, z=-175.50], EntityItem['item.item.seeds'/145, l='MpServer', x=156.32, y=75.00, z=-201.51], EntityItem['item.item.seeds'/3985, l='MpServer', x=180.55, y=64.00, z=-140.84], EntitySheep['Sheep'/146, l='MpServer', x=164.09, y=72.00, z=-180.64], EntitySheep['Sheep'/147, l='MpServer', x=167.50, y=71.00, z=-178.50], EntitySheep['Sheep'/148, l='MpServer', x=162.77, y=72.00, z=-184.20], EntitySheep['Sheep'/149, l='MpServer', x=163.00, y=72.00, z=-180.41], EntityZombie['Zombie'/3733, l='MpServer', x=220.50, y=16.00, z=-129.50], EntitySheep['Sheep'/157, l='MpServer', x=172.29, y=73.00, z=-196.81], EntitySheep['Sheep'/158, l='MpServer', x=166.74, y=73.00, z=-190.52], EntityAncientGolem['Ancient Golem'/3742, l='MpServer', x=160.70, y=41.00, z=-105.30], EntitySheep['Sheep'/159, l='MpServer', x=170.50, y=73.00, z=-197.50], EntitySheep['Sheep'/160, l='MpServer', x=171.20, y=73.00, z=-196.46], EntitySheep['Sheep'/161, l='MpServer', x=173.27, y=65.00, z=-152.59], EntitySheep['Sheep'/162, l='MpServer', x=161.84, y=64.00, z=-127.18], EntitySheep['Sheep'/163, l='MpServer', x=190.18, y=64.00, z=-139.66], EntitySheep['Sheep'/164, l='MpServer', x=172.24, y=64.00, z=-150.19], EntityBat['Bat'/3238, l='MpServer', x=149.75, y=33.57, z=-112.40], EntitySheep['Sheep'/169, l='MpServer', x=198.50, y=69.00, z=-172.50], EntitySheep['Sheep'/170, l='MpServer', x=198.50, y=70.00, z=-173.50], EntityZombie['Zombie'/4267, l='MpServer', x=115.50, y=63.00, z=-110.19], EntitySheep['Sheep'/171, l='MpServer', x=197.50, y=70.00, z=-174.50], EntitySheep['Sheep'/172, l='MpServer', x=196.50, y=71.00, z=-177.50], EntitySheep['Sheep'/173, l='MpServer', x=189.50, y=87.00, z=-104.50], EntitySheep['Sheep'/174, l='MpServer', x=201.27, y=91.00, z=-112.50], EntitySheep['Sheep'/175, l='MpServer', x=191.27, y=87.00, z=-105.49], EntitySheep['Sheep'/176, l='MpServer', x=183.27, y=81.00, z=-105.50], EntityCow['Cow'/177, l='MpServer', x=200.40, y=91.00, z=-104.84], EntityCreeper['Creeper'/3505, l='MpServer', x=223.50, y=95.00, z=-89.50], EntityCreeper['Creeper'/4018, l='MpServer', x=140.50, y=41.00, z=-113.50], EntityCow['Cow'/178, l='MpServer', x=205.01, y=93.00, z=-116.50], EntityCow['Cow'/179, l='MpServer', x=203.17, y=92.00, z=-120.49], EntityEnderman['Enderman'/3764, l='MpServer', x=87.50, y=38.00, z=-84.50], EntityCow['Cow'/180, l='MpServer', x=204.05, y=93.00, z=-116.50], EntityItem['item.item.seeds'/181, l='MpServer', x=197.13, y=95.00, z=-79.13], EntityItem['item.item.silentgems:FluffyPuffSeeds'/182, l='MpServer', x=195.13, y=89.00, z=-84.18], EntitySkeleton['Skeleton'/4023, l='MpServer', x=125.50, y=22.00, z=-67.50], EntityItem['item.item.seeds'/183, l='MpServer', x=196.01, y=96.00, z=-76.93], EntitySheep['Sheep'/184, l='MpServer', x=221.50, y=74.00, z=-205.50], EntitySheep['Sheep'/185, l='MpServer', x=218.50, y=73.00, z=-203.50], EntitySheep['Sheep'/186, l='MpServer', x=225.50, y=75.00, z=-208.50], EntitySheep['Sheep'/187, l='MpServer', x=226.50, y=75.00, z=-210.50], EntityPig['Pig'/188, l='MpServer', x=223.50, y=73.00, z=-199.50], EntityPig['Pig'/189, l='MpServer', x=223.50, y=73.00, z=-198.50], EntityPig['Pig'/190, l='MpServer', x=222.09, y=73.00, z=-194.51], EntityPig['Pig'/191, l='MpServer', x=228.50, y=77.00, z=-192.50], EntityPig['Pig'/192, l='MpServer', x=225.50, y=73.00, z=-197.50], EntityPig['Pig'/193, l='MpServer', x=220.79, y=73.00, z=-194.50], EntityPig['Pig'/194, l='MpServer', x=221.50, y=72.00, z=-193.50], EntityZombie['Zombie'/3780, l='MpServer', x=171.77, y=48.00, z=-103.26], EntityZombie['Zombie'/3781, l='MpServer', x=174.56, y=47.00, z=-91.73], EntityZombie['Zombie'/3782, l='MpServer', x=176.50, y=49.00, z=-102.19], EntityZombie['Zombie'/3783, l='MpServer', x=179.38, y=48.00, z=-93.80], EntityEnderman['Enderman'/4298, l='MpServer', x=184.50, y=14.00, z=-94.50], EntitySkeleton['Skeleton'/4300, l='MpServer', x=186.50, y=14.00, z=-94.50], EntitySkeleton['Skeleton'/3554, l='MpServer', x=112.54, y=43.00, z=-64.24], EntityCreeper['Creeper'/4331, l='MpServer', x=194.50, y=57.00, z=-211.50], EntityZombie['Zombie'/3568, l='MpServer', x=173.50, y=22.00, z=-115.50], EntityZombie['Zombie'/3575, l='MpServer', x=96.74, y=40.00, z=-61.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1561371968 bytes (1489 MB) / 2785017856 bytes (2656 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:PermSize=512m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.0.2536 Optifine OptiFine_1.12.2_HD_U_C6 80 mods loaded, 80 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version                  | Source                                        | Signature                                |
	|:------ |:--------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                   | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                         | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                         | 8.0.99.99                | forge-1.12.2-14.23.0.2536.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                       | 14.23.0.2536             | forge-1.12.2-14.23.0.2536.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | ivtoolkit                   | 1.3.3-1.12               | minecraft.jar                                 | None                                     |
	| UCHIJA | swordskillsapi              | 1.1.0                    | 1.12.2-SwordSkillsApi-1.1.0.jar               | None                                     |
	| UCHIJA | dynamicswordskills          | 1.12.2-6.0               | 1.12.2-DynamicSwordSkills-6.0.jar             | None                                     |
	| UCHIJA | tammodized                  | 0.15.3                   | TamModized-1.12.1-0.15.3.jar                  | None                                     |
	| UCHIJA | aov                         | 0.6.2                    | AoV-1.12.1-0.6.2.jar                          | None                                     |
	| UCHIJA | crafttweaker                | 4.0.9                    | CraftTweaker2-1.12-4.0.9.jar                  | None                                     |
	| UCHIJA | mtlib                       | @VERSION@                | MTLib-3.0.1.jar                               | None                                     |
	| UCHIJA | modtweaker                  | 4.0.4                    | modtweaker-4.0.4.jar                          | None                                     |
	| UCHIJA | jei                         | 4.8.0.111                | jei_1.12.2-4.8.0.111.jar                      | None                                     |
	| UCHIJA | appleskin                   | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| UCHIJA | astralsorcery               | 1.7.2                    | astralsorcery-1.12.2-1.7.2.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJA | backpacks16840              | backpacks16840           | backpacks 1.12.2 - 3.4.0.jar                  | None                                     |
	| UCHIJA | badwithernocookiereloaded   | 1.12.2-2.12              | badwithernocookiereloaded-1.12.2-2.12.jar     | None                                     |
	| UCHIJA | bedbugs                     | @VERSION@                | BedBugs-1.12-1.0.1.jar                        | None                                     |
	| UCHIJA | bibliocraft                 | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCHIJA | biomesoplenty               | 7.0.1.2302               | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar | None                                     |
	| UCHIJA | codechickenlib              | 3.1.3.313                | CodeChickenLib-1.12-3.1.3.313-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | cyclopscore                 | 0.10.22                  | CyclopsCore-1.12.2-0.10.22.jar                | None                                     |
	| UCHIJA | commoncapabilities          | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar             | None                                     |
	| UCHIJA | ctgui                       | 1.0.0                    | CraftTweaker2-1.12-4.0.9.jar                  | None                                     |
	| UCHIJA | crafttweakerjei             | 2.0.0                    | CraftTweaker2-1.12-4.0.9.jar                  | None                                     |
	| UCHIJA | ctm                         | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                        | None                                     |
	| UCHIJA | cyclicmagic                 | 1.9.9                    | Cyclic-1.12.2-1.9.9.jar                       | 59618e85d596916a0bc866ae82cfa1d7d51a6947 |
	| UCHIJA | diethopper                  | 1.1                      | diethopper-1.1.jar                            | None                                     |
	| UCHIJA | dynamiclights               | 1.4.6                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_onfire        | 1.0.7                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_creepers      | 1.0.6                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_dropitems     | 1.1.0                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_entityclasses | 1.0.1                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_mobequipment  | 1.1.0                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_flamearrows   | 1.0.1                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_floodlights   | 1.0.3                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_otherplayers  | 1.0.9                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | dynamiclights_theplayer     | 1.1.3                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UCHIJA | eleccore                    | 1.8.430                  | ElecCore-1.12-1.8.430.jar                     | None                                     |
	| UCHIJA | embers                      | 0.230                    | embers-0.230.jar                              | None                                     |
	| UCHIJA | everlastingabilities        | 1.3.6                    | EverlastingAbilities-1.12.2-1.3.6.jar         | None                                     |
	| UCHIJA | evilcraft                   | 0.10.39                  | EvilCraft-1.12.2-0.10.39.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJA | evilcraftcompat             | 1.0.0                    | EvilCraft-1.12.2-0.10.39.jar                  | None                                     |
	| UCHIJA | foamfix                     | 0.8.0-1.12               | foamfix-0.8.0-1.12-law.jar                    | None                                     |
	| UCHIJA | forgelin                    | 1.5.1                    | Forgelin-1.5.1.jar                            | None                                     |
	| UCHIJA | ftbl                        | 4.2.3                    | FTBLib-4.2.3.jar                              | None                                     |
	| UCHIJA | ftbu                        | 4.2.2                    | FTBUtilities-4.2.2.jar                        | None                                     |
	| UCHIJA | gravestone                  | 1.10.0                   | gravestone-1.10.0.jar                         | None                                     |
	| UCHIJA | inventorytweaks             | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA | ironchest                   | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar               | None                                     |
	| UCHIJA | journeymap                  | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJA | jeresources                 | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar       | None                                     |
	| UCHIJA | longfallboots               | 1.2.1a                   | longfallboots-1.2.1a.jar                      | None                                     |
	| UCHIJA | lostcities                  | 1.0.2                    | lostcities-1.12-1.0.2.jar                     | None                                     |
	| UCHIJA | radixcore                   | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| UCHIJA | mca                         | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
	| UCHIJA | mobtotems                   | 1.12.1-0.3.0             | mobtotems-1.12.1-0.3.0.jar                    | None                                     |
	| UCHIJA | morpheus                    | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                       | None                                     |
	| UCHIJA | mousetweaks                 | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
	| UCHIJA | netherportalfix             | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar             | None                                     |
	| UCHIJA | p455w0rdslib                | 2.0.24                   | p455w0rdslib-1.12-2.0.24.jar                  | None                                     |
	| UCHIJA | quickleafdecay              | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
	| UCHIJA | reauth                      | 3.5.2                    | ReAuth-3.5.2.jar                              | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCHIJA | reccomplex                  | 1.4.5                    | RecurrentComplex-1.4.5.1.jar                  | None                                     |
	| UCHIJA | xreliquary                  | 1.12.2-1.3.4.719         | Reliquary-1.12.2-1.3.4.719.jar                | None                                     |
	| UCHIJA | resourceloader              | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | roots                       | 0.103                    | roots-2-0.103.jar                             | None                                     |
	| UCHIJA | shetiphiancore              | 3.5.4                    | shetiphiancore-1.12.0-3.5.4.jar               | None                                     |
	| UCHIJA | silentlib                   | 2.2.12                   | SilentLib-1.12-2.2.12-93.jar                  | None                                     |
	| UCHIJA | silentgems                  | 2.5.10                   | SilentsGems-1.12-2.5.10-247.jar               | None                                     |
	| UCHIJA | simpleharvest               | 1.07                     | simpleharvest-1.07.jar                        | None                                     |
	| UCHIJA | theoneprobe                 | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                   | None                                     |
	| UCHIJA | supersoundmuffler           | 1.0.2.9                  | supersoundmuffler-1.12.1-1.0.2.9.jar          | None                                     |
	| UCHIJA | topaddons                   | 1.12.2-1.1.3             | topaddons-1.12.2-1.1.3.jar                    | None                                     |
	| UCHIJA | torchmaster                 | 1.6.1.53                 | torchmaster_1.12.2-1.6.1.53.jar               | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHIJA | wanionlib                   | 1.12.2-1.2               | WanionLib-1.12.2-1.2.jar                      | None                                     |
	| UCHIJA | waystones                   | 4.0.17                   | Waystones_1.12.1-4.0.17.jar                   | None                                     |
	| UCHIJA | yabba                       | 1.0.10                   | YABBA-1.0.10.jar                              | None                                     |
	| UCHIJA | elulib                      | 0.1.7                    | elulib-0.1.7.jar                              | None                                     |
	| UCHIJA | unidict                     | 1.12.2-1.2               | UniDict-1.12.2-1.2.jar                        | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BCModPlugin (backpacks 1.12.2 - 3.4.0.jar)
  brad16840.core.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.4.jar)
  shetiphian.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  atomicstryker.dynamiclights.common.DLTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AstralCore (astralsorcery-1.12.2-1.7.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 650 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2536
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 650 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD Phenom(tm) II X6 1045T Processor
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 650 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6
`

**Comment by ZeWolfTah** [comment]
Appears to be similar to
https://github.com/WildBamaBoy/minecraft-comes-alive/issues/884

This one is ticking entity, the other is rendering entity in world, but the symptoms are the same.

**Comment by AlphaMason** [comment]
I am also having this problem.

[https://paste.dimdev.org/ipahizoyut.mccrash](url)
