### ISSUE TITLE
Bizarre tombstone behavior

### ISSUE THREAD

**Issue by Galindorf** [WildBamaBoy/minecraft-comes-alive#915]
MCA + Mo'Creatures = a dangerous world for hapless villagers. I've started up a graveyard to remember them by. But tombstones are being super weird. 

1. Craft a tombstone. Works fine. 
2. Place tombstone. Tombstone is placed, and then there is a stack of 2 in your hand.

![screen shot 2017-11-11 at 10 38 09 am](https://user-images.githubusercontent.com/17105217/32691442-3d4aef4c-c6cd-11e7-89b5-f40435146856.png)

3. Place Tombstones out of the stack of 2. They continue to duplicate into the stack. 
![screen shot 2017-11-11 at 10 39 21 am](https://user-images.githubusercontent.com/17105217/32691456-7bbb8958-c6cd-11e7-80e5-85df6bea87a4.png)

4. Mine the tombstones back up, they will not stack in the original stack or with each other. 
![screen shot 2017-11-11 at 10 39 38 am](https://user-images.githubusercontent.com/17105217/32691470-9c53bf28-c6cd-11e7-962d-566ef99c2cdd.png)

5. Place Tombstones from one of the "non-stacking" tombstone items, the duplication begins again.  
![screen shot 2017-11-11 at 10 39 59 am](https://user-images.githubusercontent.com/17105217/32691487-cdf092d6-c6cd-11e7-8c0a-3371a4fe2f60.png)

I ended up with 35+ tombstones from just trying to place a few on the hill~! 

Mods:
forge1.12.2-14.23.0.2495

BetterFoliage-MC1.12-2.1.10
BiomesOPlenty-1.12.2-7.0.1.2298-universal.jar
chococraft_1.12.1-0.9.1.52.jar
CustomMobSpawner-3.11.3.jar
DrZharks MoCreatures Mod-12.0.3.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
journeymap-1.12-5.4.9.jar
JustAFewFish-1.7_for_1.12.jar
Mantle-1.12-1.3.1.21.jar
MCA-1.12.x-5.3.1-universal.jar
Natura-1.12-4.3.0.17.jar
PetBat-1.12.jar
RadixCore-1.12.x-2.2.1-universal.jar
SoundFilters-0.10_for_1.12.jar
TreeChopper-1.12.1-1.2.2.jar

**Comment by WildBamaBoy** [comment]
Odd, will look into this.
