### ISSUE TITLE
Minecraft MCA Glitch

### ISSUE THREAD

**Issue by IHaveAngerIssues** [WildBamaBoy/minecraft-comes-alive#918]
Whenever i make a new singleplayer world i spawn in a village or spawn in villagers by egg they are full on invisible i cant interact with them or anything i can see what theyre saying in chat but cant see where they are. i have tried taking out some mods out of the mod folder and restarting my game but still no hope ;(. I have tried redownloading the mod also but yet still nothing works. i dont know what to do anymore.

**Comment by Sketchysketcher** [comment]
i have the same problem they really need to fix this!

**Comment by WildBamaBoy** [comment]
#917
