### ISSUE TITLE
Invisible?

### ISSUE THREAD

**Issue by Sketchysketcher** [WildBamaBoy/minecraft-comes-alive#919]
So, i downloaded this mod and when i first started up a new world to test it out it seemed fine the crystal ball worked the questions worked, however when i went to a village i didn't see the human villagers or squidward villagers but i saw them talking to me in the chat, they were invisible, i then tried using the female and male villager spawn eggs but they didnt work, so i used normal spawn eggs and they were just invisible, please fix this bug

**Comment by WildBamaBoy** [comment]
#917
