### ISSUE TITLE
Feature Request: Disallow Guards from Marriage

### ISSUE THREAD

**Issue by Galindorf** [WildBamaBoy/minecraft-comes-alive#921]
I was thinking it might be handy to disallow the village-generated guards from marrying. My guards are getting married faster than I can keep track of, and I'd rather that my villagers get married to other 'actual' villagers than the city's protectors. Maybe make it a configuration option, or maybe a "ring of celibacy" you can give to villagers to prevent them from getting married?

**Comment by WildBamaBoy** [comment]
I like the "Ring of Celibacy" idea.
