### ISSUE TITLE
1.10.2 Villagers not spawning in villages

### ISSUE THREAD

**Issue by Mii332** [WildBamaBoy/minecraft-comes-alive#922]
Me and my friend were playing on a custom modpack we created using MCA. everything was fine and normal until she crashed. when that happened, we relaunched the world we were playing on, but the villagers weren't there anymore. we tried loading a few new worlds, both on her end and my end seperately, and we have not gotten any villagers on them. has anyone else encounted this problem? or is there known mods that aren't compatible with Minecraft comes alive? also, we did play on a LAN world together, setup through a gaming platform that is external to Minecraft.

**Comment by WildBamaBoy** [comment]
1.10.2 is not supported
