### ISSUE TITLE
Villagers are purple and black

### ISSUE THREAD

**Issue by GameRKade** [WildBamaBoy/minecraft-comes-alive#923]
I started a creative world, and all the villagers were black and pink. When I used the villager editor on them, the skin selector would just say "Texture:" and nothing more. If I change the job or skin, the game crashes.

I am using: 

Forge 1.12.2-14.23.0.2491
MCA-1.12.x-5.3.1-universal
RadixCore-1.12.x-2.2.1-universal

I have no other mods installed.

![2017-11-23_00 31 51](https://user-images.githubusercontent.com/25556353/33161064-b1fd15c8-cfe6-11e7-9ab7-d334e406bb9c.png)

**Comment by timurall** [comment]
I have the same problem(

**Comment by JEGomorph** [comment]
In your mods folder, take out all other version folders & only leave the 1.12.2 folder. It's the other MinecraftComesAlive jars loading their values for some reason & causing a conflict.

**Comment by timurall** [comment]
Yeah, it works! Also you have to load an old backup without pink and black villagers (possible to kill them), the normal textures will appear only after this operation
