### ISSUE TITLE
Feature Request: Children Variety

### ISSUE THREAD

**Issue by GameRKade** [WildBamaBoy/minecraft-comes-alive#926]
I think that your children should be able to have their own professions. After a certain point of having children, they all begin to look the same, and not have the variety of skins that come with all of the different jobs. This makes it very hard to tell them apart. You'll also end up with plenty of children that only want to trade pumpkins with you instead of iron or wheat and stuff.
![2017-11-23_20 59 21](https://user-images.githubusercontent.com/25556353/33193876-34d72038-d091-11e7-84a3-b57bfef1b63d.png)

As you can see, I have 5 sets of duplicate child skins. If other villagers can have children with professions, players should also be able to. It would add much more variety to a village.

**Comment by WildBamaBoy** [comment]
Player children having their own skins will stay, but we will look into expanding their professions
