### ISSUE TITLE
Minecraft Comes Alive - Invisible villagers from the start. 

### ISSUE THREAD

**Issue by Tirgarde** [WildBamaBoy/minecraft-comes-alive#927]
I downloaded the mod, logged in, created a world and used the crystal but I get a village with villagers I can hear but can't see... Please help.

**Comment by WildBamaBoy** [comment]
#917 
Update your installation of Forge.

**Comment by Tirgarde** [comment]
And could you tell me how I do that exactly? I've never played on the Pc so this is my first time dealing with mods.

**Comment by Tirgarde** [comment]
If the latest edition for Forge is 1.12.2 i have it.

**Comment by WildBamaBoy** [comment]
Get this, it's the current latest version of Forge for 1.12.2: http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.1.2554/forge-1.12.2-14.23.1.2554-installer.jar

You can see all of Forge's downloads/versions here: http://files.minecraftforge.net/
