### ISSUE TITLE
Exception loading model/blockstate

### ISSUE THREAD

**Issue by ghost** [WildBamaBoy/minecraft-comes-alive#928]
https://pastebin.com/6yRVwyu7

> Caused by: java.io.FileNotFoundException: mca:blockstates/memorial.json

Minecraft: 1.12.2
Forge: 14.23.1.2554
MCA: 5.3.1
RadixCore: 2.2.1

**Comment by Demodian** [comment]
Does it fail with Forge build 2491?

**Comment by ghost** [comment]
Just tested it with only MCA/RadixCore and Forge 14.23.0.2491 installed. The error stays:

https://pastebin.com/ZsxVkJtG

**Comment by Demodian** [comment]
Before WildBamaBoy asks for it, can you post the full crash log?

**Comment by ghost** [comment]
Please have a look at:

https://github.com/MinecraftForge/MinecraftForge/issues/4567

I'll wait until a forge dev comments on that.

**Comment by ghost** [comment]
Solutions so far:

> He could simply add an empty json and the error should be away.

> If it does not need one, set the block to have no model like vanilla barriers do (It's one of the methods on Block)

**Comment by WildBamaBoy** [comment]
This is a non-issue

**Comment by ghost** [comment]
It **is** an issue. You know this because it's called an ERROR in the log. There's a reason for it to be an error, and it can be fixed easily.

But people like you, who just base the quality of their mods on "no error ingame = everything ok" will never understand it, I guess.

**Comment by WildBamaBoy** [comment]
Dunno why you're so upset over this. Let me put it this way - although it **is** an error printed to the log, it has no effect on me, you, or anyone else using MCA. Therefore, I'm not wasting my time attempting to fix it.

If you want to blame something, blame bad design decisions by Mojang, the toxic community around Forge, and overall poor documentation.
