### ISSUE TITLE
Crash when placing Toy Doll (object for dead daughter)

### ISSUE THREAD

**Issue by TheLunarArtemis** [WildBamaBoy/minecraft-comes-alive#932]
Now everytime I load up the world, I cannot get in properly because it crashes everytime I look at the doll object.
![image](https://user-images.githubusercontent.com/17260497/33692479-58d44068-daa2-11e7-9c68-a8a9db9c8d2c.png)

It won't let me view the full crash report, nothing happens when I click "view crash report", so thats all I can give you.

Minecraft: 1.12.2
Forge: 14.23.1.2555
MCA: 5.3.1
RadixCore: 2.2.1
Other mods I'm using:
-Animania
-Backpacks!
-CrayfishFurnitureMod
-CraftStudio
-GuideAPI
-HWYLA
-Level Up!
-Optifine
-SilentLib
-SilentGems
-SophisticatedWolves
-TreeChopper
-Vampirism
-VampirismIntegrations
-XaerosMinimap
-AdvancedXRay

How to Reproduce (in case you want to test it yourself):
-Obtain the toy Doll or (i think? idk I havent been able to test yet) toy Train objects after your child dies. 
-Place it down (For me, it crashed immediately at this point)
-Load up the world, and you should crash if you still are looking at the object, unless you moved your mouse away just before it loads.

**Comment by WildBamaBoy** [comment]
Will attempt to reproduce this
