### ISSUE TITLE
Question/Suggestion about crystal ball

### ISSUE THREAD

**Issue by FireController1847** [WildBamaBoy/minecraft-comes-alive#941]
I am a modpack maker, and I'm looking to include this in the modpack Yogbox 2.0. I only have one issue with the mod, though, and that's that there's no way to disable the auto-structures that have to do with the crystal ball. I _do not_ want my players being able to generate a building by choosing one of the options from the crystal ball, but I _do_ want my players to be able to chose their name, gender, and preference. Is there any possible way to disable this, or could get this added to the config?

(I'm talking about the I Live Alone, I Have A Family, I Live In A Village, None Of These screen). I want to default it to "None Of These" so it forces the player to find a village.

**Comment by LittLord67** [comment]
No, Finding a village is hard and it would just be filled with Vanilla Villagers with the huh sounds and That wouldn't be great.

**Comment by FireController1847** [comment]
Lol, calm down. No, it wouldn't just be filled with vanilla villagers if you've enabled the config option that replaces vanilla villagers. Secondly, my modpack is about adventure not being able to just suddenly spawn in an entire village. It would be a configuration option, disabled by default.

**Comment by LittLord67** [comment]
Oh, Makes sense. Sorry
