### ISSUE TITLE
My kids aren't doing their work

### ISSUE THREAD

**Issue by Mrf00zy** [WildBamaBoy/minecraft-comes-alive#942]
When i assign my kids a job all they do is either move freely and do nothing or say their inventory is full, and with the woodcutting all they do is remove the leaves but not cut the wood

**Comment by LittLord67** [comment]
Same! This mod Is so buggy but its a good mod. I hope the creator fixes this issue. Btw I have another glitch where my kids grow up, get married, and when they have kids the baby just stays in my sons wife's hand all day. Does this happen to you or is it just me?

**Comment by Galindorf** [comment]
The only real chores I have gotten them to do with success is farming (wheat only though) and hunting (kill mode). For mining, I get them to create a mine but the actual work is spotty. I make their 'home' in the mine and then cover the mine to protect it from monsters.
