### ISSUE TITLE
Villagers babies wont grow!

### ISSUE THREAD

**Issue by LittLord67** [WildBamaBoy/minecraft-comes-alive#943]
I have a kid, he grew Up and I got him married. I gave him cake and his wife got a baby. But the baby never grows, It just stays in her hand all day. I've been playing Minecraft Comes Alive for About 3 days and Nothing happened. I can't Create a "Generation" If I can't get the cycle to repeat indefinitely. This also happens with Unrelated villagers, Babies stay in hands all day.

**Comment by LittLord67** [comment]
I tried every single version of Minecraft comes alive just to be clear.

**Comment by emwuzx** [comment]
I'm also having this issue. Babies just stay in villagers' hands.

**Comment by LittLord67** [comment]
Its really annoying

**Comment by emwuzx** [comment]
Try adjusting the story progression rate. The default setting is 20 and it helped to lower it to 5 or so. My villagers were able to get married, have kids, etc. after I changed that setting; I'm just letting them naturally do it for the most part, with no arranging, etc.

**Comment by sawatari01** [comment]
My baby can not be a child. It is already over so.
![image](https://user-images.githubusercontent.com/32459477/35894080-74b9edfe-0bf4-11e8-9088-d539bc02b56e.png)

**Comment by BrookWithAnE** [comment]
How do I change the progression rate? I am having the same problem I think..

**Comment by LittLord67** [comment]
Go to mod options then The mod and go to the settings and stuff
