### ISSUE TITLE
3 Bugs in MCA 1.12.2

### ISSUE THREAD

**Issue by coryhiller** [WildBamaBoy/minecraft-comes-alive#945]
1.  It seems that in the latest 1.12.2 version 95% of villagers are farmers and all have the same 3 or 4 trades.  There are no weapon smiths or armor smiths and no librarians also clerics are really hard to find which is really annoying when it seems that you start off the game married apparently. 

2. In every game I've started when it comes time to "pop the question" the woman of my dreams tells me I'm already married. So I have to go find a cleric and get divorced from my ghost spouse.  Then when it comes time for wedding bells my bride to be tells me she is already married!!!  Normally this would be handled by a brief or fight or a quick 'follow me' walk through zombie infested woods, but you can't deal with someone that doesn't exist.  So for now we have to have our children out of wedlock.  Thankfully Minecraft villagers aren't Catholic!!

3.  Wondering what is up with all the girls with guy names and vice versa in the new 1.12.2??  It seems that approximately 80% of the females in the game have male name.  The percentage of guys having female names is probably around 40%.  Nothing is more disappointing that finally meeting that really good looking girl in the local library only to find out her name is Guy or Karl or Kenneth.  I want to marry (well get engaged to, because everyone is already married) a Jessica or an Amanda so, a girl with a guy's name is sort of a deal breaker.  Is there a way to edit the villager name lists?

**Comment by LittLord67** [comment]
Commenting on number 3. Yes, there is a way you can change the villagers names. Go to creative mode. Search up "Villager editor" and a book sort of thing will pop up. now equip it and right click on the person you want to change.

Your Friend,
LittLord67

**Comment by SDPhantom** [comment]
Number 2 is a an existing issue. #902

**Comment by axellira** [comment]
I am also experiencing both numbers 1 and 2.

**Comment by allensutton** [comment]
all of the villagers always turn out completely pitch black with pink arms
