### ISSUE TITLE
Villagers teleport into walls.

### ISSUE THREAD

**Issue by froggruntking9** [WildBamaBoy/minecraft-comes-alive#946]
Because of the home point teleportation system, I have lost more villagers teleporting into walls and suffocating than all outside forces combined. I would appreciate a way to make the teleportation system optional, or villagers with enough intelligence to just walk out of the wall.

**Comment by Galindorf** [comment]
What I do, is give them homes with space, make sure their beds have at least 1 block of space all around, and set their home points myself in the *middle* of the room. Saved a lot of villagers that way (and zombies don't punch them through the walls)
