### ISSUE TITLE
Natural spawning villagers have no textures

### ISSUE THREAD

**Issue by Snowywar** [WildBamaBoy/minecraft-comes-alive#949]
Ok, so I am not sure if it's only me, but whenever I find a nature village in my world with MCA, all of the villagers in it will have no textures. Whenever I choose the option live in a village or I just spawn in some villagers, they all have textures. The game will also crash if I try to change the skins with the villager editor so I'm not sure what to do. Any help?

Also, I have no other visions of the game in the mod folder, so I'm not sure what to do.

**Comment by WildBamaBoy** [comment]
Unable to reproduce this
