### ISSUE TITLE
Game Crashes when loading a full npc inventory!!

### ISSUE THREAD

**Issue by Wrathverse** [WildBamaBoy/minecraft-comes-alive#953]
I was filling up the inventory of an npc, both waifu & kids, game crashed when the inventory was full and i shift clicked an item.

**Comment by WildBamaBoy** [comment]
Provide a crash report

**Comment by SanjivanM** [comment]
Same happens for me, except I shift-clicked from a NPC inventory to mine.  Crash Report attached
[crash-2019-06-25_16.51.19-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/3327697/crash-2019-06-25_16.51.19-client.txt)
[crash-2019-06-25_17.32.07-client.txt](https://github.com/WildBamaBoy/minecraft-comes-alive/files/3327698/crash-2019-06-25_17.32.07-client.txt)
