### ISSUE TITLE
NPC's love life in 1.12.2

### ISSUE THREAD

**Issue by Link0102** [WildBamaBoy/minecraft-comes-alive#955]
After a long day of chopping down trees, I come back to my house to find my children and... one more. Weird, I didn't remember them. I right-click on the babie and the parents are: my son and daughter.
I guess that makes some sense in the story development standpoint, villagers probably want to marry the others who live near them, but... their siblings? I would just like to know if that is a bug or an actual feature.

**Comment by Galindorf** [comment]
haha it's a feature... they don't recognize 'siblings.' For a while I kept a lineage chart for fun and it got pretty complicated

**Comment by Link0102** [comment]
xD Thanks for telling me that. You also gave me a nice idea with the "lineage chart".
