### ISSUE TITLE
Married? How!?

### ISSUE THREAD

**Issue by ChewyCooking** [WildBamaBoy/minecraft-comes-alive#959]
I went up to one of the villagers and presented her with an engagement ring, but she said that I was already married...
It's most likely because I made a wedding ring first...
Are there any solutions?

**Comment by NotAVerb** [comment]
You're probably married to "?".
You can work around this bug by finding a priest and divorcing "?".

**Comment by WildBamaBoy** [comment]
Ensure you have the latest MCA 1.12.2
