### ISSUE TITLE
MCA Crashes When right clicking broken ring to revive villager - 1/27/18

### ISSUE THREAD

**Issue by fantaphantom** [WildBamaBoy/minecraft-comes-alive#960]
Hello people, today I ran into a new issue. When I was trying to use the staff of life on my wife's broken ring it crashes. Shortly after the whole world is corrupted and I cant use it without crashing. I hope I am using the staff correctly, please help ASAP.

**Comment by WildBamaBoy** [comment]
Provide a crash report

**Comment by mrskeisha** [comment]
I'm having the same issue and I really don't know what to do. I used placed the ring down on the ground after using the staff of life and my game completely crashed. Now every time I re-enter my world it immediately crashes. Heres the crash report, I'd really like to fix this issue: 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LMRECoremod (LittleMaidMob-Mod-1.12.2.jar)
  CreativePatchingLoader (CreativeCore-1.12.2.jar)
  MovingWorldCore (MovingWorld-Mod-1.12.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 5/11/19 8:15 PM
Description: Unexpected error

java.lang.NullPointerException: mca:memorial from mod Minecraft Comes Alive returned a null ItemStack in getPickBlock(...). Please report this to them.
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:64)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:44)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:64)
	at mcp.mobius.waila.api.impl.DataAccessorCommon.set(DataAccessorCommon.java:44)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MrsKeishasDead'/2653, l='MpServer', x=3.09, y=69.91, z=7081.45]]
	Chunk stats: MultiplayerChunkCache: 164, 164
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (220,64,252), Chunk: (at 12,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3163079 game time, 3989586 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 125 total; [EntityItemFrame['entity.ItemFrame.name'/2816, l='MpServer', x=7.50, y=67.50, z=7065.03], EntityItemFrame['entity.ItemFrame.name'/2817, l='MpServer', x=7.50, y=66.50, z=7065.03], EntityItemFrame['entity.ItemFrame.name'/2818, l='MpServer', x=7.50, y=65.50, z=7065.03], EntityItemFrame['entity.ItemFrame.name'/2819, l='MpServer', x=8.97, y=67.50, z=7067.50], EntityItemFrame['entity.ItemFrame.name'/2820, l='MpServer', x=8.97, y=66.50, z=7067.50], EntityItemFrame['entity.ItemFrame.name'/2821, l='MpServer', x=8.97, y=65.50, z=7067.50], EntityItemFrame['entity.ItemFrame.name'/2822, l='MpServer', x=6.50, y=67.50, z=7069.97], EntityItemFrame['entity.ItemFrame.name'/2823, l='MpServer', x=5.03, y=65.50, z=7066.50], EntityItemFrame['entity.ItemFrame.name'/2824, l='MpServer', x=5.03, y=66.50, z=7066.50], EntityItemFrame['entity.ItemFrame.name'/2825, l='MpServer', x=5.03, y=65.50, z=7068.50], EntityItemFrame['entity.ItemFrame.name'/2826, l='MpServer', x=5.03, y=66.50, z=7068.50], EntityItemFrame['entity.ItemFrame.name'/2827, l='MpServer', x=5.03, y=67.50, z=7068.50], EntityItemFrame['entity.ItemFrame.name'/2828, l='MpServer', x=5.03, y=67.50, z=7066.50], MoCEntityKittyBed['entity.mocreatures:kittybed.name'/2829, l='MpServer', x=9.18, y=74.00, z=7071.82], EntityItemFrame['entity.ItemFrame.name'/2830, l='MpServer', x=12.03, y=71.50, z=7071.50], EntityItemFrame['entity.ItemFrame.name'/2831, l='MpServer', x=6.50, y=65.50, z=7069.97], EntityItemFrame['entity.ItemFrame.name'/2832, l='MpServer', x=6.50, y=66.50, z=7069.97], MoCEntityGreenOgre['GreenOgre'/2833, l='MpServer', x=46.50, y=30.00, z=7026.50], MoCEntityMantaRay['MantaRay'/2846, l='MpServer', x=-53.86, y=59.77, z=7140.32], MoCEntityFishy['Fishy'/2847, l='MpServer', x=-52.12, y=61.95, z=7151.07], MoCEntityTurtle['Turtle'/2848, l='MpServer', x=-67.73, y=60.80, z=7155.51], MoCEntityMaggot['Maggot'/2849, l='MpServer', x=-17.17, y=66.00, z=7105.71], MoCEntityGoat['Goat'/2850, l='MpServer', x=-33.38, y=62.64, z=7126.94], MoCEntityFly['Fly'/2851, l='MpServer', x=23.79, y=68.00, z=7070.04], EntityZombie['Zombie'/2852, l='MpServer', x=54.25, y=30.00, z=7033.45], EntityZombie['Zombie'/2853, l='MpServer', x=55.50, y=16.00, z=7024.50], EntityZombie['Zombie'/2854, l='MpServer', x=50.50, y=33.00, z=7026.30], EntityCreeper['Creeper'/2855, l='MpServer', x=59.50, y=42.00, z=7032.50], EntityCreeper['Creeper'/2856, l='MpServer', x=55.50, y=49.00, z=7032.50], MoCEntityDeer['Deer'/2857, l='MpServer', x=61.25, y=68.00, z=7038.20], MoCEntityMole['Mole'/2866, l='MpServer', x=-20.78, y=62.84, z=7133.36], MoCEntityFox['Fox'/2867, l='MpServer', x=-27.44, y=63.00, z=7122.27], MoCEntityTurtle['Turtle'/2868, l='MpServer', x=-10.33, y=63.00, z=7110.30], EntitySkeleton['Skeleton'/2869, l='MpServer', x=23.48, y=56.00, z=7083.21], EntityEnderman['Enderman'/2870, l='MpServer', x=24.73, y=56.00, z=7076.69], EntityItem['item.item.item_explorer'/2871, l='MpServer', x=17.91, y=69.00, z=7085.04], EntitySkeleton['Skeleton'/2878, l='MpServer', x=29.28, y=65.00, z=7100.53], MoCEntityMaggot['Maggot'/2879, l='MpServer', x=1.18, y=64.00, z=7112.62], MoCEntityMaggot['Maggot'/2880, l='MpServer', x=57.48, y=65.00, z=7056.43], EntityBoat['Boat'/2891, l='MpServer', x=-0.71, y=62.52, z=7137.33], EntityBoat['Boat'/2892, l='MpServer', x=-2.95, y=62.52, z=7137.30], MoCEntityShark['Shark'/2893, l='MpServer', x=10.15, y=60.03, z=7130.85], MoCEntityMantaRay['MantaRay'/2894, l='MpServer', x=7.90, y=61.00, z=7130.10], EntityBoat['Boat'/2901, l='MpServer', x=3.83, y=62.52, z=7139.69], MoCEntityMaggot['Maggot'/2904, l='MpServer', x=58.87, y=68.00, z=7093.45], MoCEntityLitterBox['entity.mocreatures:litterbox.name'/2654, l='MpServer', x=6.35, y=74.00, z=7075.70], EntityChicken['Chicken'/2910, l='MpServer', x=40.40, y=63.00, z=7132.88], EntityLittleMaid['entity.LittleMaid.name'/2655, l='MpServer', x=10.75, y=70.00, z=7075.81], EntityItem['item.item.egg'/2911, l='MpServer', x=35.16, y=63.00, z=7132.60], EntitySheep['Sheep'/2912, l='MpServer', x=25.45, y=63.00, z=7137.55], MoCEntityKitty['Kitty'/2657, l='MpServer', x=7.15, y=70.00, z=7075.65], MoCEntityGrizzlyBear['GrizzlyBear'/2913, l='MpServer', x=17.89, y=62.64, z=7146.88], EntityPlayerSP['MrsKeishasDead'/2653, l='MpServer', x=3.09, y=69.91, z=7081.45], EntityChicken['Chicken'/2663, l='MpServer', x=49.40, y=64.00, z=7152.84], MoCEntityGoldFish['GoldFish'/2922, l='MpServer', x=58.53, y=61.68, z=7115.85], MoCEntityRaccoon['Raccoon'/2923, l='MpServer', x=56.68, y=62.82, z=7114.70], MoCEntitySnake['Snake'/2924, l='MpServer', x=60.07, y=62.49, z=7105.30], EntityChicken['Chicken'/2938, l='MpServer', x=45.82, y=64.00, z=7147.52], EntityPig['Pig'/2939, l='MpServer', x=43.67, y=64.00, z=7140.25], EntityDeer['Deer'/2686, l='MpServer', x=-36.01, y=63.00, z=7005.50], MoCEntityCrab['Crab'/2690, l='MpServer', x=-51.49, y=52.00, z=7031.54], MoCEntityDeer['Deer'/2692, l='MpServer', x=-29.68, y=63.00, z=7001.97], MoCEntityMouse['Mouse'/2694, l='MpServer', x=-43.48, y=63.17, z=7016.12], MoCEntityDeer['Deer'/2695, l='MpServer', x=-34.42, y=62.65, z=7011.77], MoCEntityCrab['Crab'/2952, l='MpServer', x=59.63, y=61.00, z=7140.22], EntityChicken['Chicken'/2953, l='MpServer', x=49.48, y=63.00, z=7138.16], EntityItem['item.item.egg'/2954, l='MpServer', x=50.32, y=63.00, z=7139.05], MoCEntityGoat['Goat'/2705, l='MpServer', x=-35.77, y=62.64, z=7028.81], MoCEntityCrab['Crab'/2708, l='MpServer', x=-30.70, y=57.00, z=7013.59], GoatEntity['Goat'/2723, l='MpServer', x=-6.10, y=75.00, z=7019.30], EntityCow['Cow'/2724, l='MpServer', x=-13.55, y=75.00, z=7019.45], GoatEntity['Goat'/2725, l='MpServer', x=-9.93, y=75.00, z=7021.34], EntityPig['Pig'/2726, l='MpServer', x=-8.75, y=75.00, z=7020.44], EntityCow['Cow'/2727, l='MpServer', x=-13.55, y=75.00, z=7023.03], GoatEntity['Goat'/2728, l='MpServer', x=-9.96, y=75.00, z=7022.07], EntitySheep['Sheep'/2729, l='MpServer', x=-4.28, y=75.00, z=7019.45], EntityCow['Cow'/2730, l='MpServer', x=-12.67, y=75.00, z=7023.93], EntitySheep['Sheep'/2731, l='MpServer', x=-1.45, y=75.00, z=7019.45], EntityCow['Cow'/2732, l='MpServer', x=-11.45, y=75.00, z=7023.93], EntityCow['Cow'/2733, l='MpServer', x=-11.07, y=75.00, z=7020.45], EntityPig['Pig'/2734, l='MpServer', x=-5.07, y=75.00, z=7021.93], EntityCow['Cow'/2735, l='MpServer', x=-11.07, y=75.00, z=7023.01], EntityPig['Pig'/2736, l='MpServer', x=-5.38, y=75.00, z=7020.07], EntityCow['Cow'/2737, l='MpServer', x=-12.12, y=75.00, z=7023.08], GoatEntity['Goat'/2738, l='MpServer', x=-5.02, y=75.00, z=7020.86], EntityCow['Cow'/2739, l='MpServer', x=-12.68, y=75.00, z=7022.02], EntityCow['Cow'/2740, l='MpServer', x=-13.55, y=75.00, z=7023.93], EntityCow['Cow'/2741, l='MpServer', x=-12.57, y=75.00, z=7020.47], EntitySheep['Sheep'/2742, l='MpServer', x=-3.51, y=75.00, z=7023.29], EntitySheep['Sheep'/2743, l='MpServer', x=-2.43, y=75.00, z=7019.45], EntityPig['Pig'/2744, l='MpServer', x=-6.09, y=75.00, z=7021.53], EntityCow['Cow'/2745, l='MpServer', x=-11.07, y=75.00, z=7019.45], EntityCow['Cow'/2746, l='MpServer', x=-12.03, y=75.00, z=7021.16], EntityCow['Cow'/2747, l='MpServer', x=-13.55, y=75.00, z=7020.34], EntityCow['Cow'/2748, l='MpServer', x=-12.03, y=75.00, z=7019.45], EntityCow['Cow'/2749, l='MpServer', x=-11.07, y=75.00, z=7022.08], EntityCow['Cow'/2750, l='MpServer', x=-13.55, y=75.00, z=7021.33], EntitySheep['Sheep'/2751, l='MpServer', x=-1.50, y=75.00, z=7020.51], EntityItem['item.tile.cloth.white'/2752, l='MpServer', x=-1.13, y=75.00, z=7021.71], EntityItem['item.item.minecraft:mutton'/2753, l='MpServer', x=-1.82, y=75.00, z=7021.60], EntityCreeper['Creeper'/2764, l='MpServer', x=-38.50, y=16.00, z=7058.50], EntityWolf['Wolf'/2765, l='MpServer', x=-37.45, y=66.00, z=7059.45], EntityPig['Pig'/2766, l='MpServer', x=0.67, y=75.00, z=7022.50], MoCEntityAnt['Ant'/2767, l='MpServer', x=-13.42, y=75.00, z=7025.96], EntityTurkey['Turkey'/2768, l='MpServer', x=-11.42, y=75.00, z=7032.55], MoCEntityHorse['WildHorse'/2769, l='MpServer', x=-13.01, y=75.00, z=7030.02], EntityZombie['Zombie'/2780, l='MpServer', x=-29.50, y=15.00, z=7056.50], MoCEntitySnail['Snail'/2781, l='MpServer', x=-24.85, y=64.00, z=7070.85], MoCEntitySnail['Snail'/2783, l='MpServer', x=15.18, y=69.00, z=7031.79], MoCEntityFly['Fly'/2784, l='MpServer', x=14.54, y=70.00, z=7027.73], MoCEntityMantaRay['MantaRay'/2787, l='MpServer', x=-69.16, y=58.81, z=7125.63], MoCEntityGoat['Goat'/2793, l='MpServer', x=-38.04, y=62.59, z=7093.12], MoCEntityFishy['Fishy'/2794, l='MpServer', x=-37.28, y=61.97, z=7095.64], MoCEntityGoat['Goat'/2795, l='MpServer', x=-29.58, y=68.00, z=7083.25], EntityItem['item.item.string'/2796, l='MpServer', x=1.19, y=45.00, z=7046.13], MoCEntitySnail['Snail'/2797, l='MpServer', x=14.33, y=65.00, z=7044.29], EntityCreeper['Creeper'/2798, l='MpServer', x=59.52, y=45.00, z=7004.08], MoCEntityAnt['Ant'/2799, l='MpServer', x=47.96, y=72.00, z=7018.46], GoatEntity['Goat'/2800, l='MpServer', x=38.50, y=68.00, z=7017.90], MoCEntitySnake['Snake'/2810, l='MpServer', x=-35.10, y=63.00, z=7117.16], MoCEntityAngelFish['AngelFish'/2811, l='MpServer', x=-47.99, y=61.40, z=7105.65], MoCEntitySnail['Snail'/2812, l='MpServer', x=-18.13, y=68.00, z=7099.41], EntityItemFrame['entity.ItemFrame.name'/2813, l='MpServer', x=6.50, y=65.50, z=7065.03], EntityItemFrame['entity.ItemFrame.name'/2814, l='MpServer', x=6.50, y=66.50, z=7065.03], EntityItemFrame['entity.ItemFrame.name'/2815, l='MpServer', x=6.50, y=67.50, z=7065.03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 228051344 bytes (217 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 102
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                           | Version         | Source                                        | Signature                                |
	|:--------- |:-------------------------------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                                    | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                                          | 9.42            | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                                          | 8.0.99.99       | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                        | 14.23.4.2705    | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy                            | 1.0.0           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | OldModelLoader                               | 8.1.4.132       | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | littletilescore                              | 1.0.0           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                 | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | advancedcombat                               | 1.1.2           | advancedcombat-1.1.2-[1.12].jar               | None                                     |
	| UCHIJAAAA | baubles                                      | 1.5.2           | Baubles-Mod-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | biomesoplenty                                | 7.0.1.2399      | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
	| UCHIJAAAA | blockcraftery                                | 1.12.2-1.1.0    | Blockcraftery-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | corerm                                       | 1.3.0           | RikMuldsCore-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | camping                                      | 2.4.0           | Camping-Mod-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | creativecore                                 | 1.9.9           | CreativeCore-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | customspawner                                | 3.11.4          | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | ptrmodellib                                  | 1.0.2           | PTRLib-1.0.2.jar                              | None                                     |
	| UCHIJAAAA | props                                        | 2.6.1           | Decocraft-2.6.1_1.12.2.jar                    | None                                     |
	| UCHIJAAAA | net.blacklab.lib                             | 6.1.5.8         | EBlib-1.12.2.jar                              | None                                     |
	| UCHIJAAAA | extrautils2                                  | 1.0             | Extra-Utilities-Mod-1.12.2.jar                | None                                     |
	| UCHIJAAAA | familiarfauna                                | 1.0.10          | FamiliarFauna-1.12.2-1.0.10.jar               | None                                     |
	| UCHIJAAAA | harvestcraft                                 | 1.12.2a         | HarvestCraft-Mod-1.12.1.jar                   | None                                     |
	| UCHIJAAAA | waila                                        | 1.8.26          | Hwyla-Mod-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | ism                                          | 2.0.0 MC-1.12.2 | Instant-Structures-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | jei                                          | 4.11.0.212      | jei_1.12.2-4.11.0.212.jar                     | None                                     |
	| UCHIJAAAA | journeymap                                   | 1.12.2-5.5.2    | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | lmreengaged                                  | 8.1.4.132       | LittleMaidMob-Mod-1.12.2.jar                  | None                                     |
	| UCHIJAAAA | littletiles                                  | 1.5.0           | LittleTiles-Mod-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | locks                                        | 2.2.1           | Locks-2.2.1.jar                               | None                                     |
	| UCHIJAAAA | radixcore                                    | 1.12.x-2.2.1    | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| UCHIJAAAA | mca                                          | 1.12.2-5.3.1    | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
	| UCHIJAAAA | mocreatures                                  | 12.0.5          | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | movingworld                                  | 1.12-6.342      | MovingWorld-Mod-1.12.jar                      | None                                     |
	| UCHIJAAAA | naturescompass                               | 1.5.1           | NaturesCompass-1.12.2-1.5.1.jar               | None                                     |
	| UCHIJAAAA | prefab                                       | 1.3.0.25        | Prefab-Mod-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | secretroomsmod                               | 5.3.2           | Secret-Rooms-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | lteleporters                                 | 1.12.2-3.0.2    | simpleteleporters-1.12.2-3.0.2.jar            | None                                     |
	| UCHIJAAAA | thaumcraft                                   | 6.1.BETA23      | Thaumcraft-1.12.2-6.1.BETA23.jar              | None                                     |
	| UCHIJAAAA | bspkrscore                                   | at_0.9          | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UCHIJAAAA | treecapitator                                | at_0.9          | TreeCapitator-Mod-1.12.jar                    | None                                     |
	| UCHIJAAAA | llibrary                                     | 1.7.15          | LLibrary-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCHIJAAAA | jurassicraft                                 | 2.1.17          | Dinosaurs-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | mysticallib                                  | 1.12.2-1.0.0    | MysticalLib-1.12.2.jar                        | None                                     |

	Loaded coremods (and transformers): 
LMRECoremod (LittleMaidMob-Mod-1.12.2.jar)
  net.blacklab.lmr.util.coremod.Transformer
CreativePatchingLoader (CreativeCore-1.12.2.jar)
  
MovingWorldCore (MovingWorld-Mod-1.12.jar)
  
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.36.19' Renderer: 'Intel(R) HD Graphics 6000'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.2
	OpenGL: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-10.36.19, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Dandelion Resource Pack 1 (incompatible), dandelionv2010976106
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
