### ISSUE TITLE
Marriage Problem MCA 5.3.1 MC 1.12.2

### ISSUE THREAD

**Issue by GoldInvestor1006** [WildBamaBoy/minecraft-comes-alive#962]
On MCA 5.3.1, Minecraft 1.12.2 the game marks me as married when I spawn.

**Comment by WildBamaBoy** [comment]
Should've been fixed, will investigate more

**Comment by GoldInvestor1006** [comment]
I know!
I was excited when I thought they fixed this glitch, then it happened again.

**Comment by Pedil** [comment]
i have exctly the same problem

**Comment by Pedil** [comment]
help please!
