### ISSUE TITLE
Something spamming in server log killing server

### ISSUE THREAD

**Issue by twistedtoe** [WildBamaBoy/minecraft-comes-alive#966]
I loaded up my 1.12.2 server with mca and every 30 seconds or so, this gets spammed in the server log, this is shortened, theres about a thousand lines at a time, and it makes the server unresponsive for over 15 seconds at a time. any ideas?

https://gist.github.com/anonymous/26b2e71283e9476d8ae2add539f307ae

**Comment by Kowantify** [comment]
do u have the most recent version of MCA and Radix Core? - (am not associated with MCA) - I've never had this issue and i play mca server really frequently, I only have issues with loading villlages as i pass them in server as it crashes. but i've never had my server do that and I have 135 mods

**Comment by Kowantify** [comment]
can u also get a full crash log plz. itll help a ton, and it can help the mod developer fix this issue if there is one on his end

**Comment by twistedtoe** [comment]
Yes the most recent versions of both. I can't get a crash log because there technically wasn't a crash, but when that spams in the server log a thousand times a pop, the server is unresponsive for like 15 seconds and it happens about every 30 seconds

**Comment by DarkMatterXCIX** [comment]
can u copy your server log when it does this and paste it into Pastebin website, and put the link here>

**Comment by Kowantify** [comment]
I wish I could help more as i've used this mod a ton, but evne idk where the mod maker is WildBamaBoy, hopefully he comes back soon and releases a fix for issues, i love this mod and i know u do to. I havn't ran into this issue, have u allocated more ram to your server, and what are your system specs?

**Comment by Kowantify** [comment]
also do you have a good internet speed?

**Comment by twistedtoe** [comment]
The server has 5Gigs allocated, and is only using around 60%. It's not an internet issue. Im actually connected to it via LAN right now. that message spams in the server about 1000x a minute. not an exaggeration. it makes the server unresponsive until it times my client out.

**Comment by Kowantify** [comment]
Hopefully the mod maker comes back with a update... it's driving me nuts waiting for an update 

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 2, 2018 at 2:13 PM, twistedtoe<notifications@github.com> wrote:   
The server has 5Gigs allocated, and is only using around 60%. It's not an internet issue. Im actually connected to it via LAN right now. that message spams in the server about 1000x a minute. not an exaggeration. it makes the server unresponsive until it times my client out.

**Comment by WildBamaBoy** [comment]
Aware of several issues with MCA 1.12.2 on servers. Looking to investigate this soon.

**Comment by Kowantify** [comment]
Finally!!! Please fiixxxxx
