### ISSUE TITLE
Minecraft Comes Alive Marrige Problem?

### ISSUE THREAD

**Issue by BrookWithAnE** [WildBamaBoy/minecraft-comes-alive#969]
For some reason I am already married to somebody in Minecraft Comes Alive. This is my first day playing. There is no priest and the villager editor has no priest option. I spawned males and there were no priests, I need help please!

**Comment by Galindorf** [comment]
Hey Brook(e) ! The Villager editor designation you're looking for is "Cleric." They get called "priests" a lot, but they are actually Clerics. See if that help you!
