### ISSUE TITLE
Server Crash on Trading

### ISSUE THREAD

**Issue by Fently** [WildBamaBoy/minecraft-comes-alive#971]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.132.jar)
  SpongeCoremod (spongeforge-1.12.2-2586-7.1.0-BETA-2890.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 10/02/18 00:20
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.NullPointerException
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:663)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1854)
	at net.minecraft.entity.passive.EntityVillager.func_70934_b(EntityVillager.java:651)
	at net.minecraft.entity.player.EntityPlayerMP.func_180472_a(EntityPlayerMP.java:923)
	at mca.packets.PacketInteract.processOnGameThread(PacketInteract.java:161)
	at mca.packets.PacketInteract.processOnGameThread(PacketInteract.java:46)
	at radixcore.modules.net.AbstractPacketHandler.processPackets(AbstractPacketHandler.java:174)
	at radixcore.core.RadixEvents.serverTickEventHandler(RadixEvents.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_125_RadixEvents_serverTickEventHandler_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:663)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:4013)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.76-xxxx-std-ipv6-64-hz1000
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 825372200 bytes (787 MB) / 1780576256 bytes (1698 MB) up to 6227755008 bytes (5939 MB)
	JVM Flags: 20 total; -Xincgc -XX:+UseParNewGC -XX:MaxPermSize=256M -XX:NewRatio=2 -XX:CMSFullGCsBeforeCompaction=1 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=2048 -XX:+CMSParallelRemarkEnabled -XX:+DisableExplicitGC -Xnoclassgc -Xoss4M -Xss4M -XX:+UseFastAccessorMethods -XX:CMSInitiatingOccupancyFraction=90 -XX:UseSSE=4 -XX:+UseCMSCompactAtFullCollection -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -Xmx6144M -Xms512M
	IntCache: cache: 6, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2613 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                     | Source                                          | Signature                                |
	|:--------- |:------------------- |:--------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                      | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                        | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99                   | forge-1.12.2-14.23.2.2613.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.2.2613                | forge-1.12.2-14.23.2.2613.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |                             | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | spongeapi           | 7.1.0-SNAPSHOT-dcd7174      | spongeforge-1.12.2-2586-7.1.0-BETA-2890.jar     | None                                     |
	| UCHIJAAAA | sponge              | 1.12.2-2586-7.1.0-BETA-2890 | spongeforge-1.12.2-2586-7.1.0-BETA-2890.jar     | None                                     |
	| UCHIJAAAA | nucleus             | 1.2.2-S7.0                  | [PLUGIN] Nucleus-1.2.2-S7.0-MC1.12.2-plugin.jar | None                                     |
	| UCHIJAAAA | magibridge          | 2.4.2                       | [PLUGIN] MagiBridge-2.4.2.jar                   | None                                     |
	| UCHIJAAAA | appliedenergistics2 | rv5-stable-8                | appliedenergistics2-rv5-stable-8.jar            | None                                     |
	| UCHIJAAAA | chiselsandbits      | 14.13                       | chiselsandbits-14.13.jar                        | None                                     |
	| UCHIJAAAA | jei                 | 4.8.5.150                   | jei_1.12.2-4.8.5.150.jar                        | None                                     |
	| UCHIJAAAA | forestry            | 5.8.0.242                   | forestry_1.12.2-5.8.0.242.jar                   | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.132                   | GalacticraftCore-1.12.2-4.0.1.132.jar           | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.132                   | Galacticraft-Planets-1.12.2-4.0.1.132.jar       | None                                     |
	| UCHIJAAAA | radixcore           | 1.12.x-2.2.1                | RadixCore-1.12.x-2.2.1-universal.jar            | None                                     |
	| UCHIJAAAA | mca                 | 1.12.2-5.3.1                | MCA-1.12.x-5.3.1-universal.jar                  | None                                     |
	| UCHIJAAAA | mcmultipart         | 2.4.1                       | MCMultiPart-2.4.1.jar                           | None                                     |
	| UCHIJAAAA | mekanism            | 1.12.2-9.4.3.330            | Mekanism-1.12.2-9.4.3.330.jar                   | None                                     |
	| UCHIJAAAA | mekanismgenerators  | 9.4.3                       | MekanismGenerators-1.12.2-9.4.3.330.jar         | None                                     |
	| UCHIJAAAA | mekanismtools       | 9.4.3                       | MekanismTools-1.12.2-9.4.3.330.jar              | None                                     |
	| UCHIJAAAA | customnpcs          | 1.12                        | NPCs-core_1.12.2(20jan18).jar                   | None                                     |
	| UCHIJAAAA | omlib               | 3.0.0-138                   | omlib-1.12.2-3.0.0-138.jar                      | None                                     |
	| UCHIJAAAA | reborncore          | 3.6.5.197                   | RebornCore-1.12.2-3.6.5.197-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | rftools             | 7.27                        | rftools-1.12-7.27.jar                           | None                                     |
	| UCHIJAAAA | stevescarts         | ${version}                  | StevesCarts-1.12.2-2.4.16.81.jar                | None                                     |
	| UCHIJAAAA | variedcommodities   | 1.12.2                      | VariedCommodities_1.12.2(06nov17).jar           | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.132.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SpongeCoremod (spongeforge-1.12.2-2586-7.1.0-BETA-2890.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	RebornCore: 
		Plugin Engine: 1
		RebornCore Version: 3.6.5.197
		Runtime Debofucsation 1
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 3 / 10; [GCEntityPlayerMP['Del_Dukes'/488, l='map', x=-815.94, y=74.00, z=552.85], GCEntityPlayerMP['Xopharios'/933, l='map', x=-804.31, y=71.00, z=536.79], GCEntityPlayerMP['KasheYT'/1145, l='map', x=-133.05, y=69.00, z=73.21]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)`

**Comment by Xopharios** [comment]
It should be mentioned upon restart, all the villagers turn into STEVE THE FARMER. Textureless steve, in the entire village.
