### ISSUE TITLE
Invisible villagers that are all called Steve the Farmer, red screen and server crash

### ISSUE THREAD

**Issue by jesuslencina** [WildBamaBoy/minecraft-comes-alive#976]
Hello there. I was a fan of this mod in the 1.5 times, but I left it in 1.7.10. However, now I am playing a 1.12.2 server with friends, and we decided to include the mod in our modpack and the server. We are starting to think it was a bad idea; Here are the issues:

**Invisible villagers and all called "Steve the Farmer":** All the villagers but the guards are invisible, and have the same name, as seen [here](https://i.imgur.com/ToATUVK.png) and [here](https://i.imgur.com/hhVdn14.png)

**Crash on trading:** The server automatically crashes when we attemp to trade with a villager

**Screen turns red:** Even when we are away from the chunks where the villagers are, sometimes the screen turns red for many minutes, as seen [here](https://i.imgur.com/pO5tgUn.png)

**Guards seem to work just fine** as seen [here](https://i.imgur.com/WiPpmXQ.png)

**We lost at least 16 FPS**

The server is running **Minecraft 1.12.2**, with **Forge 1.12.2-14.23.2.2611** and **SpongeForge 1.12.2-2586-7.1.0-BETA-2887**.

Any ideas? 

Thanks.

**Comment by AlphaOneYT** [comment]
Having the same issue :/

**Comment by AlphaOneYT** [comment]
Send me your full mods list so i can compare are mods to possibly find out what the problem is my discord tag is **Tag: Alpha ツ#7142**  **Discord Invite: https://discord.gg/xzAVcCM**

**Comment by marineomi0204** [comment]
I've got the exact same problem...

**Comment by Diamonddragon41** [comment]
I'm having this same problem but the discord link expired. Did you ever find out what mod causes it?
