### ISSUE TITLE
No MCA Zombies

### ISSUE THREAD

**Issue by Galindorf** [WildBamaBoy/minecraft-comes-alive#982]
I actually posted a while ago asking for MCA zombies to be re-implemented and he said they were still there. So I'm posting a new issue, villagers that are turned into zombies become vanilla zombies (that become invisible Steve the Farmer when cured). 

Minecraft Java on Mac OS, 1.12.2
Minecraft Forge 14.23.1.2555
Minecraft Comes Alive 1.12.2-5.3.1

some other random mods.

Edit: Also occurs with Forge 14.23.2.2611
Tried on a freshly generated world in creative mode, villagers attacked by zombies became vanilla villager zombies.

**Comment by GameRKade** [comment]
More Info:

I am also having this problem. I'm not sure about the curing zombies glitch though, I tried that, it took a while, only to have a nearby guard kill it off, so I gave up trying.

 - I am running MCA 1.12.2-5.3.1
 - I am running Forge 14.23.0.2491
 - I only have this mod and World edit, so it's not a mod causing a problem, I doubt world edit would cause anything

This only seems to be the case with villager zombies. MCA zombies can still be created through the villager editor, and healed back to a normal, non Steve villager.

**Comment by SDPhantom** [comment]
There's a difference between vanilla zombies and MCA infected villagers. Vanilla zombies are created when a villager dies to a zombie. I believe MCA infected have to get hit, but survive the outcome. I haven't exactly seen it happen, but I've had a few before.

**Comment by adkins2010** [comment]
Yeah. It does happen. The fix for this should be simple, though. In my variant of the mod, I'm not letting the MCA villager's body disappear right away when they die. I did so by delaying the super class's implementation of the `onDeath(DamageSource source)` method. 
I imagine that you can stop the vanilla villager zombies from spawning by preventing them from dying whenever a zombie kills them. 
But, I'm wondering if it would be more awesome for a ghost to be spawned.

**Comment by Galindorf** [comment]
yeah we've played this for months in a very curated, populated village. I've had many villagers just up and disappear, and many killed/turned by zombies and I have seen 0 villager zombies. I had a whole dungeon  of villager zombies in an earlier version! I miss those guys (and the hilarious quirks of them story progressing as zombies... my favorite being the quarantined lady who fell in love with a guard through the door and ended up having a baby...)
