### ISSUE TITLE
Child Feature Requests

### ISSUE THREAD

**Issue by GameRKade** [WildBamaBoy/minecraft-comes-alive#983]
- Have children start at 5 red hearts instead of 5 gold hearts. There's really no reason to interact with someone after they reach gold hearts, since they don't go back down over time. I don't really interact with my children that much because I don't want hearts to go down, so they're just...there.
 - Have a child in negative hearts refuse to do chores.
 - Automatically put a child down if picking them up would cause them to suffocate. It's a cool feature and allows them to keep up with you, but I'm really paranoid about using it.
 - Disable the pick up function when a child reaches a certain age. Having a 16 year old sit on your shoulders is pretty difficult.
 - Ability to hug children. Possible negative phrases could be something like "Dad/Mom, I'm too old for this!"
 - Death puts everyone in a bad mood, but if a child dies, set their parents to the lowest mood possible
 - Having a child with an infected spouse automatically creates an infected baby
 - Know when you're having twins and the genders before you name them, so you can pick twin names like Tim and Tom or Summer and Winter

Not sure how many of these are possible, but hopefully some of them are worthwhile.

**Comment by Magician539** [comment]
The last one has always been a feature.

**Comment by GameRKade** [comment]
Has it been a feature? I turned twins to 100% chance to test it out, but for me this happens:
First, I get a message saying "It's a boy/girl!". Then, I name the child.
After that, I get another message later saying that I had another child, but there was no way to know beforehand that this would happen. Is there something I'm just not seeing?
