### ISSUE TITLE
Everyone hates me and I can't get married

### ISSUE THREAD

**Issue by peachestheconvict** [WildBamaBoy/minecraft-comes-alive#984]
For some reason, villagers will go through periods where, no matter what action i use or what gift I give, they dislike it. I even turned off diminishing returns and they still hate everything I do, including giving them diamonds, diamond tools, gold, etc. Sometimes they will accept gifts, but more often they will decline everything.

More importantly, this hatred-glitch prevents me from getting married. Like other players I spawned with a non-existent spouse, but even after divorcing them, unmarried villagers with five gold hearts will turn down wedding and engagement rings. They will either outright say decline them (a "no, i don't want this" etc) or on rare occasions they will accept the rings as normal gifts rather than activating a marriage/proposal (a "thanks so much" etc).

In one save I even managed to get a villager to accept my engagement ring, but afterwards she would decline the wedding ring and our children would turn down any gifts I gave them, including new outfits, meaning I couldn't actually get married and our illegitimate children hated me.

Please, is there some way I can fix this?

I'm running MCA 1.12.2 - 5.3.1 and Forge 14.23.2.2611

**Comment by peachestheconvict** [comment]
Update: I just noticed that even though villagers at five gold hearts will reject rings as though they were mundane gifts, I will still be marked as married. It doesn't change the villager's interface and they will remain single, but I will have the option to get divorced via the cleric.

**Comment by SuperGirl398** [comment]
I have the same issue, I have version 6.0.1 so I don't know what's going on.
