### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by SallySabrina** [WildBamaBoy/minecraft-comes-alive#986]
It says in the minecraft ''Minecraft Comes Alive is missing mods it depends on. Include the following mods or remove Minecraft Comes Alive.''

I'm so sad because i don't understand what this means.. i really wanted the MCA. And yes, i have tried to download it again, downloading from different sites etc! -Desperate
# # # #

**Comment by Galindorf** [comment]
Hey Sally! Did you make sure to also install the latest version of Radix-Core ? MCA needs Radix-Core to work. Just put it in your mods folder, same as the MCA.
