### ISSUE TITLE
Children do not want to work and the hud is not right.

### ISSUE THREAD

**Issue by Lunarous** [WildBamaBoy/minecraft-comes-alive#988]
Ok, so I just go the mod to play around with it on 1.12.2, on the 5.3.1 update, I adopted a child and raised her up, but when I tell her to shop wood she doesn't do it. She will chop a single piece of oak wood from one of the village houses and then say her inventory is full. But if I bring her out to the woods (don't hear that phrased very often) she does absolutely nothing, even if given an axe.

The next bit is her inventory, its like the actual slots are over and down some from what the menu graphic actually shows. 

I don't have screenshots right now as I am posting this late but while its still fresh in the mind, but I will screen shot what I mean tomorrow hopefully.

Thanks in advance for any and all help.

**Comment by missycud** [comment]
The same issue is happening to me:
![issue2](https://user-images.githubusercontent.com/38250327/38556931-ad85d90e-3d0e-11e8-99fd-b00d60285a7a.PNG)
![issue3](https://user-images.githubusercontent.com/38250327/38556932-adc3ae32-3d0e-11e8-9e08-6cfa72202c22.PNG)

BUT my husband is also playing up (the option for everything but cooking and combat are not able to be pressed even though he has all the right tools to do so)
![issue](https://user-images.githubusercontent.com/38250327/38556928-ad46e672-3d0e-11e8-8fcb-7e779cddd789.PNG)

**Comment by Magician539** [comment]
The husband or Wife don't do any chores unless you go to a previous Mca version hire them forever then marry them. Once hired a and married if they were a farmer they do farming things if miner they mine etc

**Comment by silverdrake3** [comment]
I'm having the same issue. I asked my daughter to chop wood, and she'll chop one block and say "My inventory is full!" at which point I can repeat the request and she'll chop one more block, then complain about the full inventory again. All she's carrying is an axe, that's it, so she's got plenty of room in there.
She will, however, farm as long as you like.
