### ISSUE TITLE
1.12.2 After update from 1.10, Forge reports "missing registry entries" for MCA

### ISSUE THREAD

**Issue by BigGrayGolem** [WildBamaBoy/minecraft-comes-alive#992]
I am trying to update from 1.10 to 1.12.2. When running the game under 1.12.2 for the first time, I get an error saying Forge Mod Loader cannot find MCA related registry entries. If I select "yes" to proceed, MCA loads but there are no villagers and some items are missing (those listed in the offending registry entries.) 

I'm really not sure where to even begin to look for the problem.

![mcerror](https://user-images.githubusercontent.com/37187460/37162960-9c06418c-22c4-11e8-9de6-75fcc5422e61.JPG)

**Comment by adkins2010** [comment]
Make a backup of your save folder and try to load it and see what happens. I think that I saw that too, but loaded it and it was fine.

**Comment by BigGrayGolem** [comment]
I'm already running from a backup. I will try again, though, but I don't think that's it.

**Comment by BigGrayGolem** [comment]
Why was this closed? Issue was never resolved. Or is the mod just dead? (Don't tell me that....)

**Comment by BigGrayGolem** [comment]
Never mind, just saw announcement!!!! Can't wait to try new version.
