### ISSUE TITLE
Steve skin?

### ISSUE THREAD

**Issue by GasW0lf** [WildBamaBoy/minecraft-comes-alive#994]
I like to use the villager editor to give villagers skins from players and it's worked perfectly so far, but all of a sudden (and I can't remember if there's been a mod update) any villager with a player skin now just has the steve skin?
I've tried re-adding the skins but it just keeps making it the steve skin.

**Comment by DustyUmbry** [comment]
This issue occurs even without updating the mod. The newer updates removed this feature from the mod. It's quite disappointing to me, as it was one of the main reasons I really enjoyed this mod...
