### ISSUE TITLE
Just me?

### ISSUE THREAD

**Issue by ashleygames101** [WildBamaBoy/minecraft-comes-alive#996]
When i try to play with a friend using minecraft comes alive it crashes, could it be the mods i play with or that i am using to many of them?.. ik you get crash reports so id just like to know what I'm doing wrong or if it needs to be updated for LAN server use...

**Comment by adkins2010** [comment]
I'm not sure if they get the crash reports. By the way, might I interest you in my spin-off of the MCA mod? It's called "Minecraft Comes Alive: Orcs and Elves Edition". 
Link to my Github below:  

https://github.com/adkins2010/Minecraft-Comes-Alive-Elves-and-Orcs-Edition
Also, you can download the JAR of my mod at the following link:
https://drive.google.com/file/d/1mLLfOdBnWHH-TknShDZw7k1iAtm9wIQ-/view?usp=drivesdk
If you send me the crash reports then I'll look at them. But, I would prefer it if you were using the mod that I'm giving you. However, if it's just the original MCA then I'll still take look at it.
