### ISSUE TITLE
How to put MCA on a server

### ISSUE THREAD

**Issue by Nixxietail** [WildBamaBoy/minecraft-comes-alive#999]
I've been trying to figure this out and I have a head ache please help me.

**Comment by m4d-m4x** [comment]
Hello,
take the RadixCore file and Minecraft Comes Alive (MCA) file and copy it into ur (server) mods directory.
If u dont have a mods directory install forge, than u will get a mods directory.

**Comment by Nixxietail** [comment]
Okay thank you

**Comment by m4d-m4x** [comment]
Hello,
u can use to copy it into the server mods directory winscp. Winscp is a gui (graphical user interface) programm like e.g. Windows 10.
